In [ ]:
from datasets import load_dataset

ds = load_dataset("sewon/ambig_qa", "light")

ModuleNotFoundError: No module named 'datasets'

In [ ]:
data = ds['train']
print(len(data))

In [ ]:
data[1]

NameError: name 'data' is not defined

In [ ]:
import pandas as pd
import json

# --- 1. Load your data (if not already loaded) ---
# data = [json.loads(line) for line in open("ambignq_train_data.json")]

rows = []
for entry in data:
    ann = entry["annotations"]

    # Extract question type (string)
    ann_type = ann["type"][0] if isinstance(ann["type"], list) else ann["type"]

    # Extract qaPairs safely
    qa_pairs = ann.get("qaPairs", [])
    if len(qa_pairs) == 1 and isinstance(qa_pairs[0], list):
        qa_pairs = qa_pairs[0]

    # Extract single-answer list (only for singleAnswer entries)
    single_ans_list = ann.get("answer", [])
    single_ans_flat = []
    if isinstance(single_ans_list, list):
        for ans in single_ans_list:
            if isinstance(ans, list):
                single_ans_flat.extend(ans)
            elif isinstance(ans, str):
                single_ans_flat.append(ans)

    row = {
        "question": entry["question"],
        "type": ann_type,
        "qaPairs": qa_pairs,
        "single_answers": single_ans_flat if ann_type == "singleAnswer" else []
    }
    rows.append(row)

og_df = pd.DataFrame(rows)

# =========================================================
# 🔹 Extract Disambiguated Questions
# =========================================================
def extract_disambig_questions(qa_pairs):
    disambig = []
    if not isinstance(qa_pairs, list):
        return disambig
    for pair in qa_pairs:
        if not isinstance(pair, dict):
            continue
        qs = pair.get("question", [])
        if isinstance(qs, list):
            disambig.extend(qs)
        elif isinstance(qs, str):
            disambig.append(qs)
    return disambig


# =========================================================
# 🔹 Extract Disambiguated Answers
# =========================================================
def extract_disambig_answers(qa_pairs):
    answers = []
    if not isinstance(qa_pairs, list):
        return answers
    for pair in qa_pairs:
        if not isinstance(pair, dict):
            continue
        ans_list = pair.get("answer", [])
        if isinstance(ans_list, list):
            for a in ans_list:
                if isinstance(a, list):
                    answers.extend(a)
                elif isinstance(a, str):
                    answers.append(a)
    return answers


# =========================================================
# 🔹 Apply extraction to DataFrame
# =========================================================
og_df["disambig_questions"] = og_df["qaPairs"].apply(extract_disambig_questions)
og_df["disambig_answers"] = og_df["qaPairs"].apply(extract_disambig_answers)
og_df["is_ambiguous"] = og_df["type"].apply(lambda t: t == "multipleQAs")

# --- For singleAnswer entries, copy their answers from annotations ---
og_df["single_answers"] = og_df.apply(
    lambda r: r["single_answers"] if r["type"] == "singleAnswer" else [], axis=1
)

# =========================================================
# ✅ Sanity Check
# =========================================================
print(og_df[["question", "type", "disambig_questions", "disambig_answers", "single_answers", "is_ambiguous"]].head(5))

                                            question          type  \
0     When did the simpsons first air on television?   multipleQAs
1  Who played george washington in the john adams...  singleAnswer
2          What is the legal age of marriage in usa?   multipleQAs
3   Who starred in barefoot in the park on broadway?   multipleQAs
4      When did the manhattan project began and end?   multipleQAs

                                  disambig_questions  \
0  [When did the Simpsons first air on television...
1                                                 []
2  [What is the legal age of marriage, without pa...
3  [Who starred in barefoot in the park on broadw...
4  [Based on the initial thoughts of the project,...

                                    disambig_answers single_answers  \
0                [April 19, 1987, December 17, 1989]             []
1                                                 []  [David Morse]
2                   [18 years of age, 18, 19, 21, 0]             []
3  [Elizabeth Ashley, Kurt Kasznar, Mildred Natwi...             []
4       [Began 1939, end 1946, Began 1942, end 1946]             []

   is_ambiguous
0          True
1         False
2          True
3          True
4          True

In [ ]:
og_df

,question,type,qaPairs,single_answers,disambig_questions,disambig_answers,is_ambiguous
0,When did the simpsons first air on television?,multipleQAs,[{'question': ['When did the Simpsons first ai...,[],[When did the Simpsons first air on television...,"[April 19, 1987, December 17, 1989]",True
1,Who played george washington in the john adams...,singleAnswer,"[{'question': [], 'answer': []}]",[David Morse],[],[],False
2,What is the legal age of marriage in usa?,multipleQAs,[{'question': ['What is the legal age of marri...,[],"[What is the legal age of marriage, without pa...","[18 years of age, 18, 19, 21, 0]",True
3,Who starred in barefoot in the park on broadway?,multipleQAs,[{'question': ['Who starred in barefoot in the...,[],[Who starred in barefoot in the park on broadw...,"[Elizabeth Ashley, Kurt Kasznar, Mildred Natwi...",True
4,When did the manhattan project began and end?,multipleQAs,[{'question': ['Based on the initial thoughts ...,[],"[Based on the initial thoughts of the project,...","[Began 1939, end 1946, Began 1942, end 1946]",True
...,...,...,...,...,...,...,...
10031,When do the summer holidays start for schools?,multipleQAs,[{'question': ['When do summer holidays start ...,[],[When do summer holidays start for schools in ...,"[end of June, between late-May and mid-June, B...",True
10032,Who is the band in the movie 10 things i hate ...,multipleQAs,[{'question': ['What band plays at Club Skunk ...,[],[What band plays at Club Skunk in the movie 10...,"[Letters to Cleo, Save Ferris, Letters to Cleo...",True
10033,Who was the last person in the uk to be executed?,singleAnswer,"[{'question': [], 'answer': []}]",[Gwynne Evans and Peter Allen],[],[],False
10034,Who does wonder woman end up with in the comics?,multipleQAs,[{'question': ['Who does wonder woman end up w...,[],[Who does wonder woman end up with in All Star...,"[General Steven Rockwell Trevor, Steve Trevor,...",True
10035,When were the first pair of jordans released?,multipleQAs,[{'question': ['When were the first pair of Ai...,[],[When were the first pair of Air Jordans relea...,"[early 1984, November 17, 1984]",True

Positive answers for disambiguous questions

In [ ]:
full_facet_df=pd.read_csv('full_reasoning_df.csv')
full_facet_df.head()

,Unnamed: 0,question,type,qaPairs,disambig_questions,is_ambiguous,facets,reasoning
0,0,When did the simpsons first air on television?,multipleQAs,[{'question': ['When did the Simpsons first ai...,['When did the Simpsons first air on televisio...,True,"['Type of Show', 'Platform']",The question is ambiguous because it does not ...
1,1,Who played george washington in the john adams...,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...
2,2,What is the legal age of marriage in usa?,multipleQAs,[{'question': ['What is the legal age of marri...,"['What is the legal age of marriage, without p...",True,"['State', 'Circumstances for Marriage']",The question is ambiguous because the legal ag...
3,3,Who starred in barefoot in the park on broadway?,multipleQAs,[{'question': ['Who starred in barefoot in the...,['Who starred in barefoot in the park on broad...,True,['Character Name'],The question is ambiguous because it does not ...
4,4,When did the manhattan project began and end?,multipleQAs,[{'question': ['Based on the initial thoughts ...,['Based on the initial thoughts of the project...,True,['Time Frame Interpretation'],The question is ambiguous because it does not ...

In [ ]:
og_df

,question,type,qaPairs,single_answers,disambig_questions,disambig_answers,is_ambiguous
0,When did the simpsons first air on television?,multipleQAs,[{'question': ['When did the Simpsons first ai...,[],[When did the Simpsons first air on television...,"[April 19, 1987, December 17, 1989]",True
1,Who played george washington in the john adams...,singleAnswer,"[{'question': [], 'answer': []}]",[David Morse],[],[],False
2,What is the legal age of marriage in usa?,multipleQAs,[{'question': ['What is the legal age of marri...,[],"[What is the legal age of marriage, without pa...","[18 years of age, 18, 19, 21, 0]",True
3,Who starred in barefoot in the park on broadway?,multipleQAs,[{'question': ['Who starred in barefoot in the...,[],[Who starred in barefoot in the park on broadw...,"[Elizabeth Ashley, Kurt Kasznar, Mildred Natwi...",True
4,When did the manhattan project began and end?,multipleQAs,[{'question': ['Based on the initial thoughts ...,[],"[Based on the initial thoughts of the project,...","[Began 1939, end 1946, Began 1942, end 1946]",True
...,...,...,...,...,...,...,...
10031,When do the summer holidays start for schools?,multipleQAs,[{'question': ['When do summer holidays start ...,[],[When do summer holidays start for schools in ...,"[end of June, between late-May and mid-June, B...",True
10032,Who is the band in the movie 10 things i hate ...,multipleQAs,[{'question': ['What band plays at Club Skunk ...,[],[What band plays at Club Skunk in the movie 10...,"[Letters to Cleo, Save Ferris, Letters to Cleo...",True
10033,Who was the last person in the uk to be executed?,singleAnswer,"[{'question': [], 'answer': []}]",[Gwynne Evans and Peter Allen],[],[],False
10034,Who does wonder woman end up with in the comics?,multipleQAs,[{'question': ['Who does wonder woman end up w...,[],[Who does wonder woman end up with in All Star...,"[General Steven Rockwell Trevor, Steve Trevor,...",True
10035,When were the first pair of jordans released?,multipleQAs,[{'question': ['When were the first pair of Ai...,[],[When were the first pair of Air Jordans relea...,"[early 1984, November 17, 1984]",True

In [ ]:
pos_ans=full_facet_df.merge(og_df[['question','single_answers']], how='inner', on='question')
pos_ans

,Unnamed: 0,question,type,qaPairs,disambig_questions,is_ambiguous,facets,reasoning,single_answers
0,0,When did the simpsons first air on television?,multipleQAs,[{'question': ['When did the Simpsons first ai...,['When did the Simpsons first air on televisio...,True,"['Type of Show', 'Platform']",The question is ambiguous because it does not ...,[]
1,1,Who played george washington in the john adams...,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,[David Morse]
2,2,What is the legal age of marriage in usa?,multipleQAs,[{'question': ['What is the legal age of marri...,"['What is the legal age of marriage, without p...",True,"['State', 'Circumstances for Marriage']",The question is ambiguous because the legal ag...,[]
3,3,Who starred in barefoot in the park on broadway?,multipleQAs,[{'question': ['Who starred in barefoot in the...,['Who starred in barefoot in the park on broad...,True,['Character Name'],The question is ambiguous because it does not ...,[]
4,4,When did the manhattan project began and end?,multipleQAs,[{'question': ['Based on the initial thoughts ...,['Based on the initial thoughts of the project...,True,['Time Frame Interpretation'],The question is ambiguous because it does not ...,[]
...,...,...,...,...,...,...,...,...,...
10031,10031,When do the summer holidays start for schools?,multipleQAs,[{'question': ['When do summer holidays start ...,['When do summer holidays start for schools in...,True,"['Geographical Region', 'Specific Location']",The question is ambiguous because it does not ...,[]
10032,10032,Who is the band in the movie 10 things i hate ...,multipleQAs,[{'question': ['What band plays at Club Skunk ...,['What band plays at Club Skunk in the movie 1...,True,"['Location', 'Event Type']",The question is ambiguous because it does not ...,[]
10033,10033,Who was the last person in the uk to be executed?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,[Gwynne Evans and Peter Allen]
10034,10034,Who does wonder woman end up with in the comics?,multipleQAs,[{'question': ['Who does wonder woman end up w...,['Who does wonder woman end up with in All Sta...,True,"['Story Universe', 'Publication Series']",The question is ambiguous because 'Wonder Woma...,[]
10035,10035,When were the first pair of jordans released?,multipleQAs,[{'question': ['When were the first pair of Ai...,['When were the first pair of Air Jordans rele...,True,"['Release Target Audience', 'Release Scope']",The question is ambiguous because it does not ...,[]

Generating positive responses for ambiguous questions

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

# # Choose model
# model_name = "Qwen/Qwen2.5-7B-Instruct"

# # Load tokenizer and model
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.bfloat16)

# # Move to GPU if available
# device = "cuda" if torch.cuda.is_available() else "cpu"
# model = model.to(device)

model_name = "Qwen/Qwen2.5-7B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",          # let Accelerate place layers
    torch_dtype=torch.bfloat16, # good precision for A100/T4
)

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
df=pos_ans.copy()
df=df[:990]
print(df.shape)
df.head()

(990, 9)

,Unnamed: 0,question,type,qaPairs,disambig_questions,is_ambiguous,facets,reasoning,single_answers
0,0,When did the simpsons first air on television?,multipleQAs,[{'question': ['When did the Simpsons first ai...,['When did the Simpsons first air on televisio...,True,"['Type of Show', 'Platform']",The question is ambiguous because it does not ...,[]
1,1,Who played george washington in the john adams...,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,[David Morse]
2,2,What is the legal age of marriage in usa?,multipleQAs,[{'question': ['What is the legal age of marri...,"['What is the legal age of marriage, without p...",True,"['State', 'Circumstances for Marriage']",The question is ambiguous because the legal ag...,[]
3,3,Who starred in barefoot in the park on broadway?,multipleQAs,[{'question': ['Who starred in barefoot in the...,['Who starred in barefoot in the park on broad...,True,['Character Name'],The question is ambiguous because it does not ...,[]
4,4,When did the manhattan project began and end?,multipleQAs,[{'question': ['Based on the initial thoughts ...,['Based on the initial thoughts of the project...,True,['Time Frame Interpretation'],The question is ambiguous because it does not ...,[]

In [ ]:
# ==============================================================
# 🔹 IMPORTS & SETUP
# ==============================================================
import re
import ast
import gc
import torch
import pandas as pd
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM

# ---- Device Setup ----
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)


# ==============================================================
# 🔹 Helper: Extract only [OUTPUT] content
# ==============================================================
def extract_output(text):
    """
    Extracts the model-generated clarifying question from between [OUTPUT] tags.
    """
    m = re.search(r"\[OUTPUT\](.*?)\[/OUTPUT\]", text, flags=re.DOTALL)
    if m:
        return m.group(1).strip()
    else:
        # fallback — return last few lines if no tags
        lines = text.strip().splitlines()
        return lines[-1].strip() if lines else text.strip()

# ==============================================================
# 🔹 Build Positive Clarifying Prompt
# ==============================================================
def build_positive_prompt(question, facets):
    facets_txt = ", ".join(facets) if facets else "N/A"
    #tax_txt = ", ".join(taxonomies) if taxonomies else "N/A"

    return f"""
You are a helpful assistant that clarifies ambiguous questions.

Your task: Ask a **single-turn clarifying question** that helps the user
specify their intent and resolve all the ambiguity. Use the provided facets (as clues about *what* is ambiguous)

---

**Ambiguous Question:**
{question}

**Facets (dimensions of ambiguity):**
{facets_txt}

---

Guidelines:
1. Ask one polite, natural question that helps clarify **all listed facets**.
2. Do **not** answer the question.
3. Keep your response short (1 sentence max).
4. Output the clarifying question only between [OUTPUT] and [/OUTPUT].

---

### Example 1
Ambiguous: "When did The Simpsons first air?"
Facets: Type of Show, Broadcast Region
Output: [OUTPUT]Could you clarify which type of Simpsons show you’re referring to, and in which region it aired?[/OUTPUT]

### Example 2
Ambiguous: "Who won the US Open?"
Facets: Sport Type, Year
Output: [OUTPUT]Do you mean the US Open in tennis or golf, and which year are you asking about?[/OUTPUT]

---

Now write your clarifying question.
Remember to wrap it exactly as [OUTPUT] ... [/OUTPUT].
"""

# ==============================================================
# 🔹 LLM Call Utility
# ==============================================================
def generate_text(prompt, temperature=0.5, max_new_tokens=100, debug=False):
    """
    Generates only the model's clarifying question, not the prompt.
    """
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=3000).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_p=0.9,
            do_sample=True
        )

    # Decode only the newly generated part, not the input prompt
    gen_tokens = outputs[0][inputs["input_ids"].shape[1]:]
    text = tokenizer.decode(gen_tokens, skip_special_tokens=True)

    if debug:
        print("\n=== RAW MODEL OUTPUT ===\n", text, "\n=========================\n")

    return extract_output(text)

# ==============================================================
# 🔹 MAIN LOOP — GENERATE POSITIVE RESPONSES ONLY
# ==============================================================
positive_responses = []

for idx, row in tqdm(df.iterrows(), total=len(df), desc="Generating positive clarifying questions"):
    if not row.get("is_ambiguous", False):
        positive_responses.append("N/A")
        continue

    question = row["question"]

    # --- Parse facet_taxonomies safely ---
    facets_raw = row.get("facets", [])
    if isinstance(facets_raw, str):
        try:
            facets = ast.literal_eval(facets_raw)
        except Exception:
            facets = [facets_raw]
    elif isinstance(facets_raw, list):
        facets = facets_raw
    else:
        facets = []

    #taxonomies = [ft.get("taxonomy", "") for ft in raw_ft if isinstance(ft, dict)]

    try:
        pos_prompt = build_positive_prompt(question, facets)
        pos_out = generate_text(pos_prompt, temperature=0.6, debug=True)
        positive_responses.append(pos_out)
    except torch.cuda.OutOfMemoryError:
        print(f"\n⚠️ OOM at row {idx}, switching to CPU temporarily...")
        model.to("cpu")
        pos_out = generate_text(pos_prompt, temperature=0.6, debug=False)
        positive_responses.append(pos_out)
        model.to(device)
    finally:
        torch.cuda.empty_cache()
        gc.collect()

    # --- Print summary per question ---
    print(f"\n🟩 Row {idx}")
    print(f"Q: {question}")
    print(f"Facets: {facets}")
    #print(f"Taxonomies: {taxonomies}")
    print(f"✅ Clarifying Question: {pos_out}")
    print("------------------------------------------------------\n")

# ==============================================================
# 🔹 SAVE OUTPUT
# ==============================================================
df["positive_response"] = positive_responses
df.to_csv("positive_clarifying_responses.csv", index=False)
print("\n✅ Saved results to positive_clarifying_responses.csv")

Using device: cuda

Generating positive clarifying questions:   0%|          | 0/990 [00:00<?, ?it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the original TV series or a movie, and on which platform (e.g., network, streaming service) did it first air?[/OUTPUT]
=========================

Generating positive clarifying questions:   0%|          | 1/990 [00:01<26:50,  1.63s/it]

🟩 Row 0
Q: When did the simpsons first air on television?
Facets: ['Type of Show', 'Platform']
✅ Clarifying Question: Are you asking about the original TV series or a movie, and on which platform (e.g., network, streaming service) did it first air?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which U.S. state and under what circumstances are you asking about the legal age of marriage?[/OUTPUT]
=========================


🟩 Row 2
Q: What is the legal age of marriage in usa?
Facets: ['State', 'Circumstances for Marriage']
✅ Clarifying Question: In which U.S. state and under what circumstances are you asking about the legal age of marriage?
------------------------------------------------------

Generating positive clarifying questions:   0%|          | 3/990 [00:02<14:41,  1.12it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did you mean the character names or the actors who played them in the Broadway production of Barefoot in the Park?[/OUTPUT]
=========================

Generating positive clarifying questions:   0%|          | 4/990 [00:03<15:48,  1.04it/s]

🟩 Row 3
Q: Who starred in barefoot in the park on broadway?
Facets: ['Character Name']
✅ Clarifying Question: Did you mean the character names or the actors who played them in the Broadway production of Barefoot in the Park?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific year or time period are you interested in knowing about the Manhattan Project's start and end?[/OUTPUT]
=========================

Generating positive clarifying questions:   1%|          | 5/990 [00:04<15:37,  1.05it/s]

🟩 Row 4
Q: When did the manhattan project began and end?
Facets: ['Time Frame Interpretation']
✅ Clarifying Question: In which specific year or time period are you interested in knowing about the Manhattan Project's start and end?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about football or college football specifically, and which season's championship are you inquiring about?[/OUTPUT]
=========================

Generating positive clarifying questions:   1%|          | 8/990 [00:05<09:21,  1.75it/s]

🟩 Row 7
Q: When was the last time uga won a national championship?
Facets: ['Sport Type']
✅ Clarifying Question: Are you asking about football or college football specifically, and which season's championship are you inquiring about?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know who performed "Play That Funky Music White Boy"?[/OUTPUT]
=========================

Generating positive clarifying questions:   1%|          | 9/990 [00:06<10:21,  1.58it/s]

🟩 Row 8
Q: Who sing play that funky music white boy?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know who performed "Play That Funky Music White Boy"?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you prefer a translation into a particular language, and if so, which one, or if you're looking for a preferred translation version of the phrase?[/OUTPUT]
=========================


🟩 Row 11
Q: Consubstantial with the father in the creed means what?
Facets: ['Translation Language', 'Preferred Translation']
✅ Clarifying Question: Could you specify whether you prefer a translation into a particular language, and if so, which one, or if you're looking for a preferred translation version of the phrase?
------------------------------------------------------

Generating positive clarifying questions:   1%|▏         | 14/990 [00:09<09:02,  1.80it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the voice actor for the snake in the original 1967 Disney film or a more recent adaptation, such as the 2016 live-action version?[/OUTPUT]
=========================


🟩 Row 13
Q: Voice of the snake in the jungle book?
Facets: ['Film Year', 'Medium of Adaptation']
✅ Clarifying Question: Are you asking about the voice actor for the snake in the original 1967 Disney film or a more recent adaptation, such as the 2016 live-action version?
------------------------------------------------------

Generating positive clarifying questions:   2%|▏         | 20/990 [00:09<04:56,  3.27it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region and what specific Han Solo movie are you asking about?[/OUTPUT]
=========================


🟩 Row 19
Q: When did the han solo movie come out?
Facets: ['Geographical Region', 'Event Type']
✅ Clarifying Question: In which geographical region and what specific Han Solo movie are you asking about?
------------------------------------------------------

Generating positive clarifying questions:   2%|▏         | 22/990 [00:10<05:12,  3.10it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the IATA or ICAO airport code for Abu Dhabi?[/OUTPUT]
=========================


🟩 Row 21
Q: What is the airport code for abu dhabi?
Facets: ['Airport Code Type']
✅ Clarifying Question: Are you asking about the IATA or ICAO airport code for Abu Dhabi?
------------------------------------------------------

Generating positive clarifying questions:   3%|▎         | 25/990 [00:11<05:05,  3.16it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about a particular version of the song or a specific context where it was performed?[/OUTPUT]
=========================


🟩 Row 24
Q: Who sings don't mess around with jim?
Facets: ['Version of Song', 'Contextual Setting']
✅ Clarifying Question: Could you specify if you're asking about a particular version of the song or a specific context where it was performed?
------------------------------------------------------

Generating positive clarifying questions:   3%|▎         | 26/990 [00:12<05:55,  2.71it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year are you asking about PSG's Ligue 1 titles?[/OUTPUT]
=========================


🟩 Row 25
Q: How many ligue 1 titles does psg have?
Facets: ['Time']
✅ Clarifying Question: In which year are you asking about PSG's Ligue 1 titles?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific year are you asking when Easter will coincide with April Fool's Day?[/OUTPUT]
=========================


🟩 Row 27
Q: When's the next time easter falls on april fools day?
Facets: ['Year']
✅ Clarifying Question: In which specific year are you asking when Easter will coincide with April Fool's Day?
------------------------------------------------------

Generating positive clarifying questions:   3%|▎         | 28/990 [00:13<06:50,  2.34it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the number of seasons for Star Wars: The Clone Wars specifically from a certain year, or is there another title you're referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:   3%|▎         | 31/990 [00:14<07:08,  2.24it/s]

🟩 Row 30
Q: How many seasons are there of star wars the clone wars?
Facets: ['Year of Release', 'Title']
✅ Clarifying Question: Are you asking about the number of seasons for Star Wars: The Clone Wars specifically from a certain year, or is there another title you're referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the construction date of the physical memorial or the dedication ceremony, and are you referring to the United States National World War II Memorial or another similar memorial?[/OUTPUT]
=========================

Generating positive clarifying questions:   3%|▎         | 32/990 [00:16<09:20,  1.71it/s]

🟩 Row 31
Q: When was the national world war ii memorial built?
Facets: ['Event Category', 'Action Verb']
✅ Clarifying Question: Are you asking about the construction date of the physical memorial or the dedication ceremony, and are you referring to the United States National World War II Memorial or another similar memorial?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are the German Die Brücke artists associated with a specific art movement or medium?[/OUTPUT]
=========================


🟩 Row 32
Q: With what are the german die brücke artists associated?
Facets: ['Group Association', 'Art Type']
✅ Clarifying Question: Are the German Die Brücke artists associated with a specific art movement or medium?
------------------------------------------------------

Generating positive clarifying questions:   3%|▎         | 33/990 [00:17<10:59,  1.45it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region and subspecies are you referring to when asking about the scientific name for a red fox?[/OUTPUT]
=========================

Generating positive clarifying questions:   4%|▎         | 37/990 [00:18<07:55,  2.01it/s]

🟩 Row 36
Q: What is the scientific name for a red fox?
Facets: ['Geographical Region', 'Subspecies or Variety']
✅ Clarifying Question: In which geographical region and subspecies are you referring to when asking about the scientific name for a red fox?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period and specific role do you refer to the father of accounting?[/OUTPUT]
=========================

Generating positive clarifying questions:   4%|▍         | 38/990 [00:19<08:42,  1.82it/s]

🟩 Row 37
Q: Who is the father of accounting when and what did he describe?
Facets: ['Role Definition', 'Time Period']
✅ Clarifying Question: In which time period and specific role do you refer to the father of accounting?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which jurisdiction, during which historical period, and for what severity of crime are you asking about the number of jury members in a criminal trial?[/OUTPUT]
=========================

Generating positive clarifying questions:   4%|▍         | 40/990 [00:20<08:48,  1.80it/s]

🟩 Row 39
Q: How many jury members in a criminal trial?
Facets: ['Jurisdiction', 'Historical Period', 'Severity of Crime']
✅ Clarifying Question: In which jurisdiction, during which historical period, and for what severity of crime are you asking about the number of jury members in a criminal trial?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the team with the highest goal tally or the goalkeeper with the most conceded goals, and is this for the current season or a specific past season?[/OUTPUT]
=========================


🟩 Row 40
Q: Who has conceded the most goals in the premiership?
Facets: ['Type of Entity (Team/Goalkeeper)']
✅ Clarifying Question: Are you asking about the team with the highest goal tally or the goalkeeper with the most conceded goals, and is this for the current season or a specific past season?
------------------------------------------------------

Generating positive clarifying questions:   4%|▍         | 41/990 [00:21<10:35,  1.49it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about a particular country or region, and if you're referring to the removal of First Nations children from their homes?[/OUTPUT]
=========================

Generating positive clarifying questions:   4%|▍         | 42/990 [00:22<11:57,  1.32it/s]

🟩 Row 41
Q: Where did the 60's scoop take place?
Facets: ['Geographical Level', 'Type of Entity Involved']
✅ Clarifying Question: Could you specify whether you're asking about a particular country or region, and if you're referring to the removal of First Nations children from their homes?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Is the nationality of the inventor you're asking about relevant, and if so, could you specify which nationality you are interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:   5%|▍         | 45/990 [00:23<08:57,  1.76it/s]

🟩 Row 44
Q: Who invented the process to remove impurities by blasts of cold air blown through heated iron?
Facets: ['Nationality']
✅ Clarifying Question: Is the nationality of the inventor you're asking about relevant, and if so, could you specify which nationality you are interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which season and during which time period were you referring to when asking about who played Lionel in All in the Family?[/OUTPUT]
=========================

Generating positive clarifying questions:   5%|▍         | 47/990 [00:24<08:34,  1.83it/s]

🟩 Row 46
Q: Who played lionel in all in the family?
Facets: ['Time Period', 'Season']
✅ Clarifying Question: In which season and during which time period were you referring to when asking about who played Lionel in All in the Family?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the origin aspect, the creator, or the inspiration source of the phrase "just do it"?[/OUTPUT]
=========================

Generating positive clarifying questions:   5%|▍         | 49/990 [00:25<08:14,  1.90it/s]

🟩 Row 48
Q: Where did the saying just do it come from?
Facets: ['Origin Aspect', 'Creator', 'Inspiration Source']
✅ Clarifying Question: Are you asking about the origin aspect, the creator, or the inspiration source of the phrase "just do it"?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the host country's role or another organizing body, and which World Cup edition you're referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:   5%|▌         | 50/990 [00:27<09:49,  1.59it/s]

🟩 Row 49
Q: When did brazil organize its first world cup?
Facets: ['Event Type', 'Organizer Role']
✅ Clarifying Question: Could you specify whether you're asking about the host country's role or another organizing body, and which World Cup edition you're referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're referring to economic, political, or military ideas, and if there's a particular country or region you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:   5%|▌         | 52/990 [00:28<09:31,  1.64it/s]

🟩 Row 51
Q: What idea was used to justify u.s. foreign policy during the cold war era?
Facets: ['Type of Entity']
✅ Clarifying Question: Could you specify whether you're referring to economic, political, or military ideas, and if there's a particular country or region you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region and what specific release scope are you inquiring about for The Sims Mobile?[/OUTPUT]
=========================

Generating positive clarifying questions:   5%|▌         | 53/990 [00:29<10:45,  1.45it/s]

🟩 Row 52
Q: When is the sims mobile supposed to come out?
Facets: ['Geographical Region', 'Release Scope']
✅ Clarifying Question: In which geographical region and what specific release scope are you inquiring about for The Sims Mobile?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which year's Peach Bowl are you asking about?[/OUTPUT]
=========================

Generating positive clarifying questions:   5%|▌         | 54/990 [00:30<11:35,  1.35it/s]

🟩 Row 53
Q: Who is playing in the peach bowl this year?
Facets: ['Year']
✅ Clarifying Question: Which year's Peach Bowl are you asking about?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a single Grand Slam victory or multiple wins, and are you interested in the most recent occurrence?[/OUTPUT]
=========================

Generating positive clarifying questions:   6%|▌         | 56/990 [00:31<11:00,  1.41it/s]

🟩 Row 55
Q: When did ireland rugby last win the grand slam?
Facets: ['Number of Grand Slams Won']
✅ Clarifying Question: Are you asking about a single Grand Slam victory or multiple wins, and are you interested in the most recent occurrence?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the most recent Super Bowl appearance by any team with "eagles" in its name, or specifically the Philadelphia Eagles?[/OUTPUT]
=========================

Generating positive clarifying questions:   6%|▌         | 57/990 [00:32<13:17,  1.17it/s]

🟩 Row 56
Q: When was the last time eagles were in the superbowl?
Facets: ['Order of Occurrence']
✅ Clarifying Question: Are you asking about the most recent Super Bowl appearance by any team with "eagles" in its name, or specifically the Philadelphia Eagles?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the gender of the first captain, or if there was a specific category of Indian cricket team in mind?[/OUTPUT]
=========================

Generating positive clarifying questions:   6%|▌         | 58/990 [00:33<14:21,  1.08it/s]

🟩 Row 57
Q: Whi was the first captain of indian cricket team?
Facets: ['Gender', 'Team Category']
✅ Clarifying Question: Are you asking about the gender of the first captain, or if there was a specific category of Indian cricket team in mind?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which order were the Ten Commandments listed in the book of the Bible?[/OUTPUT]
=========================

Generating positive clarifying questions:   7%|▋         | 65/990 [00:34<05:32,  2.78it/s]

🟩 Row 64
Q: What book of the bible is the ten commandments in?
Facets: ['Order of Mention']
✅ Clarifying Question: In which order were the Ten Commandments listed in the book of the Bible?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year are you asking about the minister of agriculture in South Africa?[/OUTPUT]
=========================

Generating positive clarifying questions:   7%|▋         | 67/990 [00:35<05:45,  2.67it/s]

🟩 Row 66
Q: Who is the minister of agriculture in south africa?
Facets: ['Year']
✅ Clarifying Question: In which year are you asking about the minister of agriculture in South Africa?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year's release schedule are you asking about the new Star Wars movie?[/OUTPUT]
=========================

Generating positive clarifying questions:   7%|▋         | 69/990 [00:36<05:54,  2.60it/s]

🟩 Row 68
Q: What day is the new star wars movie?
Facets: ['Year']
✅ Clarifying Question: In which year's release schedule are you asking about the new Star Wars movie?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific model variant of the LG G6, such as the international or US version?[/OUTPUT]
=========================

Generating positive clarifying questions:   7%|▋         | 70/990 [00:37<07:13,  2.12it/s]

🟩 Row 69
Q: When did the lg g6 phone come out?
Facets: ['Model Variant']
✅ Clarifying Question: Are you asking about a specific model variant of the LG G6, such as the international or US version?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the character who sings the song "What's Love Got to Do with It" in the movie or the singer of the song within the movie's plot?[/OUTPUT]
=========================

Generating positive clarifying questions:   7%|▋         | 72/990 [00:38<07:53,  1.94it/s]

🟩 Row 71
Q: Who sings in what's love got to do with it movie?
Facets: ['Character Name']
✅ Clarifying Question: Are you asking about the character who sings the song "What's Love Got to Do with It" in the movie or the singer of the song within the movie's plot?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the NFL team 'Jets', and do you want the exact date or just the year of their last Super Bowl victory?[/OUTPUT]
=========================

Generating positive clarifying questions:   8%|▊         | 76/990 [00:39<06:08,  2.48it/s]

🟩 Row 75
Q: When was the last time the jets won a superbowl?
Facets: ['Time Granularity']
✅ Clarifying Question: Are you asking about the NFL team 'Jets', and do you want the exact date or just the year of their last Super Bowl victory?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the voice actor for Cortana in a specific Halo game or series?[/OUTPUT]
=========================

Generating positive clarifying questions:   8%|▊         | 77/990 [00:40<07:05,  2.15it/s]

🟩 Row 76
Q: Who does the voice of cortana in halo?
Facets: ['Media Type', 'Specific Series or Game']
✅ Clarifying Question: Are you asking about the voice actor for Cortana in a specific Halo game or series?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which medium (e.g., film, television series) were you referring to when asking about Obi-Wan Kenobi in Star Wars Episode 3?[/OUTPUT]
=========================

Generating positive clarifying questions:   8%|▊         | 80/990 [00:41<06:38,  2.28it/s]

🟩 Row 79
Q: Who played obi wan kenobi in star wars episode 3?
Facets: ['Medium of Representation']
✅ Clarifying Question: In which medium (e.g., film, television series) were you referring to when asking about Obi-Wan Kenobi in Star Wars Episode 3?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are these movies part of a specific hobbit trilogy or do you mean the entire series of films based on J.R.R. Tolkien's works?[/OUTPUT]
=========================

Generating positive clarifying questions:   8%|▊         | 82/990 [00:42<07:03,  2.14it/s]

🟩 Row 81
Q: What are the names of the three hobbit movies?
Facets: ['Movie Series']
✅ Clarifying Question: Are these movies part of a specific hobbit trilogy or do you mean the entire series of films based on J.R.R. Tolkien's works?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the historical origin of the term "black death" or a specific event, and if there's a particular geographical region you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:   8%|▊         | 83/990 [00:44<08:58,  1.68it/s]

🟩 Row 82
Q: Where do historians believe the black death originated?
Facets: ['Type of Entity', 'Meaning of Term']
✅ Clarifying Question: Could you specify whether you're asking about the historical origin of the term "black death" or a specific event, and if there's a particular geographical region you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are the tests for performance-enhancing drugs or recreational drugs, and which specific drug tests are conducted at the Olympics?[/OUTPUT]
=========================

Generating positive clarifying questions:   9%|▉         | 87/990 [00:45<06:23,  2.35it/s]

🟩 Row 86
Q: How do they test for drugs at the olympics?
Facets: ['Type of Drug']
✅ Clarifying Question: Are the tests for performance-enhancing drugs or recreational drugs, and which specific drug tests are conducted at the Olympics?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you asking about the Secretary of State in Arkansas?[/OUTPUT]
=========================

Generating positive clarifying questions:   9%|▉         | 89/990 [00:45<06:14,  2.40it/s]

🟩 Row 88
Q: Who is the secretary of state in arkansas?
Facets: ['Time Period']
✅ Clarifying Question: In which time period are you asking about the Secretary of State in Arkansas?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the musical score or the lyrics for Shrek the Musical?[/OUTPUT]
=========================

Generating positive clarifying questions:   9%|▉         | 90/990 [00:46<07:06,  2.11it/s]

🟩 Row 89
Q: Who wrote the music for shrek the musical?
Facets: ['Type of Music (Scores/Lyrics)']
✅ Clarifying Question: Are you asking about the musical score or the lyrics for Shrek the Musical?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the standard dimensions of a California king size mattress or a specific mattress that might have variations?[/OUTPUT]
=========================

Generating positive clarifying questions:  10%|▉         | 96/990 [00:47<04:22,  3.40it/s]

🟩 Row 95
Q: What size is a california king size mattress?
Facets: ['Measurement Dimension']
✅ Clarifying Question: Are you asking about the standard dimensions of a California king size mattress or a specific mattress that might have variations?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're referring to land area or another measurement criterion for determining the largest province?[/OUTPUT]
=========================

Generating positive clarifying questions:  10%|▉         | 98/990 [00:48<04:48,  3.09it/s]

🟩 Row 97
Q: What is the largest province in sri lanka?
Facets: ['Measurement Criterion']
✅ Clarifying Question: Could you specify whether you're referring to land area or another measurement criterion for determining the largest province?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the TV series or movie adaptation, and which specific film title are you referring to for "the man in the yellow hat"?[/OUTPUT]
=========================

Generating positive clarifying questions:  10%|█         | 101/990 [00:49<05:00,  2.96it/s]

🟩 Row 100
Q: Who plays the man in the yellow hat on curious george?
Facets: ['Medium (TV series vs. Movie)', 'Film Title']
✅ Clarifying Question: Are you asking about the TV series or movie adaptation, and which specific film title are you referring to for "the man in the yellow hat"?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In what year did Amy Pond first appear on Doctor Who, and was she a child or an adult character?[/OUTPUT]
=========================

Generating positive clarifying questions:  11%|█         | 104/990 [00:50<04:52,  3.03it/s]

🟩 Row 103
Q: Actress who played amy pond in doctor who?
Facets: ['Character Age']
✅ Clarifying Question: In what year did Amy Pond first appear on Doctor Who, and was she a child or an adult character?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the original version or a specific cover, by whom, in what year, and whether as a group or individual performance?[/OUTPUT]
=========================

Generating positive clarifying questions:  11%|█         | 105/990 [00:51<06:16,  2.35it/s]

🟩 Row 104
Q: Who sings you make me feel like dancing?
Facets: ['Vocal Role', 'Year of Cover', 'Covered Artist', 'Group vs Individual Singers', 'Song Version']
✅ Clarifying Question: Are you asking about the original version or a specific cover, by whom, in what year, and whether as a group or individual performance?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In what context do you want to know the legal drinking age in Russia?[/OUTPUT]
=========================


🟩 Row 105
Q: What's the legal age to drink in russia?
Facets: ['Context of Drinking']
✅ Clarifying Question: In what context do you want to know the legal drinking age in Russia?
------------------------------------------------------

Generating positive clarifying questions:  11%|█         | 106/990 [00:52<07:03,  2.09it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Do you need to know if parental consent is required for those under 18 to get a tattoo in Indiana?[/OUTPUT]
=========================

Generating positive clarifying questions:  11%|█         | 107/990 [00:53<08:20,  1.77it/s]

🟩 Row 106
Q: How old do you have to be to get a tattoo in indiana?
Facets: ['Parental Consent Required']
✅ Clarifying Question: Do you need to know if parental consent is required for those under 18 to get a tattoo in Indiana?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Is the princess you're asking about the main character or a supporting one, and does she have any siblings in the story?[/OUTPUT]
=========================

Generating positive clarifying questions:  11%|█         | 110/990 [00:54<06:49,  2.15it/s]

🟩 Row 109
Q: What is the name of the princess in frozen?
Facets: ['Character Role', 'Sibling Relationship']
✅ Clarifying Question: Is the princess you're asking about the main character or a supporting one, and does she have any siblings in the story?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about California becoming a state in general terms, or specifically within a certain time frame, such as during the 19th century?[/OUTPUT]
=========================


🟩 Row 110
Q: When did california become a state of the united states?
Facets: ["Definition of 'become a state'", 'Time Frame']
✅ Clarifying Question: Are you asking about California becoming a state in general terms, or specifically within a certain time frame, such as during the 19th century?
------------------------------------------------------

Generating positive clarifying questions:  12%|█▏        | 115/990 [00:56<06:00,  2.43it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Do you mean the movie or the stage production, and which specific version of "High School Musical" are you referring to?[/OUTPUT]
=========================


🟩 Row 114
Q: Who sings bet on it in high school musical?
Facets: ['Media Type', 'Production Stage']
✅ Clarifying Question: Do you mean the movie or the stage production, and which specific version of "High School Musical" are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about a single song or the entire album, and which specific Ariana Grande album you're referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  12%|█▏        | 118/990 [00:57<05:44,  2.53it/s]

🟩 Row 117
Q: When did ariana grandes new album come out?
Facets: ['Album Type', 'Album Name']
✅ Clarifying Question: Could you specify if you're asking about a single song or the entire album, and which specific Ariana Grande album you're referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the start and end dates according to the general consensus, or if there's a particular source you're referring to for the end date?[/OUTPUT]
=========================

Generating positive clarifying questions:  12%|█▏        | 119/990 [00:58<07:26,  1.95it/s]

🟩 Row 118
Q: When did the edwardian era start and end?
Facets: ['Start Date', 'End Date', 'Consensus on End Date']
✅ Clarifying Question: Could you specify whether you're asking about the start and end dates according to the general consensus, or if there's a particular source you're referring to for the end date?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In Marley and Me, were you referring to the role the dog played in the story or its age during the events?[/OUTPUT]
=========================


🟩 Row 119
Q: Who was the dog in marley and me?
Facets: ['Role in Story', 'Age of Dog']
✅ Clarifying Question: In Marley and Me, were you referring to the role the dog played in the story or its age during the events?
------------------------------------------------------

Generating positive clarifying questions:  12%|█▏        | 120/990 [00:59<08:35,  1.69it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical features and under what specific conditions is mass wasting most likely to occur?[/OUTPUT]
=========================

Generating positive clarifying questions:  12%|█▏        | 122/990 [01:00<07:44,  1.87it/s]

🟩 Row 121
Q: Where is mass wasting most likely to occur?
Facets: ['Geographical Features', 'Conditions']
✅ Clarifying Question: In which geographical features and under what specific conditions is mass wasting most likely to occur?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year were the music scores written for Conan the Barbarian?[/OUTPUT]
=========================

Generating positive clarifying questions:  13%|█▎        | 124/990 [01:01<07:03,  2.05it/s]

🟩 Row 123
Q: Who wrote the music for conan the barbarian?
Facets: ['Year']
✅ Clarifying Question: In which year were the music scores written for Conan the Barbarian?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're interested in the intended age group, the general content, or the serious illnesses of the young characters in "The Fault in Our Stars"?[/OUTPUT]
=========================


🟩 Row 126
Q: What type of book is the fault in our stars?
Facets: ['Intended Age Group', 'General Content', "Young Characters' Serious Illnesses"]
✅ Clarifying Question: Could you specify if you're interested in the intended age group, the general content, or the serious illnesses of the young characters in "The Fault in Our Stars"?
------------------------------------------------------

Generating positive clarifying questions:  13%|█▎        | 127/990 [01:02<07:14,  1.99it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the national policy implementation date or a specific state's implementation date for the old age pension in Australia?[/OUTPUT]
=========================


🟩 Row 127
Q: When did the old age pension start in australia?
Facets: ['Geographical Scope', 'National vs. Local Policy']
✅ Clarifying Question: Are you asking about the national policy implementation date or a specific state's implementation date for the old age pension in Australia?
------------------------------------------------------

Generating positive clarifying questions:  13%|█▎        | 128/990 [01:04<09:12,  1.56it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the plant's name from the Little Shop of Horrors adaptation from a particular year or genre?[/OUTPUT]
=========================

Generating positive clarifying questions:  13%|█▎        | 129/990 [01:05<11:30,  1.25it/s]

🟩 Row 128
Q: What was the name of the plant from little shop of horrors?
Facets: ['Medium Type', 'Adaptation Year', 'Genre']
✅ Clarifying Question: Could you specify if you're asking about the plant's name from the Little Shop of Horrors adaptation from a particular year or genre?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time frame do you want to know about the brightest star visible from Earth?[/OUTPUT]
=========================

Generating positive clarifying questions:  13%|█▎        | 131/990 [01:07<10:30,  1.36it/s]

🟩 Row 130
Q: What is the brightest star seen from earth?
Facets: ['Time Frame']
✅ Clarifying Question: In which time frame do you want to know about the brightest star visible from Earth?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about a specific type of asset the sea dogs had, or the cause of their defeat, or both?[/OUTPUT]
=========================

Generating positive clarifying questions:  14%|█▎        | 134/990 [01:08<08:57,  1.59it/s]

🟩 Row 133
Q: What did the sea dogs have that led to their defeat of the spanish armada?
Facets: ['Type of Asset', 'Event Cause']
✅ Clarifying Question: Could you specify whether you're asking about a specific type of asset the sea dogs had, or the cause of their defeat, or both?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year and month were you referring to when asking about the opening of the Forbidden City to the public?[/OUTPUT]
=========================


🟩 Row 135
Q: When was the forbidden city opened to the public?
Facets: ['Time Granularity', 'Unit of Time']
✅ Clarifying Question: In which year and month were you referring to when asking about the opening of the Forbidden City to the public?
------------------------------------------------------

Generating positive clarifying questions:  14%|█▎        | 136/990 [01:09<09:08,  1.56it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the standardization of king size beds or the size specifications for the first king size bed made?[/OUTPUT]
=========================

Generating positive clarifying questions:  14%|█▍        | 139/990 [01:11<07:51,  1.81it/s]

🟩 Row 138
Q: When was the first king size bed made?
Facets: ['Standardization Status', 'Size Specification']
✅ Clarifying Question: Could you specify whether you're asking about the standardization of king size beds or the size specifications for the first king size bed made?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the purchase price, operating cost, or another type of cost, and if there's a specific time period you're interested in? Additionally, are you referring to a new or used aircraft?[/OUTPUT]
=========================

Generating positive clarifying questions:  14%|█▍        | 141/990 [01:12<08:44,  1.62it/s]

🟩 Row 140
Q: What is the cost of an airbus a380?
Facets: ['Time Period', 'Cost Type', 'Entity Type']
✅ Clarifying Question: Could you specify whether you're asking about the purchase price, operating cost, or another type of cost, and if there's a specific time period you're interested in? Additionally, are you referring to a new or used aircraft?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the purpose of Rolls Royce's jet engines or the specific type of jet engines they produce, and do you have a particular time frame in mind?[/OUTPUT]
=========================

Generating positive clarifying questions:  14%|█▍        | 142/990 [01:13<10:12,  1.38it/s]

🟩 Row 141
Q: When did rolls royce start making jet engines?
Facets: ['Purpose of Jet Engines', 'Type of Engine']
✅ Clarifying Question: Are you asking about the purpose of Rolls Royce's jet engines or the specific type of jet engines they produce, and do you have a particular time frame in mind?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region are you referring to when you ask about "I Can't Get No Satisfaction"?[/OUTPUT]
=========================

Generating positive clarifying questions:  14%|█▍        | 143/990 [01:14<10:40,  1.32it/s]

🟩 Row 142
Q: When did i can't get no satisfaction come out?
Facets: ['Geographical Region']
✅ Clarifying Question: In which geographical region are you referring to when you ask about "I Can't Get No Satisfaction"?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a male or female player, and which specific FIFA World Cup final are you referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  15%|█▍        | 146/990 [01:15<08:08,  1.73it/s]

🟩 Row 145
Q: Who scored hattrick in fifa world cup final?
Facets: ['Sport Type', 'Gender']
✅ Clarifying Question: Are you asking about a male or female player, and which specific FIFA World Cup final are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the highest paid Hollywood actor based on a single film's salary, or do you consider all acting roles in a movie, and which specific movie are we comparing?[/OUTPUT]
=========================

Generating positive clarifying questions:  15%|█▌        | 149/990 [01:17<08:39,  1.62it/s]

🟩 Row 148
Q: Highest paid hollywood actor for a single movie?
Facets: ['Salary Basis', 'Actor Definition']
✅ Clarifying Question: Are you asking about the highest paid Hollywood actor based on a single film's salary, or do you consider all acting roles in a movie, and which specific movie are we comparing?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the total land area or another measurement criterion for the top 10 largest countries in Africa?[/OUTPUT]
=========================

Generating positive clarifying questions:  15%|█▌        | 153/990 [01:18<06:25,  2.17it/s]

🟩 Row 152
Q: List of top 10 largest countries in africa?
Facets: ['Measurement Criterion']
✅ Clarifying Question: Are you asking about the total land area or another measurement criterion for the top 10 largest countries in Africa?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the theme song for a specific episode year of Only Fools and Horses?[/OUTPUT]
=========================

Generating positive clarifying questions:  16%|█▌        | 154/990 [01:20<08:11,  1.70it/s]

🟩 Row 153
Q: Who sings the only fools and horses theme?
Facets: ['Theme Type', 'Episode Year']
✅ Clarifying Question: Are you asking about the theme song for a specific episode year of Only Fools and Horses?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the origin of the phrase or the setting of the saying, and if there's a particular context or time period you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  16%|█▌        | 155/990 [01:22<11:13,  1.24it/s]

🟩 Row 154
Q: Where does the saying all quiet on the western front come from?
Facets: ['Type of Entity', 'Role or Function']
✅ Clarifying Question: Could you specify whether you're asking about the origin of the phrase or the setting of the saying, and if there's a particular context or time period you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the episode number or release date, and on which platform will it be available?[/OUTPUT]
=========================


🟩 Row 155
Q: When is the next batman telltale coming out?
Facets: ['Episode Number', 'Platform']
✅ Clarifying Question: Are you asking about the episode number or release date, and on which platform will it be available?
------------------------------------------------------

Generating positive clarifying questions:  16%|█▌        | 156/990 [01:23<12:28,  1.11it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which season of "The OC" did Ryan have a brother, and were you referring to a specific role or character development?[/OUTPUT]
=========================

Generating positive clarifying questions:  16%|█▌        | 157/990 [01:25<14:56,  1.08s/it]

🟩 Row 156
Q: Who played ryan's brother in the oc?
Facets: ['Season', 'Role Specificity']
✅ Clarifying Question: In which season of "The OC" did Ryan have a brother, and were you referring to a specific role or character development?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the current population or a historical figure, and do you need a specific date range for the estimate?[/OUTPUT]
=========================


🟩 Row 158
Q: What is the population of rochester new york?
Facets: ['Time Period', 'Population Estimate']
✅ Clarifying Question: Are you asking about the current population or a historical figure, and do you need a specific date range for the estimate?
------------------------------------------------------

Generating positive clarifying questions:  16%|█▌        | 159/990 [01:26<13:20,  1.04it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the People's Republic of China or the Chinese Taipei delegation representing China, and which specific UN body's membership are you inquiring about?[/OUTPUT]
=========================

Generating positive clarifying questions:  16%|█▋        | 161/990 [01:28<12:35,  1.10it/s]

🟩 Row 160
Q: When did china become a member of the united nations?
Facets: ['Type of Entity']
✅ Clarifying Question: Are you asking about the People's Republic of China or the Chinese Taipei delegation representing China, and which specific UN body's membership are you inquiring about?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify which Lorax story you're referring to and whether you're asking about a book, movie, or other medium?[/OUTPUT]
=========================

Generating positive clarifying questions:  16%|█▋        | 162/990 [01:29<13:44,  1.00it/s]

🟩 Row 161
Q: Who cut down the trees in the lorax?
Facets: ['Character Identity', 'Medium of Representation']
✅ Clarifying Question: Could you specify which Lorax story you're referring to and whether you're asking about a book, movie, or other medium?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if Jessica Fletcher moved in a specific episode, across seasons, or during the overall timeline of the show? Additionally, which version of the show are you referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  16%|█▋        | 163/990 [01:31<15:54,  1.15s/it]

🟩 Row 162
Q: When does jessica fletcher moved to new york?
Facets: ['Media Work', 'Episode Information', 'Character Timeline']
✅ Clarifying Question: Could you specify if Jessica Fletcher moved in a specific episode, across seasons, or during the overall timeline of the show? Additionally, which version of the show are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you looking for a record of the route, time taken, or total distance covered during the cycling journey from Land's End to John O'Groats?[/OUTPUT]
=========================

Generating positive clarifying questions:  17%|█▋        | 164/990 [01:33<17:10,  1.25s/it]

🟩 Row 163
Q: Record for cycling from lands end to john o'groats?
Facets: ['Type of Entity', 'Aspect of Record']
✅ Clarifying Question: Are you looking for a record of the route, time taken, or total distance covered during the cycling journey from Land's End to John O'Groats?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the political party of the candidates, or the stage of the election such as primary or general, in Florida's 2018 attorney general race?[/OUTPUT]
=========================

Generating positive clarifying questions:  17%|█▋        | 165/990 [01:34<18:44,  1.36s/it]

🟩 Row 164
Q: Who is running for attorney general in florida 2018?
Facets: ['Political Party', 'Election Stage']
✅ Clarifying Question: Are you asking about the political party of the candidates, or the stage of the election such as primary or general, in Florida's 2018 attorney general race?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the NCAA or another league, and specifically which type of football (American or Canadian)?[/OUTPUT]
=========================

Generating positive clarifying questions:  17%|█▋        | 166/990 [01:36<18:22,  1.34s/it]

🟩 Row 165
Q: When did university of georgia start playing football?
Facets: ['League/Association', 'Type of Football']
✅ Clarifying Question: Are you asking about the NCAA or another league, and specifically which type of football (American or Canadian)?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the primary filming location or a particular scene, and whether you're interested in the U.S. or international locations?[/OUTPUT]
=========================

Generating positive clarifying questions:  17%|█▋        | 167/990 [01:37<18:45,  1.37s/it]

🟩 Row 166
Q: Where was the movie charlie st. cloud filmed?
Facets: ['Type of Location', 'Specific Location Type']
✅ Clarifying Question: Could you specify if you're asking about the primary filming location or a particular scene, and whether you're interested in the U.S. or international locations?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year are you asking about the NFC Championship game involving the Eagles?[/OUTPUT]
=========================


🟩 Row 167
Q: Who do the eagles play in the nfc championship game?
Facets: ['Year']
✅ Clarifying Question: In which year are you asking about the NFC Championship game involving the Eagles?
------------------------------------------------------

Generating positive clarifying questions:  17%|█▋        | 168/990 [01:38<17:32,  1.28s/it]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the start and end points of the river within a specific state or basin, or are these locations relative to a particular geographical context?[/OUTPUT]
=========================


🟩 Row 168
Q: Where does the cumberland river begin and end?
Facets: ['Start Location', 'End Location']
✅ Clarifying Question: Are you asking about the start and end points of the river within a specific state or basin, or are these locations relative to a particular geographical context?
------------------------------------------------------

Generating positive clarifying questions:  17%|█▋        | 169/990 [01:40<18:35,  1.36s/it]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the size of the mattress and whether you prefer the measurements in inches or centimeters?[/OUTPUT]
=========================


🟩 Row 170
Q: What are the measurements of a full mattress?
Facets: ['Mattress Size', 'Measurement Unit']
✅ Clarifying Question: Could you specify the size of the mattress and whether you prefer the measurements in inches or centimeters?
------------------------------------------------------

Generating positive clarifying questions:  17%|█▋        | 171/990 [01:41<13:46,  1.01s/it]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the time when color television was introduced in the UK, for which specific channels, and whether it covered the entire country or just certain regions?[/OUTPUT]
=========================

Generating positive clarifying questions:  17%|█▋        | 173/990 [01:42<12:37,  1.08it/s]

🟩 Row 172
Q: When did colour tv start in the uk?
Facets: ['Event Category', 'Broadcast Channel', 'Scope of Coverage', 'Time of Introduction']
✅ Clarifying Question: Are you asking about the time when color television was introduced in the UK, for which specific channels, and whether it covered the entire country or just certain regions?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the exact date or season, and whether you're asking about a home game or another type of event?[/OUTPUT]
=========================

Generating positive clarifying questions:  18%|█▊        | 177/990 [01:44<08:25,  1.61it/s]

🟩 Row 176
Q: When did the packers play at camp randall?
Facets: ['Time Frame', 'Event Type']
✅ Clarifying Question: Could you specify the exact date or season, and whether you're asking about a home game or another type of event?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which season and for which type of game do you want to know about the player with the most passing touchdowns?[/OUTPUT]
=========================

Generating positive clarifying questions:  18%|█▊        | 179/990 [01:45<08:18,  1.63it/s]

🟩 Row 178
Q: Who has the most passing touchdowns in the nfl?
Facets: ['Time Frame', 'Game Type']
✅ Clarifying Question: In which season and for which type of game do you want to know about the player with the most passing touchdowns?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific episode number, a particular series year, or a different version of Berserk when you inquire about new episode releases?[/OUTPUT]
=========================


🟩 Row 179
Q: When do new episodes of berserk come out?
Facets: ['Episode Number', 'Series Year', 'Series Version']
✅ Clarifying Question: Are you asking about a specific episode number, a particular series year, or a different version of Berserk when you inquire about new episode releases?
------------------------------------------------------

Generating positive clarifying questions:  18%|█▊        | 182/990 [01:48<10:06,  1.33it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the process for appointing members to the national level state human rights commissions, or specifically about a particular state's commission, and who holds the power to make these appointments?[/OUTPUT]
=========================


🟩 Row 181
Q: Who appoints the member of state human rights commission in india?
Facets: ['Action Verb', 'Role of Appointer']
✅ Clarifying Question: Are you asking about the process for appointing members to the national level state human rights commissions, or specifically about a particular state's commission, and who holds the power to make these appointments?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the character named "Dresser" in the live-action or animated version of Beauty and the Beast?[/OUTPUT]
=========================

Generating positive clarifying questions:  18%|█▊        | 183/990 [01:49<11:34,  1.16it/s]

🟩 Row 182
Q: Who played the dresser in beauty and the beast?
Facets: ['Film Type', 'Character Name']
✅ Clarifying Question: Are you asking about the character named "Dresser" in the live-action or animated version of Beauty and the Beast?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the leadership role and party affiliation of the Senate leader in 2018?[/OUTPUT]
=========================


🟩 Row 184
Q: Who is the leader of the senate 2018?
Facets: ['Leadership Role', 'Party Affiliation']
✅ Clarifying Question: Could you specify whether you're asking about the leadership role and party affiliation of the Senate leader in 2018?
------------------------------------------------------

Generating positive clarifying questions:  19%|█▊        | 185/990 [01:51<10:47,  1.24it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the episode number, title, and air date of Full House where Michelle starts kindergarten?[/OUTPUT]
=========================


🟩 Row 185
Q: Full house michelle's first day of kindergarten?
Facets: ['Episode Number', 'Episode Title', 'Air Date']
✅ Clarifying Question: Could you specify the episode number, title, and air date of Full House where Michelle starts kindergarten?
------------------------------------------------------

Generating positive clarifying questions:  19%|█▉        | 186/990 [01:52<12:07,  1.10it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which version of The Odd Couple TV show and what year are you asking about?[/OUTPUT]
=========================


🟩 Row 186
Q: Who played oscar in the odd couple tv show?
Facets: ['Year', 'Version of the Show']
✅ Clarifying Question: In which version of The Odd Couple TV show and what year are you asking about?
------------------------------------------------------

Generating positive clarifying questions:  19%|█▉        | 187/990 [01:53<13:03,  1.02it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the number of songs performed in the movie or who performs specific songs from the movie's soundtrack?[/OUTPUT]
=========================

Generating positive clarifying questions:  19%|█▉        | 188/990 [01:54<13:57,  1.04s/it]

🟩 Row 187
Q: Who sings in the movie walk the line?
Facets: ['Number of Songs']
✅ Clarifying Question: Are you asking about the number of songs performed in the movie or who performs specific songs from the movie's soundtrack?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about male or female tennis players?[/OUTPUT]
=========================

Generating positive clarifying questions:  19%|█▉        | 190/990 [01:56<11:06,  1.20it/s]

🟩 Row 189
Q: Who has won the most tennis matches in history?
Facets: ['Gender']
✅ Clarifying Question: Are you asking about male or female tennis players?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific version of "Rock Me Mama Like a Wagon Wheel" are you asking about?[/OUTPUT]
=========================

Generating positive clarifying questions:  19%|█▉        | 192/990 [01:57<09:44,  1.36it/s]

🟩 Row 191
Q: Original singer of rock me mama like a wagon wheel?
Facets: ['Part of Song']
✅ Clarifying Question: Which specific version of "Rock Me Mama Like a Wagon Wheel" are you asking about?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a new episode or season of The Walking Dead, and specifically which season or title are you interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  19%|█▉        | 193/990 [01:58<11:16,  1.18it/s]

🟩 Row 192
Q: When is the next telltale walking dead coming out?
Facets: ['Season Number', 'Title of Game']
✅ Clarifying Question: Are you asking about a new episode or season of The Walking Dead, and specifically which season or title are you interested in?
------------------------------------------------------

Generating positive clarifying questions:  20%|██        | 199/990 [01:59<05:59,  2.20it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the career total or season total for triple doubles, and do you want the record holder for all NBA history or a specific time frame?[/OUTPUT]
=========================


🟩 Row 198
Q: Who holds the most triple doubles in nba history?
Facets: ['Time Frame: Career vs. Season', 'Type of Record: Career Total vs. Season Total']
✅ Clarifying Question: Are you asking about the career total or season total for triple doubles, and do you want the record holder for all NBA history or a specific time frame?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about a movie or another type of work, and if it's a specific edition or version?[/OUTPUT]
=========================

Generating positive clarifying questions:  20%|██        | 200/990 [02:01<07:44,  1.70it/s]

🟩 Row 199
Q: When did my sister's keeper come out?
Facets: ['Type of Entity']
✅ Clarifying Question: Could you specify whether you're asking about a movie or another type of work, and if it's a specific edition or version?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether Glenn Miller's final concert was a live performance or broadcasted, and provide any additional details on the location context?[/OUTPUT]
=========================

Generating positive clarifying questions:  20%|██        | 201/990 [02:02<09:28,  1.39it/s]

🟩 Row 200
Q: Where did glenn miller perform his final concert?
Facets: ['Type of Performance', 'Location Context']
✅ Clarifying Question: Could you specify whether Glenn Miller's final concert was a live performance or broadcasted, and provide any additional details on the location context?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the winning context, whether it's a specific episode type, and the time frame you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  21%|██        | 203/990 [02:04<09:11,  1.43it/s]

🟩 Row 202
Q: Who wants to be a millionaire american winner?
Facets: ['Winning Context', 'Episode Type', 'Time Frame']
✅ Clarifying Question: Could you specify the winning context, whether it's a specific episode type, and the time frame you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the specific electron acceptor in photosynthesis's light reactions or a general term for any electron acceptor in the chain?[/OUTPUT]
=========================

Generating positive clarifying questions:  21%|██        | 205/990 [02:05<09:17,  1.41it/s]

🟩 Row 204
Q: What are the final electron acceptors for the electron transport chains in light reactions?
Facets: ['Specificity of the Electron Acceptor']
✅ Clarifying Question: Are you asking about the specific electron acceptor in photosynthesis's light reactions or a general term for any electron acceptor in the chain?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country was the TV show "Who Wants to Be a Millionaire" located when the first million-dollar winner appeared?[/OUTPUT]
=========================

Generating positive clarifying questions:  21%|██        | 207/990 [02:06<09:12,  1.42it/s]

🟩 Row 206
Q: Who was the first person to win a million on who wants to be a millionaire?
Facets: ['Country', 'Prize Amount', 'TV Show Location']
✅ Clarifying Question: In which country was the TV show "Who Wants to Be a Millionaire" located when the first million-dollar winner appeared?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year and what specific work (song or musical) are you referring to when asking about the lyrics for New York, New York?[/OUTPUT]
=========================

Generating positive clarifying questions:  21%|██        | 208/990 [02:08<10:58,  1.19it/s]

🟩 Row 207
Q: Who wrote the lyrics for new york new york?
Facets: ['Year', 'Work Type']
✅ Clarifying Question: In which year and what specific work (song or musical) are you referring to when asking about the lyrics for New York, New York?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year and at what performance location was the song "It Must Be Love on the Brain" performed?[/OUTPUT]
=========================


🟩 Row 209
Q: Who sings it must be love on the brain?
Facets: ['Year', 'Performance Location']
✅ Clarifying Question: In which year and at what performance location was the song "It Must Be Love on the Brain" performed?
------------------------------------------------------

Generating positive clarifying questions:  21%|██        | 210/990 [02:09<10:06,  1.29it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which sport's All-Star Game are you asking about, and do you need information about the MVP winner from a specific team or the overall league?[/OUTPUT]
=========================


🟩 Row 210
Q: Who won mvp at the all star game 2018?
Facets: ['Sport Type', 'Event Category', 'Year']
✅ Clarifying Question: Which sport's All-Star Game are you asking about, and do you need information about the MVP winner from a specific team or the overall league?
------------------------------------------------------

Generating positive clarifying questions:  21%|██▏       | 211/990 [02:11<11:42,  1.11it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the nickname for a specific player known for strong batting or bowling in Indian cricket, or is there another aspect I should consider?[/OUTPUT]
=========================

Generating positive clarifying questions:  21%|██▏       | 212/990 [02:12<13:32,  1.04s/it]

🟩 Row 211
Q: Who is known as the wall of india in cricket?
Facets: ['Popularity of Nickname', 'Role']
✅ Clarifying Question: Are you asking about the nickname for a specific player known for strong batting or bowling in Indian cricket, or is there another aspect I should consider?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which season and what specific character role does the 'ali brother' refer to in Pretty Little Liars?[/OUTPUT]
=========================


🟩 Row 212
Q: Who plays ali brother in pretty little liars?
Facets: ['Season Range', 'Character Role']
✅ Clarifying Question: In which season and what specific character role does the 'ali brother' refer to in Pretty Little Liars?
------------------------------------------------------

Generating positive clarifying questions:  22%|██▏       | 213/990 [02:13<14:21,  1.11s/it]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In what year and for which age group version of 'Beauty and the Beast' are you asking about the actor who plays 'the beast'?[/OUTPUT]
=========================

Generating positive clarifying questions:  22%|██▏       | 215/990 [02:15<11:54,  1.09it/s]

🟩 Row 214
Q: Who plays 'the beast' in disney's live action movie beauty and the beast?
Facets: ['Character Age']
✅ Clarifying Question: In what year and for which age group version of 'Beauty and the Beast' are you asking about the actor who plays 'the beast'?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period were you referring to when asking about who played Stefano on Days of Our Lives?[/OUTPUT]
=========================

Generating positive clarifying questions:  22%|██▏       | 218/990 [02:16<08:33,  1.50it/s]

🟩 Row 217
Q: Who played stefano on days of our lives?
Facets: ['Time Period']
✅ Clarifying Question: In which time period were you referring to when asking about who played Stefano on Days of Our Lives?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period do you refer to when asking about the first periodic table, and what specific definition of 'first' are you using?[/OUTPUT]
=========================


🟩 Row 218
Q: Who made the first periodic table of elements?
Facets: ["Definition of 'first periodic table'", 'Time Period']
✅ Clarifying Question: In which time period do you refer to when asking about the first periodic table, and what specific definition of 'first' are you using?
------------------------------------------------------

Generating positive clarifying questions:  22%|██▏       | 219/990 [02:17<09:40,  1.33it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which episode and event category were you referring to when asking about Wonder Woman's mother's role on the TV series?[/OUTPUT]
=========================


🟩 Row 219
Q: Who played wonder woman's mother on the tv series?
Facets: ['Episode Name', 'Event Category']
✅ Clarifying Question: In which episode and event category were you referring to when asking about Wonder Woman's mother's role on the TV series?
------------------------------------------------------

Generating positive clarifying questions:  22%|██▏       | 220/990 [02:18<10:23,  1.23it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're referring to the five pillars of Islam or another religion, and if any particular year or context is needed?[/OUTPUT]
=========================

Generating positive clarifying questions:  22%|██▏       | 222/990 [02:19<09:07,  1.40it/s]

🟩 Row 221
Q: What is the name of the five pillars?
Facets: ['Pillar Type', 'Religious Denomination']
✅ Clarifying Question: Could you specify whether you're referring to the five pillars of Islam or another religion, and if any particular year or context is needed?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which season of Have and Have Nots are you referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  23%|██▎       | 224/990 [02:20<07:42,  1.66it/s]

🟩 Row 223
Q: The last episode of have and have nots?
Facets: ['Season']
✅ Clarifying Question: Which season of Have and Have Nots are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the release year for Assassins Creed Black Flag on a specific platform or in general?[/OUTPUT]
=========================

Generating positive clarifying questions:  23%|██▎       | 226/990 [02:21<07:09,  1.78it/s]

🟩 Row 225
Q: What year did assassins creed black flag come out?
Facets: ['Release Year', 'Platform']
✅ Clarifying Question: Are you asking about the release year for Assassins Creed Black Flag on a specific platform or in general?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the location relative to other landmarks on the strip, specifically on which side of the strip it is situated, or do you need the full address?[/OUTPUT]
=========================

Generating positive clarifying questions:  23%|██▎       | 228/990 [02:22<07:43,  1.64it/s]

🟩 Row 227
Q: Where is the cosmopolitan located on the strip?
Facets: ['Spatial Relation', 'Side of Strip', 'Address']
✅ Clarifying Question: Are you asking about the location relative to other landmarks on the strip, specifically on which side of the strip it is situated, or do you need the full address?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the character's name and gender in the animated series "Big Mouth"?[/OUTPUT]
=========================

Generating positive clarifying questions:  23%|██▎       | 230/990 [02:23<07:25,  1.70it/s]

🟩 Row 229
Q: Who plays the hormone monster in big mouth?
Facets: ['Character Name', 'Character Gender']
✅ Clarifying Question: Are you asking about the character's name and gender in the animated series "Big Mouth"?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the anime series Inuyasha specifically, or does this include any related series or movies as well?[/OUTPUT]
=========================

Generating positive clarifying questions:  23%|██▎       | 232/990 [02:25<07:50,  1.61it/s]

🟩 Row 231
Q: How many episodes of inuyasha are there total?
Facets: ['Series Specificity']
✅ Clarifying Question: Are you asking about the anime series Inuyasha specifically, or does this include any related series or movies as well?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the original source or medium of the song, and who wrote it?[/OUTPUT]
=========================

Generating positive clarifying questions:  24%|██▎       | 233/990 [02:26<09:01,  1.40it/s]

🟩 Row 232
Q: Where did the song santa claus is coming to town come from?
Facets: ['Medium of Origin', 'Authorship']
✅ Clarifying Question: Are you asking about the original source or medium of the song, and who wrote it?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the position of the songs in the soundtrack or any other details?[/OUTPUT]
=========================

Generating positive clarifying questions:  24%|██▎       | 234/990 [02:27<10:32,  1.19it/s]

🟩 Row 233
Q: List of songs from sonu ki titu ki sweety?
Facets: ['Song Position in Soundtrack']
✅ Clarifying Question: Could you specify if you're asking about the position of the songs in the soundtrack or any other details?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the height of the ride itself or the building, and specifically in which Hollywood location?[/OUTPUT]
=========================

Generating positive clarifying questions:  24%|██▎       | 235/990 [02:28<11:44,  1.07it/s]

🟩 Row 234
Q: How tall is the hollywood tower of terror?
Facets: ['Aspect of Height/Drop', 'Location']
✅ Clarifying Question: Are you asking about the height of the ride itself or the building, and specifically in which Hollywood location?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Did you mean the start and end dates for the entire Human Genome Project, or are you interested in specific phases or subprojects within it?[/OUTPUT]
=========================


🟩 Row 235
Q: When did the human genome project start and finish?
Facets: ['Time Event: Start', 'Time Event: End']
✅ Clarifying Question: Did you mean the start and end dates for the entire Human Genome Project, or are you interested in specific phases or subprojects within it?
------------------------------------------------------

Generating positive clarifying questions:  24%|██▍       | 236/990 [02:30<13:04,  1.04s/it]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the NFL team's Super Bowl victory or another context, and would you like the date in a specific format?[/OUTPUT]
=========================

Generating positive clarifying questions:  24%|██▍       | 237/990 [02:31<14:21,  1.14s/it]

🟩 Row 236
Q: When did the washington redskins last win the super bowl?
Facets: ['Time Format', 'Query Focus']
✅ Clarifying Question: Are you asking about the NFL team's Super Bowl victory or another context, and would you like the date in a specific format?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific Harry Potter movie series are you referring to, as there have been multiple with different actors playing Dumbledore?[/OUTPUT]
=========================

Generating positive clarifying questions:  24%|██▍       | 238/990 [02:33<14:55,  1.19s/it]

🟩 Row 237
Q: Who played dumbledore in the harry potter movies?
Facets: ['Movie Range']
✅ Clarifying Question: Which specific Harry Potter movie series are you referring to, as there have been multiple with different actors playing Dumbledore?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which version of "American Pie" are you asking about, and do you need the original release date or a re-release date?[/OUTPUT]
=========================

Generating positive clarifying questions:  24%|██▍       | 240/990 [02:34<12:14,  1.02it/s]

🟩 Row 239
Q: When did the song american pie come out?
Facets: ['Original Release Date', 'Re-release Date', 'Artist Version']
✅ Clarifying Question: Which version of "American Pie" are you asking about, and do you need the original release date or a re-release date?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the Tunisian national football team's ranking, or a specific club team's ranking?[/OUTPUT]
=========================


🟩 Row 240
Q: Where is tunisia football team ranked in the world?
Facets: ['Gender of Football Team']
✅ Clarifying Question: Are you asking about the Tunisian national football team's ranking, or a specific club team's ranking?
------------------------------------------------------

Generating positive clarifying questions:  24%|██▍       | 241/990 [02:35<13:17,  1.07s/it]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the live-action film adaptation or the original animated series, and which specific version of the character "beast" are you referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  24%|██▍       | 242/990 [02:37<14:38,  1.17s/it]

🟩 Row 241
Q: Who voiced beast in new beauty and the beast?
Facets: ['Medium of Performance', 'Type of Entity']
✅ Clarifying Question: Are you asking about the live-action film adaptation or the original animated series, and which specific version of the character "beast" are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Did you want to know who originally performed the song or who covered it later?[/OUTPUT]
=========================

Generating positive clarifying questions:  25%|██▍       | 243/990 [02:38<14:29,  1.16s/it]

🟩 Row 242
Q: Who sang i left my heart in sanfrancisco?
Facets: ['Original Performer', 'Subsequent Performer']
✅ Clarifying Question: Did you want to know who originally performed the song or who covered it later?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region does the trivago advertisement featuring the actress appear?[/OUTPUT]
=========================


🟩 Row 243
Q: Who is the actress that does the trivago advert?
Facets: ['Geographical Region']
✅ Clarifying Question: In which geographical region does the trivago advertisement featuring the actress appear?
------------------------------------------------------

Generating positive clarifying questions:  25%|██▍       | 244/990 [02:39<14:17,  1.15s/it]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the age of the sister character and provide her name if known?[/OUTPUT]
=========================


🟩 Row 246
Q: Who played the sister in love and basketball?
Facets: ['Age of the Character', 'Character Name']
✅ Clarifying Question: Could you specify the age of the sister character and provide her name if known?
------------------------------------------------------

Generating positive clarifying questions:  25%|██▍       | 247/990 [02:40<09:06,  1.36it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the easternmost point on the main continent of Australia, or does this include any islands?[/OUTPUT]
=========================

Generating positive clarifying questions:  25%|██▌       | 251/990 [02:41<06:17,  1.96it/s]

🟩 Row 250
Q: What is the eastern-most point of mainland australia?
Facets: ['Type of Entity', 'Geographical Region']
✅ Clarifying Question: Are you asking about the easternmost point on the main continent of Australia, or does this include any islands?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Have you specified whether you're asking about the lyrics or the composition of the song?[/OUTPUT]
=========================


🟩 Row 251
Q: Who has written the patriotic song kadam kadam badhaye ja khushi ke geet gaye ja?
Facets: ['Aspect of Writing (lyrics/composition)']
✅ Clarifying Question: Have you specified whether you're asking about the lyrics or the composition of the song?
------------------------------------------------------

Generating positive clarifying questions:  25%|██▌       | 252/990 [02:43<07:28,  1.65it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did you mean the transition from colonies to the United States as a nation, and was there a specific document or agreement involved in this process?[/OUTPUT]
=========================

Generating positive clarifying questions:  26%|██▌       | 253/990 [02:44<09:02,  1.36it/s]

🟩 Row 252
Q: When did the colonies became the united states?
Facets: ['Event Category', 'Action Verb', 'Document or Agreement']
✅ Clarifying Question: Did you mean the transition from colonies to the United States as a nation, and was there a specific document or agreement involved in this process?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the main character who narrates the show, or perhaps the actor who provided the narration?[/OUTPUT]
=========================


🟩 Row 253
Q: Who narrates the dukes of hazzard tv show?
Facets: ['Type of Entity', 'Meaning of Term']
✅ Clarifying Question: Are you asking about the main character who narrates the show, or perhaps the actor who provided the narration?
------------------------------------------------------

Generating positive clarifying questions:  26%|██▌       | 254/990 [02:45<10:25,  1.18it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific time period, conference, historical season, or the number of teams in the playoffs across all NBA seasons?[/OUTPUT]
=========================

Generating positive clarifying questions:  26%|██▌       | 255/990 [02:47<11:44,  1.04it/s]

🟩 Row 254
Q: How many teams make the playoffs in the nba?
Facets: ['Time Period', 'Conference', 'Historical Season', 'Number of Teams']
✅ Clarifying Question: Are you asking about a specific time period, conference, historical season, or the number of teams in the playoffs across all NBA seasons?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the current captain of England's men's national cricket team, or perhaps a different sequence or context?[/OUTPUT]
=========================

Generating positive clarifying questions:  26%|██▌       | 257/990 [02:48<09:56,  1.23it/s]

🟩 Row 256
Q: Current captain of the england mens test cricket team?
Facets: ['Sequence Number']
✅ Clarifying Question: Are you asking about the current captain of England's men's national cricket team, or perhaps a different sequence or context?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the start or end date, the duration of the last season, or a particular episode's air date?[/OUTPUT]
=========================

Generating positive clarifying questions:  26%|██▌       | 258/990 [02:49<11:50,  1.03it/s]

🟩 Row 257
Q: When did the last season of one tree hill air?
Facets: ['Event Timing: Start', 'Event Timing: End', 'Duration of Event']
✅ Clarifying Question: Could you specify whether you're asking about the start or end date, the duration of the last season, or a particular episode's air date?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you referring to, and which specific aspect of the scientific method are you interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  26%|██▋       | 260/990 [02:51<10:30,  1.16it/s]

🟩 Row 259
Q: Who is credited with developing the scientific method?
Facets: ['Aspect of Scientific Method', 'Time Period']
✅ Clarifying Question: In which time period are you referring to, and which specific aspect of the scientific method are you interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the character's name, the actor who played the role, or both, and in what year or type of performance?[/OUTPUT]
=========================

Generating positive clarifying questions:  27%|██▋       | 264/990 [02:52<07:11,  1.68it/s]

🟩 Row 263
Q: Name of attorney in to kill a mockingbird?
Facets: ['Character vs Actor', 'Type of Performance', 'Year of Performance']
✅ Clarifying Question: Are you asking about the character's name, the actor who played the role, or both, and in what year or type of performance?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which season's third episode of Jersey Shore family vacation are you asking about?[/OUTPUT]
=========================


🟩 Row 267
Q: When did jersey shore family vacation episode 3 air?
Facets: ['Season Number']
✅ Clarifying Question: Which season's third episode of Jersey Shore family vacation are you asking about?
------------------------------------------------------

Generating positive clarifying questions:  27%|██▋       | 268/990 [02:53<05:37,  2.14it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're referring to the method used for measuring latitudes and longitudes or the geographical reference point, and provide more details on the context or specific application in the 2nd century AD?[/OUTPUT]
=========================

Generating positive clarifying questions:  27%|██▋       | 269/990 [02:55<07:31,  1.60it/s]

🟩 Row 268
Q: Who invented the system of latitudes and longitudes in 2nd century a.d?
Facets: ['Method of Measuring Latitudes', 'Geographical Reference Point']
✅ Clarifying Question: Could you specify whether you're referring to the method used for measuring latitudes and longitudes or the geographical reference point, and provide more details on the context or specific application in the 2nd century AD?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the largest denomination of paper currency or coin, and is there a preference for the material it's made from?[/OUTPUT]
=========================

Generating positive clarifying questions:  27%|██▋       | 272/990 [02:56<06:52,  1.74it/s]

🟩 Row 271
Q: What is the largest bill made in the us?
Facets: ['Type of Bill', 'Material']
✅ Clarifying Question: Are you asking about the largest denomination of paper currency or coin, and is there a preference for the material it's made from?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which Leprechaun movie are you referring to, and in what year was it released?[/OUTPUT]
=========================


🟩 Row 272
Q: Who plays the leprechaun in the leprechaun movie?
Facets: ['Year', 'Movie Title']
✅ Clarifying Question: Which Leprechaun movie are you referring to, and in what year was it released?
------------------------------------------------------

Generating positive clarifying questions:  28%|██▊       | 273/990 [02:58<08:07,  1.47it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the current holder of the Receiver General position in Canada, and whether they are in a high-ranking official role?[/OUTPUT]
=========================


🟩 Row 274
Q: Who is the current receiver general of canada?
Facets: ['Current Status', 'Position Rank']
✅ Clarifying Question: Are you asking about the current holder of the Receiver General position in Canada, and whether they are in a high-ranking official role?
------------------------------------------------------

Generating positive clarifying questions:  28%|██▊       | 275/990 [02:59<08:12,  1.45it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region are you referring to when asking about the first Pokémon movie?[/OUTPUT]
=========================


🟩 Row 275
Q: When did the first pokemon movie come out?
Facets: ['Geographical Region']
✅ Clarifying Question: In which geographical region are you referring to when asking about the first Pokémon movie?
------------------------------------------------------

Generating positive clarifying questions:  28%|██▊       | 276/990 [03:00<09:02,  1.32it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about when a specific episode of Lost in Space aired, or are you interested in the overall time span during which the show was broadcast?[/OUTPUT]
=========================

Generating positive clarifying questions:  28%|██▊       | 278/990 [03:02<09:02,  1.31it/s]

🟩 Row 277
Q: When did lost in space air on tv?
Facets: ['Show Year', 'Episode vs Show', 'Time Span vs Instant']
✅ Clarifying Question: Are you asking about when a specific episode of Lost in Space aired, or are you interested in the overall time span during which the show was broadcast?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Did you ask about the position of President of the Republic of China immediately after the end of the Qing Dynasty, or were you referring to a different type of presidency?[/OUTPUT]
=========================

Generating positive clarifying questions:  28%|██▊       | 279/990 [03:03<10:42,  1.11it/s]

🟩 Row 278
Q: Who became president of the republic of china after the overthrow of the qing dynasty?
Facets: ['Type of Presidency']
✅ Clarifying Question: Did you ask about the position of President of the Republic of China immediately after the end of the Qing Dynasty, or were you referring to a different type of presidency?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the character focus of the cartoon, the creation year, and whether you're referring to a particular region or global audience?[/OUTPUT]
=========================

Generating positive clarifying questions:  28%|██▊       | 281/990 [03:05<09:49,  1.20it/s]

🟩 Row 280
Q: What popular cartoon was created by a risd graduate?
Facets: ['Cartoon Series', 'Creation Year', 'Character Focus']
✅ Clarifying Question: Could you specify the character focus of the cartoon, the creation year, and whether you're referring to a particular region or global audience?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about Disneyland or Disney World, and which specific location within the United States do you need information about?[/OUTPUT]
=========================

Generating positive clarifying questions:  29%|██▊       | 284/990 [03:06<07:52,  1.49it/s]

🟩 Row 283
Q: Where is disney land located in the united states?
Facets: ['Specific Disney Location', 'Geographical Detail']
✅ Clarifying Question: Are you asking about Disneyland or Disney World, and which specific location within the United States do you need information about?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the coastline of contiguous states or including Alaska and Hawaii as well?[/OUTPUT]
=========================

Generating positive clarifying questions:  29%|██▉       | 288/990 [03:07<05:51,  2.00it/s]

🟩 Row 287
Q: Which state has the most coastline in the us?
Facets: ["Definition of 'contiguous' or 'continental'"]
✅ Clarifying Question: Are you asking about the coastline of contiguous states or including Alaska and Hawaii as well?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific Pirates of the Caribbean film are you referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  29%|██▉       | 290/990 [03:08<05:48,  2.01it/s]

🟩 Row 289
Q: Who composed the pirates of the caribbean theme song?
Facets: ['Film Title']
✅ Clarifying Question: Which specific Pirates of the Caribbean film are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the location where Macbeth was originally performed or the geographical setting of the story within the play?[/OUTPUT]
=========================


🟩 Row 290
Q: What is the setting of the play macbeth?
Facets: ['Geographical Location']
✅ Clarifying Question: Are you asking about the location where Macbeth was originally performed or the geographical setting of the story within the play?
------------------------------------------------------

Generating positive clarifying questions:  29%|██▉       | 291/990 [03:09<07:13,  1.61it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which episode of My Hero Academia are you asking about, and is this for the current season or a future one?[/OUTPUT]
=========================

Generating positive clarifying questions:  30%|███       | 297/990 [03:11<04:40,  2.47it/s]

🟩 Row 296
Q: When does next episode of my hero academia come out?
Facets: ['Episode Number']
✅ Clarifying Question: Which episode of My Hero Academia are you asking about, and is this for the current season or a future one?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether Don refers to a person's name or a type of entity, and provide more context about the meditations and the emergency?[/OUTPUT]
=========================


🟩 Row 298
Q: Who did don mail meditations in an emergency to?
Facets: ['Type of Entity']
✅ Clarifying Question: Could you specify whether Don refers to a person's name or a type of entity, and provide more context about the meditations and the emergency?
------------------------------------------------------

Generating positive clarifying questions:  30%|███       | 299/990 [03:12<05:33,  2.07it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about Jon B's release date for a book or a movie?[/OUTPUT]
=========================

Generating positive clarifying questions:  30%|███       | 300/990 [03:14<06:35,  1.74it/s]

🟩 Row 299
Q: Jon b are you still down release date?
Facets: ['Type of Entity', 'Title of Work']
✅ Clarifying Question: Could you specify whether you're asking about Jon B's release date for a book or a movie?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the location of a specific waterfall in Zimbabwe or its size compared to other waterfalls there?[/OUTPUT]
=========================

Generating positive clarifying questions:  30%|███       | 301/990 [03:15<07:42,  1.49it/s]

🟩 Row 300
Q: What is the name of the waterfall in zimbabwe?
Facets: ['Location', 'Size of Waterfall']
✅ Clarifying Question: Are you asking about the location of a specific waterfall in Zimbabwe or its size compared to other waterfalls there?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the year of the song, the singer's role in the song, and which specific river is being referred to?[/OUTPUT]
=========================


🟩 Row 302
Q: Who sang on the banks of the river?
Facets: ['Song Year', 'Role in Song', 'Specific River Mentioned']
✅ Clarifying Question: Could you specify the year of the song, the singer's role in the song, and which specific river is being referred to?
------------------------------------------------------

Generating positive clarifying questions:  31%|███       | 303/990 [03:16<07:35,  1.51it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the delivery date for a pre-ordered Model 3 or one produced and ready for shipment?[/OUTPUT]
=========================


🟩 Row 304
Q: When will the first tesla model 3 be delivered?
Facets: ['Recipient of Delivery', 'Production Status']
✅ Clarifying Question: Are you asking about the delivery date for a pre-ordered Model 3 or one produced and ready for shipment?
------------------------------------------------------

Generating positive clarifying questions:  31%|███       | 305/990 [03:17<07:33,  1.51it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the entity that made the decision, the time period during the Vietnam War, the specific operation related to its use, or the country involved?[/OUTPUT]
=========================

Generating positive clarifying questions:  31%|███       | 306/990 [03:19<09:26,  1.21it/s]

🟩 Row 305
Q: Who decided to use agent orange in vietnam?
Facets: ['Deciding Entity', 'Time', 'Operation Context', 'Country Involved']
✅ Clarifying Question: Could you specify whether you're asking about the entity that made the decision, the time period during the Vietnam War, the specific operation related to its use, or the country involved?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the transition from a branch of the army to an independent service, or specifically about the formal establishment of the Air Force with its own legal status?[/OUTPUT]
=========================

Generating positive clarifying questions:  31%|███       | 307/990 [03:20<10:42,  1.06it/s]

🟩 Row 306
Q: When did the army air corp become the air force?
Facets: ['Type of Entity', 'Legal Status']
✅ Clarifying Question: Are you asking about the transition from a branch of the army to an independent service, or specifically about the formal establishment of the Air Force with its own legal status?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a character's role at the start of Pretty Little Liars, or perhaps someone who was involved in the production from the beginning?[/OUTPUT]
=========================

Generating positive clarifying questions:  31%|███       | 308/990 [03:22<11:53,  1.05s/it]

🟩 Row 307
Q: Who was a at the beginning of pretty little liars?
Facets: ['Type of Entity', 'Role']
✅ Clarifying Question: Are you asking about a character's role at the start of Pretty Little Liars, or perhaps someone who was involved in the production from the beginning?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which Olympic season were the games held in the US? Winter or Summer?[/OUTPUT]
=========================

Generating positive clarifying questions:  32%|███▏      | 315/990 [03:23<04:40,  2.41it/s]

🟩 Row 314
Q: Where in the us has hosted the olympics?
Facets: ['Olympic Season']
✅ Clarifying Question: In which Olympic season were the games held in the US? Winter or Summer?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the total number of layers in the OSI model specifically, or do you need information about other networking models as well?[/OUTPUT]
=========================

Generating positive clarifying questions:  32%|███▏      | 317/990 [03:24<05:14,  2.14it/s]

🟩 Row 316
Q: How many layers are there in osi model?
Facets: ['Scope of OSI Model', 'Entity Inclusion']
✅ Clarifying Question: Are you asking about the total number of layers in the OSI model specifically, or do you need information about other networking models as well?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the type of entity (e.g., city, province, kingdom), the time period during which the Spanish Empire was active, and the geographical region within the Spanish Empire you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  32%|███▏      | 319/990 [03:26<06:22,  1.76it/s]

🟩 Row 318
Q: What was the capital of a large area of the spanish empire?
Facets: ['Area of Empire', 'Time Period', 'Type of Entity']
✅ Clarifying Question: Could you specify the type of entity (e.g., city, province, kingdom), the time period during which the Spanish Empire was active, and the geographical region within the Spanish Empire you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which year's NBA MVP are you asking about?[/OUTPUT]
=========================

Generating positive clarifying questions:  32%|███▏      | 320/990 [03:27<06:51,  1.63it/s]

🟩 Row 319
Q: Who won the nba mvp of the regular season?
Facets: ['Year']
✅ Clarifying Question: Which year's NBA MVP are you asking about?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the King James Version specifically, or another version that might share this name?[/OUTPUT]
=========================

Generating positive clarifying questions:  32%|███▏      | 321/990 [03:28<08:01,  1.39it/s]

🟩 Row 320
Q: When was the king james version of the bible first printed?
Facets: ['Version of Bible']
✅ Clarifying Question: Could you specify if you're asking about the King James Version specifically, or another version that might share this name?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you interested—first occurrence or last occurrence—of the Black Death in the UK?[/OUTPUT]
=========================

Generating positive clarifying questions:  33%|███▎      | 322/990 [03:29<08:49,  1.26it/s]

🟩 Row 321
Q: When did the black death start in the uk?
Facets: ['Time Period: First Occurrence', 'Time Period: Last Occurrence']
✅ Clarifying Question: In which time period are you interested—first occurrence or last occurrence—of the Black Death in the UK?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the first European explorer and the exact year of arrival?[/OUTPUT]
=========================

Generating positive clarifying questions:  33%|███▎      | 323/990 [03:30<09:20,  1.19it/s]

🟩 Row 322
Q: Who were the first european to reach the americas and when did they arrive?
Facets: ['Entity Type', 'Time']
✅ Clarifying Question: Could you specify whether you're asking about the first European explorer and the exact year of arrival?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the document itself or its content, and in which year was this declaration made?[/OUTPUT]
=========================


🟩 Row 323
Q: Who created the declaration of the rights of man?
Facets: ['Type of Entity Created', 'Date']
✅ Clarifying Question: Are you asking about the document itself or its content, and in which year was this declaration made?
------------------------------------------------------

Generating positive clarifying questions:  33%|███▎      | 324/990 [03:31<09:47,  1.13it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the general location, or specifically within a particular country or region?[/OUTPUT]
=========================

Generating positive clarifying questions:  33%|███▎      | 326/990 [03:32<07:55,  1.40it/s]

🟩 Row 325
Q: Where is the tigris and euphrates river valley located?
Facets: ['Geographical Level of Detail']
✅ Clarifying Question: Are you asking about the general location, or specifically within a particular country or region?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the specific type of drum, or is there another aspect of the pair of hand drums used in Indian classical music you're inquiring about?[/OUTPUT]
=========================


🟩 Row 327
Q: The pair of hand drums used in indian classical music is called?
Facets: ['Type of Entity']
✅ Clarifying Question: Are you asking about the specific type of drum, or is there another aspect of the pair of hand drums used in Indian classical music you're inquiring about?
------------------------------------------------------

Generating positive clarifying questions:  33%|███▎      | 328/990 [03:33<07:40,  1.44it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the Kokoda Track campaign or a different war, and the particular years involved?[/OUTPUT]
=========================


🟩 Row 328
Q: When did the kokoda war start and end?
Facets: ['Time Event: Start', 'Time Event: End']
✅ Clarifying Question: Could you specify if you're asking about the Kokoda Track campaign or a different war, and the particular years involved?
------------------------------------------------------

Generating positive clarifying questions:  33%|███▎      | 329/990 [03:34<08:41,  1.27it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether the overalls were thrown into Mistress Murphy's chowder intentionally or accidentally, and if there's any reference to Tim Nolan in this context?[/OUTPUT]
=========================

Generating positive clarifying questions:  33%|███▎      | 330/990 [03:36<10:23,  1.06it/s]

🟩 Row 329
Q: Who threw the overalls in mistress murphy's chowder?
Facets: ['Intent of the Question', "Referent of 'Tim Nolan'"]
✅ Clarifying Question: Could you specify whether the overalls were thrown into Mistress Murphy's chowder intentionally or accidentally, and if there's any reference to Tim Nolan in this context?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the type of bomb used or the specific model, and if there's a particular date or context you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  34%|███▍      | 337/990 [03:37<04:29,  2.42it/s]

🟩 Row 336
Q: What kind of bomb did japan drop on pearl harbor?
Facets: ['Type of Bomb', 'Specificity']
✅ Clarifying Question: Could you specify whether you're asking about the type of bomb used or the specific model, and if there's a particular date or context you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the geographical location within Canada or the international boundary with the United States?[/OUTPUT]
=========================

Generating positive clarifying questions:  34%|███▍      | 338/990 [03:38<05:14,  2.08it/s]

🟩 Row 337
Q: Where is st lawrence river located in canada?
Facets: ['Geographical Level of Detail']
✅ Clarifying Question: Could you specify if you're asking about the geographical location within Canada or the international boundary with the United States?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the historical ownership period or the current ownership status of the Golden Nugget in Atlantic City?[/OUTPUT]
=========================

Generating positive clarifying questions:  34%|███▍      | 339/990 [03:39<06:02,  1.80it/s]

🟩 Row 338
Q: Who owns the golden nugget in atlantic city?
Facets: ['Ownership Period', 'Current Ownership Status']
✅ Clarifying Question: Are you asking about the historical ownership period or the current ownership status of the Golden Nugget in Atlantic City?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the time period, geographical region, and whether you're asking about the manufacturing process or the location where they are assembled?[/OUTPUT]
=========================

Generating positive clarifying questions:  34%|███▍      | 341/990 [03:40<05:59,  1.81it/s]

🟩 Row 340
Q: Where are fisher & paykel washing machines made?
Facets: ['Time Period', 'Geographical Region', 'Duration']
✅ Clarifying Question: Could you specify the time period, geographical region, and whether you're asking about the manufacturing process or the location where they are assembled?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the brand, model, year, and origin of the watch you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  35%|███▍      | 343/990 [03:41<05:40,  1.90it/s]

🟩 Row 342
Q: How long does a self-winding watch stay wound?
Facets: ['Watch Brand', 'Watch Model', 'Watch Year', 'Watch Movement Origin']
✅ Clarifying Question: Could you specify the brand, model, year, and origin of the watch you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the dog from a specific media type, the release year of the story, or which Rich Rich story or movie you're referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  35%|███▍      | 344/990 [03:42<06:52,  1.57it/s]

🟩 Row 343
Q: What is the name of the dog in richie rich?
Facets: ['Media Type', 'Release Year', 'Franchise']
✅ Clarifying Question: Are you asking about the dog from a specific media type, the release year of the story, or which Rich Rich story or movie you're referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know the biggest automobile company?[/OUTPUT]
=========================

Generating positive clarifying questions:  35%|███▍      | 346/990 [03:43<05:48,  1.85it/s]

🟩 Row 345
Q: What is the biggest automobile company in the world?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know the biggest automobile company?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which medium of storytelling and context did Snape become the Defense Against the Dark Arts teacher?[/OUTPUT]
=========================

Generating positive clarifying questions:  35%|███▌      | 348/990 [03:44<05:23,  1.99it/s]

🟩 Row 347
Q: When did snape become defense against the dark arts teacher?
Facets: ['Context', 'Medium of Storytelling']
✅ Clarifying Question: In which medium of storytelling and context did Snape become the Defense Against the Dark Arts teacher?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're looking for recent evidence or historical studies, and if there are any particular schizophrenia symptoms you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  35%|███▌      | 350/990 [03:45<05:23,  1.98it/s]

🟩 Row 349
Q: What schizophrenic symptoms are decreased by drugs that selectively block the d2 dopamine receptor?
Facets: ['Degree of Evidence']
✅ Clarifying Question: Could you specify whether you're looking for recent evidence or historical studies, and if there are any particular schizophrenia symptoms you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific location does the story of True Grit take place, and are you asking about a particular character's action or the setting itself?[/OUTPUT]
=========================

Generating positive clarifying questions:  36%|███▌      | 352/990 [03:46<05:36,  1.90it/s]

🟩 Row 351
Q: Where is true grit supposed to take place?
Facets: ['Specific Location in Story', 'Character Action Destination']
✅ Clarifying Question: In which specific location does the story of True Grit take place, and are you asking about a particular character's action or the setting itself?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether the "pinhole gamma ray" refers to a device or a method, and provide more context about when or where this was designed?[/OUTPUT]
=========================

Generating positive clarifying questions:  36%|███▌      | 353/990 [03:47<07:19,  1.45it/s]

🟩 Row 352
Q: Who designed a pinhole gamma ray called the collimeter?
Facets: ['Type of Entity', 'Action or Work']
✅ Clarifying Question: Could you specify whether the "pinhole gamma ray" refers to a device or a method, and provide more context about when or where this was designed?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific time period or discipline within neuroscience that focuses on nervous system disorders?[/OUTPUT]
=========================

Generating positive clarifying questions:  36%|███▌      | 354/990 [03:48<08:05,  1.31it/s]

🟩 Row 353
Q: Which discipline of neuroscience studies nervous system disorders?
Facets: ['Time Period']
✅ Clarifying Question: Are you asking about a specific time period or discipline within neuroscience that focuses on nervous system disorders?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In what temperature scale (Fahrenheit or Celsius) are you asking about the hottest temperature ever recorded in Eugene, Oregon?[/OUTPUT]
=========================

Generating positive clarifying questions:  36%|███▌      | 355/990 [03:50<09:51,  1.07it/s]

🟩 Row 354
Q: What is the hottest temperature ever recorded in eugene oregon?
Facets: ['Temperature Scale']
✅ Clarifying Question: In what temperature scale (Fahrenheit or Celsius) are you asking about the hottest temperature ever recorded in Eugene, Oregon?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Did you mean the song's composer or someone else involved in its production, such as the producer or lyricist?[/OUTPUT]
=========================

Generating positive clarifying questions:  36%|███▌      | 356/990 [03:51<10:54,  1.03s/it]

🟩 Row 355
Q: Who made sitting on the dock of the bay?
Facets: ['Role in Song Production']
✅ Clarifying Question: Did you mean the song's composer or someone else involved in its production, such as the producer or lyricist?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific "Wedding March" movie are you referring to, and is there a particular number associated with it?[/OUTPUT]
=========================


🟩 Row 358
Q: Where is the hallmark movie wedding march filmed?
Facets: ['Movie Number']
✅ Clarifying Question: Which specific "Wedding March" movie are you referring to, and is there a particular number associated with it?
------------------------------------------------------

Generating positive clarifying questions:  36%|███▋      | 359/990 [03:53<07:35,  1.38it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know who sings "Now That We Found Love What Are We Going To Do With It"?[/OUTPUT]
=========================

Generating positive clarifying questions:  37%|███▋      | 362/990 [03:54<06:20,  1.65it/s]

🟩 Row 361
Q: Who sings now that we found love what are we going to do with it?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know who sings "Now That We Found Love What Are We Going To Do With It"?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the method of control, the extent of control, or any other aspect, and if you're interested in a specific part of the economy such as trade, agriculture, or taxation?[/OUTPUT]
=========================

Generating positive clarifying questions:  37%|███▋      | 364/990 [03:56<07:01,  1.49it/s]

🟩 Row 363
Q: Who controlled the economy of the incan empire?
Facets: ['Type of Control', 'Aspect of Economic Control']
✅ Clarifying Question: Could you specify whether you're asking about the method of control, the extent of control, or any other aspect, and if you're interested in a specific part of the economy such as trade, agriculture, or taxation?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific song are you asking about, and in what year was it released?[/OUTPUT]
=========================

Generating positive clarifying questions:  37%|███▋      | 366/990 [03:57<06:34,  1.58it/s]

🟩 Row 365
Q: Who sang if it wasn't for bad luck?
Facets: ['Song Title', 'Year']
✅ Clarifying Question: Which specific song are you asking about, and in what year was it released?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the total number of movies released annually, or the average per year, and do you want data for a specific year or over multiple years?[/OUTPUT]
=========================

Generating positive clarifying questions:  37%|███▋      | 367/990 [03:58<07:55,  1.31it/s]

🟩 Row 366
Q: Number of movies released in india every year?
Facets: ['Year', 'Stat Type']
✅ Clarifying Question: Are you asking about the total number of movies released annually, or the average per year, and do you want data for a specific year or over multiple years?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about a video actress's performance aspect or media type, and which particular video or actress you have in mind?[/OUTPUT]
=========================

Generating positive clarifying questions:  37%|███▋      | 368/990 [04:00<09:26,  1.10it/s]

🟩 Row 367
Q: I would do anything for love video actress?
Facets: ['Media Type', 'Aspect of Performance']
✅ Clarifying Question: Could you specify whether you're asking about a video actress's performance aspect or media type, and which particular video or actress you have in mind?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if "that's so raven" refers to a character or an actor, and clarify whether you're asking about a specific mother character or a real-life person?[/OUTPUT]
=========================

Generating positive clarifying questions:  37%|███▋      | 370/990 [04:01<09:09,  1.13it/s]

🟩 Row 369
Q: Where did the mom go in that's so raven?
Facets: ['Character vs. Actor', 'Entity Type']
✅ Clarifying Question: Could you specify if "that's so raven" refers to a character or an actor, and clarify whether you're asking about a specific mother character or a real-life person?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you referring to for the head of a sub-county in Kenya?[/OUTPUT]
=========================

Generating positive clarifying questions:  37%|███▋      | 371/990 [04:02<09:47,  1.05it/s]

🟩 Row 370
Q: Who is the head of a sub county in kenya?
Facets: ['Time Period']
✅ Clarifying Question: In which time period are you referring to for the head of a sub-county in Kenya?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region are you asking about the release date for Wynonna Earp season 2?[/OUTPUT]
=========================

Generating positive clarifying questions:  38%|███▊      | 373/990 [04:04<08:27,  1.22it/s]

🟩 Row 372
Q: When is wynonna earp season 2 coming out?
Facets: ['Geographical Region']
✅ Clarifying Question: In which geographical region are you asking about the release date for Wynonna Earp season 2?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the current highest-paid government employee, or a specific time period in the past? Also, do you want information on a particular type of government officeholder?[/OUTPUT]
=========================

Generating positive clarifying questions:  38%|███▊      | 375/990 [04:05<08:22,  1.22it/s]

🟩 Row 374
Q: Who is highest paid government employee in india?
Facets: ['Type of Officeholder', 'Time Period']
✅ Clarifying Question: Are you asking about the current highest-paid government employee, or a specific time period in the past? Also, do you want information on a particular type of government officeholder?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the men's or women's division, and which specific NCAA basketball tournament are you referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  38%|███▊      | 376/990 [04:07<09:28,  1.08it/s]

🟩 Row 375
Q: Ncaa basketball national player of the year 2018?
Facets: ['Sport Type', 'Gender']
✅ Clarifying Question: Are you asking about the men's or women's division, and which specific NCAA basketball tournament are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific song by Gwen Stefani with this line, or is this part of a different context or lyric content?[/OUTPUT]
=========================


🟩 Row 376
Q: High on the hill was a lonely goatherd gwen stefani?
Facets: ['Song Title', 'Lyrics Content']
✅ Clarifying Question: Are you asking about a specific song by Gwen Stefani with this line, or is this part of a different context or lyric content?
------------------------------------------------------

Generating positive clarifying questions:  38%|███▊      | 377/990 [04:08<10:36,  1.04s/it]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about New Zealand's transition from a dominion to a different status within its geographical region, or are you inquiring about changes in its legislative body?[/OUTPUT]
=========================

Generating positive clarifying questions:  38%|███▊      | 380/990 [04:10<07:56,  1.28it/s]

🟩 Row 379
Q: When did new zealand stop being a dominion?
Facets: ['Geographical Region', 'Legislative Body']
✅ Clarifying Question: Are you asking about New Zealand's transition from a dominion to a different status within its geographical region, or are you inquiring about changes in its legislative body?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the number of levels in Super Mario Bros. for the Super Nintendo Entertainment System (SNES)?[/OUTPUT]
=========================

Generating positive clarifying questions:  39%|███▉      | 384/990 [04:11<05:49,  1.74it/s]

🟩 Row 383
Q: How many levels in super mario super nintendo?
Facets: ['Game Title', 'Game Series']
✅ Clarifying Question: Are you asking about the number of levels in Super Mario Bros. for the Super Nintendo Entertainment System (SNES)?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the flavor, shape, design, or any other characteristics of the shortbread Girl Scout cookie?[/OUTPUT]
=========================


🟩 Row 384
Q: What is the name of the shortbread girl scout cookie?
Facets: ['Cookie Flavor', 'Cookie Shape', 'Cookie Topping', 'Cookie Design', 'Cookie Status', 'Cookie Flavor Variety', 'Cookie Coating']
✅ Clarifying Question: Could you specify if you're asking about the flavor, shape, design, or any other characteristics of the shortbread Girl Scout cookie?
------------------------------------------------------

Generating positive clarifying questions:  39%|███▉      | 385/990 [04:12<06:59,  1.44it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did it end completely, partially, or during a specific time period, and are you asking about a particular year or era?[/OUTPUT]
=========================


🟩 Row 385
Q: When did the gold standard end in the us?
Facets: ['Degree of End', 'Temporal Aspect']
✅ Clarifying Question: Did it end completely, partially, or during a specific time period, and are you asking about a particular year or era?
------------------------------------------------------

Generating positive clarifying questions:  39%|███▉      | 386/990 [04:14<08:12,  1.23it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Do you want to know when the show "How to Get Away with Murder" started airing season 4, or are you asking about the duration of the season's run?[/OUTPUT]
=========================

Generating positive clarifying questions:  39%|███▉      | 387/990 [04:15<09:49,  1.02it/s]

🟩 Row 386
Q: When does how to get away with a murderer air season 4?
Facets: ['Type of Query (start vs. span)', 'Event Timing']
✅ Clarifying Question: Do you want to know when the show "How to Get Away with Murder" started airing season 4, or are you asking about the duration of the season's run?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the physical location of the Ark from the Bible or a modern-day structure, and specifically in which state or city within the United States?[/OUTPUT]
=========================

Generating positive clarifying questions:  39%|███▉      | 389/990 [04:17<09:01,  1.11it/s]

🟩 Row 388
Q: Where is the ark located in the united states?
Facets: ['Type of Entity', 'Specific Location within Entity']
✅ Clarifying Question: Are you asking about the physical location of the Ark from the Bible or a modern-day structure, and specifically in which state or city within the United States?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the movie, the book, or another source, and if there's a particular event related to "The Fault in Our Stars"?[/OUTPUT]
=========================

Generating positive clarifying questions:  39%|███▉      | 390/990 [04:19<10:27,  1.05s/it]

🟩 Row 389
Q: Where do they go in fault in our stars?
Facets: ['Media Type', 'Event Details', 'Source Text']
✅ Clarifying Question: Could you specify whether you're asking about the movie, the book, or another source, and if there's a particular event related to "The Fault in Our Stars"?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the exact title of the Disney movie, and clarify if you're asking about its release date or a specific time of day it's being released?[/OUTPUT]
=========================

Generating positive clarifying questions:  39%|███▉      | 391/990 [04:20<11:28,  1.15s/it]

🟩 Row 390
Q: When is the disney movie zombies coming out?
Facets: ['Time of Day', 'Movie Title', 'Date of Release']
✅ Clarifying Question: Could you specify the exact title of the Disney movie, and clarify if you're asking about its release date or a specific time of day it's being released?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Do you mean a game with or without a bonus number, and are these 3 numbers part of the main draw or a separate section of Lotto Max?[/OUTPUT]
=========================

Generating positive clarifying questions:  40%|███▉      | 393/990 [04:21<09:45,  1.02it/s]

🟩 Row 392
Q: What do you win on lotto max with 3 numbers?
Facets: ['Bonus Number Presence']
✅ Clarifying Question: Do you mean a game with or without a bonus number, and are these 3 numbers part of the main draw or a separate section of Lotto Max?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year did the current Secretary of State for Transport's tenure begin?[/OUTPUT]
=========================


🟩 Row 398
Q: Who is the secretary of state for transport?
Facets: ['Year of Tenure Begin']
✅ Clarifying Question: In which year did the current Secretary of State for Transport's tenure begin?
------------------------------------------------------

Generating positive clarifying questions:  40%|████      | 399/990 [04:23<04:40,  2.11it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year's World Series are you referring, and do you have a specific location in mind for Game 7?[/OUTPUT]
=========================

Generating positive clarifying questions:  40%|████      | 400/990 [04:24<05:32,  1.77it/s]

🟩 Row 399
Q: Where is game 7 of the world series going to be held?
Facets: ['Year', 'Location']
✅ Clarifying Question: In which year's World Series are you referring, and do you have a specific location in mind for Game 7?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about a particular time period, date of appointment or departure, and which specific role within the Canberra Times?[/OUTPUT]
=========================

Generating positive clarifying questions:  41%|████      | 401/990 [04:25<06:20,  1.55it/s]

🟩 Row 400
Q: Who is the editor of the canberra times?
Facets: ['Editorial Role', 'Time Period', 'Date of Appointment/Departure']
✅ Clarifying Question: Could you specify if you're asking about a particular time period, date of appointment or departure, and which specific role within the Canberra Times?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know who played the ice queen in The Lion, the Witch and the Wardrobe?[/OUTPUT]
=========================

Generating positive clarifying questions:  41%|████      | 402/990 [04:26<07:36,  1.29it/s]

🟩 Row 401
Q: Who plays the ice queen in the lion the witch and the wardrobe?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know who played the ice queen in The Lion, the Witch and the Wardrobe?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]For what purpose do you plan to visit Hong Kong, and is this trip covered by any visa waiver program for New Zealand citizens?[/OUTPUT]
=========================

Generating positive clarifying questions:  41%|████      | 406/990 [04:28<05:28,  1.78it/s]

🟩 Row 405
Q: Do nz citizens need a visa for hong kong?
Facets: ['Purpose of Visit', 'Visa Waiver Program']
✅ Clarifying Question: For what purpose do you plan to visit Hong Kong, and is this trip covered by any visa waiver program for New Zealand citizens?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In what year did they cease production of the Dodge Viper, and for how long was the production stopped?[/OUTPUT]
=========================

Generating positive clarifying questions:  41%|████      | 408/990 [04:29<05:43,  1.69it/s]

🟩 Row 407
Q: When did they stop making the dodge viper?
Facets: ['Duration of Stoppage']
✅ Clarifying Question: In what year did they cease production of the Dodge Viper, and for how long was the production stopped?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know when the season finale of have and have nots aired?[/OUTPUT]
=========================

Generating positive clarifying questions:  42%|████▏     | 411/990 [04:30<05:06,  1.89it/s]

🟩 Row 410
Q: When is have and have nots season finale?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know when the season finale of have and have nots aired?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In what medium (e.g., film, book, game) is this submarine story presented?[/OUTPUT]
=========================

Generating positive clarifying questions:  42%|████▏     | 414/990 [04:31<04:42,  2.04it/s]

🟩 Row 413
Q: Name of submarine in voyage to the bottom of the sea?
Facets: ['Medium of Work']
✅ Clarifying Question: In what medium (e.g., film, book, game) is this submarine story presented?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which medium (movie or stage) does the song play during the opening of The Rocky Horror Picture Show?[/OUTPUT]
=========================

Generating positive clarifying questions:  42%|████▏     | 415/990 [04:33<05:45,  1.66it/s]

🟩 Row 414
Q: Who sings the opening song of rocky horror?
Facets: ['Medium (Movie/Stage)']
✅ Clarifying Question: In which medium (movie or stage) does the song play during the opening of The Rocky Horror Picture Show?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you asking about Billy Abbott's role on Young and the Restless?[/OUTPUT]
=========================


🟩 Row 424
Q: Who played billy abbott on young and the restless?
Facets: ['Time Period']
✅ Clarifying Question: In which time period are you asking about Billy Abbott's role on Young and the Restless?
------------------------------------------------------

Generating positive clarifying questions:  43%|████▎     | 425/990 [04:34<02:39,  3.54it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the match location or the season when Arsenal won the Premier League, and provide any specific time period if applicable?[/OUTPUT]
=========================

Generating positive clarifying questions:  43%|████▎     | 426/990 [04:35<03:28,  2.71it/s]

🟩 Row 425
Q: When did arsenal won the premier league at white hart lane?
Facets: ['Time Period', 'Event Occurrence']
✅ Clarifying Question: Could you specify whether you're asking about the match location or the season when Arsenal won the Premier League, and provide any specific time period if applicable?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]For which age group is the spinal tap procedure intended?[/OUTPUT]
=========================

Generating positive clarifying questions:  43%|████▎     | 429/990 [04:36<03:10,  2.95it/s]

🟩 Row 428
Q: Where does the needle go for a spinal tap?
Facets: ['Age Group']
✅ Clarifying Question: For which age group is the spinal tap procedure intended?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year or time period were you referring to when asking about Austin Reed on Days of Our Lives?[/OUTPUT]
=========================

Generating positive clarifying questions:  44%|████▎     | 431/990 [04:37<03:22,  2.76it/s]

🟩 Row 430
Q: Who played austin reed on days of our lives?
Facets: ['Time Period', 'Year']
✅ Clarifying Question: In which year or time period were you referring to when asking about Austin Reed on Days of Our Lives?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the overall phase of the war or specific operations within the conflict?[/OUTPUT]
=========================

Generating positive clarifying questions:  44%|████▍     | 435/990 [04:38<02:47,  3.32it/s]

🟩 Row 434
Q: When did the afghanistan war start and end?
Facets: ['War Phase']
✅ Clarifying Question: Are you asking about the overall phase of the war or specific operations within the conflict?
------------------------------------------------------

Generating positive clarifying questions:  44%|████▍     | 436/990 [04:38<03:19,  2.77it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the time period and the origin of the "We Can Do It!" poster?[/OUTPUT]
=========================


🟩 Row 435
Q: Where did the we can do it poster come from?
Facets: ['Time Period', 'Origin']
✅ Clarifying Question: Could you specify the time period and the origin of the "We Can Do It!" poster?
------------------------------------------------------

Generating positive clarifying questions:  44%|████▍     | 438/990 [04:39<03:12,  2.87it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country were they drafting people when this ended?[/OUTPUT]
=========================


🟩 Row 437
Q: When did they do away with the draft?
Facets: ['Location']
✅ Clarifying Question: In which country were they drafting people when this ended?
------------------------------------------------------

Generating positive clarifying questions:  45%|████▍     | 443/990 [04:40<02:31,  3.62it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the rules for the House of Representatives or the Senate, and do you want the current rules or historical ones?[/OUTPUT]
=========================


🟩 Row 442
Q: Who makes the rules for house and senate?
Facets: ['Type of Government Body']
✅ Clarifying Question: Are you asking about the rules for the House of Representatives or the Senate, and do you want the current rules or historical ones?
------------------------------------------------------

Generating positive clarifying questions:  45%|████▍     | 444/990 [04:41<03:11,  2.85it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific Samaritan woman at the well are you referring to, and from which religious tradition does this story originate?[/OUTPUT]
=========================


🟩 Row 443
Q: What is the name of the samaritan woman at the well?
Facets: ['Question Type', 'Religious Tradition']
✅ Clarifying Question: Which specific Samaritan woman at the well are you referring to, and from which religious tradition does this story originate?
------------------------------------------------------

Generating positive clarifying questions:  45%|████▌     | 446/990 [04:42<03:59,  2.27it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the original publication date, any subsequent versions, the publisher, if there were illustrations, or the version's authority?[/OUTPUT]
=========================


🟩 Row 445
Q: When was the adventures of tom sawyer published?
Facets: ['Publisher', 'Illustration Status', 'Version Authority']
✅ Clarifying Question: Could you specify whether you're asking about the original publication date, any subsequent versions, the publisher, if there were illustrations, or the version's authority?
------------------------------------------------------

Generating positive clarifying questions:  45%|████▌     | 447/990 [04:43<04:16,  2.12it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year was the movie My Cousin Rachel filmed?[/OUTPUT]
=========================


🟩 Row 446
Q: Where was the movie my cousin rachel filmed?
Facets: ['Year']
✅ Clarifying Question: In which year was the movie My Cousin Rachel filmed?
------------------------------------------------------

Generating positive clarifying questions:  46%|████▌     | 451/990 [04:44<03:06,  2.89it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific Hindu wedding ritual are you referring to where the bride and groom walk around the fire?[/OUTPUT]
=========================


🟩 Row 450
Q: How many times does the bride and bridegroom walk around the fire during the hindu wedding ceremony?
Facets: ['Ritual Name']
✅ Clarifying Question: Which specific Hindu wedding ritual are you referring to where the bride and groom walk around the fire?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific version of the song or a particular artist's performance of "Blinded by the Light" that has been criticized?[/OUTPUT]
=========================

Generating positive clarifying questions:  46%|████▌     | 452/990 [04:45<04:15,  2.11it/s]

🟩 Row 451
Q: Who sings blinded by the light wrapped up like a douche?
Facets: ['Type of Entity']
✅ Clarifying Question: Are you asking about a specific version of the song or a particular artist's performance of "Blinded by the Light" that has been criticized?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're referring to the DSM version or another diagnostic manual, and the exact time point you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  46%|████▌     | 455/990 [04:47<04:12,  2.12it/s]

🟩 Row 454
Q: When did oppositional defiant disorder become a diagnosis?
Facets: ['Diagnostic Manual', 'Time Point']
✅ Clarifying Question: Could you specify whether you're referring to the DSM version or another diagnostic manual, and the exact time point you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the percentage of silver in the coin or the type of silver content elimination, and provide any specific year or period if applicable?[/OUTPUT]
=========================

Generating positive clarifying questions:  46%|████▌     | 456/990 [04:48<05:29,  1.62it/s]

🟩 Row 455
Q: When did they stop making silver kennedy half dollars?
Facets: ['Percentage of Silver', 'Type of Silver Content Elimination']
✅ Clarifying Question: Could you specify whether you're asking about the percentage of silver in the coin or the type of silver content elimination, and provide any specific year or period if applicable?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region were you referring to when asking about the release date of Harry Potter and the Sorcerer's Stone book?[/OUTPUT]
=========================

Generating positive clarifying questions:  46%|████▋     | 458/990 [04:49<05:29,  1.62it/s]

🟩 Row 457
Q: When was harry potter and the sorcerers stone book released?
Facets: ['Geographical Region']
✅ Clarifying Question: In which geographical region were you referring to when asking about the release date of Harry Potter and the Sorcerer's Stone book?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the year and the medium (e.g., film, TV series) in which Susan Walker appeared in Miracle on 34th Street?[/OUTPUT]
=========================

Generating positive clarifying questions:  46%|████▋     | 460/990 [04:51<05:44,  1.54it/s]

🟩 Row 459
Q: Who played susan walker in miracle on 34th street?
Facets: ['Year', 'Medium']
✅ Clarifying Question: Could you specify the year and the medium (e.g., film, TV series) in which Susan Walker appeared in Miracle on 34th Street?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which age group of Captain Jack Sparrow are you interested, and is there a specific Pirates of the Caribbean movie you have in mind?[/OUTPUT]
=========================

Generating positive clarifying questions:  47%|████▋     | 461/990 [04:52<06:53,  1.28it/s]

🟩 Row 460
Q: Who plays captain jack sparrow in pirates of the caribbean?
Facets: ['Character Age']
✅ Clarifying Question: In which age group of Captain Jack Sparrow are you interested, and is there a specific Pirates of the Caribbean movie you have in mind?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the main human protagonist in the movie Avatar or the Na'vi character, and do you need information from a specific edition of the story?[/OUTPUT]
=========================

Generating positive clarifying questions:  47%|████▋     | 463/990 [04:54<06:47,  1.29it/s]

🟩 Row 462
Q: What is the name of the main human character in avatar?
Facets: ['Character Role', 'Entity Type']
✅ Clarifying Question: Are you asking about the main human protagonist in the movie Avatar or the Na'vi character, and do you need information from a specific edition of the story?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Did you want to know about the launch date during a specific mission by Space Shuttle Discovery or generally when it was first launched?[/OUTPUT]
=========================

Generating positive clarifying questions:  47%|████▋     | 466/990 [04:55<05:39,  1.54it/s]

🟩 Row 465
Q: When was the hubble space telescope launched by space shuttle discovery?
Facets: ['Time Granularity']
✅ Clarifying Question: Did you want to know about the launch date during a specific mission by Space Shuttle Discovery or generally when it was first launched?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about American Airlines' destinations within specific regions of the UK or about the type of flights (e.g., domestic, international)?[/OUTPUT]
=========================

Generating positive clarifying questions:  47%|████▋     | 467/990 [04:56<06:35,  1.32it/s]

🟩 Row 466
Q: Where does american airlines fly in the uk?
Facets: ['Location: Region', 'Type of Entity']
✅ Clarifying Question: Are you asking about American Airlines' destinations within specific regions of the UK or about the type of flights (e.g., domestic, international)?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which type of company ownership, specific year, ranking source, and time period are you interested in for the wealthiest company in the world?[/OUTPUT]
=========================

Generating positive clarifying questions:  47%|████▋     | 468/990 [04:58<07:26,  1.17it/s]

🟩 Row 467
Q: What is the wealthiest company in the world?
Facets: ['Type of Company Ownership', 'Year', 'Ranking Source', 'Time Period']
✅ Clarifying Question: Which type of company ownership, specific year, ranking source, and time period are you interested in for the wealthiest company in the world?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about Whitney Carson's role as a competitor or a judge, and which season of Dancing with the Stars did she participate in?[/OUTPUT]
=========================

Generating positive clarifying questions:  48%|████▊     | 473/990 [04:59<04:27,  1.93it/s]

🟩 Row 472
Q: When did witney carson start dancing with the stars?
Facets: ['Role in the show', 'Type of Dance Competitor']
✅ Clarifying Question: Are you asking about Whitney Carson's role as a competitor or a judge, and which season of Dancing with the Stars did she participate in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year was the teenage activist from Swat nominated for the international children's peace prize?[/OUTPUT]
=========================


🟩 Row 474
Q: Which teenage activist girl from swat nominated for international children’s peace prize?
Facets: ['Year']
✅ Clarifying Question: In which year was the teenage activist from Swat nominated for the international children's peace prize?
------------------------------------------------------

Generating positive clarifying questions:  48%|████▊     | 475/990 [05:00<04:26,  1.93it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the main character's name, a specific relationship to another character, or a trait associated with the character in Black Panther?[/OUTPUT]
=========================


🟩 Row 475
Q: What is the character's name in black panther?
Facets: ['Character Role', 'Character Relation', 'Character Trait']
✅ Clarifying Question: Are you asking about the main character's name, a specific relationship to another character, or a trait associated with the character in Black Panther?
------------------------------------------------------

Generating positive clarifying questions:  48%|████▊     | 476/990 [05:01<05:13,  1.64it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which event and at what phase were you referring to when mentioning the US flag being carried in 2018?[/OUTPUT]
=========================

Generating positive clarifying questions:  48%|████▊     | 479/990 [05:02<04:21,  1.95it/s]

🟩 Row 478
Q: Who carried the us flag in the 2018?
Facets: ['Event Phase', 'Event Category']
✅ Clarifying Question: In which event and at what phase were you referring to when mentioning the US flag being carried in 2018?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific location did the events of Free Willy take place, and was it a real or fictional setting?[/OUTPUT]
=========================

Generating positive clarifying questions:  49%|████▉     | 483/990 [05:03<03:23,  2.49it/s]

🟩 Row 482
Q: Where did the movie free willy take place?
Facets: ['Location Type']
✅ Clarifying Question: In which specific location did the events of Free Willy take place, and was it a real or fictional setting?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're referring to a specific geographical feature, a particular historical period, the nature of the territory itself, or the bordering regions between India and Pakistan?[/OUTPUT]
=========================

Generating positive clarifying questions:  49%|████▉     | 485/990 [05:04<03:50,  2.19it/s]

🟩 Row 484
Q: What territory was fought over by india and pakistan?
Facets: ['Geographical Feature', 'Historical Context', 'Type of Territory', 'Bordering Regions']
✅ Clarifying Question: Could you specify if you're referring to a specific geographical feature, a particular historical period, the nature of the territory itself, or the bordering regions between India and Pakistan?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the character's first appearance in a particular season or episode range?[/OUTPUT]
=========================

Generating positive clarifying questions:  49%|████▉     | 487/990 [05:05<03:48,  2.20it/s]

🟩 Row 486
Q: Who played the first ryan on last man standing?
Facets: ['Season', 'Episode Range']
✅ Clarifying Question: Could you specify whether you're asking about the character's first appearance in a particular season or episode range?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific season or episode, and which character's wife in that particular context?[/OUTPUT]
=========================


🟩 Row 488
Q: Who plays the wife in how i met your mother?
Facets: ['Character Name']
✅ Clarifying Question: Are you asking about a specific season or episode, and which character's wife in that particular context?
------------------------------------------------------

Generating positive clarifying questions:  50%|████▉     | 491/990 [05:07<03:48,  2.19it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the creator, producer, or airing network of the TV show "So You Think You Can Dance"?[/OUTPUT]
=========================


🟩 Row 490
Q: Who owns so you think you can dance?
Facets: ['Creator', 'Producer', 'Airing Network']
✅ Clarifying Question: Are you asking about the creator, producer, or airing network of the TV show "So You Think You Can Dance"?
------------------------------------------------------

Generating positive clarifying questions:  50%|████▉     | 492/990 [05:08<04:23,  1.89it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region are you referring to when mentioning the man who killed Don Quixote's release?[/OUTPUT]
=========================


🟩 Row 491
Q: When will the man who killed don quixote be released?
Facets: ['Geographical Region']
✅ Clarifying Question: In which geographical region are you referring to when mentioning the man who killed Don Quixote's release?
------------------------------------------------------

Generating positive clarifying questions:  50%|████▉     | 493/990 [05:09<04:42,  1.76it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which league was the baseball season extended to 162 games?[/OUTPUT]
=========================


🟩 Row 492
Q: When did the baseball season go to 162 games?
Facets: ['League']
✅ Clarifying Question: In which league was the baseball season extended to 162 games?
------------------------------------------------------

Generating positive clarifying questions:  50%|█████     | 496/990 [05:10<03:53,  2.12it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about active players or retired players, and do you want the record as of a specific time or over the entire history of MLB?[/OUTPUT]
=========================


🟩 Row 495
Q: Who has the most career homeruns in mlb?
Facets: ['Player Status', 'Time Period']
✅ Clarifying Question: Are you asking about active players or retired players, and do you want the record as of a specific time or over the entire history of MLB?
------------------------------------------------------

Generating positive clarifying questions:  50%|█████     | 497/990 [05:11<04:47,  1.71it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether the blame refers to a particular historical source, the entity accused, or any other context, such as the specific time period or location?[/OUTPUT]
=========================


🟩 Row 496
Q: Who was blamed for the explosion of the uss maine?
Facets: ['Blame Attribution', 'Source of Information', 'Entity Involved in Blame']
✅ Clarifying Question: Could you specify whether the blame refers to a particular historical source, the entity accused, or any other context, such as the specific time period or location?
------------------------------------------------------

Generating positive clarifying questions:  51%|█████     | 503/990 [05:12<02:40,  3.03it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the release date for a specific season or the exact date for episode 3 of Tokyo Ghoul Re?[/OUTPUT]
=========================


🟩 Row 502
Q: When does tokyo ghoul re ep 3 come out?
Facets: ['Season', 'Episode Number']
✅ Clarifying Question: Are you asking about the release date for a specific season or the exact date for episode 3 of Tokyo Ghoul Re?
------------------------------------------------------

Generating positive clarifying questions:  51%|█████     | 504/990 [05:13<03:14,  2.50it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the genre or adaptation type of the new Blade Runner movie, and its expected release date?[/OUTPUT]
=========================


🟩 Row 503
Q: Who's directing the new blade runner movie?
Facets: ['Type of Film', 'Release Date']
✅ Clarifying Question: Are you asking about the genre or adaptation type of the new Blade Runner movie, and its expected release date?
------------------------------------------------------

Generating positive clarifying questions:  51%|█████     | 507/990 [05:14<02:56,  2.73it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about Jamaica's position among other islands, or its location relative to specific points in the Caribbean Sea?[/OUTPUT]
=========================


🟩 Row 506
Q: Where is jamaica located in the caribbean sea?
Facets: ['Grouping of Islands', 'Relational Position']
✅ Clarifying Question: Are you asking about Jamaica's position among other islands, or its location relative to specific points in the Caribbean Sea?
------------------------------------------------------

Generating positive clarifying questions:  51%|█████▏    | 508/990 [05:14<03:24,  2.36it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are the platforms you're asking about currently operational or are you referring to past status?[/OUTPUT]
=========================


🟩 Row 507
Q: How many platform in hazrat nizamuddin railway station?
Facets: ['Status of Platforms']
✅ Clarifying Question: Are the platforms you're asking about currently operational or are you referring to past status?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if this is referring to the sequence number of the current archbishop or another aspect of the position?[/OUTPUT]
=========================

Generating positive clarifying questions:  51%|█████▏    | 509/990 [05:16<04:25,  1.81it/s]

🟩 Row 508
Q: Who is the current archbishop of los angeles?
Facets: ['Sequence Number']
✅ Clarifying Question: Could you specify if this is referring to the sequence number of the current archbishop or another aspect of the position?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you interested in the population of Spanish speakers in the U.S.?[/OUTPUT]
=========================

Generating positive clarifying questions:  52%|█████▏    | 511/990 [05:17<04:35,  1.74it/s]

🟩 Row 510
Q: What is the population of spanish speakers in the u.s?
Facets: ['Time Period']
✅ Clarifying Question: In which time period are you interested in the population of Spanish speakers in the U.S.?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which voting method and specific year did Damir Im come in Eurovision?[/OUTPUT]
=========================


🟩 Row 513
Q: Where did dami im come in eurovision 2017?
Facets: ['Voting Method', 'Year']
✅ Clarifying Question: In which voting method and specific year did Damir Im come in Eurovision?
------------------------------------------------------

Generating positive clarifying questions:  52%|█████▏    | 514/990 [05:18<03:50,  2.06it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country are you referring to when asking about the most Little League World Series wins?[/OUTPUT]
=========================


🟩 Row 515
Q: Who has won the most little league world series?
Facets: ['Geographical Level (Country/State)']
✅ Clarifying Question: In which country are you referring to when asking about the most Little League World Series wins?
------------------------------------------------------

Generating positive clarifying questions:  52%|█████▏    | 516/990 [05:19<03:52,  2.04it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific time period are you interested in knowing when the Church of the Nazarene started?[/OUTPUT]
=========================

Generating positive clarifying questions:  52%|█████▏    | 517/990 [05:20<04:24,  1.79it/s]

🟩 Row 516
Q: When did the church of the nazarene start?
Facets: ['Time Period']
✅ Clarifying Question: In which specific time period are you interested in knowing when the Church of the Nazarene started?
------------------------------------------------------

Generating positive clarifying questions:  52%|█████▏    | 518/990 [05:21<05:32,  1.42it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're referring to a specific type of brine, the context in which you're using this information, and if there's a particular kind of salt you're interested in?[/OUTPUT]
=========================


🟩 Row 517
Q: In a solution of brine what is the salt?
Facets: ['Type of Brine', 'Context of Use', 'Nature of Salts']
✅ Clarifying Question: Could you specify whether you're referring to a specific type of brine, the context in which you're using this information, and if there's a particular kind of salt you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  53%|█████▎    | 529/990 [05:22<01:54,  4.01it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the geological process or another type of formation, and if there's a particular time frame you're interested in?[/OUTPUT]
=========================


🟩 Row 528
Q: What is formed on top of continental crust?
Facets: ['Definition of Formation', 'Process Involved']
✅ Clarifying Question: Could you specify whether you're asking about the geological process or another type of formation, and if there's a particular time frame you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  54%|█████▎    | 530/990 [05:23<02:22,  3.22it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the lead vocalist or another specific role in the Eagles' song "I Can't Tell You Why"?[/OUTPUT]
=========================


🟩 Row 529
Q: Who sings i can't tell you why by the eagles?
Facets: ['Vocal Role']
✅ Clarifying Question: Are you asking about the lead vocalist or another specific role in the Eagles' song "I Can't Tell You Why"?
------------------------------------------------------

Generating positive clarifying questions:  54%|█████▎    | 531/990 [05:24<02:42,  2.83it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific region of the UK did smoking in the workplace stop?[/OUTPUT]
=========================


🟩 Row 530
Q: When did smoking in the workplace stop uk?
Facets: ['Geographical Region']
✅ Clarifying Question: In which specific region of the UK did smoking in the workplace stop?
------------------------------------------------------

Generating positive clarifying questions:  54%|█████▍    | 533/990 [05:25<02:57,  2.58it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if Professor Lupin is from a movie or a TV show, and which year's version you're referring to?[/OUTPUT]
=========================


🟩 Row 532
Q: Who is the actor that plays professor lupin?
Facets: ['Character Age', 'Character Name']
✅ Clarifying Question: Could you specify if Professor Lupin is from a movie or a TV show, and which year's version you're referring to?
------------------------------------------------------

Generating positive clarifying questions:  54%|█████▍    | 534/990 [05:26<03:25,  2.22it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which episode number are you asking about, and is this for the main series or any specials?[/OUTPUT]
=========================


🟩 Row 533
Q: When does the next episode of star vs. the forces of evil come out?
Facets: ['Episode Number']
✅ Clarifying Question: Which episode number are you asking about, and is this for the main series or any specials?
------------------------------------------------------

Generating positive clarifying questions:  54%|█████▍    | 536/990 [05:26<03:07,  2.42it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country is the packet of sugar being referred to?[/OUTPUT]
=========================


🟩 Row 535
Q: How much sugar in a packet of sugar?
Facets: ['Location']
✅ Clarifying Question: In which country is the packet of sugar being referred to?
------------------------------------------------------

Generating positive clarifying questions:  54%|█████▍    | 537/990 [05:27<03:33,  2.12it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year was the song "I'm All the Way Up" released?[/OUTPUT]
=========================


🟩 Row 536
Q: Who sings the song i'm all the way up?
Facets: ['Year of Release']
✅ Clarifying Question: In which year was the song "I'm All the Way Up" released?
------------------------------------------------------

Generating positive clarifying questions:  54%|█████▍    | 538/990 [05:28<04:00,  1.88it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific Super Bowl did the Cowboys win, and in which year did it occur?[/OUTPUT]
=========================


🟩 Row 537
Q: When is the last time the cowboys won a superbowl?
Facets: ['Year']
✅ Clarifying Question: Which specific Super Bowl did the Cowboys win, and in which year did it occur?
------------------------------------------------------

Generating positive clarifying questions:  54%|█████▍    | 539/990 [05:29<04:19,  1.74it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year are you asking about the major league baseball all-star game?[/OUTPUT]
=========================


🟩 Row 538
Q: When is the major league baseball all-star game being played?
Facets: ['Year']
✅ Clarifying Question: In which year are you asking about the major league baseball all-star game?
------------------------------------------------------

Generating positive clarifying questions:  55%|█████▍    | 541/990 [05:30<04:05,  1.83it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the lyrics for the entire opera or specific songs, and are you interested in the primary songwriter or any additional contributors?[/OUTPUT]
=========================


🟩 Row 540
Q: Who wrote lyrics to phantom of the opera?
Facets: ['Scope of Lyrics (Opera vs Song)', 'Additional Information (Primary vs Additional)']
✅ Clarifying Question: Are you asking about the lyrics for the entire opera or specific songs, and are you interested in the primary songwriter or any additional contributors?
------------------------------------------------------

Generating positive clarifying questions:  55%|█████▍    | 542/990 [05:30<04:24,  1.70it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country, year, and specific series of Yellowstone are you referring to?[/OUTPUT]
=========================


🟩 Row 541
Q: What channel is the new yellowstone series going to be on?
Facets: ['Country of Origin', 'Year', 'Series Type']
✅ Clarifying Question: In which country, year, and specific series of Yellowstone are you referring to?
------------------------------------------------------

Generating positive clarifying questions:  55%|█████▍    | 544/990 [05:31<04:12,  1.77it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're interested in the reason behind the superstition, the object of knocking on wood, or the theory about its origin?[/OUTPUT]
=========================


🟩 Row 543
Q: Where did the superstition knock on wood come from?
Facets: ['Reason for the Superstition', 'Object of the Superstition', 'Theory of Origin']
✅ Clarifying Question: Could you specify whether you're interested in the reason behind the superstition, the object of knocking on wood, or the theory about its origin?
------------------------------------------------------

Generating positive clarifying questions:  55%|█████▌    | 546/990 [05:32<03:59,  1.85it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a male or female singer, a specific role they might have played, or a particular version of the song?[/OUTPUT]
=========================


🟩 Row 545
Q: Who sings if we could turn back time?
Facets: ['Gender', 'Role Type', 'Entity Type']
✅ Clarifying Question: Are you asking about a male or female singer, a specific role they might have played, or a particular version of the song?
------------------------------------------------------

Generating positive clarifying questions:  55%|█████▌    | 547/990 [05:33<04:46,  1.54it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the construction stage or an event related to the titan, and which specific Six Flags park you're referring to?[/OUTPUT]
=========================


🟩 Row 546
Q: When was the titan built at six flags?
Facets: ['Construction Stage', 'Event Type']
✅ Clarifying Question: Could you specify whether you're asking about the construction stage or an event related to the titan, and which specific Six Flags park you're referring to?
------------------------------------------------------

Generating positive clarifying questions:  55%|█████▌    | 548/990 [05:34<04:55,  1.50it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific version of Jumanji: The Next Level are you referring to?[/OUTPUT]
=========================


🟩 Row 547
Q: How long is the movie jumanji part 2?
Facets: ['Movie Title']
✅ Clarifying Question: Which specific version of Jumanji: The Next Level are you referring to?
------------------------------------------------------

Generating positive clarifying questions:  56%|█████▌    | 551/990 [05:35<03:38,  2.01it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the latest version for Excel specifically on Windows, or do you need information for both Windows and Mac versions?[/OUTPUT]
=========================


🟩 Row 550
Q: What is the latest version of excel for windows?
Facets: ['Version Number']
✅ Clarifying Question: Are you asking about the latest version for Excel specifically on Windows, or do you need information for both Windows and Mac versions?
------------------------------------------------------

Generating positive clarifying questions:  56%|█████▌    | 552/990 [05:36<04:37,  1.58it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the historical role or title of the person who converted the Hagia Sophia, and if there's a particular time period you're interested in?[/OUTPUT]
=========================


🟩 Row 551
Q: Who turned the hagia sophia into a mosque?
Facets: ['Type of Entity', 'Role or Title']
✅ Clarifying Question: Could you specify whether you're asking about the historical role or title of the person who converted the Hagia Sophia, and if there's a particular time period you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  56%|█████▌    | 553/990 [05:37<04:49,  1.51it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know the latest version of Adobe Dreamweaver?[/OUTPUT]
=========================


🟩 Row 552
Q: What is the latest version of adobe dreamweaver?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know the latest version of Adobe Dreamweaver?
------------------------------------------------------

Generating positive clarifying questions:  56%|█████▌    | 554/990 [05:38<05:18,  1.37it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific scene or throughout the entire story do you want to know where "Fried Green Tomatoes" takes place?[/OUTPUT]
=========================


🟩 Row 553
Q: Where does the movie fried green tomatoes take place?
Facets: ['Scene Specificity', 'Story vs. Setting']
✅ Clarifying Question: In which specific scene or throughout the entire story do you want to know where "Fried Green Tomatoes" takes place?
------------------------------------------------------

Generating positive clarifying questions:  56%|█████▋    | 557/990 [05:39<03:49,  1.89it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the geographical locations on a map, or do you need information about the courses or specific points along these rivers?[/OUTPUT]
=========================


🟩 Row 556
Q: Location of tigris and euphrates rivers on a map?
Facets: ['Type of Entity', 'Geographical Feature']
✅ Clarifying Question: Are you asking about the geographical locations on a map, or do you need information about the courses or specific points along these rivers?
------------------------------------------------------

Generating positive clarifying questions:  56%|█████▋    | 558/990 [05:40<04:22,  1.65it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which sport do you mean by 'womens world cup', and do you want to know about any specific medal type?[/OUTPUT]
=========================


🟩 Row 557
Q: Who is winner of womens world cup 2017?
Facets: ['Sport Type', 'Medal Type']
✅ Clarifying Question: Which sport do you mean by 'womens world cup', and do you want to know about any specific medal type?
------------------------------------------------------

Generating positive clarifying questions:  57%|█████▋    | 560/990 [05:41<03:59,  1.79it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the specific release date of a particular SAP GUI version, or do you need information about multiple versions?[/OUTPUT]
=========================


🟩 Row 559
Q: What is the current version of sap gui?
Facets: ['Release Date']
✅ Clarifying Question: Are you asking about the specific release date of a particular SAP GUI version, or do you need information about multiple versions?
------------------------------------------------------

Generating positive clarifying questions:  57%|█████▋    | 562/990 [05:42<03:45,  1.90it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year and for which soccer event do you want to know who Belgium plays in the round of 16?[/OUTPUT]
=========================


🟩 Row 561
Q: Who does belgium play in round of 16?
Facets: ['Year', 'Event Category']
✅ Clarifying Question: In which year and for which soccer event do you want to know who Belgium plays in the round of 16?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region are you referring to when asking about the release date of Small Soldiers?[/OUTPUT]
=========================

Generating positive clarifying questions:  57%|█████▋    | 564/990 [05:43<03:45,  1.89it/s]

🟩 Row 563
Q: When did the movie small soldiers come out?
Facets: ['Geographical Region']
✅ Clarifying Question: In which geographical region are you referring to when asking about the release date of Small Soldiers?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if this refers to a particular event in the show or a general plot point, and provide more details about the context?[/OUTPUT]
=========================

Generating positive clarifying questions:  57%|█████▋    | 565/990 [05:44<04:55,  1.44it/s]

🟩 Row 564
Q: Who did martha from home and away run away with?
Facets: ['Event Type', 'Contextual Information']
✅ Clarifying Question: Could you specify if this refers to a particular event in the show or a general plot point, and provide more details about the context?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the release date of the dolls as a toy or as a cultural event, and if there's a particular year or range of years you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  57%|█████▋    | 566/990 [05:46<06:12,  1.14it/s]

🟩 Row 565
Q: When did the cabbage patch dolls come out?
Facets: ["Definition of 'come out'", 'Event Type']
✅ Clarifying Question: Could you specify whether you're asking about the release date of the dolls as a toy or as a cultural event, and if there's a particular year or range of years you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the varicella vaccine or another type, and whether you need the introduction date for the general population or for clinical trials?[/OUTPUT]
=========================

Generating positive clarifying questions:  57%|█████▋    | 568/990 [05:47<05:26,  1.29it/s]

🟩 Row 567
Q: When was the chickenpox vaccine introduced in the united states?
Facets: ['Vaccine Type']
✅ Clarifying Question: Could you specify if you're asking about the varicella vaccine or another type, and whether you need the introduction date for the general population or for clinical trials?
------------------------------------------------------

Generating positive clarifying questions:  57%|█████▋    | 569/990 [05:48<05:40,  1.24it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which season of Riverdale are you interested in, and in which year do you want to know about the release date?[/OUTPUT]
=========================


🟩 Row 568
Q: When do new episodes of riverdale come out?
Facets: ['Season Number']
✅ Clarifying Question: Which season of Riverdale are you interested in, and in which year do you want to know about the release date?
------------------------------------------------------

Generating positive clarifying questions:  58%|█████▊    | 570/990 [05:49<06:06,  1.15it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if this is related to basketball, soccer, or another sport, and if there's a particular situation or rule you're interested in?[/OUTPUT]
=========================


🟩 Row 569
Q: What can you get a technical foul for?
Facets: ['Level of Specificity']
✅ Clarifying Question: Could you specify if this is related to basketball, soccer, or another sport, and if there's a particular situation or rule you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  58%|█████▊    | 572/990 [05:50<04:56,  1.41it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're referring to the Old or New Testament, and which author wrote about the golden rule?[/OUTPUT]
=========================


🟩 Row 571
Q: Where in the bible does it talk about the golden rule?
Facets: ['Testament', 'Author']
✅ Clarifying Question: Could you specify whether you're referring to the Old or New Testament, and which author wrote about the golden rule?
------------------------------------------------------

Generating positive clarifying questions:  58%|█████▊    | 574/990 [05:51<04:18,  1.61it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about a specific type of habanero pepper, and if so, which one?[/OUTPUT]
=========================


🟩 Row 573
Q: What is the scoville unit of a habanero pepper?
Facets: ['Type of Habanero Pepper']
✅ Clarifying Question: Could you specify if you're asking about a specific type of habanero pepper, and if so, which one?
------------------------------------------------------

Generating positive clarifying questions:  58%|█████▊    | 576/990 [05:52<03:56,  1.75it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether the republic is a presidential or parliamentary system, and if the head of state also holds executive power?[/OUTPUT]
=========================


🟩 Row 575
Q: In a republican state the head of the state is?
Facets: ['Type of Republic', 'Executive Role of Head of State']
✅ Clarifying Question: Could you specify whether the republic is a presidential or parliamentary system, and if the head of state also holds executive power?
------------------------------------------------------

Generating positive clarifying questions:  58%|█████▊    | 577/990 [05:53<04:27,  1.54it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the copyright holder of the toy line or the animated series, and in what time period are you interested?[/OUTPUT]
=========================


🟩 Row 576
Q: Who owns the rights to masters of the universe?
Facets: ['Type of Entity', 'Event Category', 'Time']
✅ Clarifying Question: Are you asking about the copyright holder of the toy line or the animated series, and in what time period are you interested?
------------------------------------------------------

Generating positive clarifying questions:  59%|█████▉    | 582/990 [05:54<02:35,  2.63it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether Robin is referring to a sidekick or a villain, and which Robin character you're asking about?[/OUTPUT]
=========================


🟩 Row 581
Q: What was robin's name in batman and robin?
Facets: ['Character Attribute', 'Role Type']
✅ Clarifying Question: Could you specify whether Robin is referring to a sidekick or a villain, and which Robin character you're asking about?
------------------------------------------------------

Generating positive clarifying questions:  59%|█████▉    | 584/990 [05:55<02:45,  2.46it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which sales model was the first personal computer sold to the public? Directly to consumers or through business-to-business channels?[/OUTPUT]
=========================


🟩 Row 583
Q: When was the first personal computer sold to the public?
Facets: ['Sales Model']
✅ Clarifying Question: In which sales model was the first personal computer sold to the public? Directly to consumers or through business-to-business channels?
------------------------------------------------------

Generating positive clarifying questions:  59%|█████▉    | 588/990 [05:56<02:08,  3.12it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country's supreme court are you referring, as appointment processes can vary by location?[/OUTPUT]
=========================


🟩 Row 587
Q: Who appoints the chief justice of the supreme court?
Facets: ['Location']
✅ Clarifying Question: In which country's supreme court are you referring, as appointment processes can vary by location?
------------------------------------------------------

Generating positive clarifying questions:  59%|█████▉    | 589/990 [05:56<02:28,  2.70it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country and geographical area does this fire fighting chief officer work?[/OUTPUT]
=========================


🟩 Row 588
Q: What colour is the fire fighting chief officers helmet?
Facets: ['Title of Position', 'Geographical Region', 'Country Specific Title']
✅ Clarifying Question: In which country and geographical area does this fire fighting chief officer work?
------------------------------------------------------

Generating positive clarifying questions:  60%|█████▉    | 590/990 [05:57<02:51,  2.33it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific time period or subgroup of Marines for basic training?[/OUTPUT]
=========================


🟩 Row 589
Q: Where do you go for basic training in the marines?
Facets: ['Time Period', 'Subgroup of Marines']
✅ Clarifying Question: Are you asking about a specific time period or subgroup of Marines for basic training?
------------------------------------------------------

Generating positive clarifying questions:  60%|█████▉    | 591/990 [05:58<03:18,  2.01it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific treaty of Utrecht are you referring to, and what year was it signed?[/OUTPUT]
=========================


🟩 Row 590
Q: What was the impact of the treaty of utrecht?
Facets: ['Name of Treaty', 'Date of Treaty']
✅ Clarifying Question: Which specific treaty of Utrecht are you referring to, and what year was it signed?
------------------------------------------------------

Generating positive clarifying questions:  60%|█████▉    | 592/990 [05:59<04:22,  1.52it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific episode number, the type of event (e.g., premiere, finale), or a geographical location related to the release of season 7 of Game of Thrones?[/OUTPUT]
=========================


🟩 Row 591
Q: When was season 7 of game of thrones released?
Facets: ['Episode Number', 'Event Type', 'Geographical Location']
✅ Clarifying Question: Are you asking about a specific episode number, the type of event (e.g., premiere, finale), or a geographical location related to the release of season 7 of Game of Thrones?
------------------------------------------------------

Generating positive clarifying questions:  60%|█████▉    | 593/990 [06:00<04:43,  1.40it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the lead vocalist or a background singer in the song "Back in the High Life Again"?[/OUTPUT]
=========================


🟩 Row 592
Q: Who sang back in the high life again?
Facets: ['Type of Vocal Role']
✅ Clarifying Question: Are you asking about the lead vocalist or a background singer in the song "Back in the High Life Again"?
------------------------------------------------------

Generating positive clarifying questions:  61%|██████    | 599/990 [06:01<02:06,  3.08it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you asking about the chief of police of Los Angeles?[/OUTPUT]
=========================


🟩 Row 598
Q: Who is the chief of police of los angeles?
Facets: ['Time Period']
✅ Clarifying Question: In which time period are you asking about the chief of police of Los Angeles?
------------------------------------------------------

Generating positive clarifying questions:  61%|██████    | 603/990 [06:02<01:53,  3.42it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the geographical features themselves or their political status, and do you want information on both areas together or separately?[/OUTPUT]
=========================


🟩 Row 602
Q: What is the west bank and gaza strip?
Facets: ['Geographical Feature']
✅ Clarifying Question: Are you asking about the geographical features themselves or their political status, and do you want information on both areas together or separately?
------------------------------------------------------

Generating positive clarifying questions:  61%|██████    | 606/990 [06:03<01:53,  3.37it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country are these districts located, and are you asking about a specific time period or just their current location?[/OUTPUT]
=========================


🟩 Row 605
Q: Where is the district of tyre and sidon?
Facets: ['Geographical Level', 'Administrative Division Type']
✅ Clarifying Question: In which country are these districts located, and are you asking about a specific time period or just their current location?
------------------------------------------------------

Generating positive clarifying questions:  61%|██████▏   | 607/990 [06:04<02:23,  2.66it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether it was an international or domestic match, and if there's a particular era you're interested in?[/OUTPUT]
=========================


🟩 Row 606
Q: When was cricket played first time in india?
Facets: ['Type of Cricket Match']
✅ Clarifying Question: Could you specify whether it was an international or domestic match, and if there's a particular era you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  62%|██████▏   | 610/990 [06:04<02:06,  3.01it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which sequence number of the show do Harvey and Sabrina get back together?[/OUTPUT]
=========================


🟩 Row 609
Q: When do harvey and sabrina get back together?
Facets: ['Sequence Number']
✅ Clarifying Question: In which sequence number of the show do Harvey and Sabrina get back together?
------------------------------------------------------

Generating positive clarifying questions:  62%|██████▏   | 611/990 [06:06<02:53,  2.18it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the character role in a specific version of Captain Scarlet, whether it's a voice or written medium, and if it's from the original series or a remake?[/OUTPUT]
=========================


🟩 Row 610
Q: Personal assistant to colonel white in captain scarlet?
Facets: ['Character Role', 'Medium (Voice or Written)', 'Version of Captain Scarlet']
✅ Clarifying Question: Are you asking about the character role in a specific version of Captain Scarlet, whether it's a voice or written medium, and if it's from the original series or a remake?
------------------------------------------------------

Generating positive clarifying questions:  62%|██████▏   | 613/990 [06:07<02:56,  2.13it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the religious tradition, the specific name of the person involved, and if there's an alternative name for this story?[/OUTPUT]
=========================


🟩 Row 612
Q: Who was turned to a pillar of salt?
Facets: ['Religious Tradition', 'Specific Name', 'Alternative Name']
✅ Clarifying Question: Could you specify the religious tradition, the specific name of the person involved, and if there's an alternative name for this story?
------------------------------------------------------

Generating positive clarifying questions:  62%|██████▏   | 614/990 [06:07<03:14,  1.93it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the original book or its film adaptation?[/OUTPUT]
=========================


🟩 Row 613
Q: Where does the perks of being a wallflower take place?
Facets: ['Medium of Adaptation']
✅ Clarifying Question: Could you specify whether you're asking about the original book or its film adaptation?
------------------------------------------------------

Generating positive clarifying questions:  62%|██████▏   | 615/990 [06:08<03:39,  1.71it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about Lara Croft's age in the new Tomb Raider movie or the character's age?[/OUTPUT]
=========================


🟩 Row 614
Q: Who plays lara croft in the new tomb raider?
Facets: ['Character Age']
✅ Clarifying Question: Are you asking about Lara Croft's age in the new Tomb Raider movie or the character's age?
------------------------------------------------------

Generating positive clarifying questions:  62%|██████▏   | 616/990 [06:09<03:50,  1.62it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did the composer or the lyricist write the French version of O Canada?[/OUTPUT]
=========================


🟩 Row 615
Q: Who wrote the french version of o canada?
Facets: ['Type of Contribution (Music/Words)']
✅ Clarifying Question: Did the composer or the lyricist write the French version of O Canada?
------------------------------------------------------

Generating positive clarifying questions:  62%|██████▏   | 617/990 [06:10<04:02,  1.54it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which NBA season were you referring to for the Rookie of the Year award?[/OUTPUT]
=========================


🟩 Row 616
Q: Who was the nba rookie of the year last year?
Facets: ['Season']
✅ Clarifying Question: In which NBA season were you referring to for the Rookie of the Year award?
------------------------------------------------------

Generating positive clarifying questions:  62%|██████▏   | 618/990 [06:11<04:24,  1.40it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which La Liga season are you asking about, and do you want the highest goal scorer from this specific season?[/OUTPUT]
=========================


🟩 Row 617
Q: La liga highest goal scorer in this season?
Facets: ['Season', 'Time Frame']
✅ Clarifying Question: Which La Liga season are you asking about, and do you want the highest goal scorer from this specific season?
------------------------------------------------------

Generating positive clarifying questions:  63%|██████▎   | 619/990 [06:12<04:42,  1.31it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which division level of the NCAA did the men's basketball championship take place in 2016?[/OUTPUT]
=========================


🟩 Row 618
Q: Who won the ncaa mens basketball championship in 2016?
Facets: ['Division Level']
✅ Clarifying Question: In which division level of the NCAA did the men's basketball championship take place in 2016?
------------------------------------------------------

Generating positive clarifying questions:  63%|██████▎   | 622/990 [06:12<03:03,  2.01it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which publication year and medium was "Picnic at Hanging Rock" released or published?[/OUTPUT]
=========================


🟩 Row 621
Q: Where is the hanging rock in picnic at hanging rock?
Facets: ['Publication Year', 'Medium of Publication']
✅ Clarifying Question: In which publication year and medium was "Picnic at Hanging Rock" released or published?
------------------------------------------------------

Generating positive clarifying questions:  63%|██████▎   | 623/990 [06:13<03:43,  1.64it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific region of America were the first Oreo cookies sold, and were they sold in a grocery store or another type of location?[/OUTPUT]
=========================


🟩 Row 622
Q: Where were the first oreo cookies sold in america?
Facets: ['Location', 'Product Attribute']
✅ Clarifying Question: In which specific region of America were the first Oreo cookies sold, and were they sold in a grocery store or another type of location?
------------------------------------------------------

Generating positive clarifying questions:  63%|██████▎   | 624/990 [06:14<04:08,  1.48it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about when season 2 of Ranch premiered or finished, and how many episodes were in that season?[/OUTPUT]
=========================


🟩 Row 623
Q: When did the ranch season 2 come out?
Facets: ['Part of Season', 'Number of Episodes']
✅ Clarifying Question: Are you asking about when season 2 of Ranch premiered or finished, and how many episodes were in that season?
------------------------------------------------------

Generating positive clarifying questions:  63%|██████▎   | 626/990 [06:15<03:44,  1.62it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the total number of presidents assassinated, the order in which they were assassinated, or the most recent assassination event?[/OUTPUT]
=========================


🟩 Row 625
Q: Who were the presidents that were assassinated while in office?
Facets: ['Number of Presidents', 'Order of Assassination', 'Most Recent Event']
✅ Clarifying Question: Are you asking about the total number of presidents assassinated, the order in which they were assassinated, or the most recent assassination event?
------------------------------------------------------

Generating positive clarifying questions:  63%|██████▎   | 627/990 [06:16<04:13,  1.43it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]At what specific date or event does the time zone officially switch from Eastern to Central, and in which geographical region are you referring?[/OUTPUT]
=========================


🟩 Row 626
Q: Where does eastern time zone change to central?
Facets: ['Geographical Region']
✅ Clarifying Question: At what specific date or event does the time zone officially switch from Eastern to Central, and in which geographical region are you referring?
------------------------------------------------------

Generating positive clarifying questions:  63%|██████▎   | 628/990 [06:17<04:36,  1.31it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're interested in a total or partial solar eclipse, and over what period of time you're considering?[/OUTPUT]
=========================


🟩 Row 627
Q: When is the last time there was a solar eclipse in the us?
Facets: ['Type of Solar Eclipse', 'Time Frame']
✅ Clarifying Question: Could you specify whether you're interested in a total or partial solar eclipse, and over what period of time you're considering?
------------------------------------------------------

Generating positive clarifying questions:  64%|██████▎   | 630/990 [06:20<05:52,  1.02it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which version of "Dumb and Dumber" are you referring to, considering there might be different releases or adaptations?[/OUTPUT]

(Note: This example assumes there might be different versions or adaptations of "Dumb and Dumber," but based on the original facets provided, the clarification focuses on the movie title aspect.)

If the intention was to strictly adhere to the facets provided, the question would be:

[OUTPUT]Are you asking about "Dumb and Dumber"
=========================


🟩 Row 629
Q: Who played freda in dumb and dumber 2?
Facets: ['Movie Title']
✅ Clarifying Question: Which version of "Dumb and Dumber" are you referring to, considering there might be different releases or adaptations?
------------------------------------------------------

Generating positive clarifying questions:  64%|██████▍   | 632/990 [06:21<04:41,  1.27it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the Doctor Who series, and specifically which actor played the role immediately following David Tennant?[/OUTPUT]
=========================


🟩 Row 631
Q: Who is the next doctor after david tennant?
Facets: ['Doctor Number', 'Character Name']
✅ Clarifying Question: Are you asking about the Doctor Who series, and specifically which actor played the role immediately following David Tennant?
------------------------------------------------------

Generating positive clarifying questions:  64%|██████▍   | 635/990 [06:22<03:27,  1.71it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the current location of the Golden State Warriors or a historical one, and in what time period are you interested?[/OUTPUT]
=========================


🟩 Row 634
Q: What city is home for the golden state warriors?
Facets: ['Time Period', 'Current Status']
✅ Clarifying Question: Are you asking about the current location of the Golden State Warriors or a historical one, and in what time period are you interested?
------------------------------------------------------

Generating positive clarifying questions:  64%|██████▍   | 637/990 [06:23<03:28,  1.69it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about a specific medium of adaptation or type of entity, such as a character or production version, for the matchmaker in Fiddler?[/OUTPUT]
=========================


🟩 Row 636
Q: What is the name of the matchmaker in fiddler?
Facets: ['Medium of Adaptation', 'Type of Entity']
✅ Clarifying Question: Could you specify whether you're asking about a specific medium of adaptation or type of entity, such as a character or production version, for the matchmaker in Fiddler?
------------------------------------------------------

Generating positive clarifying questions:  65%|██████▍   | 639/990 [06:24<03:05,  1.90it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know who calculated the most digits of pi?[/OUTPUT]
=========================


🟩 Row 638
Q: Who has calculated the most digits of pi?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know who calculated the most digits of pi?
------------------------------------------------------

Generating positive clarifying questions:  65%|██████▍   | 643/990 [06:25<02:22,  2.44it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about a particular mountain range or area, and if there's a specific part of North Carolina you're interested in?[/OUTPUT]
=========================


🟩 Row 642
Q: Where is the mountain region located in north carolina?
Facets: ["Definition of 'mountain region'", 'Geographical Region']
✅ Clarifying Question: Could you specify whether you're asking about a particular mountain range or area, and if there's a specific part of North Carolina you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  65%|██████▌   | 646/990 [06:26<02:02,  2.82it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In what specific year and month did Britain hand over Hong Kong to China?[/OUTPUT]
=========================


🟩 Row 645
Q: When did britain give hong kong to china?
Facets: ['Time Granularity']
✅ Clarifying Question: In what specific year and month did Britain hand over Hong Kong to China?
------------------------------------------------------

Generating positive clarifying questions:  65%|██████▌   | 648/990 [06:27<02:24,  2.37it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the number of runs scored in a single IPL match or across all matches in a season, and if it's for a specific player or all players?[/OUTPUT]
=========================


🟩 Row 647
Q: Most runs by a player in single ipl season?
Facets: ['Type of Entity', 'Measure of Success']
✅ Clarifying Question: Could you specify whether you're asking about the number of runs scored in a single IPL match or across all matches in a season, and if it's for a specific player or all players?
------------------------------------------------------

Generating positive clarifying questions:  66%|██████▌   | 652/990 [06:28<02:00,  2.80it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're referring to the crust type or topping type, and whether you want information about a filled pie or something else?[/OUTPUT]
=========================


🟩 Row 651
Q: American type of apple pie in a deep dish?
Facets: ['Crust Type', 'Topping Type']
✅ Clarifying Question: Could you specify if you're referring to the crust type or topping type, and whether you want information about a filled pie or something else?
------------------------------------------------------

Generating positive clarifying questions:  66%|██████▋   | 656/990 [06:29<01:44,  3.20it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you are referring to the denomination series or any other aspect of the 500 Rs note?[/OUTPUT]
=========================


🟩 Row 655
Q: When was 500 rs note introduced in india?
Facets: ['Series of Note']
✅ Clarifying Question: Could you specify whether you are referring to the denomination series or any other aspect of the 500 Rs note?
------------------------------------------------------

Generating positive clarifying questions:  67%|██████▋   | 665/990 [06:30<01:08,  4.75it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the Grammy Award for Record of the Year or another specific category, and do you want the most wins overall or in a particular genre?[/OUTPUT]
=========================


🟩 Row 664
Q: Who won the most grammys of all time?
Facets: ['Type of Entity']
✅ Clarifying Question: Are you asking about the Grammy Award for Record of the Year or another specific category, and do you want the most wins overall or in a particular genre?
------------------------------------------------------

Generating positive clarifying questions:  67%|██████▋   | 666/990 [06:31<01:22,  3.93it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know who had the most babies in one pregnancy?[/OUTPUT]
=========================


🟩 Row 665
Q: Who has had the most babies in one pregnancy?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know who had the most babies in one pregnancy?
------------------------------------------------------

Generating positive clarifying questions:  68%|██████▊   | 671/990 [06:31<01:10,  4.54it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Is this about a specific location, such as Japan or Italy, known for geological activity?[/OUTPUT]
=========================


🟩 Row 670
Q: Very geologically active region with many earthquakes and volcanoes?
Facets: ['Location']
✅ Clarifying Question: Is this about a specific location, such as Japan or Italy, known for geological activity?
------------------------------------------------------

Generating positive clarifying questions:  68%|██████▊   | 672/990 [06:32<01:28,  3.59it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the number of white or black keys, or both, on a standard piano?[/OUTPUT]
=========================


🟩 Row 671
Q: How many keys does a piano have full size?
Facets: ['Type of Key']
✅ Clarifying Question: Are you asking about the number of white or black keys, or both, on a standard piano?
------------------------------------------------------

Generating positive clarifying questions:  68%|██████▊   | 675/990 [06:33<01:36,  3.26it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did the term "combined Bible" refer to a specific name or label given to the combined version, or was there a particular event or meeting where this happened?[/OUTPUT]
=========================


🟩 Row 674
Q: When were the old and new testaments combined into the bible?
Facets: ['Name or Label Given to Combined Bible', 'Event or Meeting']
✅ Clarifying Question: Did the term "combined Bible" refer to a specific name or label given to the combined version, or was there a particular event or meeting where this happened?
------------------------------------------------------

Generating positive clarifying questions:  68%|██████▊   | 676/990 [06:34<01:54,  2.73it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the main score composer or a specific musical role for the film adaptation?[/OUTPUT]
=========================


🟩 Row 675
Q: Who did the music for last of the mohicans?
Facets: ['Role']
✅ Clarifying Question: Are you asking about the main score composer or a specific musical role for the film adaptation?
------------------------------------------------------

Generating positive clarifying questions:  68%|██████▊   | 677/990 [06:35<02:13,  2.35it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you asking about the director of the FBI's reporting structure?[/OUTPUT]
=========================


🟩 Row 676
Q: Who does the director of the fbi report to?
Facets: ['Time Period']
✅ Clarifying Question: In which time period are you asking about the director of the FBI's reporting structure?
------------------------------------------------------

Generating positive clarifying questions:  68%|██████▊   | 678/990 [06:36<02:40,  1.94it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about Delhi, the city, or Delhi, the state, and specifically for which period of British rule?[/OUTPUT]
=========================


🟩 Row 677
Q: When did delhi become capital of british india?
Facets: ['Type of Delhi']
✅ Clarifying Question: Are you asking about Delhi, the city, or Delhi, the state, and specifically for which period of British rule?
------------------------------------------------------

Generating positive clarifying questions:  69%|██████▊   | 680/990 [06:37<02:45,  1.87it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about when the U.S. ended its military conscription for the armed forces, or is there another specific event you're interested in regarding the draft?[/OUTPUT]
=========================


🟩 Row 679
Q: When did america get rid of the draft?
Facets: ['Specific Event', 'Type of Action']
✅ Clarifying Question: Are you asking about when the U.S. ended its military conscription for the armed forces, or is there another specific event you're interested in regarding the draft?
------------------------------------------------------

Generating positive clarifying questions:  69%|██████▉   | 683/990 [06:38<02:10,  2.36it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know who the captain of the Cornelia Marie was?[/OUTPUT]
=========================


🟩 Row 682
Q: Who was the captain of the cornelia marie?
Facets: ['Time Period', 'Year']
✅ Clarifying Question: In which year do you want to know who the captain of the Cornelia Marie was?
------------------------------------------------------

Generating positive clarifying questions:  69%|██████▉   | 685/990 [06:39<02:10,  2.34it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific scene of the movie The Lion King do you hear "Can You Feel the Love Tonight"?[/OUTPUT]
=========================


🟩 Row 684
Q: Who sings can you feel the love tonight in the movie the lion king?
Facets: ['Scene Context']
✅ Clarifying Question: In which specific scene of the movie The Lion King do you hear "Can You Feel the Love Tonight"?
------------------------------------------------------

Generating positive clarifying questions:  70%|██████▉   | 691/990 [06:40<01:28,  3.37it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about defensive or offensive rings, and do you want the total number of championship rings or a specific type of ring such as playoff or regular season?[/OUTPUT]
=========================


🟩 Row 690
Q: Who got the most rings in nba history?
Facets: ['Role in Team', 'Type of Ring']
✅ Clarifying Question: Are you asking about defensive or offensive rings, and do you want the total number of championship rings or a specific type of ring such as playoff or regular season?
------------------------------------------------------

Generating positive clarifying questions:  70%|██████▉   | 692/990 [06:41<01:45,  2.82it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which Harry Potter film and at what age stage of Tom Riddle were you referring?[/OUTPUT]
=========================


🟩 Row 691
Q: Who played young tom riddle in harry potter?
Facets: ['Character Age', 'Film Title', 'Character Stage of Life']
✅ Clarifying Question: In which Harry Potter film and at what age stage of Tom Riddle were you referring?
------------------------------------------------------

Generating positive clarifying questions:  70%|███████   | 696/990 [06:41<01:24,  3.50it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which term number are you referring to for the current president of the USA?[/OUTPUT]
=========================


🟩 Row 695
Q: Who is the current president of u s a?
Facets: ['Presidential Term Number']
✅ Clarifying Question: Which term number are you referring to for the current president of the USA?
------------------------------------------------------

Generating positive clarifying questions:  70%|███████   | 697/990 [06:42<01:41,  2.88it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the print edition or the digital version of The New York Times?[/OUTPUT]
=========================


🟩 Row 696
Q: Who is the publisher for the new york times?
Facets: ['Type of Entity']
✅ Clarifying Question: Are you asking about the print edition or the digital version of The New York Times?
------------------------------------------------------

Generating positive clarifying questions:  71%|███████   | 698/990 [06:44<02:24,  2.02it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the role of the golem, the actor who played the golem, or the golem's age in the novel "The Golem of Limehouse"?[/OUTPUT]
=========================


🟩 Row 697
Q: Who is the golem in the limehouse golem?
Facets: ['Character Role', 'Actor', 'Age of Character']
✅ Clarifying Question: Could you specify whether you're asking about the role of the golem, the actor who played the golem, or the golem's age in the novel "The Golem of Limehouse"?
------------------------------------------------------

Generating positive clarifying questions:  71%|███████   | 700/990 [06:45<02:27,  1.96it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific World Series event between the Dodgers and Yankees, and do you want the most recent occurrence or a particular year's game?[/OUTPUT]
=========================


🟩 Row 699
Q: When was the last time the dodgers and the yankees played in the world series?
Facets: ['Event Type', 'Time Frame']
✅ Clarifying Question: Are you asking about a specific World Series event between the Dodgers and Yankees, and do you want the most recent occurrence or a particular year's game?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the time period, the setting of the story, or where the film was shot?[/OUTPUT]
=========================

Generating positive clarifying questions:  71%|███████   | 701/990 [06:46<02:52,  1.67it/s]

🟩 Row 700
Q: Where does drag me to hell take place?
Facets: ['Time Period', 'Setting vs Filming Location']
✅ Clarifying Question: Could you specify if you're asking about the time period, the setting of the story, or where the film was shot?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Is the left lane specifically for overtaking, or does it serve another purpose on the motorway?[/OUTPUT]
=========================


🟩 Row 701
Q: What is the left lane of a motorway used for?
Facets: ['Type of Lane']
✅ Clarifying Question: Is the left lane specifically for overtaking, or does it serve another purpose on the motorway?
------------------------------------------------------

Generating positive clarifying questions:  71%|███████   | 702/990 [06:47<03:08,  1.53it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country's version of Hell's Kitchen are you referring, and was it the first season of the show itself or the first season broadcast in your country?[/OUTPUT]
=========================


🟩 Row 704
Q: Who won the first season of hells kitchen?
Facets: ['Location', 'Country']
✅ Clarifying Question: In which country's version of Hell's Kitchen are you referring, and was it the first season of the show itself or the first season broadcast in your country?
------------------------------------------------------

Generating positive clarifying questions:  71%|███████▏  | 706/990 [06:49<02:58,  1.59it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did the 1000 rs note get introduced or reintroduced, and are you asking about the first introduction or a later reintroduction?[/OUTPUT]
=========================


🟩 Row 705
Q: When was 1000 rs note introduced in india?
Facets: ['Action (introduced/reintroduced)', 'Time Frame (first/last)']
✅ Clarifying Question: Did the 1000 rs note get introduced or reintroduced, and are you asking about the first introduction or a later reintroduction?
------------------------------------------------------

Generating positive clarifying questions:  72%|███████▏  | 708/990 [06:50<02:54,  1.62it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did you refer to the visual observation or a scientific study for its discovery, and do you want the date of the initial report or the date of the first public announcement?[/OUTPUT]
=========================


🟩 Row 707
Q: When was the great pacific garbage patch found?
Facets: ['Nature of Discovery', 'Method of Discovery']
✅ Clarifying Question: Did you refer to the visual observation or a scientific study for its discovery, and do you want the date of the initial report or the date of the first public announcement?
------------------------------------------------------

Generating positive clarifying questions:  72%|███████▏  | 716/990 [06:51<01:21,  3.36it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're interested in the biggest stadium for a particular sport, and if there's a specific sport you have in mind?[/OUTPUT]
=========================


🟩 Row 715
Q: Which is the biggest stadium in the india?
Facets: ['Purpose', 'Sport Type']
✅ Clarifying Question: Could you specify whether you're interested in the biggest stadium for a particular sport, and if there's a specific sport you have in mind?
------------------------------------------------------

Generating positive clarifying questions:  72%|███████▏  | 717/990 [06:52<01:33,  2.90it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year did the Ladies' Roar of the Rings take place?[/OUTPUT]
=========================


🟩 Row 716
Q: Who won the ladies roar of the rings?
Facets: ['Year']
✅ Clarifying Question: In which year did the Ladies' Roar of the Rings take place?
------------------------------------------------------

Generating positive clarifying questions:  73%|███████▎  | 720/990 [06:53<01:33,  2.88it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if the title has changed from Anne with an E to Anne E, and which version of the show you're asking about?[/OUTPUT]
=========================


🟩 Row 719
Q: How many episodes in the first season of anne with an e?
Facets: ['Title Change Status']
✅ Clarifying Question: Could you specify if the title has changed from Anne with an E to Anne E, and which version of the show you're asking about?
------------------------------------------------------

Generating positive clarifying questions:  73%|███████▎  | 722/990 [06:54<01:45,  2.54it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific Stargate movie or TV series are you referring to, and do you want information about the filming location or another aspect of the property?[/OUTPUT]
=========================


🟩 Row 721
Q: Where were the desert scenes in stargate filmed?
Facets: ['Media Type', 'Year', 'Property Belonging To']
✅ Clarifying Question: Which specific Stargate movie or TV series are you referring to, and do you want information about the filming location or another aspect of the property?
------------------------------------------------------

Generating positive clarifying questions:  73%|███████▎  | 723/990 [06:55<01:59,  2.24it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the equatorial or polar diameter of the Earth in kilometers?[/OUTPUT]
=========================


🟩 Row 722
Q: What is the diameter of the earth in km?
Facets: ['Diameter Type']
✅ Clarifying Question: Are you asking about the equatorial or polar diameter of the Earth in kilometers?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the complete abolition of the death penalty, specifically in England and Wales, Scotland, or Northern Ireland, and during which time period?[/OUTPUT]
=========================


🟩 Row 723
Q: When did the death penalty stop in the uk?
Facets: ['Temporal Aspect', 'Geographical Region', 'Type of Abolition']
✅ Clarifying Question: Are you asking about the complete abolition of the death penalty, specifically in England and Wales, Scotland, or Northern Ireland, and during which time period?
------------------------------------------------------

Generating positive clarifying questions:  73%|███████▎  | 724/990 [06:56<02:28,  1.80it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know who sang "he don't love you like i love you"?[/OUTPUT]
=========================


🟩 Row 724
Q: Who sings he don't love you like i love you?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know who sang "he don't love you like i love you"?
------------------------------------------------------

Generating positive clarifying questions:  74%|███████▎  | 728/990 [06:58<02:05,  2.09it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific car ride, which part of Disneyland, and if there was any sponsor involved?[/OUTPUT]
=========================


🟩 Row 727
Q: When did the cars ride open at disneyland?
Facets: ['Car Ride Type', 'Location within Disneyland', 'Sponsorship']
✅ Clarifying Question: Are you asking about a specific car ride, which part of Disneyland, and if there was any sponsor involved?
------------------------------------------------------

Generating positive clarifying questions:  74%|███████▎  | 730/990 [06:58<01:57,  2.22it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific geographical region are you asking about the distribution of Buddhism's followers?[/OUTPUT]
=========================


🟩 Row 729
Q: Where do most followers of buddhism live today?
Facets: ['Geographical Unit']
✅ Clarifying Question: In which specific geographical region are you asking about the distribution of Buddhism's followers?
------------------------------------------------------

Generating positive clarifying questions:  74%|███████▍  | 731/990 [06:59<02:24,  1.79it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the aspect of the second person of the Trinity's nature that became man, or a specific doctrine related to this event?[/OUTPUT]
=========================


🟩 Row 730
Q: The second person of the trinity who became man?
Facets: ['Doctrine or Belief', "Aspect of Person's Nature"]
✅ Clarifying Question: Are you asking about the aspect of the second person of the Trinity's nature that became man, or a specific doctrine related to this event?
------------------------------------------------------

Generating positive clarifying questions:  74%|███████▍  | 732/990 [07:00<02:32,  1.69it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which country's version of Dancing with the Stars are you asking about?[/OUTPUT]
=========================


🟩 Row 731
Q: When was first season of dancing with the stars?
Facets: ['Country Version']
✅ Clarifying Question: Which country's version of Dancing with the Stars are you asking about?
------------------------------------------------------

Generating positive clarifying questions:  74%|███████▍  | 733/990 [07:01<02:54,  1.47it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did Sir Arthur Conan Doyle write his first book in present tense or past tense, and what specific book are you referring to?[/OUTPUT]
=========================


🟩 Row 732
Q: When did sir arthur conan doyle wrote his first book?
Facets: ['Type of Query (Age vs. Time)', 'Verb Tense']
✅ Clarifying Question: Did Sir Arthur Conan Doyle write his first book in present tense or past tense, and what specific book are you referring to?
------------------------------------------------------

Generating positive clarifying questions:  74%|███████▍  | 734/990 [07:02<03:09,  1.35it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which season of Vampire Diaries are you referring to, and do you need information for a specific range of seasons?[/OUTPUT]
=========================


🟩 Row 733
Q: How many episodes in a season of vampire diaries?
Facets: ['Season Number', 'Season Range']
✅ Clarifying Question: Which season of Vampire Diaries are you referring to, and do you need information for a specific range of seasons?
------------------------------------------------------

Generating positive clarifying questions:  75%|███████▍  | 738/990 [07:03<01:47,  2.35it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the side of the war and whether the soldier was Confederate or not?[/OUTPUT]
=========================


🟩 Row 737
Q: When did the last soldier of the civil war die?
Facets: ['Side of the War', 'Confederate Status']
✅ Clarifying Question: Could you specify the side of the war and whether the soldier was Confederate or not?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the origin of the style, the geographical region where it became popular, or the time period when baggy pants became trendy?[/OUTPUT]
=========================


🟩 Row 740
Q: Where did the baggy pants trend come from?
Facets: ['Type of Garment', 'Trend Aspect', 'Geographical Origin']
✅ Clarifying Question: Could you specify whether you're asking about the origin of the style, the geographical region where it became popular, or the time period when baggy pants became trendy?
------------------------------------------------------

Generating positive clarifying questions:  75%|███████▍  | 742/990 [07:05<02:03,  2.01it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did Case Keenum play for this team before joining the Vikings, and do you have a specific time period in mind?[/OUTPUT]
=========================


🟩 Row 741
Q: What team was case keenum on before the vikings?
Facets: ['Time Period', 'Specific Date']
✅ Clarifying Question: Did Case Keenum play for this team before joining the Vikings, and do you have a specific time period in mind?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the mission type, whether it was a religious or political mission, the exact location within England, and the approximate time period during which this occurred?[/OUTPUT]
=========================


🟩 Row 743
Q: Who was sent to england to convert the pagan anglo-saxons?
Facets: ['Mission Type', 'Location', 'Time Period']
✅ Clarifying Question: Could you specify the mission type, whether it was a religious or political mission, the exact location within England, and the approximate time period during which this occurred?
------------------------------------------------------

Generating positive clarifying questions:  75%|███████▌  | 744/990 [07:06<02:08,  1.91it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the author of the phrase or the title of a work, and if it's a book, movie, song, or something else?[/OUTPUT]
=========================

Generating positive clarifying questions:  75%|███████▌  | 746/990 [07:07<02:14,  1.82it/s]

🟩 Row 745
Q: Who wrote why dont we do it in the road?
Facets: ["Meaning of 'wrote'", 'Type of Entity']
✅ Clarifying Question: Could you specify whether you're asking about the author of the phrase or the title of a work, and if it's a book, movie, song, or something else?
------------------------------------------------------

Generating positive clarifying questions:  76%|███████▌  | 748/990 [07:09<02:21,  1.71it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the exact location of the Palace of Fine Arts, whether it refers to the construction start or completion date, and if there's a particular phase of its development you're interested in?[/OUTPUT]
=========================


🟩 Row 747
Q: When was the palace of fine arts built?
Facets: ['Building Event', 'Location', 'Building Phase']
✅ Clarifying Question: Could you specify the exact location of the Palace of Fine Arts, whether it refers to the construction start or completion date, and if there's a particular phase of its development you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  76%|███████▌  | 749/990 [07:10<02:36,  1.54it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which medium was this quote performed, in what year, and who is the speaker or entity you're referring to?[/OUTPUT]
=========================


🟩 Row 748
Q: Who said et tu brute in julius caesar?
Facets: ['Medium of Performance', 'Year', 'Type of Entity']
✅ Clarifying Question: In which medium was this quote performed, in what year, and who is the speaker or entity you're referring to?
------------------------------------------------------

Generating positive clarifying questions:  76%|███████▌  | 751/990 [07:11<02:26,  1.63it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a new Tomb Raider movie sequel, and if so, in which geographical region and when do you expect it to be released?[/OUTPUT]
=========================


🟩 Row 750
Q: When is the next tomb raider movie coming out?
Facets: ['Sequels', 'Geographical Region', 'Time of Release']
✅ Clarifying Question: Are you asking about a new Tomb Raider movie sequel, and if so, in which geographical region and when do you expect it to be released?
------------------------------------------------------

Generating positive clarifying questions:  76%|███████▌  | 753/990 [07:12<02:21,  1.68it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the TV series or the film, and which version of "The Seasons in the Sun" you're referring to?[/OUTPUT]
=========================


🟩 Row 752
Q: When did seasons in the sun come out?
Facets: ["Meaning of 'seasons in the sun'", 'Type of Entity']
✅ Clarifying Question: Could you specify whether you're asking about the TV series or the film, and which version of "The Seasons in the Sun" you're referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the geographical locations of its start and finish points, or if you need a definition of the Canal du Midi?[/OUTPUT]
=========================

Generating positive clarifying questions:  76%|███████▋  | 756/990 [07:13<01:57,  1.99it/s]

🟩 Row 755
Q: Where does canal du midi start and finish?
Facets: ['Start Location', 'Finish Location', 'Definition Clarification']
✅ Clarifying Question: Could you specify whether you're asking about the geographical locations of its start and finish points, or if you need a definition of the Canal du Midi?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the original theatrical film version or a different movie adaptation, and which specific year are you interested in?[/OUTPUT]
=========================


🟩 Row 757
Q: When did phantom of the opera movie come out?
Facets: ['Year', 'Movie Version']
✅ Clarifying Question: Are you asking about the original theatrical film version or a different movie adaptation, and which specific year are you interested in?
------------------------------------------------------

Generating positive clarifying questions:  77%|███████▋  | 761/990 [07:15<01:33,  2.46it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you are asking about gold, silver, or bronze medals?[/OUTPUT]
=========================


🟩 Row 760
Q: How many medals did canada win in the 2018 commonwealth games?
Facets: ['Medal Type']
✅ Clarifying Question: Could you specify if you are asking about gold, silver, or bronze medals?
------------------------------------------------------

Generating positive clarifying questions:  77%|███████▋  | 764/990 [07:16<01:23,  2.71it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region and during which phase of the eclipse are you asking about the start and end points?[/OUTPUT]
=========================


🟩 Row 763
Q: Where did the 2017 eclipse start and end?
Facets: ['Event Phase', 'Geographical Region']
✅ Clarifying Question: In which geographical region and during which phase of the eclipse are you asking about the start and end points?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific character's actions or an actor's performance, and which season or episode of the show are you referring to?[/OUTPUT]
=========================


🟩 Row 764
Q: Where did henry go on grounded for life?
Facets: ['Character vs Actor', 'Show Context']
✅ Clarifying Question: Are you asking about a specific character's actions or an actor's performance, and which season or episode of the show are you referring to?
------------------------------------------------------

Generating positive clarifying questions:  77%|███████▋  | 765/990 [07:17<01:45,  2.14it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the payment status for a particular event on July 4th or related to a specific context?[/OUTPUT]
=========================

Generating positive clarifying questions:  78%|███████▊  | 768/990 [07:18<01:33,  2.37it/s]

🟩 Row 767
Q: When did the 4th of july become a federal holiday?
Facets: ['Payment Status']
✅ Clarifying Question: Could you specify whether you're asking about the payment status for a particular event on July 4th or related to a specific context?
------------------------------------------------------

Generating positive clarifying questions:  78%|███████▊  | 771/990 [07:19<01:19,  2.75it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which season number of Law and Order: Special Victims Unit are you asking about?[/OUTPUT]
=========================


🟩 Row 770
Q: When does the new season of law and order special victims unit start?
Facets: ['Season Number']
✅ Clarifying Question: Which season number of Law and Order: Special Victims Unit are you asking about?
------------------------------------------------------

Generating positive clarifying questions:  78%|███████▊  | 772/990 [07:20<01:39,  2.20it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which sport and what specific event are you asking about regarding the first batsman to be given out by the third umpire?[/OUTPUT]
=========================


🟩 Row 771
Q: Who was the first batsman to be given out by third umpire?
Facets: ['Sport Type', 'Event Category']
✅ Clarifying Question: In which sport and what specific event are you asking about regarding the first batsman to be given out by the third umpire?
------------------------------------------------------

Generating positive clarifying questions:  78%|███████▊  | 773/990 [07:20<01:55,  1.88it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about Jeep Liberty models manufactured by a specific manufacturer or is there another manufacturer you're interested in?[/OUTPUT]
=========================


🟩 Row 772
Q: What was the last year jeep liberty was made?
Facets: ['Manufacturer']
✅ Clarifying Question: Are you asking about Jeep Liberty models manufactured by a specific manufacturer or is there another manufacturer you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  78%|███████▊  | 774/990 [07:21<02:07,  1.69it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the start or end of the French and Indian War?[/OUTPUT]
=========================


🟩 Row 773
Q: When did the french and indian war happen?
Facets: ['Event Phase']
✅ Clarifying Question: Could you specify whether you're asking about the start or end of the French and Indian War?
------------------------------------------------------

Generating positive clarifying questions:  78%|███████▊  | 775/990 [07:22<02:34,  1.39it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether the Hindenburg flight was intended for a particular location, and if you are asking about the number of passengers on the German or British airship?[/OUTPUT]
=========================


🟩 Row 774
Q: Where was the hindenburg scheduled to fly and how many passengers were on the british airship?
Facets: ['Facet of Ambiguity: Location of Flight', 'Facet of Ambiguity: Number of Passengers']
✅ Clarifying Question: Could you specify whether the Hindenburg flight was intended for a particular location, and if you are asking about the number of passengers on the German or British airship?
------------------------------------------------------

Generating positive clarifying questions:  79%|███████▊  | 778/990 [07:24<01:57,  1.80it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if this is from a film or a TV show, the exact line being spoken, the character's name, and the voice actor's name?[/OUTPUT]
=========================


🟩 Row 777
Q: Who says i late i late for a very important date?
Facets: ['Work Type', 'Medium', 'Character', 'Voice Actor', 'Film Year']
✅ Clarifying Question: Could you specify if this is from a film or a TV show, the exact line being spoken, the character's name, and the voice actor's name?
------------------------------------------------------

Generating positive clarifying questions:  79%|███████▊  | 779/990 [07:25<02:18,  1.52it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the rugby tour or another event, and if it's a specific location within South Africa or an international tour?[/OUTPUT]
=========================


🟩 Row 778
Q: When did the springbok tour start and end?
Facets: ['Event Phase', 'Geographical Location']
✅ Clarifying Question: Could you specify whether you're asking about the rugby tour or another event, and if it's a specific location within South Africa or an international tour?
------------------------------------------------------

Generating positive clarifying questions:  79%|███████▉  | 780/990 [07:26<02:41,  1.30it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're referring to the phrase from a historical quote or a modern expression, and if there's a particular context or source you have in mind?[/OUTPUT]
=========================


🟩 Row 779
Q: Who said these are times that try men's souls?
Facets: ['Action Performed', 'Phrase Used']
✅ Clarifying Question: Could you specify whether you're referring to the phrase from a historical quote or a modern expression, and if there's a particular context or source you have in mind?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which season are you referring to, and is this for a specific season number?[/OUTPUT]
=========================


🟩 Row 780
Q: When does the next step new season start?
Facets: ['Season Number']
✅ Clarifying Question: Which season are you referring to, and is this for a specific season number?
------------------------------------------------------

Generating positive clarifying questions:  79%|███████▉  | 781/990 [07:27<02:40,  1.30it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which work context, year, and medium was the song "I'm Telling You I'm Not Going" performed or released?[/OUTPUT]
=========================


🟩 Row 781
Q: Who sings i'm telling you i'm not going?
Facets: ['Work Context', 'Year', 'Medium']
✅ Clarifying Question: In which work context, year, and medium was the song "I'm Telling You I'm Not Going" performed or released?
------------------------------------------------------

Generating positive clarifying questions:  79%|███████▉  | 782/990 [07:28<02:53,  1.20it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which jurisdiction, what is the name of the legislation, and in which year do you want to know when the new data protection laws come into effect?[/OUTPUT]
=========================


🟩 Row 784
Q: When do the new data protection laws come into effect?
Facets: ['Jurisdiction', 'Legislation Name', 'Year']
✅ Clarifying Question: In which jurisdiction, what is the name of the legislation, and in which year do you want to know when the new data protection laws come into effect?
------------------------------------------------------

Generating positive clarifying questions:  79%|███████▉  | 786/990 [07:30<02:16,  1.49it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period or year do you want to know who played Drusilla on The Young and the Restless?[/OUTPUT]
=========================


🟩 Row 785
Q: Who played drusilla on the young and the restless?
Facets: ['Time Period', 'Year']
✅ Clarifying Question: In which time period or year do you want to know who played Drusilla on The Young and the Restless?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific character named Chef from South Park, and if so, which version or adaptation are you interested in?[/OUTPUT]
=========================


🟩 Row 786
Q: Who does chef's voice in south park?
Facets: ['Character Name', 'Voice Actor Assignment']
✅ Clarifying Question: Are you asking about a specific character named Chef from South Park, and if so, which version or adaptation are you interested in?
------------------------------------------------------

Generating positive clarifying questions:  80%|███████▉  | 789/990 [07:32<02:00,  1.67it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which part of the world or church tradition does this question pertain?[/OUTPUT]
=========================


🟩 Row 788
Q: Who wrote the book of philippians in the bible?
Facets: ['Location']
✅ Clarifying Question: In which part of the world or church tradition does this question pertain?
------------------------------------------------------

Generating positive clarifying questions:  80%|███████▉  | 790/990 [07:32<02:02,  1.63it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which country or region does this special election take place?[/OUTPUT]
=========================


🟩 Row 789
Q: Who calls a special election to fill a vacancy in the senate?
Facets: ['Location']
✅ Clarifying Question: In which country or region does this special election take place?
------------------------------------------------------

Generating positive clarifying questions:  80%|████████  | 795/990 [07:33<01:10,  2.77it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region and at which performance venue did you want to know when Star Wars: The Empire Strikes Back came out?[/OUTPUT]
=========================


🟩 Row 794
Q: When did star wars the empire strikes back come out?
Facets: ['Geographical Region', 'Performance Venue']
✅ Clarifying Question: In which geographical region and at which performance venue did you want to know when Star Wars: The Empire Strikes Back came out?
------------------------------------------------------

Generating positive clarifying questions:  81%|████████  | 798/990 [07:34<01:06,  2.88it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which series of Doctor Who are you asking about, and is this for the most recent season or a specific upcoming one?[/OUTPUT]
=========================


🟩 Row 797
Q: When do the new dr who episodes start?
Facets: ['Series Number']
✅ Clarifying Question: Which series of Doctor Who are you asking about, and is this for the most recent season or a specific upcoming one?
------------------------------------------------------

Generating positive clarifying questions:  81%|████████  | 800/990 [07:35<01:09,  2.74it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the location within South Africa and the severity of the drought you're interested in?[/OUTPUT]
=========================


🟩 Row 799
Q: When did the drought started in south africa?
Facets: ['Drought Location', 'Severity of Drought']
✅ Clarifying Question: Could you specify the location within South Africa and the severity of the drought you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  81%|████████  | 803/990 [07:36<01:15,  2.49it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the setting for the entire season 3, a specific episode within it, or a particular character's time period, and if it's a character's time period, who is the main focus?[/OUTPUT]
=========================


🟩 Row 802
Q: What year is outlander season 3 set in?
Facets: ['Episode Number', "Character's Time Period", 'Main Character Focus']
✅ Clarifying Question: Are you asking about the setting for the entire season 3, a specific episode within it, or a particular character's time period, and if it's a character's time period, who is the main focus?
------------------------------------------------------

Generating positive clarifying questions:  81%|████████  | 804/990 [07:38<01:34,  1.97it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the cause type you're interested in, whether there were specific entities involved, and if there's a particular source or author you're referring to?[/OUTPUT]
=========================


🟩 Row 803
Q: What led to the end of indus valley civilization?
Facets: ['Author/Source', 'Cause Type', 'Entity Involved']
✅ Clarifying Question: Could you specify the cause type you're interested in, whether there were specific entities involved, and if there's a particular source or author you're referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year's version of The Jungle Book were you referring to when asking about Kaa's voice actor?[/OUTPUT]
=========================


🟩 Row 804
Q: Who voiced kaa in the original jungle book?
Facets: ['Film Year']
✅ Clarifying Question: In which year's version of The Jungle Book were you referring to when asking about Kaa's voice actor?
------------------------------------------------------

Generating positive clarifying questions:  82%|████████▏ | 808/990 [07:39<01:26,  2.10it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Is the Colorado Plateau referring to a specific part within New Mexico, or are you asking about its neighboring states besides New Mexico?[/OUTPUT]
=========================


🟩 Row 807
Q: The colorado plateau covers northern new mexico and what other state?
Facets: ['Geographical Part']
✅ Clarifying Question: Is the Colorado Plateau referring to a specific part within New Mexico, or are you asking about its neighboring states besides New Mexico?
------------------------------------------------------

Generating positive clarifying questions:  82%|████████▏ | 810/990 [07:40<01:22,  2.17it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which specific year do you want to know when Collingwood last won a grand final?[/OUTPUT]
=========================


🟩 Row 809
Q: When did collingwood last won a grand final?
Facets: ['Year']
✅ Clarifying Question: In which specific year do you want to know when Collingwood last won a grand final?
------------------------------------------------------

Generating positive clarifying questions:  82%|████████▏ | 811/990 [07:41<01:38,  1.82it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if these objects are asteroids, planets, or something else, and if they have any particular characteristics or names?[/OUTPUT]
=========================


🟩 Row 810
Q: A group of objects orbiting between mars and jupiter?
Facets: ['Definition']
✅ Clarifying Question: Could you specify if these objects are asteroids, planets, or something else, and if they have any particular characteristics or names?
------------------------------------------------------

Generating positive clarifying questions:  83%|████████▎ | 819/990 [07:42<00:45,  3.76it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the movie or the TV series, and which specific Guardians of the Galaxy release are you referring to?[/OUTPUT]
=========================


🟩 Row 818
Q: Who plays drax on gaurdians of the galaxy?
Facets: ['Media Type', 'Release Year', 'Specific Product']
✅ Clarifying Question: Are you asking about the movie or the TV series, and which specific Guardians of the Galaxy release are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Do you want to know when Tony Romo's documentary "A Football Life" aired, and on which specific date?[/OUTPUT]
=========================

Generating positive clarifying questions:  83%|████████▎ | 820/990 [07:43<00:57,  2.94it/s]

🟩 Row 819
Q: When does tony romo a football life air?
Facets: ['Time', 'Date']
✅ Clarifying Question: Do you want to know when Tony Romo's documentary "A Football Life" aired, and on which specific date?
------------------------------------------------------

Generating positive clarifying questions:  83%|████████▎ | 823/990 [07:44<00:51,  3.26it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which season were the Olympic Games held in the United States?[/OUTPUT]
=========================


🟩 Row 822
Q: Where was the first olympics held in the united states?
Facets: ['Season']
✅ Clarifying Question: In which season were the Olympic Games held in the United States?
------------------------------------------------------

Generating positive clarifying questions:  83%|████████▎ | 824/990 [07:45<01:04,  2.56it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which version of Beauty and the Beast are you referring to, and is there a specific time period you're interested in?[/OUTPUT]
=========================


🟩 Row 823
Q: When was the original story of beauty and the beast written?
Facets: ['Version of the Story']
✅ Clarifying Question: Which version of Beauty and the Beast are you referring to, and is there a specific time period you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which season of Dragon Ball Super do you want to know about the release date for the English dub?[/OUTPUT]
=========================


🟩 Row 829
Q: When will dragon ball super english dub be released?
Facets: ['Season Number']
✅ Clarifying Question: In which season of Dragon Ball Super do you want to know about the release date for the English dub?
------------------------------------------------------

Generating positive clarifying questions:  84%|████████▍ | 830/990 [07:46<00:45,  3.51it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which season and specific episode are you referring to, and do you want to know by what name the episode was titled or its original air date?[/OUTPUT]
=========================


🟩 Row 830
Q: Prison break what episode do michael and sara kiss?
Facets: ['Season and Episode', 'Episode Name', 'Original Air Date']
✅ Clarifying Question: Which season and specific episode are you referring to, and do you want to know by what name the episode was titled or its original air date?
------------------------------------------------------

Generating positive clarifying questions:  84%|████████▍ | 831/990 [07:47<01:06,  2.39it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which specific Tomb Raider film version are you asking about, and in what time period does it fall?[/OUTPUT]
=========================

Generating positive clarifying questions:  84%|████████▍ | 835/990 [07:49<00:59,  2.62it/s]

🟩 Row 834
Q: Who's the actress that plays in tomb raider?
Facets: ['Media Type', 'Time Period', 'Specific Film Version']
✅ Clarifying Question: Which specific Tomb Raider film version are you asking about, and in what time period does it fall?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know when the FA Cup semi-final was played?[/OUTPUT]
=========================

Generating positive clarifying questions:  85%|████████▍ | 838/990 [07:50<00:57,  2.65it/s]

🟩 Row 837
Q: When is the fa cup semi final played?
Facets: ['Year']
✅ Clarifying Question: In which year do you want to know when the FA Cup semi-final was played?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the movie, album, or book titled "The Sky's the Limit," and the exact year you're interested in?[/OUTPUT]
=========================


🟩 Row 840
Q: When did the sky's the limit come out?
Facets: ['Title of Work', 'Release Type', 'Year', 'Genre/Category']
✅ Clarifying Question: Could you specify whether you're asking about the movie, album, or book titled "The Sky's the Limit," and the exact year you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  85%|████████▍ | 841/990 [07:51<00:59,  2.50it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about club teams, countries, or individual players who have won the Europa League the most?[/OUTPUT]
=========================

Generating positive clarifying questions:  85%|████████▌ | 843/990 [07:52<01:02,  2.36it/s]

🟩 Row 842
Q: Who has won the europa league the most?
Facets: ['Type of Entity (Club/Country/Player)']
✅ Clarifying Question: Are you asking about club teams, countries, or individual players who have won the Europa League the most?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the initial release date or an update for iOS 11 on iPhone 7, and is this specific to a particular version status?[/OUTPUT]
=========================

Generating positive clarifying questions:  86%|████████▌ | 847/990 [07:53<00:54,  2.64it/s]

🟩 Row 846
Q: When does ios 11 release for iphone 7?
Facets: ['Release Type', 'Version Status']
✅ Clarifying Question: Are you asking about the initial release date or an update for iOS 11 on iPhone 7, and is this specific to a particular version status?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the main character's mother in the TV show "How I Met Your Mother," or someone else's mother mentioned in the series?[/OUTPUT]
=========================

Generating positive clarifying questions:  86%|████████▌ | 848/990 [07:55<01:07,  2.10it/s]

🟩 Row 847
Q: Who is the mother in how i met you mother?
Facets: ['Role', 'Entity Type']
✅ Clarifying Question: Are you asking about the main character's mother in the TV show "How I Met Your Mother," or someone else's mother mentioned in the series?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which field of the Nobel Peace Prize are you asking about, specifically in relation to the first African American to win this prize?[/OUTPUT]
=========================


🟩 Row 849
Q: First african american to win a nobel peace prize?
Facets: ['Field of Nobel Prize']
✅ Clarifying Question: Which field of the Nobel Peace Prize are you asking about, specifically in relation to the first African American to win this prize?
------------------------------------------------------

Generating positive clarifying questions:  86%|████████▌ | 850/990 [07:56<01:08,  2.04it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which season and country are you referring to for the judges of So You Think You Can Dance?[/OUTPUT]
=========================

Generating positive clarifying questions:  86%|████████▌ | 851/990 [07:57<01:17,  1.79it/s]

🟩 Row 850
Q: Who are the judges of so you think you dance?
Facets: ['Season', 'Country']
✅ Clarifying Question: In which season and country are you referring to for the judges of So You Think You Can Dance?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the name of the Magic the Gathering set and whether you're asking about its pre-order release date or the official release date?[/OUTPUT]
=========================

Generating positive clarifying questions:  86%|████████▋ | 854/990 [07:58<01:06,  2.05it/s]

🟩 Row 853
Q: When is the new magic the gathering set coming out?
Facets: ['Set Name', 'Release Type']
✅ Clarifying Question: Could you specify the name of the Magic the Gathering set and whether you're asking about its pre-order release date or the official release date?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which language and year do you want to know about the original singer of "Seasons in the Sun"?[/OUTPUT]
=========================

Generating positive clarifying questions:  86%|████████▋ | 855/990 [07:59<01:16,  1.77it/s]

🟩 Row 854
Q: Who sings the original seasons in the sun?
Facets: ['Language', 'Year']
✅ Clarifying Question: In which language and year do you want to know about the original singer of "Seasons in the Sun"?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Did the movie feature a specific character named "A Summer Place," or were you referring to the actors who starred in it?[/OUTPUT]
=========================


🟩 Row 860
Q: Who starred in the movie a summer place?
Facets: ['Character Name']
✅ Clarifying Question: Did the movie feature a specific character named "A Summer Place," or were you referring to the actors who starred in it?
------------------------------------------------------

Generating positive clarifying questions:  87%|████████▋ | 861/990 [08:00<00:43,  2.94it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the television series or a movie adaptation, and if it's the series, do you want to know when each episode was released or the full season?[/OUTPUT]
=========================

Generating positive clarifying questions:  87%|████████▋ | 864/990 [08:01<00:45,  2.76it/s]

🟩 Row 863
Q: The truth about the harry quebert affair tv show release date?
Facets: ['Type of Release', 'Amount of Content Released']
✅ Clarifying Question: Are you asking about the television series or a movie adaptation, and if it's the series, do you want to know when each episode was released or the full season?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the original version or a remix, the media format, and the geographical region where it was released?[/OUTPUT]
=========================

Generating positive clarifying questions:  87%|████████▋ | 865/990 [08:02<00:56,  2.20it/s]

🟩 Row 864
Q: When did there's nothing holdin me back come out?
Facets: ['Type of Release', 'Media Format', 'Geographical Region', 'Remix/Version']
✅ Clarifying Question: Could you specify whether you're asking about the original version or a remix, the media format, and the geographical region where it was released?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you asking about the number of congressional districts in Michigan?[/OUTPUT]
=========================

Generating positive clarifying questions:  88%|████████▊ | 867/990 [08:03<00:54,  2.27it/s]

🟩 Row 866
Q: How many congressional districts are there in michigan?
Facets: ['Time Period']
✅ Clarifying Question: In which time period are you asking about the number of congressional districts in Michigan?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time frame and during which presidency were you referring to when asking about the longest living president?[/OUTPUT]
=========================

Generating positive clarifying questions:  88%|████████▊ | 868/990 [08:04<01:02,  1.94it/s]

🟩 Row 867
Q: Who was the longest living president of the united states?
Facets: ['Time Frame', 'Scope of Presidency']
✅ Clarifying Question: In which time frame and during which presidency were you referring to when asking about the longest living president?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which version of "Candle in the Wind" are you referring to, and for which specific person?[/OUTPUT]
=========================

Generating positive clarifying questions:  88%|████████▊ | 871/990 [08:05<00:51,  2.31it/s]

🟩 Row 870
Q: Who was the song candle in the wind written about?
Facets: ['Version of the Song']
✅ Clarifying Question: Which version of "Candle in the Wind" are you referring to, and for which specific person?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether these are FIFA's continental confederations for men's soccer or any other sport, and if there's a particular year or period you're interested in?[/OUTPUT]
=========================


🟩 Row 873
Q: What are the six continental confederations of fifa?
Facets: ['Function', 'Name']
✅ Clarifying Question: Could you specify whether these are FIFA's continental confederations for men's soccer or any other sport, and if there's a particular year or period you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  88%|████████▊ | 874/990 [08:06<00:49,  2.33it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which year's version of "Abide With Me" are you asking about, and what is the title of the song?[/OUTPUT]
=========================

Generating positive clarifying questions:  88%|████████▊ | 875/990 [08:07<00:59,  1.95it/s]

🟩 Row 874
Q: Who wrote the words to abide with me?
Facets: ['Year', 'Title of the Song']
✅ Clarifying Question: Which year's version of "Abide With Me" are you asking about, and what is the title of the song?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the time frame, type of match, and competition for the matches you're considering?[/OUTPUT]
=========================

Generating positive clarifying questions:  89%|████████▊ | 877/990 [08:08<00:55,  2.04it/s]

🟩 Row 876
Q: Who has scored the most goals for chelsea?
Facets: ['Time Frame', 'Type of Match', 'Competition']
✅ Clarifying Question: Could you specify the time frame, type of match, and competition for the matches you're considering?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a musical play or a song, and if it's a song, would you like information on its lyrics or composer?[/OUTPUT]
=========================

Generating positive clarifying questions:  89%|████████▊ | 878/990 [08:09<01:11,  1.57it/s]

🟩 Row 877
Q: Who wrote play your own kind of music?
Facets: ['Type of Work']
✅ Clarifying Question: Are you asking about a musical play or a song, and if it's a song, would you like information on its lyrics or composer?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which season of The Punisher are you asking about, and do you mean the release date for the series or a specific episode?[/OUTPUT]
=========================


🟩 Row 879
Q: What's the release date for the punisher on netflix?
Facets: ['Season Number']
✅ Clarifying Question: Which season of The Punisher are you asking about, and do you mean the release date for the series or a specific episode?
------------------------------------------------------

Generating positive clarifying questions:  89%|████████▉ | 880/990 [08:11<01:09,  1.59it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the character who played the banjo or the actor who portrayed him in the movie Deliverance?[/OUTPUT]
=========================

Generating positive clarifying questions:  89%|████████▉ | 881/990 [08:12<01:19,  1.37it/s]

🟩 Row 880
Q: Who was the boy who played the banjo in the movie deliverance?
Facets: ['Character vs Actor']
✅ Clarifying Question: Are you asking about the character who played the banjo or the actor who portrayed him in the movie Deliverance?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which season and year did Eddie appear on Frasier?[/OUTPUT]
=========================

Generating positive clarifying questions:  89%|████████▉ | 885/990 [08:13<00:48,  2.17it/s]

🟩 Row 884
Q: Who played eddie on the tv show frasier?
Facets: ['Time Period', 'Character Role']
✅ Clarifying Question: In which season and year did Eddie appear on Frasier?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Did you mean the first use of the term by a specific individual, or during a particular time period in history?[/OUTPUT]
=========================

Generating positive clarifying questions:  89%|████████▉ | 886/990 [08:14<00:59,  1.75it/s]

🟩 Row 885
Q: Who used the word psychology for the first time?
Facets: ['Credit Attribution', 'Time Period']
✅ Clarifying Question: Did you mean the first use of the term by a specific individual, or during a particular time period in history?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the specific year blood transfusions became generally safer, the inventor behind a significant improvement, the event category such as medical breakthrough or regulatory change, or a particular time period like the mid-20th century?[/OUTPUT]
=========================

Generating positive clarifying questions:  90%|████████▉ | 887/990 [08:15<01:20,  1.28it/s]

🟩 Row 886
Q: When did blood transfusions become safer and why?
Facets: ['Year', 'Inventor/Discovery', 'Event Category', 'Time Period']
✅ Clarifying Question: Are you asking about the specific year blood transfusions became generally safer, the inventor behind a significant improvement, the event category such as medical breakthrough or regulatory change, or a particular time period like the mid-20th century?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about the episode where Doug and Carol get married, and which episode or season number it is in?[/OUTPUT]
=========================

Generating positive clarifying questions:  90%|████████▉ | 888/990 [08:17<01:30,  1.13it/s]

🟩 Row 887
Q: When do doug and carol get married in er?
Facets: ['Type of Query', 'Episode Information']
✅ Clarifying Question: Could you specify if you're asking about the episode where Doug and Carol get married, and which episode or season number it is in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region are you referring to when asking about the release date of Dirty Dancing?[/OUTPUT]
=========================

Generating positive clarifying questions:  90%|████████▉ | 890/990 [08:18<01:16,  1.30it/s]

🟩 Row 889
Q: When did the movie dirty dancing come out?
Facets: ['Geographical Region']
✅ Clarifying Question: In which geographical region are you referring to when asking about the release date of Dirty Dancing?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the most own goals scored by a player in Premier League history, and if there's a specific time period you're interested in?[/OUTPUT]
=========================

Generating positive clarifying questions:  90%|█████████ | 891/990 [08:19<01:28,  1.12it/s]

🟩 Row 890
Q: Player with most own goals in premier league?
Facets: ['Time Period', 'Type of Record']
✅ Clarifying Question: Are you asking about the most own goals scored by a player in Premier League history, and if there's a specific time period you're interested in?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region were you referring to when asking about the first Walt Disney Studios film released in 2017?[/OUTPUT]
=========================

Generating positive clarifying questions:  90%|█████████ | 892/990 [08:20<01:33,  1.05it/s]

🟩 Row 891
Q: What was the first walt disney studios film to be released in 2017?
Facets: ['Geographical Region']
✅ Clarifying Question: In which geographical region were you referring to when asking about the first Walt Disney Studios film released in 2017?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the character named Ursula from The Little Mermaid or the actress who voiced her?[/OUTPUT]
=========================

Generating positive clarifying questions:  90%|█████████ | 894/990 [08:21<01:14,  1.29it/s]

🟩 Row 893
Q: Who does the voice of ursula in the little mermaid?
Facets: ['Character Name', 'Actor Name']
✅ Clarifying Question: Are you asking about the character named Ursula from The Little Mermaid or the actress who voiced her?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period were you referring to when asking about the first Unix operating system's programming language?[/OUTPUT]
=========================

Generating positive clarifying questions:  91%|█████████ | 896/990 [08:22<01:02,  1.51it/s]

🟩 Row 895
Q: The first unix operating system was written in which language?
Facets: ['Time of Writing']
✅ Clarifying Question: In which time period were you referring to when asking about the first Unix operating system's programming language?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the country whose Freedom of Information Act you are referring to, the specific types of exemptions you're interested in, and if there have been any recent amendments?[/OUTPUT]
=========================

Generating positive clarifying questions:  91%|█████████ | 897/990 [08:24<01:20,  1.16it/s]

🟩 Row 896
Q: How many exemptions are there to the freedom of information act?
Facets: ['Country', 'Type of Exemption', 'Time of Amendment']
✅ Clarifying Question: Could you specify the country whose Freedom of Information Act you are referring to, the specific types of exemptions you're interested in, and if there have been any recent amendments?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In "How the Grinch Stole Christmas," does the title character live in a specific location within the story, or are you asking about a real-world geographical feature associated with the movie or book?[/OUTPUT]
=========================

Generating positive clarifying questions:  91%|█████████ | 898/990 [08:26<01:40,  1.09s/it]

🟩 Row 897
Q: In how the grinch stole christmas where does the title character live?
Facets: ['Title Character Residence', 'Geographical Feature']
✅ Clarifying Question: In "How the Grinch Stole Christmas," does the title character live in a specific location within the story, or are you asking about a real-world geographical feature associated with the movie or book?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the original version of the song, a specific performance event, the year it was popular, or a particular location where it was performed?[/OUTPUT]
=========================

Generating positive clarifying questions:  91%|█████████ | 899/990 [08:27<01:49,  1.21s/it]

🟩 Row 898
Q: Who sang the song a change is going to come?
Facets: ['Year', 'Event Category', 'Location', 'Type of Performance', 'Covered Version', 'Tribute Performance']
✅ Clarifying Question: Are you asking about the original version of the song, a specific performance event, the year it was popular, or a particular location where it was performed?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year and on which streaming platform does series 2 of Handmaid's Tale air?[/OUTPUT]
=========================

Generating positive clarifying questions:  91%|█████████ | 901/990 [08:28<01:23,  1.07it/s]

🟩 Row 900
Q: When does series 2 of handmaid's tale?
Facets: ['Event Timing']
✅ Clarifying Question: In which year and on which streaming platform does series 2 of Handmaid's Tale air?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which region and on which platform was Call of Duty WW2 released?[/OUTPUT]
=========================

Generating positive clarifying questions:  91%|█████████ | 903/990 [08:29<01:04,  1.34it/s]

🟩 Row 902
Q: When did call of duty ww2 come out?
Facets: ['Game Title', 'Region']
✅ Clarifying Question: In which region and on which platform was Call of Duty WW2 released?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the percentage ownership or the current status of the owner of the Rajasthan Royals?[/OUTPUT]
=========================

Generating positive clarifying questions:  91%|█████████▏| 904/990 [08:30<01:08,  1.26it/s]

🟩 Row 903
Q: Who is the owner of the rajasthan royals?
Facets: ['Ownership Percentage', 'Owner Status']
✅ Clarifying Question: Are you asking about the percentage ownership or the current status of the owner of the Rajasthan Royals?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which geographical region and on what medium did Pirates of the Caribbean 2 first release?[/OUTPUT]
=========================

Generating positive clarifying questions:  92%|█████████▏| 906/990 [08:31<00:55,  1.50it/s]

🟩 Row 905
Q: When did pirates of the caribbean 2 come out?
Facets: ['Release Medium', 'Geographical Region']
✅ Clarifying Question: In which geographical region and on what medium did Pirates of the Caribbean 2 first release?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Did Michael Jordan score these points during the regular season or playoffs?[/OUTPUT]
=========================

Generating positive clarifying questions:  92%|█████████▏| 907/990 [08:32<00:57,  1.46it/s]

🟩 Row 906
Q: How many points did michael jordan make in his career?
Facets: ['Type of Points (Regular Season vs Playoff)']
✅ Clarifying Question: Did Michael Jordan score these points during the regular season or playoffs?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which film version of Jeepers Creepers are you referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  92%|█████████▏| 908/990 [08:33<00:58,  1.41it/s]

🟩 Row 907
Q: Who's the guy that plays jeepers creepers?
Facets: ['Film Version']
✅ Clarifying Question: Which film version of Jeepers Creepers are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Which version of "The Nightmare Before Christmas" are you referring to?[/OUTPUT]
=========================

Generating positive clarifying questions:  92%|█████████▏| 909/990 [08:33<00:58,  1.39it/s]

🟩 Row 908
Q: Who plays sally in the nightmare before christmas?
Facets: ['Film Version']
✅ Clarifying Question: Which version of "The Nightmare Before Christmas" are you referring to?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the original movie or the musical stage production, and do you want the performer's name or a specific version of the song?[/OUTPUT]
=========================

Generating positive clarifying questions:  92%|█████████▏| 910/990 [08:35<01:05,  1.23it/s]

🟩 Row 909
Q: Who sings i need a hero in footloose?
Facets: ['Media Type', 'Entity Type']
✅ Clarifying Question: Are you asking about the original movie or the musical stage production, and do you want the performer's name or a specific version of the song?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the number of amendments currently ratified or those proposed but not yet ratified?[/OUTPUT]
=========================

Generating positive clarifying questions:  92%|█████████▏| 913/990 [08:35<00:40,  1.89it/s]

🟩 Row 912
Q: How many current amendments are there to the us constitution?
Facets: ['Status of Amendment']
✅ Clarifying Question: Are you asking about the number of amendments currently ratified or those proposed but not yet ratified?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year and on what medium was the character Bonnie from Gone with the Wind portrayed?[/OUTPUT]
=========================


🟩 Row 913
Q: Who played bonnie in gone with the wind?
Facets: ['Year', 'Medium (Film/Musical)']
✅ Clarifying Question: In which year and on what medium was the character Bonnie from Gone with the Wind portrayed?
------------------------------------------------------

Generating positive clarifying questions:  93%|█████████▎| 921/990 [08:37<00:18,  3.70it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Which season of Sabrina are you referring to, and in what year was it broadcast?[/OUTPUT]
=========================


🟩 Row 920
Q: Who did the voice of salem on sabrina?
Facets: ['Year', 'TV Series Title']
✅ Clarifying Question: Which season of Sabrina are you referring to, and in what year was it broadcast?
------------------------------------------------------

Generating positive clarifying questions:  93%|█████████▎| 922/990 [08:38<00:26,  2.61it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the social classes in France during the late 18th century specifically for the French Revolution period, and do you need the names or descriptions of these groups?[/OUTPUT]
=========================


🟩 Row 921
Q: What three groups composed french society in the late 1700s?
Facets: ['Question Type', 'Specificity of Answer Required']
✅ Clarifying Question: Are you asking about the social classes in France during the late 18th century specifically for the French Revolution period, and do you need the names or descriptions of these groups?
------------------------------------------------------

Generating positive clarifying questions:  93%|█████████▎| 923/990 [08:39<00:28,  2.38it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year was this U.S. Army general born?[/OUTPUT]
=========================


🟩 Row 922
Q: U.s. army general who won several victories in the mexican-american war?
Facets: ['Year of Birth']
✅ Clarifying Question: In which year was this U.S. Army general born?
------------------------------------------------------

Generating positive clarifying questions:  93%|█████████▎| 924/990 [08:40<00:33,  1.97it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year and version of the song are you referring to when asking about "you put the lime in the coconut"?[/OUTPUT]
=========================


🟩 Row 923
Q: Who sings you put the lime in the coconut?
Facets: ['Year', 'Version of Song']
✅ Clarifying Question: In which year and version of the song are you referring to when asking about "you put the lime in the coconut"?
------------------------------------------------------

Generating positive clarifying questions:  94%|█████████▎| 927/990 [08:41<00:28,  2.24it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the original recording, a specific version by a particular artist, or a cover version, and do you have a specific year in mind?[/OUTPUT]
=========================


🟩 Row 926
Q: Who recorded i can't make you love me?
Facets: ['Year', 'Action Verb', 'Song Title']
✅ Clarifying Question: Are you asking about the original recording, a specific version by a particular artist, or a cover version, and do you have a specific year in mind?
------------------------------------------------------

Generating positive clarifying questions:  94%|█████████▍| 930/990 [08:42<00:24,  2.49it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Did Italy fall under the control of a specific person, group, or nation after the 1525 Battle of Pavia?[/OUTPUT]
=========================


🟩 Row 929
Q: After the 1525 battle of pavia italy fell under the control of?
Facets: ['Type of Entity']
✅ Clarifying Question: Did Italy fall under the control of a specific person, group, or nation after the 1525 Battle of Pavia?
------------------------------------------------------

Generating positive clarifying questions:  94%|█████████▍| 932/990 [08:43<00:25,  2.31it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the setting for an indoor or outdoor scene, and if it's a specific location or a broader area?[/OUTPUT]
=========================


🟩 Row 931
Q: Where did they film battle of the network stars?
Facets: ['Scene Type', 'Location Type']
✅ Clarifying Question: Could you specify whether you're asking about the setting for an indoor or outdoor scene, and if it's a specific location or a broader area?
------------------------------------------------------

Generating positive clarifying questions:  95%|█████████▍| 939/990 [08:44<00:13,  3.68it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the prisoner with the longest continuous term or total time served, and over what period of time are you interested in this record?[/OUTPUT]
=========================


🟩 Row 938
Q: Who is the longest serving prisoner in australia?
Facets: ["Definition of 'longest serving'", 'Scope of Time']
✅ Clarifying Question: Are you asking about the prisoner with the longest continuous term or total time served, and over what period of time are you interested in this record?
------------------------------------------------------

Generating positive clarifying questions:  95%|█████████▍| 940/990 [08:45<00:17,  2.90it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]On which side of the note is the face located, and in which country and currency is the $100 bill used?[/OUTPUT]
=========================


🟩 Row 939
Q: Who's face is on $100 bill?
Facets: ['Country', 'Currency', 'Note Side']
✅ Clarifying Question: On which side of the note is the face located, and in which country and currency is the $100 bill used?
------------------------------------------------------

Generating positive clarifying questions:  95%|█████████▌| 942/990 [08:46<00:17,  2.82it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year of Emmerdale Farm were Chris Tate's character and his wife featured?[/OUTPUT]
=========================


🟩 Row 941
Q: Who was chris tate's wife in emmerdale farm?
Facets: ['Time Period']
✅ Clarifying Question: In which year of Emmerdale Farm were Chris Tate's character and his wife featured?
------------------------------------------------------

Generating positive clarifying questions:  95%|█████████▌| 944/990 [08:47<00:18,  2.45it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific season of The Closer, and are you interested in the character's role becoming chief of police or a different aspect of the position?[/OUTPUT]
=========================


🟩 Row 943
Q: Who becomes chief of police on the closer?
Facets: ['Season', 'Role Specificity']
✅ Clarifying Question: Are you asking about a specific season of The Closer, and are you interested in the character's role becoming chief of police or a different aspect of the position?
------------------------------------------------------

Generating positive clarifying questions:  95%|█████████▌| 945/990 [08:48<00:21,  2.14it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which year do you want to know who Hope is engaged to on Days of Our Lives?[/OUTPUT]
=========================


🟩 Row 944
Q: Who is hope engaged to on days of our lives?
Facets: ['Year of Marriage']
✅ Clarifying Question: In which year do you want to know who Hope is engaged to on Days of Our Lives?
------------------------------------------------------

Generating positive clarifying questions:  96%|█████████▌| 948/990 [08:49<00:17,  2.47it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the original artist who first performed "Raise a Little Hell," or a cover version by another artist?[/OUTPUT]
=========================


🟩 Row 947
Q: Who sings the song raise a little hell?
Facets: ['Original Artist', 'Cover Artist']
✅ Clarifying Question: Are you asking about the original artist who first performed "Raise a Little Hell," or a cover version by another artist?
------------------------------------------------------

Generating positive clarifying questions:  96%|█████████▌| 949/990 [08:49<00:19,  2.08it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the character Bridget Jones's romantic partner in the movie or the actress who plays her?[/OUTPUT]
=========================


🟩 Row 948
Q: Who does bridget end up with in bridget jones baby?
Facets: ['Type of Entity (Character/Actor)', 'Role Description']
✅ Clarifying Question: Are you asking about the character Bridget Jones's romantic partner in the movie or the actress who plays her?
------------------------------------------------------

Generating positive clarifying questions:  96%|█████████▌| 950/990 [08:50<00:22,  1.75it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the virtual band Gorillaz or the actual people behind the scenes who create the band's music and image?[/OUTPUT]
=========================


🟩 Row 949
Q: Who are the members of the band gorillaz?
Facets: ['Type of Entity']
✅ Clarifying Question: Are you asking about the virtual band Gorillaz or the actual people behind the scenes who create the band's music and image?
------------------------------------------------------

Generating positive clarifying questions:  96%|█████████▌| 952/990 [08:51<00:18,  2.01it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which time period are you asking about the Packers vs Bears game wins?[/OUTPUT]
=========================


🟩 Row 951
Q: Who has won more games packers or bears?
Facets: ['Time Period']
✅ Clarifying Question: In which time period are you asking about the Packers vs Bears game wins?
------------------------------------------------------

Generating positive clarifying questions:  96%|█████████▋| 953/990 [08:52<00:23,  1.59it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether "The" refers to a specific country or organization, which region in Asia you are interested in, and what aspect of recognition you're asking about?[/OUTPUT]
=========================


🟩 Row 952
Q: The un recognises how many regions in asia?
Facets: ['Type of Entity', 'Geographical Region', 'Meaning of Term']
✅ Clarifying Question: Could you specify whether "The" refers to a specific country or organization, which region in Asia you are interested in, and what aspect of recognition you're asking about?
------------------------------------------------------

Generating positive clarifying questions:  96%|█████████▋| 954/990 [08:53<00:24,  1.45it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the original story published in a specific year, or a different adaptation of the Snowman character?[/OUTPUT]
=========================


🟩 Row 953
Q: Who wrote the children's book the snowman?
Facets: ['Year', 'Type of Literary Work']
✅ Clarifying Question: Are you asking about the original story published in a specific year, or a different adaptation of the Snowman character?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about football or cricket, and do you want information on the most recent occurrence or a specific year's event?[/OUTPUT]
=========================

Generating positive clarifying questions:  97%|█████████▋| 956/990 [08:54<00:20,  1.63it/s]

🟩 Row 955
Q: When was the last time england got through to the quarter finals in world cup?
Facets: ['Sport Type', 'Gender']
✅ Clarifying Question: Are you asking about football or cricket, and do you want information on the most recent occurrence or a specific year's event?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify if you're asking about a specific Super Bowl game or a general event, and what year you're interested in?[/OUTPUT]
=========================


🟩 Row 957
Q: When was the last time cowboys went to the superbowl?
Facets: ['Sequence Number']
✅ Clarifying Question: Could you specify if you're asking about a specific Super Bowl game or a general event, and what year you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  97%|█████████▋| 958/990 [08:55<00:18,  1.74it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the general setting or a specific location within the game, and is it set in a particular region or country?[/OUTPUT]
=========================


🟩 Row 958
Q: Where does assassin's creed 3 take place?
Facets: ['Type of Location', 'Specific Location']
✅ Clarifying Question: Are you asking about the general setting or a specific location within the game, and is it set in a particular region or country?
------------------------------------------------------

Generating positive clarifying questions:  97%|█████████▋| 960/990 [08:57<00:23,  1.29it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether you're asking about the number of books in the series or editions of the publication, and if there's a specific edition you're interested in?[/OUTPUT]
=========================


🟩 Row 959
Q: How many books are lord of the rings?
Facets: ['Type of Entity', 'Publication Format']
✅ Clarifying Question: Could you specify whether you're asking about the number of books in the series or editions of the publication, and if there's a specific edition you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  97%|█████████▋| 962/990 [08:58<00:18,  1.48it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]In which season, with which character, and under what specific circumstances does the marriage occur in "Secret Life of the American Teenager"?[/OUTPUT]
=========================


🟩 Row 961
Q: Who gets married in secret life of the american teenager?
Facets: ['Season', 'Character', 'Marriage Details']
✅ Clarifying Question: In which season, with which character, and under what specific circumstances does the marriage occur in "Secret Life of the American Teenager"?
------------------------------------------------------

Generating positive clarifying questions:  97%|█████████▋| 964/990 [08:59<00:16,  1.60it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the historical practice of presidential tickets including vice presidents, and if so, in which specific time period or event are you interested?[/OUTPUT]
=========================


🟩 Row 963
Q: When did presidents start running with vice presidents?
Facets: ['Time Period', 'Specific Event']
✅ Clarifying Question: Are you asking about the historical practice of presidential tickets including vice presidents, and if so, in which specific time period or event are you interested?
------------------------------------------------------

Generating positive clarifying questions:  98%|█████████▊| 972/990 [09:01<00:05,  3.34it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the format of the channel (e.g., digital, HD) or the specific Direct TV channel number where the weather channel is located?[/OUTPUT]
=========================


🟩 Row 971
Q: What channel is the weather channel.on direct tv?
Facets: ['Channel Format', 'Service Type']
✅ Clarifying Question: Are you asking about the format of the channel (e.g., digital, HD) or the specific Direct TV channel number where the weather channel is located?
------------------------------------------------------

Generating positive clarifying questions:  98%|█████████▊| 975/990 [09:02<00:04,  3.15it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify whether this measure is applied at the time of data collection or during storage, and what medium is involved in storing the patient identifiable information?[/OUTPUT]
=========================


🟩 Row 974
Q: A measure using algorithms to publically protect patient identifiable information is?
Facets: ['Time of Application', 'Storage Medium Involved']
✅ Clarifying Question: Could you specify whether this measure is applied at the time of data collection or during storage, and what medium is involved in storing the patient identifiable information?
------------------------------------------------------

Generating positive clarifying questions:  99%|█████████▊| 976/990 [09:03<00:05,  2.57it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a country's performance or an athlete's individual achievements in the 2014 Commonwealth Games?[/OUTPUT]
=========================


🟩 Row 975
Q: Who won the most gold medals in the 2014 commonwealth games?
Facets: ['Type of Entity (Country/Athlete)']
✅ Clarifying Question: Are you asking about a country's performance or an athlete's individual achievements in the 2014 Commonwealth Games?
------------------------------------------------------

Generating positive clarifying questions:  99%|█████████▊| 977/990 [09:04<00:05,  2.19it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the primary or secondary character, and is there a specific year you're interested in?[/OUTPUT]
=========================


🟩 Row 976
Q: Who do you play as in battlefront 2 campaign?
Facets: ['Primary vs. Secondary Character', 'Year']
✅ Clarifying Question: Are you asking about the primary or secondary character, and is there a specific year you're interested in?
------------------------------------------------------

Generating positive clarifying questions:  99%|█████████▉| 978/990 [09:05<00:06,  1.86it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about a specific song title, and if so, do you have any details on the artist or album?[/OUTPUT]
=========================


🟩 Row 977
Q: Who sings love you like there's no tomorrow?
Facets: ['Song Title']
✅ Clarifying Question: Are you asking about a specific song title, and if so, do you have any details on the artist or album?
------------------------------------------------------

Generating positive clarifying questions:  99%|█████████▉| 979/990 [09:06<00:08,  1.35it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Could you specify the format of the date, the geographical region where the war ended, whether you're asking about the formal end or the last military action, the local time zone, and if you're interested in the official declaration or the celebratory end?[/OUTPUT]
=========================


🟩 Row 978
Q: What date did the second world war end?
Facets: ['Date Format', 'Geographical Region', 'Type of End Date', 'Local Time Zone', 'Celebration Context']
✅ Clarifying Question: Could you specify the format of the date, the geographical region where the war ended, whether you're asking about the formal end or the last military action, the local time zone, and if you're interested in the official declaration or the celebratory end?
------------------------------------------------------


=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the historical sources of Rome's drinking water, the current sources, or both; what kind of water source (e.g., aqueducts, wells) are you interested in; and how do you want the information presented (e.g., through ancient records, modern methods)?[/OUTPUT]
=========================

Generating positive clarifying questions:  99%|█████████▉| 980/990 [09:08<00:09,  1.03it/s]

🟩 Row 979
Q: Where does rome's drinking water come from?
Facets: ['Time Period', 'Type of Water Source', 'Transportation Method']
✅ Clarifying Question: Are you asking about the historical sources of Rome's drinking water, the current sources, or both; what kind of water source (e.g., aqueducts, wells) are you interested in; and how do you want the information presented (e.g., through ancient records, modern methods)?
------------------------------------------------------

Generating positive clarifying questions:  99%|█████████▉| 984/990 [09:09<00:03,  1.77it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the type of alpha amylase, and in which specific part of the body it is found?[/OUTPUT]
=========================


🟩 Row 983
Q: Where is alpha amylase found in the body?
Facets: ['Type of Alpha Amylase', 'Location in the Body']
✅ Clarifying Question: Are you asking about the type of alpha amylase, and in which specific part of the body it is found?
------------------------------------------------------

Generating positive clarifying questions: 100%|██████████| 990/990 [09:10<00:00,  1.80it/s]

=== RAW MODEL OUTPUT ===
 [OUTPUT]Are you asking about the total number of NBA Defensive Player of the Year awards won by an individual player, considering both consistency and continuity of the award over time?[/OUTPUT]
=========================


🟩 Row 987
Q: Who has the most nba defensive player of the year awards?
Facets: ['Team Consistency', 'Award Continuity']
✅ Clarifying Question: Are you asking about the total number of NBA Defensive Player of the Year awards won by an individual player, considering both consistency and continuity of the award over time?
------------------------------------------------------


✅ Saved results to positive_clarifying_responses.csv

In [ ]:
df

,Unnamed: 0,question,type,qaPairs,disambig_questions,is_ambiguous,facets,reasoning,single_answers,positive_response
990,990,Kansas city chief player who is a doctor?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,"[Laurent Duvernay-Tardif CQ, Laurent Duvernay-...",N/A
991,991,When did the last civil war widow die?,multipleQAs,[{'question': ['When did the last civil war wi...,['When did the last civil war widow from the U...,True,['Side of Civil War'],The question is ambiguous because it does not ...,[],Could you specify which side of the Civil War ...
992,992,What does sho stand for on ford taurus?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,[Super High Output],N/A
993,993,Who won australia's next top model season 7?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,"[Montana Cox, Cox]",N/A
994,994,What is the climate in the gobi desert?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,"[a rain shadow desert, great extremes, combine...",N/A
...,...,...,...,...,...,...,...,...,...,...
10031,10031,When do the summer holidays start for schools?,multipleQAs,[{'question': ['When do summer holidays start ...,['When do summer holidays start for schools in...,True,"['Geographical Region', 'Specific Location']",The question is ambiguous because it does not ...,[],In which geographical region and specific loca...
10032,10032,Who is the band in the movie 10 things i hate ...,multipleQAs,[{'question': ['What band plays at Club Skunk ...,['What band plays at Club Skunk in the movie 1...,True,"['Location', 'Event Type']",The question is ambiguous because it does not ...,[],Are you asking about the band featured in the ...
10033,10033,Who was the last person in the uk to be executed?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,[Gwynne Evans and Peter Allen],N/A
10034,10034,Who does wonder woman end up with in the comics?,multipleQAs,[{'question': ['Who does wonder woman end up w...,['Who does wonder woman end up with in All Sta...,True,"['Story Universe', 'Publication Series']",The question is ambiguous because 'Wonder Woma...,[],Are you asking about Wonder Woman's relationsh...
10035,10035,When were the first pair of jordans released?,multipleQAs,[{'question': ['When were the first pair of Ai...,['When were the first pair of Air Jordans rele...,True,"['Release Target Audience', 'Release Scope']",The question is ambiguous because it does not ...,[],Could you specify whether you're asking about ...

## concat the first 1k df with the rest 9k df

In [ ]:
import pandas as pd
import numpy as np

first_half=pd.read_csv('positive_clarifying_responses-4.csv')
second_half=pd.read_csv('positive_clarifying_responses-3.csv')

print(first_half.shape)
print(second_half.shape)

(990, 10)
(9046, 10)

In [ ]:
first_half.tail()

,Unnamed: 0,question,type,qaPairs,disambig_questions,is_ambiguous,facets,reasoning,single_answers,positive_response
985,985,How many pages in a brave new world?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,['311'],NaN
986,986,When was the last time newcastle won the fa cup?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,['1954-55'],NaN
987,987,Who has the most nba defensive player of the y...,multipleQAs,[{'question': ['Who has the most nba defensive...,['Who has the most nba defensive player of the...,True,"['Team Consistency', 'Award Continuity']",The question is ambiguous because it does not ...,[],Are you asking about the total number of NBA D...
988,988,What are the components of the renal corpuscle?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,"[""glomerulus, Bowman's capsule""]",NaN
989,989,Who sang bird bird bird bird is the word?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it provi...,['The Trashmen'],NaN

In [ ]:
second_half.tail()

,Unnamed: 0,question,type,qaPairs,disambig_questions,is_ambiguous,facets,reasoning,single_answers,positive_response
9041,10031,When do the summer holidays start for schools?,multipleQAs,[{'question': ['When do summer holidays start ...,['When do summer holidays start for schools in...,True,"['Geographical Region', 'Specific Location']",The question is ambiguous because it does not ...,[],In which geographical region and specific loca...
9042,10032,Who is the band in the movie 10 things i hate ...,multipleQAs,[{'question': ['What band plays at Club Skunk ...,['What band plays at Club Skunk in the movie 1...,True,"['Location', 'Event Type']",The question is ambiguous because it does not ...,[],Are you asking about the band featured in the ...
9043,10033,Who was the last person in the uk to be executed?,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,['Gwynne Evans and Peter Allen'],NaN
9044,10034,Who does wonder woman end up with in the comics?,multipleQAs,[{'question': ['Who does wonder woman end up w...,['Who does wonder woman end up with in All Sta...,True,"['Story Universe', 'Publication Series']",The question is ambiguous because 'Wonder Woma...,[],Are you asking about Wonder Woman's relationsh...
9045,10035,When were the first pair of jordans released?,multipleQAs,[{'question': ['When were the first pair of Ai...,['When were the first pair of Air Jordans rele...,True,"['Release Target Audience', 'Release Scope']",The question is ambiguous because it does not ...,[],Could you specify whether you're asking about ...

In [ ]:
final_df = pd.concat([first_half, second_half], ignore_index=True)

# Step 2: Drop duplicates (keeps the first occurrence)
final_df = final_df.drop_duplicates(ignore_index=True)

# Check final shape
print(final_df.shape)

final_df.head()

(10036, 10)

,Unnamed: 0,question,type,qaPairs,disambig_questions,is_ambiguous,facets,reasoning,single_answers,positive_response
0,0,When did the simpsons first air on television?,multipleQAs,[{'question': ['When did the Simpsons first ai...,['When did the Simpsons first air on televisio...,True,"['Type of Show', 'Platform']",The question is ambiguous because it does not ...,[],Are you asking about the original TV series or...
1,1,Who played george washington in the john adams...,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],The question is not ambiguous because it speci...,['David Morse'],NaN
2,2,What is the legal age of marriage in usa?,multipleQAs,[{'question': ['What is the legal age of marri...,"['What is the legal age of marriage, without p...",True,"['State', 'Circumstances for Marriage']",The question is ambiguous because the legal ag...,[],In which U.S. state and under what circumstanc...
3,3,Who starred in barefoot in the park on broadway?,multipleQAs,[{'question': ['Who starred in barefoot in the...,['Who starred in barefoot in the park on broad...,True,['Character Name'],The question is ambiguous because it does not ...,[],Did you mean the character names or the actors...
4,4,When did the manhattan project began and end?,multipleQAs,[{'question': ['Based on the initial thoughts ...,['Based on the initial thoughts of the project...,True,['Time Frame Interpretation'],The question is ambiguous because it does not ...,[],In which specific year or time period are you ...

In [ ]:
final_df['action']=np.where(final_df['is_ambiguous']==True, 'Clarify', 'Answer')

In [ ]:
final_df.to_csv('final_SFT_training_data.csv')

## SETTING UP DATA FOR TRAINING PHASE

In [ ]:
final_df.columns

Index(['Unnamed: 0', 'question', 'type', 'qaPairs', 'disambig_questions',
       'is_ambiguous', 'facets', 'reasoning', 'single_answers',
       'positive_response', 'action'],
      dtype='object')

In [ ]:
final_df['positive_response']=final_df['positive_response'].fillna(final_df['single_answers'])

In [ ]:
final_sft_df=final_df[['question', 'is_ambiguous', 'facets', 'reasoning', 'positive_response', 'action']]
pd.set_option('display.max_colwidth', None)
final_sft_df.head()

,question,is_ambiguous,facets,reasoning,positive_response,action
0,When did the simpsons first air on television?,True,"['Type of Show', 'Platform']","The question is ambiguous because it does not specify whether 'The Simpsons' refers to the TV series or another type of show, and it does not clarify if the platform (e.g., network, streaming service) is relevant. Without this information, we cannot determine the exact date of its first broadcast.","Are you asking about the original TV series or a movie, and on which platform (e.g., network, streaming service) did it first air?",Clarify
1,Who played george washington in the john adams series?,False,[],"The question is not ambiguous because it specifies the exact role and series, providing enough detail to uniquely identify the actor who portrayed George Washington in the John Adams miniseries.",['David Morse'],Answer
2,What is the legal age of marriage in usa?,True,"['State', 'Circumstances for Marriage']","The question is ambiguous because the legal age of marriage can vary by state in the USA. Additionally, there might be different circumstances or exceptions that affect the age requirement, such as parental consent or a court order. Without specifying the state and the circumstances, the answer can differ significantly.",In which U.S. state and under what circumstances are you asking about the legal age of marriage?,Clarify
3,Who starred in barefoot in the park on broadway?,True,['Character Name'],"The question is ambiguous because it does not specify which character from the play ""Barefoot in the Park"" was starred in. Without knowing the character name, we cannot determine who played that specific role on Broadway.",Did you mean the character names or the actors who played them in the Broadway production of Barefoot in the Park?,Clarify
4,When did the manhattan project began and end?,True,['Time Frame Interpretation'],"The question is ambiguous because it does not specify which aspect of the Manhattan Project is being referred to—whether it's the start date, end date, or a broader time frame such as the duration. The term ""began and ended"" could imply either two separate dates or the entire period of the project.",In which specific year or time period are you interested in knowing about the Manhattan Project's start and end?,Clarify

In [ ]:
final_sft_df.to_csv('final_SFT_data_for_use.csv')

In [ ]:
import pandas as pd
final_sft_df=pd.read_csv('final_SFT_data_for_use.csv')

In [ ]:
#results_primitive.to_csv('pos_amb_disambig_answers.csv')

### Pre-process the data to get it into proper json format

In [ ]:
# import json
# import ast
# import pandas as pd

# df = final_sft_df.copy()

# def clean_facets(facets):
#     if isinstance(facets, list):
#         return facets
#     if isinstance(facets, str):
#         try:
#             val = ast.literal_eval(facets)
#             return val if isinstance(val, list) else []
#         except:
#             return []
#     return []

# def clean_response(resp):
#     if resp is None:
#         return ""

#     # If it's a list, return the first element
#     if isinstance(resp, list):
#         return resp[0] if len(resp) > 0 else ""

#     # If it's a string of a list, extract content
#     if isinstance(resp, str) and resp.startswith("[") and resp.endswith("]"):
#         try:
#             list_val = ast.literal_eval(resp)
#             if isinstance(list_val, list) and len(list_val) > 0:
#                 return list_val[0]
#         except:
#             pass

#     # Otherwise return clean string
#     return resp.strip()


# records = []

# for _, row in df.iterrows():
#     q = row["question"]
#     is_amb = row["is_ambiguous"]
#     reasoning = row["reasoning"]
#     action = row["action"].strip()
#     facets = clean_facets(row["facets"])

#     # Clarify vs Answer
#     response_raw = row["positive_response"]
#     response = clean_response(response_raw)

#     record = {
#         "instruction": (
#             "Decide whether the user's question is ambiguous. "
#             "If ambiguous, explain the ambiguity, list facets, and generate a clarifying question. "
#             "If not ambiguous, explain why and answer directly."
#         ),
#         "input": q,
#         "output": {
#             "action": action,
#             "reasoning": reasoning,
#             "facets": facets if is_amb else [],
#             "response": response
#         }
#     }
#     records.append(record)

# with open("sft_data.jsonl", "w") as f:
#     for r in records:
#         f.write(json.dumps(r) + "\n")

# print("⭐ CLEAN SFT dataset created: sft_data.jsonl")

In [ ]:
# import json

# with open("sft_data.jsonl") as f:
#     for _ in range(5):
#         print(json.loads(next(f)))
#         print("------")

In [ ]:
!pip install torch transformers>=4.37.0 datasets peft trl accelerate bitsandbytes sentencepiece protobuf einops

In [ ]:
# # ============================================================================
# # COMPLETE QWEN SFT TRAINING PIPELINE (FINAL STABLE VERSION)
# # ============================================================================

# import json
# import ast
# import pandas as pd
# import torch
# from datasets import load_dataset
# from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments
# from peft import LoraConfig
# from trl import SFTTrainer

# print("\n" + "="*80)
# print("STEP 1: PREPARING DATASET")
# print("="*80)

# # Use your dataframe
# df = final_sft_df.copy()

# # ----------------------------------------------------------
# # Cleaning helpers
# # ----------------------------------------------------------

# def clean_facets(facets):
#     if isinstance(facets, list):
#         return facets
#     if isinstance(facets, str):
#         try:
#             val = ast.literal_eval(facets)
#             return val if isinstance(val, list) else []
#         except:
#             return []
#     return []

# def clean_response(resp):
#     if resp is None:
#         return ""
#     if isinstance(resp, list):
#         return resp[0] if resp else ""
#     if isinstance(resp, str) and resp.startswith("[") and resp.endswith("]"):
#         try:
#             lst = ast.literal_eval(resp)
#             return lst[0] if lst else ""
#         except:
#             pass
#     return str(resp).strip()

# # ----------------------------------------------------------
# # Build SFT JSONL
# # ----------------------------------------------------------

# records = []

# for _, row in df.iterrows():
#     q = row["question"]
#     is_amb = row["is_ambiguous"]
#     reasoning = row["reasoning"]
#     action = row["action"]
#     facets = clean_facets(row["facets"])
#     response = clean_response(row["positive_response"])

#     records.append({
#         "instruction": (
#             "Decide whether the user's question is ambiguous. "
#             "If ambiguous, explain the ambiguity, list facets, and ask a clarifying question. "
#             "If not ambiguous, explain why and answer directly."
#         ),
#         "input": q,
#         "output": {
#             "action": action,
#             "reasoning": reasoning,
#             "facets": facets if is_amb else [],
#             "response": response
#         }
#     })

# with open("sft_data.jsonl", "w") as f:
#     for r in records:
#         f.write(json.dumps(r) + "\n")

# print(f"✅ Created SFT dataset with {len(records)} rows")


# # ============================================================================
# # STEP 2: LOAD DATASET
# # ============================================================================

# print("\n" + "="*80)
# print("STEP 2: LOADING DATASET")
# print("="*80)

# train_dataset = load_dataset("json", data_files="sft_data.jsonl")["train"]
# print(f"Loaded {len(train_dataset)} examples")


# # ============================================================================
# # STEP 3: LOAD MODEL + TOKENIZER
# # ============================================================================

# print("\n" + "="*80)
# print("STEP 3: LOADING MODEL & TOKENIZER")
# print("="*80)

# model_name = "Qwen/Qwen2.5-7B-Instruct"

# tokenizer = AutoTokenizer.from_pretrained(
#     model_name,
#     trust_remote_code=True
# )

# # Critical fix
# if tokenizer.pad_token is None:
#     tokenizer.pad_token = tokenizer.eos_token
# tokenizer.padding_side = "right"

# model = AutoModelForCausalLM.from_pretrained(
#     model_name,
#     torch_dtype=torch.bfloat16,
#     device_map="auto",
#     trust_remote_code=True
# )

# model.config.use_cache = False
# model.gradient_checkpointing_enable()


# # ============================================================================
# # STEP 4: FORMAT TEXT FOR TRAINING USING CHAT TEMPLATE
# # ============================================================================

# print("\n" + "="*80)
# print("STEP 4: FORMATTING DATASET (CHAT TEMPLATE)")
# print("="*80)

# def format_chat(example):
#     question = example["input"]
#     action = example["output"]["action"]
#     reasoning = example["output"]["reasoning"]
#     facets = example["output"]["facets"]
#     response = example["output"]["response"]

#     facets_str = "[" + ", ".join(facets) + "]" if facets else "[]"

#     system_msg = (
#         "You are a question understanding agent. For each user question:\n"
#         "1) Decide if it is ambiguous.\n"
#         "2) Explain your reasoning.\n"
#         "3) List facets if ambiguous.\n"
#         "4) Ask a clarifying question OR give a direct answer.\n\n"
#         "Format:\n"
#         "Action: Clarify|Answer\n"
#         "Reasoning: ...\n"
#         "Facets: [...]\n"
#         "Response: ...\n"
#     )

#     assistant_msg = (
#         f"Action: {action}\n"
#         f"Reasoning: {reasoning}\n"
#         f"Facets: {facets_str}\n"
#         f"Response: {response}"
#     )

#     messages = [
#         {"role": "system", "content": system_msg},
#         {"role": "user", "content": question},
#         {"role": "assistant", "content": assistant_msg}
#     ]

#     formatted = tokenizer.apply_chat_template(
#         messages, tokenize=False, add_generation_prompt=False
#     )
#     return {"text": formatted}

# formatted_dataset = train_dataset.map(
#     format_chat,
#     remove_columns=train_dataset.column_names
# )

# print("Example formatted text:")
# print("-"*80)
# print(formatted_dataset[0]["text"][:400])
# print("-"*80)


# # ============================================================================
# # STEP 5: LoRA CONFIG
# # ============================================================================

# print("\n" + "="*80)
# print("STEP 5: LORA CONFIG")
# print("="*80)

# lora_config = LoraConfig(
#     r=32,
#     lora_alpha=16,
#     lora_dropout=0.05,
#     bias="none",
#     task_type="CAUSAL_LM",
#     target_modules=[
#         "q_proj","k_proj","v_proj","o_proj",
#         "gate_proj","up_proj","down_proj"
#     ],
# )

# print("LoRA config loaded.")


# # ============================================================================
# # STEP 6: TRAINING ARGUMENTS
# # ============================================================================

# print("\n" + "="*80)
# print("STEP 6: TRAINING ARGS")
# print("="*80)

# training_args = TrainingArguments(
#     output_dir="clarifier_sft_output",
#     per_device_train_batch_size=1,
#     gradient_accumulation_steps=8,
#     num_train_epochs=1,
#     learning_rate=2e-4,
#     warmup_ratio=0.05,
#     bf16=True,
#     logging_steps=10,
#     save_steps=200,
#     save_total_limit=2,
#     optim="paged_adamw_8bit",
#     report_to="none",
# )


# # ============================================================================
# # STEP 7: CREATE TRAINER
# # ============================================================================

# print("\n" + "="*80)
# print("STEP 7: INITIALIZING TRAINER")
# print("="*80)

# trainer = SFTTrainer(
#     model=model,
#     tokenizer=tokenizer,
#     train_dataset=formatted_dataset,
#     dataset_text_field="text",   # IMPORTANT
#     max_seq_length=2048,
#     packing=True,
#     peft_config=lora_config,
#     args=training_args,
# )

# print("Trainer initialized successfully.")


# # ============================================================================
# # STEP 8: TRAIN
# # ============================================================================

# print("\n" + "="*80)
# print("STEP 8: TRAINING")
# print("="*80)

# trainer.train()

# print("Training complete!")


# # ============================================================================
# # STEP 9: SAVE MODEL
# # ============================================================================

# trainer.save_model("clarifier_final_model")
# tokenizer.save_pretrained("clarifier_final_model")

# print("Model saved!")


# # ============================================================================
# # STEP 10: TEST INFERENCE
# # ============================================================================

# print("\n" + "="*80)
# print("STEP 10: TESTING INFERENCE")
# print("="*80)

# from peft import AutoPeftModelForCausalLM

# trained_model = AutoPeftModelForCausalLM.from_pretrained(
#     "clarifier_final_model",
#     torch_dtype=torch.bfloat16,
#     device_map="auto"
# )

# test_question = "What is the best programming language?"

# system_msg = (
#     "You are a question understanding agent. Decide ambiguity, explain reasoning, "
#     "list facets if needed, and respond in required format."
# )

# messages = [
#     {"role": "system", "content": system_msg},
#     {"role": "user", "content": test_question}
# ]

# input_text = tokenizer.apply_chat_template(
#     messages, tokenize=False, add_generation_prompt=True
# )

# inputs = tokenizer(input_text, return_tensors="pt").to(trained_model.device)

# with torch.no_grad():
#     outputs = trained_model.generate(
#         **inputs,
#         max_new_tokens=300,
#         temperature=0.7,
#         top_p=0.9,
#         do_sample=True
#     )

# print("\n--- MODEL RESPONSE ---")
# print(tokenizer.decode(outputs[0], skip_special_tokens=True))
# print("-----------------------")

In [ ]:
# sample_out = run_model_on_question("Who won the US Open?")
# print(sample_out)

In [ ]:
# print(run_model_on_question("Who is the president?"))

In [ ]:
# import pandas as pd

# final_sft_df  # <-- adjust filename
# print(final_sft_df.head())
# print(len(final_sft_df), "rows loaded")

In [ ]:
# import torch
# from transformers import AutoTokenizer
# from peft import AutoPeftModelForCausalLM

# # ============================================================
# # LOAD MODEL
# # ============================================================
# model_path = "clarifier_final_model"

# tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
# model = AutoPeftModelForCausalLM.from_pretrained(
#     model_path,
#     torch_dtype=torch.bfloat16,
#     device_map="auto"
# )

# model.eval()

# # ============================================================
# # INFERENCE FUNCTION
# # ============================================================
# def run_inference(question):

#     system_prompt = (
#         "You are a question understanding agent. For each user question:\n"
#         "1) Decide if it is ambiguous.\n"
#         "2) Explain your reasoning.\n"
#         "3) List facets if ambiguous.\n"
#         "4) Ask a clarifying question OR give a direct answer.\n\n"
#         "Format:\n"
#         "Action: Clarify|Answer\n"
#         "Reasoning: ...\n"
#         "Facets: [...]\n"
#         "Response: ...\n"
#     )

#     messages = [
#         {"role": "system", "content": system_prompt},
#         {"role": "user", "content": question}
#     ]

#     # Build input according to Qwen chat template
#     prompt = tokenizer.apply_chat_template(
#         messages,
#         tokenize=False,
#         add_generation_prompt=True
#     )

#     inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

#     with torch.no_grad():
#         outputs = model.generate(
#             **inputs,
#             max_new_tokens=300,
#             temperature=0.7,
#             top_p=0.9,
#             do_sample=True
#         )

#     decoded = tokenizer.decode(outputs[0], skip_special_tokens=False)

#     # ============================================================
#     # EXTRACT ASSISTANT OUTPUT ONLY
#     # ============================================================
#     if "<|im_start|>assistant" in decoded:
#         assistant = decoded.split("<|im_start|>assistant")[1]
#     else:
#         assistant = decoded

#     assistant = assistant.split("<|im_end|>")[0].strip()

#     return assistant


# # ================== TEST ==================
# print(run_inference("Who won the US Open?"))

In [ ]:
# import pandas as pd
# import torch
# from transformers import AutoTokenizer
# from peft import AutoPeftModelForCausalLM

# # ============================================================
# # LOAD MODEL
# # ============================================================
# model_path = "clarifier_final_model"

# tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
# model = AutoPeftModelForCausalLM.from_pretrained(
#     model_path,
#     torch_dtype=torch.bfloat16,
#     device_map="auto"
# )

# model.eval()

# # ============================================================
# # INFERENCE (MATCHES TRAINING EXACTLY)
# # ============================================================
# def run_inference(question):

#     system_prompt = (
#         "You are a question understanding agent. For each user question:\n"
#         "1) Decide if it is ambiguous.\n"
#         "2) Explain your reasoning.\n"
#         "3) List facets if ambiguous.\n"
#         "4) Ask a clarifying question OR give a direct answer.\n\n"
#         "Format:\n"
#         "Action: Clarify|Answer\n"
#         "Reasoning: ...\n"
#         "Facets: [...]\n"
#         "Response: ...\n"
#     )

#     messages = [
#         {"role": "system", "content": system_prompt},
#         {"role": "user", "content": question}
#     ]

#     prompt = tokenizer.apply_chat_template(
#         messages,
#         tokenize=False,
#         add_generation_prompt=True
#     )

#     inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

#     with torch.no_grad():
#         outputs = model.generate(
#             **inputs,
#             max_new_tokens=200,
#             do_sample=False,        # <---- FIXED (GREEDY)
#         )

#     decoded = tokenizer.decode(outputs[0], skip_special_tokens=False)

#     # Extract only assistant part
#     if "<|im_start|>assistant" in decoded:
#         assistant = decoded.split("<|im_start|>assistant")[1]
#     else:
#         assistant = decoded

#     assistant = assistant.split("<|im_end|>")[0].strip()

#     return assistant


# # ============================================================
# # EVALUATION
# # ============================================================

# def extract_action(text):
#     for line in text.split("\n"):
#         if line.lower().startswith("action:"):
#             if "clarify" in line.lower():
#                 return "Clarify"
#             if "answer" in line.lower():
#                 return "Answer"
#     return None

# # SAMPLE EVAL DATASET
# eval_df = final_sft_df.sample(200, random_state=42)

# correct = 0
# total = len(eval_df)
# errors = []

# print("\n🔍 Running evaluation...\n")

# for _, row in eval_df.iterrows():
#     q = row["question"]
#     true = row["action"]

#     out = run_inference(q)
#     pred = extract_action(out)

#     if pred == true:
#         correct += 1
#     else:
#         errors.append((q, true, pred, out))

# acc = correct / total

# print("===== RESULTS =====")
# print(f"Action accuracy: {acc:.3f}\n")

# print("===== SAMPLE ERRORS =====")
# for q, true, pred, out in errors[:5]:
#     print("------------------------------------------------------------")
#     print(f"Q: {q}")
#     print(f"True: {true}")
#     print(f"Pred: {pred}")
#     print("\nMODEL OUTPUT:\n", out[:500])

# RE-DOING SFT PT 2

In [ ]:
# ============================================================================
# QWEN SFT TRAINING PIPELINE (AMBIGQA STYLE, FIXED)
# ============================================================================

import json
import ast
import pandas as pd
import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments
from peft import LoraConfig
from trl import SFTTrainer

print("\n" + "="*80)
print("STEP 1: PREPARING DATASET")
print("="*80)

# Use your dataframe
df = final_sft_df.copy()

# ----------------------------------------------------------
# Cleaning helpers
# ----------------------------------------------------------

def clean_facets(facets):
    if isinstance(facets, list):
        return facets
    if isinstance(facets, str):
        try:
            val = ast.literal_eval(facets)
            return val if isinstance(val, list) else []
        except:
            return []
    return []

def clean_response(resp):
    if resp is None:
        return ""
    if isinstance(resp, list):
        return resp[0] if resp else ""
    if isinstance(resp, str) and resp.startswith("[") and resp.endswith("]"):
        try:
            lst = ast.literal_eval(resp)
            return lst[0] if lst else ""
        except:
            pass
    return str(resp).strip()

# ----------------------------------------------------------
# Build SFT JSONL (instruction/input/output is just an intermediate form)
# ----------------------------------------------------------

records = []

for _, row in df.iterrows():
    q = row["question"]
    is_amb = row["is_ambiguous"]
    reasoning = row["reasoning"]
    action = row["action"]           # "Clarify" or "Answer"
    facets = clean_facets(row["facets"])
    response = clean_response(row["positive_response"])

    records.append({
        "instruction": (
            "Decide whether the user's question is ambiguous (in the AmbigQA sense: "
            "multiple plausible interpretations or answer targets). "
            "If ambiguous, explain the ambiguity, list facets, and ask a clarifying question. "
            "If not ambiguous, explain why and answer directly."
        ),
        "input": q,
        "output": {
            "action": action,
            "reasoning": reasoning,
            "facets": facets if is_amb else [],
            "response": response
        }
    })

with open("sft_data.jsonl", "w") as f:
    for r in records:
        f.write(json.dumps(r) + "\n")

print(f"✅ Created SFT dataset with {len(records)} rows")


# ============================================================================
# STEP 2: LOAD DATASET
# ============================================================================

print("\n" + "="*80)
print("STEP 2: LOADING DATASET")
print("="*80)

train_dataset = load_dataset("json", data_files="sft_data.jsonl")["train"]
print(f"Loaded {len(train_dataset)} examples")


# ============================================================================
# STEP 3: LOAD MODEL + TOKENIZER
# ============================================================================

print("\n" + "="*80)
print("STEP 3: LOADING MODEL & TOKENIZER")
print("="*80)

model_name = "Qwen/Qwen2.5-7B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    trust_remote_code=True
)

# Critical fix
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True
)

model.config.use_cache = False
model.gradient_checkpointing_enable()

print("✅ Model & tokenizer loaded.")


# ============================================================================
# STEP 4: FORMAT TEXT FOR TRAINING USING CHAT TEMPLATE
# ============================================================================

print("\n" + "="*80)
print("STEP 4: FORMATTING DATASET (CHAT TEMPLATE)")
print("="*80)

def format_chat(example):
    question  = example["input"]
    action    = example["output"]["action"]
    reasoning = example["output"]["reasoning"]
    facets    = example["output"]["facets"]
    response  = example["output"]["response"]

    facets_str = "[" + ", ".join(facets) + "]" if facets else "[]"

    # System message: explicitly references AmbigQA-style ambiguity
    system_msg = (
        "You are a question understanding agent trained on AmbigQA-style ambiguity. "
        "For each user question:\n"
        "1) Decide if it is ambiguous (i.e., multiple plausible interpretations/answers).\n"
        "2) Explain your reasoning.\n"
        "3) List facets if ambiguous.\n"
        "4) Ask a clarifying question OR give a direct answer.\n\n"
        "Format:\n"
        "Action: Clarify|Answer\n"
        "Reasoning: ...\n"
        "Facets: [...]\n"
        "Response: ...\n"
    )

    assistant_msg = (
        f"Action: {action}\n"
        f"Reasoning: {reasoning}\n"
        f"Facets: {facets_str}\n"
        f"Response: {response}"
    )

    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": question},
        {"role": "assistant", "content": assistant_msg}
    ]

    formatted = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": formatted}

formatted_dataset = train_dataset.map(
    format_chat,
    remove_columns=train_dataset.column_names
)

print("Example formatted text:")
print("-"*80)
print(formatted_dataset[0]["text"][:400])
print("-"*80)


# ============================================================================
# STEP 5: LoRA CONFIG
# ============================================================================

print("\n" + "="*80)
print("STEP 5: LORA CONFIG")
print("="*80)

lora_config = LoraConfig(
    r=32,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj","k_proj","v_proj","o_proj",
        "gate_proj","up_proj","down_proj"
    ],
)

print("LoRA config loaded.")


# ============================================================================
# STEP 6: TRAINING ARGUMENTS
# ============================================================================

print("\n" + "="*80)
print("STEP 6: TRAINING ARGS")
print("="*80)

training_args = TrainingArguments(
    output_dir="clarifier_sft_output_ambigqa",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    num_train_epochs=1,        # 🔥 more than 1 epoch now
    learning_rate=2e-4,
    warmup_ratio=0.05,
    bf16=True,
    logging_steps=10,
    save_steps=200,
    save_total_limit=2,
    optim="paged_adamw_8bit",
    report_to="none",
)

print("Training args ready.")


# ============================================================================
# STEP 7: CREATE TRAINER
# ============================================================================

print("\n" + "="*80)
print("STEP 7: INITIALIZING TRAINER")
print("="*80)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=formatted_dataset,
    dataset_text_field="text",
    max_seq_length=2048,
    packing=False,           # 🔥 CRITICAL FIX: NO PACKING
    peft_config=lora_config,
    args=training_args,
)

print("Trainer initialized successfully.")


# ============================================================================
# STEP 8: TRAIN
# ============================================================================

print("\n" + "="*80)
print("STEP 8: TRAINING")
print("="*80)

trainer.train()

print("Training complete!")


# ============================================================================
# STEP 9: SAVE MODEL
# ============================================================================

save_path = "clarifier_final_model_ambigqa"
trainer.save_model(save_path)
tokenizer.save_pretrained(save_path)

print(f"Model saved to: {save_path}")

================================================================================
STEP 1: PREPARING DATASET
================================================================================
✅ Created SFT dataset with 10036 rows

================================================================================
STEP 2: LOADING DATASET
================================================================================

Generating train split: 0 examples [00:00, ? examples/s]

Loaded 10036 examples

================================================================================
STEP 3: LOADING MODEL & TOKENIZER
================================================================================

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

✅ Model & tokenizer loaded.

================================================================================
STEP 4: FORMATTING DATASET (CHAT TEMPLATE)
================================================================================

Map:   0%|          | 0/10036 [00:00<?, ? examples/s]

Example formatted text:
--------------------------------------------------------------------------------
<|im_start|>system
You are a question understanding agent trained on AmbigQA-style ambiguity. For each user question:
1) Decide if it is ambiguous (i.e., multiple plausible interpretations/answers).
2) Explain your reasoning.
3) List facets if ambiguous.
4) Ask a clarifying question OR give a direct answer.

Format:
Action: Clarify|Answer
Reasoning: ...
Facets: [...]
Response: ...
<|im_end|>
<|im_
--------------------------------------------------------------------------------

================================================================================
STEP 5: LORA CONFIG
================================================================================
LoRA config loaded.

================================================================================
STEP 6: TRAINING ARGS
================================================================================
Training args ready.

================================================================================
STEP 7: INITIALIZING TRAINER
================================================================================

Map:   0%|          | 0/10036 [00:00<?, ? examples/s]

/home/bsanghi2/.local/lib/python3.11/site-packages/trl/trainer/sft_trainer.py:323: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Trainer initialized successfully.

================================================================================
STEP 8: TRAINING
================================================================================

In [ ]:
# ============================================================
# MULTI-CHECKPOINT EVALUATOR FOR QWEN CLARIFIER MODEL
# ============================================================

import os
import re
import pandas as pd
import torch
from transformers import AutoTokenizer
from peft import AutoPeftModelForCausalLM

# ============================================================
# CONFIG
# ============================================================

CHECKPOINT_DIR = "clarifier_sft_output_ambigqa"
MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"

# SAMPLE 500 rows for evaluation to keep it fast
EVAL_SIZE = 50

print("🔧 Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# ============================================================
# Load your eval dataframe
# (Assumes final_sft_df exists in session)
# ============================================================

df_eval = final_sft_df.copy()
df_eval = df_eval.sample(min(EVAL_SIZE, len(df_eval))).reset_index(drop=True)

print(f"📊 Using {len(df_eval)} evaluation samples")

# ============================================================
# Parse model output action
# ============================================================

def extract_action(text):
    """
    Extracts `Clarify` or `Answer` from model output.
    Looks for lines like: "Action: Clarify"
    """
    text = text.strip()

    # Search explicitly in formatted lines
    for line in text.split("\n"):
        if line.lower().startswith("action:"):
            action = line.split(":", 1)[1].strip()
            if action in ["Clarify", "Answer"]:
                return action

    return None


# ============================================================
# Run inference on a single question for any model
# ============================================================

SYSTEM_PROMPT = (
    "You are a question understanding agent.\n"
    "1) Decide if a question is ambiguous.\n"
    "2) Explain your reasoning.\n"
    "3) List facets (if ambiguous).\n"
    "4) Output in format:\n\n"
    "Action: Clarify|Answer\n"
    "Reasoning: ...\n"
    "Facets: [...]\n"
    "Response: ...\n"
)

def run_inference(model, question):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": question}
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=200,
            do_sample=False,
            temperature=None,
        )

    decoded = tokenizer.decode(output[0], skip_special_tokens=False)

    # Extract assistant section
    if "<|im_start|>assistant" in decoded:
        return decoded.split("<|im_start|>assistant")[-1].strip()

    return decoded.strip()


# ============================================================
# Evaluate a checkpoint directory
# ============================================================

def evaluate_checkpoint(path):
    print(f"\n🚀 Loading model: {path}")

    try:
        model = AutoPeftModelForCausalLM.from_pretrained(
            path,
            torch_dtype=torch.bfloat16,
            device_map="auto"
        )
    except Exception as e:
        print(f"❌ Failed to load {path}: {e}")
        return None

    correct = 0
    total = len(df_eval)
    errors = []

    for idx, row in df_eval.iterrows():
        q = row["question"]
        true_label = row["action"]

        model_output = run_inference(model, q)
        pred_label = extract_action(model_output)

        if pred_label == true_label:
            correct += 1
        else:
            errors.append((q, true_label, pred_label, model_output))

    accuracy = correct / total
    return accuracy, errors


# ============================================================
# Find all checkpoints
# ============================================================

print("\n🔍 Searching for checkpoints...")
checkpoints = []

for item in os.listdir(CHECKPOINT_DIR):
    if item.startswith("checkpoint-"):
        num = int(item.split("-")[-1])
        checkpoints.append((num, os.path.join(CHECKPOINT_DIR, item)))

checkpoints = sorted(checkpoints)

print(f"📦 Found checkpoints: {[num for num, _ in checkpoints]}")

# ============================================================
# Evaluate each checkpoint
# ============================================================

results = []

for num, path in checkpoints:
    acc, errors = evaluate_checkpoint(path)
    if acc is not None:
        results.append((num, acc, errors))
        print(f"✅ checkpoint-{num} accuracy: {acc:.3f}")

# ============================================================
# Leaderboard
# ============================================================

print("\n🏆 CHECKPOINT LEADERBOARD\n")
for num, acc, _ in sorted(results, key=lambda x: -x[1]):
    print(f"checkpoint-{num}: {acc:.3f}")

# ============================================================
# Show sample errors from the best model
# ============================================================

best_num, best_acc, best_errors = sorted(results, key=lambda x: -x[1])[0]

print("\n===== SAMPLE ERRORS FROM BEST MODEL =====")
print(f"📌 Best checkpoint: {best_num}  (accuracy={best_acc:.3f})")

for i, (q, true, pred, out) in enumerate(best_errors[:5]):
    print("\n------------------------------------------------------------")
    print(f"Q: {q}")
    print(f"True: {true}")
    print(f"Pred: {pred}")
    print("\nMODEL OUTPUT:\n", out[:500])

🔧 Loading tokenizer...

`torch_dtype` is deprecated! Use `dtype` instead!

📊 Using 50 evaluation samples

🔍 Searching for checkpoints...
📦 Found checkpoints: [2400, 2510]

🚀 Loading model: clarifier_sft_output_ambigqa/checkpoint-2400

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

✅ checkpoint-2400 accuracy: 0.560

🚀 Loading model: clarifier_sft_output_ambigqa/checkpoint-2510

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

✅ checkpoint-2510 accuracy: 0.520

🏆 CHECKPOINT LEADERBOARD

checkpoint-2400: 0.560
checkpoint-2510: 0.520

===== SAMPLE ERRORS FROM BEST MODEL =====
📌 Best checkpoint: 2400  (accuracy=0.560)

------------------------------------------------------------
Q: Who is girl in we don't talk anymore?
True: Clarify
Pred: Answer

MODEL OUTPUT:
 Action: Answer
Reasoning: The question is not ambiguous because it specifies the song "We Don't Talk Anymore" and asks about a particular character within that context. This information alone is sufficient to uniquely identify the subject being referred to, as the song has a known lyric with a specific girl mentioned.
Facets: []
Response: Taylor Swift<|im_end|>

------------------------------------------------------------
Q: When did one direction go on a hiatus?
True: Answer
Pred: Clarify

MODEL OUTPUT:
 Action: Clarify
Reasoning: The question is ambiguous because it does not specify which phase of One Direction's hiatus is being referred to. Without this information, it's unclear if the question is asking about their initial hiatus or any subsequent periods where they were inactive.
Facets: [Phase of Hiatus]
Response: Are you asking about when One Direction went on their first hiatus or a later one, and which specific period within that hiatus are you interested in?<|im_end|>

------------------------------------------------------------
Q: When did the tv show dallas first air?
True: Clarify
Pred: Answer

MODEL OUTPUT:
 Action: Answer
Reasoning: The question is not ambiguous because it specifies the exact TV show, "Dallas," and asks about its original broadcast date. This information uniquely identifies one event with no missing details.
Facets: []
Response: September 6, 1978<|im_end|>

------------------------------------------------------------
Q: Where are the guys from impractical jokers from?
True: Clarify
Pred: Answer

MODEL OUTPUT:
 Action: Answer
Reasoning: The question is not ambiguous because it specifies the group "impractical jokers" and asks about their origin, which uniquely identifies the location of the show's cast members. There is no missing information that would make this question unclear.
Facets: []
Response: New York City<|im_end|>

------------------------------------------------------------
Q: Who won most man of the match in ipl?
True: Answer
Pred: Clarify

MODEL OUTPUT:
 Action: Clarify
Reasoning: The question is ambiguous because it does not specify which season of the IPL is being referred to. Without knowing the particular season, it's impossible to determine who won the most Man of the Match awards.
Facets: [Season]
Response: Which season of the IPL are you referring to?<|im_end|>

# training one more epoch

In [ ]:
import json
import ast
import pandas as pd
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer

# ----------------------------------------
# LOAD YOUR ORIGINAL DATAFRAME
# ----------------------------------------
df = final_sft_df.copy()

def clean_facets(f):
    if isinstance(f, list):
        return f
    if isinstance(f, str):
        try:
            v = ast.literal_eval(f)
            return v if isinstance(v, list) else []
        except:
            return []
    return []

def clean_response(r):
    if r is None:
        return ""
    if isinstance(r, list):
        return r[0] if r else ""
    if isinstance(r, str) and r.startswith("[") and r.endswith("]"):
        try:
            lst = ast.literal_eval(r)
            return lst[0] if lst else ""
        except:
            pass
    return str(r).strip()

# ----------------------------------------
# LOAD TOKENIZER (needed for formatting)
# ----------------------------------------
model_name = "Qwen/Qwen2.5-7B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# ----------------------------------------
# BUILD FORMATTED DATASET
# ----------------------------------------
def format_chat_row(row):
    q = row["question"]
    action = row["action"]
    reasoning = row["reasoning"]
    facets = clean_facets(row["facets"])
    response = clean_response(row["positive_response"])

    facets_str = "[" + ", ".join(facets) + "]" if facets else "[]"

    system_msg = (
        "You are a question understanding agent. "
        "For each user question:\n"
        "1) Decide if it is ambiguous.\n"
        "2) Explain your reasoning.\n"
        "3) List facets if ambiguous.\n"
        "4) Ask a clarifying question OR give a direct answer.\n\n"
        "Format:\n"
        "Action: Clarify|Answer\n"
        "Reasoning: ...\n"
        "Facets: [...]\n"
        "Response: ...\n"
    )

    assistant_msg = (
        f"Action: {action}\n"
        f"Reasoning: {reasoning}\n"
        f"Facets: {facets_str}\n"
        f"Response: {response}"
    )

    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": q},
        {"role": "assistant", "content": assistant_msg}
    ]

    formatted = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return formatted

df["text"] = df.apply(format_chat_row, axis=1)

# Convert to HF Dataset
formatted_dataset = Dataset.from_pandas(df[["text"]])

print("Formatted dataset size:", len(formatted_dataset))
print("Example:\n", formatted_dataset[0]["text"][:500])

# Save if you want
formatted_dataset.save_to_disk("formatted_sft_dataset")

Formatted dataset size: 10036
Example:
 <|im_start|>system
You are a question understanding agent. For each user question:
1) Decide if it is ambiguous.
2) Explain your reasoning.
3) List facets if ambiguous.
4) Ask a clarifying question OR give a direct answer.

Format:
Action: Clarify|Answer
Reasoning: ...
Facets: [...]
Response: ...
<|im_end|>
<|im_start|>user
When did the simpsons first air on television?<|im_end|>
<|im_start|>assistant
Action: Clarify
Reasoning: The question is ambiguous because it does not specify whether 'The S

Saving the dataset (0/1 shards):   0%|          | 0/10036 [00:00<?, ? examples/s]

In [ ]:
# ============================================================
# RESUME QWEN SFT TRAINING — EPOCH 2 USING CHECKPOINT 2400
# (BUG-FREE, MATCHES YOUR ORIGINAL WORKING PIPELINE)
# ============================================================

import json
import ast
import torch
import pandas as pd
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, TrainingArguments
from peft import AutoPeftModelForCausalLM
from trl import SFTTrainer

print("\n==================== STEP 0: LOAD ORIGINAL DATA ====================")

df = final_sft_df.copy()

# ---- Helpers used in your original epoch 1 script ----
def clean_facets(f):
    if isinstance(f, list):
        return f
    if isinstance(f, str):
        try:
            v = ast.literal_eval(f)
            return v if isinstance(v, list) else []
        except:
            return []
    return []

def clean_response(r):
    if r is None:
        return ""
    if isinstance(r, list):
        return r[0] if r else ""
    if isinstance(r, str) and r.startswith("[") and r.endswith("]"):
        try:
            lst = ast.literal_eval(r)
            return lst[0] if lst else ""
        except:
            pass
    return str(r).strip()

print("Loaded dataframe with", len(df), "rows.")


# ============================================================
# STEP 1: LOAD TOKENIZER
# ============================================================

print("\n==================== STEP 1: LOAD TOKENIZER ====================")

model_name = "Qwen/Qwen2.5-7B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

print("Tokenizer ready.")


# ============================================================
# STEP 2: REBUILD FORMATTED DATASET (IDENTICAL TO EPOCH 1)
# ============================================================

print("\n==================== STEP 2: REBUILD FORMATTED DATASET ====================")

def format_chat_row(row):
    q = row["question"]
    action = row["action"]
    reasoning = row["reasoning"]
    facets = clean_facets(row["facets"])
    response = clean_response(row["positive_response"])

    facets_str = "[" + ", ".join(facets) + "]" if facets else "[]"

    system_msg = (
        "You are a question understanding agent trained on AmbigQA-style ambiguity. "
        "For each user question:\n"
        "1) Decide if it is ambiguous.\n"
        "2) Explain your reasoning.\n"
        "3) List facets if ambiguous.\n"
        "4) Ask a clarifying question OR give a direct answer.\n\n"
        "Format:\n"
        "Action: Clarify|Answer\n"
        "Reasoning: ...\n"
        "Facets: [...]\n"
        "Response: ...\n"
    )

    assistant_msg = (
        f"Action: {action}\n"
        f"Reasoning: {reasoning}\n"
        f"Facets: {facets_str}\n"
        f"Response: {response}"
    )

    msgs = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": q},
        {"role": "assistant", "content": assistant_msg}
    ]

    return tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=False
    )

df["text"] = df.apply(format_chat_row, axis=1)

formatted_dataset = Dataset.from_pandas(df[["text"]])

print("Formatted dataset created with size:", len(formatted_dataset))
print("Example:\n", formatted_dataset[0]["text"][:300])


# ============================================================
# STEP 3: LOAD CHECKPOINT-2400 (THE RIGHT WAY)
# ============================================================

print("\n==================== STEP 3: LOAD CHECKPOINT 2400 ====================")

checkpoint_path = "clarifier_sft_output_ambigqa/checkpoint-2400"

model = AutoPeftModelForCausalLM.from_pretrained(
    checkpoint_path,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

model.config.use_cache = False

print("Loaded PEFT LoRA model from checkpoint-2400.")


# Make sure LoRA parameters require grad
trainable_params = 0
total_params = 0
for name, param in model.named_parameters():
    total_params += param.numel()
    if "lora_" in name:
        param.requires_grad = True
        trainable_params += param.numel()
    else:
        # keep base model frozen (8-bit) to avoid exploding VRAM
        param.requires_grad = False

print(f"Trainable LoRA params: {trainable_params} / {total_params} "
      f"({trainable_params/total_params:.4%})")


# ============================================================
# STEP 4: TRAINING ARGS FOR SECOND EPOCH
# ============================================================

print("\n==================== STEP 4: SET TRAINING ARGS ====================")

training_args = TrainingArguments(
    output_dir="clarifier_sft_output_ambigqa_epoch2",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    num_train_epochs=1,        # <-- SECOND EPOCH
    learning_rate=2e-4,
    warmup_ratio=0.05,
    bf16=True,
    logging_steps=10,
    save_steps=200,
    save_total_limit=2,
    optim="paged_adamw_8bit",
    report_to="none",
)

print("Training args ready.")


# ============================================================
# STEP 5: CREATE TRAINER (IMPORTANT: NO peft_config)
# ============================================================

print("\n==================== STEP 5: INITIALIZE TRAINER ====================")

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=formatted_dataset,
    dataset_text_field="text",
    max_seq_length=2048,
    packing=False,   # same as epoch 1
    args=training_args,
)

print("Trainer ready.")


# ============================================================
# STEP 6: TRAIN FOR SECOND EPOCH
# ============================================================

print("\n==================== STEP 6: TRAINING EPOCH 2 ====================")

trainer.train(resume_from_checkpoint=False)

print("🎉 Finished epoch 2!")


# ============================================================
# STEP 7: SAVE FINAL MODEL
# ============================================================

save_path = "clarifier_final_model_ambigqa_epoch2"
trainer.save_model(save_path)
tokenizer.save_pretrained(save_path)

print("Saved final model to:", save_path)

==================== STEP 0: LOAD ORIGINAL DATA ====================
Loaded dataframe with 10036 rows.

==================== STEP 1: LOAD TOKENIZER ====================
Tokenizer ready.

==================== STEP 2: REBUILD FORMATTED DATASET ====================
Formatted dataset created with size: 10036
Example:
 <|im_start|>system
You are a question understanding agent trained on AmbigQA-style ambiguity. For each user question:
1) Decide if it is ambiguous.
2) Explain your reasoning.
3) List facets if ambiguous.
4) Ask a clarifying question OR give a direct answer.

Format:
Action: Clarify|Answer
Reasoning:

==================== STEP 3: LOAD CHECKPOINT 2400 ====================

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Loaded PEFT LoRA model from checkpoint-2400.
Trainable LoRA params: 80740352 / 7696356864 (1.0491%)

==================== STEP 4: SET TRAINING ARGS ====================
Training args ready.

==================== STEP 5: INITIALIZE TRAINER ====================

Map:   0%|          | 0/10036 [00:00<?, ? examples/s]

/home/bsanghi2/.local/lib/python3.11/site-packages/trl/trainer/sft_trainer.py:323: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Trainer ready.

==================== STEP 6: TRAINING EPOCH 2 ====================

🎉 Finished epoch 2!
Saved final model to: clarifier_final_model_ambigqa_epoch2

In [ ]:
# ============================================================
# FINAL EVALUATION SCRIPT FOR AMBIGQA CLARIFIER MODEL
# ============================================================

import re
import pandas as pd
import torch
from transformers import AutoTokenizer
from peft import AutoPeftModelForCausalLM
from difflib import SequenceMatcher

# ============================================================
# CONFIG
# ============================================================

MODEL_PATH = "clarifier_final_model_ambigqa_epoch2"   # <<< your saved model
MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"
EVAL_SIZE = 500      # evaluate on 500 rows
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("🔧 Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

print("🔧 Loading model...")
model = AutoPeftModelForCausalLM.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

# ============================================================
# LOAD DATA
# (final_sft_df must exist in memory)
# ============================================================

df_eval = final_sft_df.copy()
df_eval = df_eval.sample(min(EVAL_SIZE, len(df_eval))).reset_index(drop=True)

print(f"📊 Evaluating on {len(df_eval)} samples\n")


# ============================================================
# HELPER: CLEAN MODEL OUTPUT TO EXTRACT ASSISTANT PART ONLY
# ============================================================

def extract_assistant(text):
    """Extract assistant message content cleanly."""
    if "<|im_start|>assistant" in text:
        text = text.split("<|im_start|>assistant")[-1]

    # Remove final <|im_end|> tokens
    text = text.replace("<|im_end|>", "").strip()

    # Remove accidental system/user echoes
        # Remove accidental system/user echoes
    cleaned_lines = []
    for line in text.split("\n"):
        if line.strip().lower().startswith("system"):
            continue
        if line.strip().lower().startswith("user"):
            continue
        cleaned_lines.append(line)

    text = "\n".join(cleaned_lines).strip()
    return text


# ============================================================
# EXTRACT PREDICTED ACTION
# ============================================================

def extract_action(text):
    """Find 'Action: Clarify' or 'Action: Answer'."""
    for line in text.split("\n"):
        if line.lower().startswith("action:"):
            val = line.split(":", 1)[1].strip()
            if val in ["Clarify", "Answer"]:
                return val
    return None


# ============================================================
# EXTRACT PREDICTED ANSWER (if Action = Answer)
# ============================================================

def extract_response(text):
    """Get the content of 'Response:'"""
    for line in text.split("\n"):
        if line.lower().startswith("response:"):
            return line.split(":", 1)[1].strip()
    return ""


# ============================================================
# SEMANTIC STRING MATCHING FOR ANSWER CHECKING
# ============================================================

def semantic_match(a, b):
    """
    More lenient answer comparison:
    - lowercase
    - remove punctuation
    - fuzzy token match
    """
    if not a or not b:
        return False

    import string
    table = str.maketrans("", "", string.punctuation)

    a_clean = a.lower().translate(table).strip()
    b_clean = b.lower().translate(table).strip()

    if a_clean == b_clean:
        return True

    # fuzzy match ratio
    ratio = SequenceMatcher(None, a_clean, b_clean).ratio()
    return ratio > 0.75


# ============================================================
# RUN INFERENCE
# ============================================================

SYSTEM_PROMPT = (
    "You are a question understanding agent.\n"
    "1) Decide if a question is ambiguous.\n"
    "2) Explain your reasoning.\n"
    "3) List facets.\n"
    "4) Output ONLY in the format:\n\n"
    "Action: Clarify|Answer\n"
    "Reasoning: ...\n"
    "Facets: [...]\n"
    "Response: ...\n"
)

def run_inference(question):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": question}
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=200,
            do_sample=False
        )

    decoded = tokenizer.decode(output[0], skip_special_tokens=False)
    return extract_assistant(decoded)


# ============================================================
# EVALUATION LOOP
# ============================================================

correct_action = 0
correct_answer = 0
answer_cases = 0

errors = []

for _, row in df_eval.iterrows():
    q = row["question"]
    gold_action = row["action"]
    gold_answer = row["positive_response"]

    model_out = run_inference(q)
    pred_action = extract_action(model_out)
    pred_answer = extract_response(model_out)

    # Action accuracy
    if pred_action == gold_action:
        correct_action += 1
    else:
        errors.append((q, gold_action, pred_action, model_out))

    # Answer accuracy (semantic)
    if gold_action == "Answer":
        answer_cases += 1
        if semantic_match(pred_answer, gold_answer):
            correct_answer += 1


# ============================================================
# PRINT RESULTS
# ============================================================

print("\n===== RESULTS =====")
print(f"Action accuracy: {correct_action / len(df_eval):.3f}")

if answer_cases > 0:
    print(f"Answer accuracy (semantic): {correct_answer / answer_cases:.3f}")
else:
    print("No Answer examples in evaluation subset.")

print("\n===== SAMPLE ERRORS =====")
for q, gold, pred, out in errors[:5]:
    print("\n------------------------------------------------------------")
    print(f"Q: {q}")
    print(f"Gold Action: {gold}")
    print(f"Pred Action: {pred}")
    print(f"MODEL OUTPUT:\n{out[:500]}")

🔧 Loading tokenizer...
🔧 Loading model...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

📊 Evaluating on 500 samples


===== RESULTS =====
Action accuracy: 0.600
Answer accuracy (semantic): 0.238

===== SAMPLE ERRORS =====

------------------------------------------------------------
Q: When can the new ball be taken in test cricket?
Gold Action: Clarify
Pred Action: Answer
MODEL OUTPUT:
Action: Answer
Reasoning: The question is not ambiguous because it specifies the sport (test cricket) and asks about a particular rule (when the new ball can be taken). This information alone is sufficient to determine the answer based on the rules of test cricket.
Facets: [Sport Type, Event Category]
Response: In test cricket, the new ball can be taken at the start of each innings or if the ball becomes worn out during play.

------------------------------------------------------------
Q: Metal gear solid v ground zeroes how many missions?
Gold Action: Clarify
Pred Action: Answer
MODEL OUTPUT:
Action: Answer
Reasoning: The question is not ambiguous because it specifies the game "Metal Gear Solid V: Ground Zeroes" and asks about the number of missions within this particular game. This information provides enough detail to uniquely determine the answer.
Facets: [Game Title, Game Series]
Response: 20

------------------------------------------------------------
Q: Who played boss hogg on the dukes of hazzard?
Gold Action: Clarify
Pred Action: Answer
MODEL OUTPUT:
Action: Answer
Reasoning: The question is not ambiguous because it specifies the character and the TV show. This combination uniquely identifies the role and actor without any missing information.
Facets: [Character Name, TV Show Title]
Response: Lowman Sheridan

------------------------------------------------------------
Q: What people group established an empire in the valley of mexico?
Gold Action: Clarify
Pred Action: Answer
MODEL OUTPUT:
Action: Answer
Reasoning: The question is not ambiguous because it clearly asks about a specific historical event—the establishment of an empire in the Valley of Mexico—and does not require additional information such as a time period or more context to determine the answer. The details provided are sufficient to uniquely identify the subject.
Facets: [Empire Location, Historical Event]
Response: Aztecs established an empire in the valley of Mexico.

------------------------------------------------------------
Q: When did bob dylan wrote knockin on heavens door?
Gold Action: Clarify
Pred Action: Answer
MODEL OUTPUT:
Action: Answer
Reasoning: The question is not ambiguous because it specifies the song title "knockin' on heaven's door" and the artist Bob Dylan. This combination provides enough detail to uniquely determine the answer, which is known to be written in 1965.
Facets: []

# DPO PIPELINE

### merge the negative and postive dataset

In [ ]:
import pandas as pd
final_sft_df=pd.read_csv('final_SFT_data_for_use.csv')
final_sft_df.head()

,Unnamed: 0,question,is_ambiguous,facets,reasoning,positive_response,action
0,0,When did the simpsons first air on television?,True,"['Type of Show', 'Platform']",The question is ambiguous because it does not ...,Are you asking about the original TV series or...,Clarify
1,1,Who played george washington in the john adams...,False,[],The question is not ambiguous because it speci...,['David Morse'],Answer
2,2,What is the legal age of marriage in usa?,True,"['State', 'Circumstances for Marriage']",The question is ambiguous because the legal ag...,In which U.S. state and under what circumstanc...,Clarify
3,3,Who starred in barefoot in the park on broadway?,True,['Character Name'],The question is ambiguous because it does not ...,Did you mean the character names or the actors...,Clarify
4,4,When did the manhattan project began and end?,True,['Time Frame Interpretation'],The question is ambiguous because it does not ...,In which specific year or time period are you ...,Clarify

In [ ]:
neg_data=pd.read_csv('neg_synthetic_full.csv')
neg_data.head()

,Unnamed: 0,question,type,qaPairs,disambig_questions,is_ambiguous,facets,neg_response
0,0,When did the simpsons first air on television?,multipleQAs,[{'question': ['When did the Simpsons first ai...,['When did the Simpsons first air on televisio...,True,"['Type of Show', 'Platform']","The Simpsons first aired on December 17, 1989."
1,1,Who played george washington in the john adams...,singleAnswer,"[{'question': [], 'answer': []}]",[],False,[],Could you tell me which season of the John Ada...
2,2,What is the legal age of marriage in usa?,multipleQAs,[{'question': ['What is the legal age of marri...,"['What is the legal age of marriage, without p...",True,"['State', 'Circumstances for Marriage']",The legal age of marriage in the USA is 18.
3,3,Who starred in barefoot in the park on broadway?,multipleQAs,[{'question': ['Who starred in barefoot in the...,['Who starred in barefoot in the park on broad...,True,['Character Name'],Walter Matthau and Anne Bancroft starred in Ba...
4,4,When did the manhattan project began and end?,multipleQAs,[{'question': ['Based on the initial thoughts ...,['Based on the initial thoughts of the project...,True,['Time Frame Interpretation'],The Manhattan Project began in 1942 and ended ...

In [ ]:
final_dpo_df=pd.merge(final_sft_df,neg_data[['question', 'neg_response']], how='left', on='question')
final_dpo_df.to_csv('final_dpo_df.csv')

# Starting on DPO- Bhoomika

In [ ]:
!pip install torch

Collecting torch
  Using cached torch-2.9.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.11/site-packages (from torch) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.11/site-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/conda/lib/python3.11/site-packages (from torch) (3.6)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec>=0.8.5 in /opt/conda/lib/python3.11/site-packages (from torch) (2025.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.90)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch)
  Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.4.1)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch)
  Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /opt/conda/lib/python3.11/site-packages (from torch) (10.3.9.90)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch)
  Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch)
  Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /opt/conda/lib/python3.11/site-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /opt/conda/lib/python3.11/site-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /opt/conda/lib/python3.11/site-packages (from torch) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /opt/conda/lib/python3.11/site-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /opt/conda/lib/python3.11/site-packages (from torch) (3.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch) (2.1.3)
Using cached torch-2.9.1-cp311-cp311-manylinux_2_28_x86_64.whl (899.8 MB)
Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
Installing collected packages: nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch
Successfully installed nvidia-cudnn-cu12-9.10.2.21 nvidia-cufft-cu12-11.3.3.83 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 torch-2.9.1

In [ ]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install transformers>=4.40.0 datasets accelerate trl>=0.9.0 peft>=0.11.0 bitsandbytes pandas scikit-learn

Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch in /opt/conda/lib/python3.11/site-packages (2.9.1)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu118/torchvision-0.22.1%2Bcu118-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cu118/torchaudio-2.7.1%2Bcu118-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.11/site-packages (from torch) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.11/site-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/conda/lib/python3.11/site-packages (from torch) (3.6)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec>=0.8.5 in /opt/conda/lib/python3.11/site-packages (from torch) (2025.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /opt/conda/lib/python3.11/site-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /opt/conda/lib/python3.11/site-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /opt/conda/lib/python3.11/site-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /opt/conda/lib/python3.11/site-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /opt/conda/lib/python3.11/site-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /opt/conda/lib/python3.11/site-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /opt/conda/lib/python3.11/site-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /opt/conda/lib/python3.11/site-packages (from torch) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /opt/conda/lib/python3.11/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /opt/conda/lib/python3.11/site-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /opt/conda/lib/python3.11/site-packages (from torch) (3.5.1)
Collecting numpy (from torchvision)
  Downloading https://download.pytorch.org/whl/numpy-2.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 2.0 MB/s eta 0:00:00
Collecting torch
  Downloading https://download.pytorch.org/whl/cu118/torch-2.7.1%2Bcu118-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (28 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Downloading https://download.pytorch.org/whl/pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Collecting nvidia-cuda-nvrtc-cu11==11.8.89 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cuda_nvrtc_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (23.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 71.6 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-runtime-cu11==11.8.89 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 875.6/875.6 kB 24.4 MB/s eta 0:00:0000:01
Collecting nvidia-cuda-cupti-cu11==11.8.87 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cuda_cupti_cu11-11.8.87-py3-none-manylinux1_x86_64.whl (13.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 88.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cudnn-cu11==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cudnn_cu11-9.1.0.70-py3-none-manylinux2014_x86_64.whl (663.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 663.9/663.9 MB 5.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cublas-cu11==11.11.3.6 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cublas_cu11-11.11.3.6-py3-none-manylinux1_x86_64.whl (417.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.9/417.9 MB 8.2 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cufft-cu11==10.9.0.58 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 20.0 MB/s eta 0:00:0000:0100:01
Collecting nvidia-curand-cu11==10.3.0.86 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_curand_cu11-10.3.0.86-py3-none-manylinux1_x86_64.whl (58.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 MB 43.9 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusolver-cu11==11.4.1.48 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cusolver_cu11-11.4.1.48-py3-none-manylinux1_x86_64.whl (128.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 MB 23.3 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparse-cu11==11.7.5.86 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_cusparse_cu11-11.7.5.86-py3-none-manylinux1_x86_64.whl (204.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.1/204.1 MB 15.6 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nccl-cu11==2.21.5 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_nccl_cu11-2.21.5-py3-none-manylinux2014_x86_64.whl (147.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 MB 19.5 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nvtx-cu11==11.8.86 (from torch)
  Downloading https://download.pytorch.org/whl/cu118/nvidia_nvtx_cu11-11.8.86-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 3.1 MB/s eta 0:00:00
Collecting triton==3.3.1 (from torch)
  Downloading https://download.pytorch.org/whl/triton-3.3.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: setuptools>=40.8.0 in /opt/conda/lib/python3.11/site-packages (from triton==3.3.1->torch) (68.2.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch) (2.1.3)
Downloading https://download.pytorch.org/whl/cu118/torchvision-0.22.1%2Bcu118-cp311-cp311-manylinux_2_28_x86_64.whl (6.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 68.9 MB/s eta 0:00:00:00:0100:01
Downloading https://download.pytorch.org/whl/cu118/torch-2.7.1%2Bcu118-cp311-cp311-manylinux_2_28_x86_64.whl (905.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 905.3/905.3 MB 4.0 MB/s eta 0:00:00:00:010:03m
Downloading https://download.pytorch.org/whl/triton-3.3.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (155.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.7/155.7 MB 20.5 MB/s eta 0:00:0000:0100:01
Downloading https://download.pytorch.org/whl/cu118/torchaudio-2.7.1%2Bcu118-cp311-cp311-manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 57.0 MB/s eta 0:00:00:00:01
Downloading https://download.pytorch.org/whl/pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 79.6 MB/s eta 0:00:00:00:0100:01
Downloading https://download.pytorch.org/whl/numpy-2.3.3-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 83.7 MB/s eta 0:00:00:00:0100:01
Installing collected packages: triton, pillow, nvidia-nvtx-cu11, nvidia-nccl-cu11, nvidia-cusparse-cu11, nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, numpy, nvidia-cusolver-cu11, nvidia-cudnn-cu11, torch, torchvision, torchaudio
  Attempting uninstall: triton
    Found existing installation: triton 3.5.1
    Uninstalling triton-3.5.1:
      Successfully uninstalled triton-3.5.1
  Attempting uninstall: torch
    Found existing installation: torch 2.9.1
    Uninstalling torch-2.9.1:
      Successfully uninstalled torch-2.9.1
Successfully installed numpy-2.3.3 nvidia-cublas-cu11-11.11.3.6 nvidia-cuda-cupti-cu11-11.8.87 nvidia-cuda-nvrtc-cu11-11.8.89 nvidia-cuda-runtime-cu11-11.8.89 nvidia-cudnn-cu11-9.1.0.70 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.3.0.86 nvidia-cusolver-cu11-11.4.1.48 nvidia-cusparse-cu11-11.7.5.86 nvidia-nccl-cu11-2.21.5 nvidia-nvtx-cu11-11.8.86 pillow-11.3.0 torch-2.7.1+cu118 torchaudio-2.7.1+cu118 torchvision-0.22.1+cu118 triton-3.3.1

In [ ]:
!nvidia-smi

Tue Nov 25 20:19:05 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.172.08             Driver Version: 570.172.08     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  |   00000000:00:05.0 Off |                    0 |
| N/A   26C    P0             82W /  500W |   21924MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
!pip install transformers>=4.40.0 datasets accelerate trl>=0.9.0 peft>=0.11.0 bitsandbytes pandas scikit-learn

Looking in indexes: https://download.pytorch.org/whl/cu124
Collecting torch
  Downloading https://download.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp311-cp311-linux_x86_64.whl.metadata (28 kB)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp311-cp311-linux_x86_64.whl.metadata (6.1 kB)
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cu124/torchaudio-2.6.0%2Bcu124-cp311-cp311-linux_x86_64.whl.metadata (6.6 kB)
Collecting filelock (from torch)
  Downloading https://download.pytorch.org/whl/filelock-3.19.1-py3-none-any.whl.metadata (2.1 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading https://download.pytorch.org/whl/typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting networkx (from torch)
  Downloading https://download.pytorch.org/whl/networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.11/site-packages (from torch) (3.1.2)
Collecting fsspec (from torch)
  Downloading https://download.pytorch.org/whl/fsspec-2025.9.0-py3-none-any.whl.metadata (10 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 69.3 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 25.2 MB/s eta 0:00:0000:01
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 83.3 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 6.1 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 10.3 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 17.2 MB/s eta 0:00:0000:0100:01
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 46.5 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 26.4 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 18.0 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cusparselt-cu12==0.6.2 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://download.pytorch.org/whl/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 18.8 MB/s eta 0:00:0000:0100:01
Collecting nvidia-nvtx-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 3.1 MB/s eta 0:00:00
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 74.9 MB/s eta 0:00:0000:0100:01
Collecting triton==3.2.0 (from torch)
  Downloading https://download.pytorch.org/whl/triton-3.2.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.4 kB)
Collecting sympy==1.13.1 (from torch)
  Downloading https://download.pytorch.org/whl/sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 24.8 MB/s eta 0:00:0000:0100:01
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch)
  Downloading https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 15.1 MB/s eta 0:00:0000:01
Requirement already satisfied: numpy in /opt/conda/lib/python3.11/site-packages (from torchvision) (2.3.5)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Using cached https://download.pytorch.org/whl/pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2->torch) (2.1.3)
Downloading https://download.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp311-cp311-linux_x86_64.whl (768.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 768.5/768.5 MB 5.3 MB/s eta 0:00:00:00:0100:01
Downloading https://download.pytorch.org/whl/cu124/nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl (150.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 20.0 MB/s eta 0:00:0000:0100:01
Downloading https://download.pytorch.org/whl/triton-3.2.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (166.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.7/166.7 MB 19.1 MB/s eta 0:00:0000:0100:01
Downloading https://download.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp311-cp311-linux_x86_64.whl (7.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 75.1 MB/s eta 0:00:00:00:0100:01
Downloading https://download.pytorch.org/whl/cu124/torchaudio-2.6.0%2Bcu124-cp311-cp311-linux_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 52.3 MB/s eta 0:00:00:00:01
Using cached https://download.pytorch.org/whl/pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
Downloading https://download.pytorch.org/whl/typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 986.8 kB/s eta 0:00:00a 0:00:01
Downloading https://download.pytorch.org/whl/filelock-3.19.1-py3-none-any.whl (15 kB)
Downloading https://download.pytorch.org/whl/fsspec-2025.9.0-py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 5.9 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/networkx-3.5-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 46.6 MB/s eta 0:00:00:00:01
Installing collected packages: triton, nvidia-cusparselt-cu12, mpmath, typing-extensions, sympy, pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, fsspec, filelock, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch, torchvision, torchaudio
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.8.0
    Uninstalling typing_extensions-4.8.0:
      Successfully uninstalled typing_extensions-4.8.0
Successfully installed filelock-3.19.1 fsspec-2025.9.0 mpmath-1.3.0 networkx-3.5 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-cusparselt-cu12-0.6.2 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 pillow-11.3.0 sympy-1.13.1 torch-2.6.0+cu124 torchaudio-2.6.0+cu124 torchvision-0.21.0+cu124 triton-3.2.0 typing-extensions-4.15.0

# DPO- Jupyter NCSA- A100 80Gb

In [ ]:
!pip install transformers>=4.45.0 trl>=0.12.0 --upgrade

In [ ]:
!which gcc
!gcc --version

/bin/bash: line 1: gcc: command not found

In [ ]:
import os
os.environ['CC'] = '/usr/bin/gcc'
os.environ['CXX'] = '/usr/bin/g++'

In [ ]:
!ls /usr/bin/ | grep -E "gcc|cc|clang"

kpseaccess
run-one-until-success

In [ ]:
!which cc
!which clang
!ls /opt/*/bin/ 2>/dev/null | head -20
!cat /etc/os-release

2to3
2to3-3.11
accelerate
accelerate-config
accelerate-estimate-memory
accelerate-launch
accelerate-merge-weights
activate
adig
ahost
alembic
bsdcat
bsdcpio
bsdtar
bsdunzip
bunzip2
bzcat
bzcmp
bzdiff
bzegrep
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

In [ ]:
!conda install -y gcc_linux-64 gxx_linux-64/

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - gxx_linux-64/

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

# DPO- Bhoomika

In [ ]:
import torch
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import DPOTrainer, DPOConfig
from peft import LoraConfig, get_peft_model

# Load your DPO data
import pandas as pd
final_dpo_df = pd.read_csv('final_dpo_df.csv')

# Check your column names first
print(final_dpo_df.columns.tolist())
final_dpo_df.head(10)

ModuleNotFoundError: No module named 'torch'

In [ ]:
!apt install trl

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package trl

In [ ]:
df = pd.read_csv('final_dpo_df.csv')

# Clean up - drop the extra index columns
df = df.drop(columns=['Unnamed: 0', ''], errors='ignore')
df = df.drop(columns=[c for c in df.columns if 'Unnamed' in c], errors='ignore')

print(f"Total samples: {len(df)}")
print(f"Ambiguous: {(df['is_ambiguous'] == 'True').sum()}")
print(f"Unambiguous: {(df['is_ambiguous'] == 'False').sum()}")

Total samples: 10036
Ambiguous: 0
Unambiguous: 0

In [ ]:
# Check the actual dtype and values
print(f"is_ambiguous dtype: {df['is_ambiguous'].dtype}")
print(f"Unique values: {df['is_ambiguous'].unique()}")

# Correct count
print(f"\nAmbiguous: {df['is_ambiguous'].sum()}")
print(f"Unambiguous: {(~df['is_ambiguous']).sum()}")

# Or if it's actually stored as string "True"/"False":
# print(f"Ambiguous: {(df['is_ambiguous'] == True).sum()}")

is_ambiguous dtype: bool
Unique values: [ True False]

Ambiguous: 4747
Unambiguous: 5289

In [ ]:
# Check the full positive and negative response format
print("=== AMBIGUOUS EXAMPLE ===")
amb_row = df[df['is_ambiguous'] == True].iloc[0]
print(f"Question: {amb_row['question']}")
print(f"Action: {amb_row['action']}")
print(f"Facets: {amb_row['facets']}")
print(f"Reasoning: {amb_row['reasoning']}")
print(f"Positive: {amb_row['positive_response']}")
print(f"Negative: {amb_row['neg_response']}")

print("\n=== UNAMBIGUOUS EXAMPLE ===")
unamb_row = df[df['is_ambiguous'] == False].iloc[0]
print(f"Question: {unamb_row['question']}")
print(f"Action: {unamb_row['action']}")
print(f"Facets: {unamb_row['facets']}")
print(f"Reasoning: {unamb_row['reasoning']}")
print(f"Positive: {unamb_row['positive_response']}")
print(f"Negative: {unamb_row['neg_response']}")

=== AMBIGUOUS EXAMPLE ===
Question: When did the simpsons first air on television?
Action: Clarify
Facets: ['Type of Show', 'Platform']
Reasoning: The question is ambiguous because it does not specify whether 'The Simpsons' refers to the TV series or another type of show, and it does not clarify if the platform (e.g., network, streaming service) is relevant. Without this information, we cannot determine the exact date of its first broadcast.
Positive: Are you asking about the original TV series or a movie, and on which platform (e.g., network, streaming service) did it first air?
Negative: The Simpsons first aired on December 17, 1989.

=== UNAMBIGUOUS EXAMPLE ===
Question: Who played george washington in the john adams series?
Action: Answer
Facets: []
Reasoning: The question is not ambiguous because it specifies the exact role and series, providing enough detail to uniquely identify the actor who portrayed George Washington in the John Adams miniseries.
Positive: ['David Morse']
Negative: Could you tell me which season of the John Adams series you're referring to?

In [ ]:
def format_chosen(row):
    """Format the full structured output as 'chosen' response"""
    return f"""Action: {row['action']}
Reasoning: {row['reasoning']}
Facets: {row['facets']}
Response: {row['positive_response']}"""

def format_rejected(row):
    """Format rejected with wrong action"""
    # Flip the action for rejected
    wrong_action = "Answer" if row['action'] == "Clarify" else "Clarify"
    wrong_facets = "[]" if row['action'] == "Clarify" else "['Unnecessary Clarification']"

    return f"""Action: {wrong_action}
Reasoning: Incorrect reasoning that led to wrong action.
Facets: {wrong_facets}
Response: {row['neg_response']}"""

def format_prompt(question):
    """Format the input prompt"""
    return f"""You are an intelligent assistant that determines whether a question is ambiguous.

Question: {question}

Analyze this question and respond with:
- Action: "Clarify" if ambiguous, "Answer" if not
- Reasoning: Brief explanation
- Facets: List of ambiguous aspects (if any)
- Response: Either a clarifying question or the direct answer"""

# Test on one example
test_row = df[df['is_ambiguous'] == True].iloc[0]
print("=== PROMPT ===")
print(format_prompt(test_row['question']))
print("\n=== CHOSEN ===")
print(format_chosen(test_row))
print("\n=== REJECTED ===")
print(format_rejected(test_row))

=== PROMPT ===
You are an intelligent assistant that determines whether a question is ambiguous.

Question: When did the simpsons first air on television?

Analyze this question and respond with:
- Action: "Clarify" if ambiguous, "Answer" if not
- Reasoning: Brief explanation
- Facets: List of ambiguous aspects (if any)
- Response: Either a clarifying question or the direct answer

=== CHOSEN ===
Action: Clarify
Reasoning: The question is ambiguous because it does not specify whether 'The Simpsons' refers to the TV series or another type of show, and it does not clarify if the platform (e.g., network, streaming service) is relevant. Without this information, we cannot determine the exact date of its first broadcast.
Facets: ['Type of Show', 'Platform']
Response: Are you asking about the original TV series or a movie, and on which platform (e.g., network, streaming service) did it first air?

=== REJECTED ===
Action: Answer
Reasoning: Incorrect reasoning that led to wrong action.
Facets: []
Response: The Simpsons first aired on December 17, 1989.

In [ ]:
# Build the DPO dataset
dpo_data = []

for _, row in df.iterrows():
    dpo_data.append({
        'prompt': format_prompt(row['question']),
        'chosen': format_chosen(row),
        'rejected': format_rejected(row)
    })

# Convert to HuggingFace Dataset
from datasets import Dataset
dpo_dataset = Dataset.from_list(dpo_data)

print(f"DPO Dataset: {len(dpo_dataset)} samples")
print(f"Columns: {dpo_dataset.column_names}")

# Train/eval split
dpo_dataset = dpo_dataset.train_test_split(test_size=0.05, seed=42)
train_dataset = dpo_dataset['train']
eval_dataset = dpo_dataset['test']

print(f"Train: {len(train_dataset)}")
print(f"Eval: {len(eval_dataset)}")

# Print full sample
print("=== FULL SAMPLE FROM TRAIN ===\n")
print("PROMPT:")
print(train_dataset[0]['prompt'])
print("\n" + "="*50 + "\n")
print("CHOSEN:")
print(train_dataset[0]['chosen'])
print("\n" + "="*50 + "\n")
print("REJECTED:")
print(train_dataset[0]['rejected'])

DPO Dataset: 10036 samples
Columns: ['prompt', 'chosen', 'rejected']
Train: 9534
Eval: 502
=== FULL SAMPLE FROM TRAIN ===

PROMPT:
You are an intelligent assistant that determines whether a question is ambiguous.

Question: What is the name of the first ewok leia meets?

Analyze this question and respond with:
- Action: "Clarify" if ambiguous, "Answer" if not
- Reasoning: Brief explanation
- Facets: List of ambiguous aspects (if any)
- Response: Either a clarifying question or the direct answer

==================================================

CHOSEN:
Action: Answer
Reasoning: The question is not ambiguous because it specifies the exact scenario of Leia meeting an Ewok, and there is only one first meeting described in the original Star Wars canon. This uniquely identifies a single character.
Facets: []
Response: ['Wicket Widget Warrick', 'Wicket W. Warrick']

==================================================

REJECTED:
Action: Clarify
Reasoning: Incorrect reasoning that led to wrong action.
Facets: ['Unnecessary Clarification']
Response: Could you confirm if you're referring to the original movie or the video game adaptation?

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_name = "Qwen/Qwen2.5-7B-Instruct"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

print(f"Tokenizer loaded: {tokenizer.name_or_path}")
print(f"Vocab size: {tokenizer.vocab_size}")
print(f"Pad token: {tokenizer.pad_token}")

Tokenizer loaded: Qwen/Qwen2.5-7B-Instruct
Vocab size: 151643
Pad token: <|im_end|>

In [ ]:
!nvidia-smi

Tue Nov 25 20:27:14 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.172.08             Driver Version: 570.172.08     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  |   00000000:00:05.0 Off |                    0 |
| N/A   26C    P0             82W /  500W |   36893MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A             362      C   /opt/conda/bin/python                 14962MiB |
+-----------------------------------------------------------------------------------------+

# Restarting session after downloading everything!

# LoRa and DPO config

In [ ]:
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
    task_type="CAUSAL_LM",
)

training_args = DPOConfig(
    output_dir="./dpo_output",
    num_train_epochs=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    gradient_checkpointing=True,
    learning_rate=5e-6,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    logging_steps=20,
    save_steps=200,
    eval_steps=200,
    eval_strategy="steps",
    bf16=True,
    max_length=512,
    max_prompt_length=384,
    beta=0.1,
    remove_unused_columns=False,
    report_to="none",
)

print("LoRA and DPO configs ready")

LoRA and DPO configs ready

# Training Iteration 1

In [ ]:
import pandas as pd
import torch
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig
from trl import DPOTrainer, DPOConfig

print(f"torch: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'None'}")

torch: 2.7.1+cu118
CUDA available: True
GPU: NVIDIA A100-SXM4-80GB

In [ ]:
 model_name = "Qwen/Qwen2.5-7B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

print(f"Tokenizer loaded: {model_name}")

Tokenizer loaded: Qwen/Qwen2.5-7B-Instruct

In [ ]:
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True,
)

print(f"Model loaded: {model.config._name_or_path}")

Loading checkpoint shards: 100%|██████████| 4/4 [00:50<00:00, 12.74s/it]

Model loaded: Qwen/Qwen2.5-7B-Instruct

In [ ]:
trainer = DPOTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    processing_class=tokenizer,
    peft_config=peft_config,
)

print(f"Trainer created")
print(f"Total steps: {len(train_dataset) // (8 * 2)}")

/opt/conda/lib/python3.11/site-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/peft/tuners/tuners_utils.py:282: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
Extracting prompt in train dataset: 100%|██████████| 9534/9534 [00:00<00:00, 11330.43 examples/s]
Applying chat template to train dataset: 100%|██████████| 9534/9534 [00:00<00:00, 19413.68 examples/s]
Tokenizing train dataset: 100%|██████████| 9534/9534 [00:07<00:00, 1272.55 examples/s]
Extracting prompt in eval dataset: 100%|██████████| 502/502 [00:00<00:00, 10920.97 examples/s]
Applying chat template to eval dataset: 100%|██████████| 502/502 [00:00<00:00, 18086.97 examples/s]
Tokenizing eval dataset: 100%|██████████| 502/502 [00:00<00:00, 1338.59 examples/s]
The model is already on multiple devices. Skipping the move to device specified in `args`.

Trainer created
Total steps: 595

In [ ]:
!conda install -y gxx_linux-64 gcc_linux-64 -c conda-forge

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.9.0
  latest version: 25.11.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=25.11.0



# All requested packages already installed.

In [ ]:
import os
os.environ['CC'] = '/opt/conda/bin/x86_64-conda-linux-gnu-gcc'
os.environ['CXX'] = '/opt/conda/bin/x86_64-conda-linux-gnu-g++'

In [ ]:
print("Starting DPO training...")
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151645}.

Starting DPO training...

/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:86: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:86: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:86: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

TrainOutput(global_step=596, training_loss=0.04845607046357468, metrics={'train_runtime': 1779.245, 'train_samples_per_second': 5.358, 'train_steps_per_second': 0.335, 'total_flos': 0.0, 'train_loss': 0.04845607046357468, 'epoch': 1.0})

In [ ]:
trainer.save_model("./dpo_final")
tokenizer.save_pretrained("./dpo_final")
print("Model saved to ./dpo_final")

Model saved to ./dpo_final

# Test the model

In [ ]:
from peft import PeftModel

# Load the trained model for inference
model.eval()

def test_question(question):
    prompt = format_prompt(question)

    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=256,
            temperature=0.7,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)
    return response

# Test on ambiguous question
print("=== AMBIGUOUS QUESTION ===")
print("Q: When did the simpsons first air on television?")
print(test_question("When did the simpsons first air on television?"))

print("\n" + "="*50 + "\n")

# Test on unambiguous question
print("=== UNAMBIGUOUS QUESTION ===")
print("Q: Who played george washington in the john adams series?")
print(test_question("Who played george washington in the john adams series?"))

=== AMBIGUOUS QUESTION ===
Q: When did the simpsons first air on television?
Action: Answer

Reasoning: The question is not ambiguous as it clearly asks for a specific date or time period when the TV show "The Simpsons" first aired.

Facets: None

Response: The Simpsons first aired on December 17, 1989, on Fox.

==================================================

=== UNAMBIGUOUS QUESTION ===
Q: Who played george washington in the john adams series?
Action: Clarify
Reasoning: The question is ambiguous because it does not specify which adaptation of John Adams' life or presidency is being referred to. There have been multiple productions about John Adams and his era.
Facets:
- Which specific production or series of "John Adams" is being asked about (e.g., the 2008 HBO miniseries, a stage play, etc.)

Response: Could you please specify which adaptation or series of "John Adams" you are referring to?

### Ambiguous question → Model says "Answer" (should be "Clarify")
### Unambiguous question → Model says "Clarify" (should be "Answer")

#This suggests the DPO training may not have properly loaded on top of the base model, or the LoRA weights aren't being #applied during inference.
#Let's check and fix:

In [ ]:
# Check if LoRA is active
print(f"Model type: {type(model)}")
print(f"Is PEFT model: {hasattr(model, 'peft_config')}")

# List adapter info
if hasattr(model, 'peft_config'):
    print(f"Adapters: {model.peft_config}")

Model type: <class 'transformers.models.qwen2.modeling_qwen2.Qwen2ForCausalLM'>
Is PEFT model: True
Adapters: {'default': LoraConfig(task_type='CAUSAL_LM', peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, peft_version='0.18.0', base_model_name_or_path='Qwen/Qwen2.5-7B-Instruct', revision=None, inference_mode=False, r=16, target_modules={'v_proj', 'down_proj', 'gate_proj', 'k_proj', 'up_proj', 'o_proj', 'q_proj'}, exclude_modules=None, lora_alpha=32, lora_dropout=0.05, fan_in_fan_out=False, bias='none', use_rslora=False, modules_to_save=None, init_lora_weights=True, layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={}, megatron_config=None, megatron_core='megatron.core', trainable_token_indices=None, loftq_config={}, eva_config=None, corda_config=None, use_dora=False, alora_invocation_tokens=None, use_qalora=False, qalora_group_size=16, layer_replication=None, runtime_config=LoraRuntimeConfig(ephemeral_gpu_offload=False), lora_bias=False, target_parameters=None, arrow_config=None, ensure_weight_tying=False)}

In [ ]:
model.eval()

def test_question(question):
    prompt = format_prompt(question)

    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=256,
            temperature=0.1,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)
    return response

# Test again
print("=== AMBIGUOUS ===")
print("Q: What is the legal age of marriage in usa?")
print(test_question("What is the legal age of marriage in usa?"))

print("\n" + "="*50 + "\n")

print("=== UNAMBIGUOUS ===")
print("Q: When did the frozen ride open at epcot?")
print(test_question("When did the frozen ride open at epcot?"))

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

=== AMBIGUOUS ===
Q: What is the legal age of marriage in usa?
Action: Clarify
Reasoning: The question is ambiguous because it does not specify which state within the USA is being referred to, as marriage laws can vary from one state to another.
Facets:
- State specificity: The question does not mention a particular state.

Response: In which U.S. state would you like to know the legal age of marriage?

==================================================

=== UNAMBIGUOUS ===
Q: When did the frozen ride open at epcot?
Action: Clarify
Reasoning: The question is ambiguous because it does not specify which "frozen ride" is being referred to. EPCOT has multiple rides, and without additional context, it's unclear which one is meant.
Facets:
- Specific frozen ride not mentioned

Response: Could you please specify which frozen ride you're asking about, such as "Frozen Ever After" or another attraction?

In [ ]:
# Test clearly unambiguous questions
test_cases = [
    "What is the capital of France?",
    "Who wrote Romeo and Juliet?",
    "What year did World War 2 end?",
    "Who is the first president of the United States?",
]

for q in test_cases:
    print(f"Q: {q}")
    result = test_question(q)
    action = result.split('\n')[0] if result else "N/A"
    print(f"{action}\n")

Q: What is the capital of France?
Action: Answer

Q: Who wrote Romeo and Juliet?
Action: Answer

Q: What year did World War 2 end?
Action: Answer

Q: Who is the first president of the United States?
Action: Answer

In [ ]:
# Test cases from your dataset
test_cases = [
    ("When did the simpsons first air on television?", "Ambiguous"),
    ("Who played george washington in the john adams series?", "Unambiguous"),
    ("When was the last time uga won a national championship?", "Ambiguous"),
    ("What is the name of the first ewok leia meets?", "Unambiguous"),
    ("Who sing play that funky music white boy?", "Ambiguous"),
]

for q, expected in test_cases:
    print(f"Q: {q}")
    print(f"Expected: {expected}")
    result = test_question(q)
    print(result[:200] + "..." if len(result) > 200 else result)
    print("-"*50)

Q: When did the simpsons first air on television?
Expected: Ambiguous
Action: Answer

Reasoning: The question is not ambiguous as it clearly asks for a specific date or time period when the TV show "The Simpsons" first aired.

Facets: None

Response: The Simpsons first ...
--------------------------------------------------
Q: Who played george washington in the john adams series?
Expected: Unambiguous
Action: Clarify
Reasoning: The question is ambiguous because it does not specify which version of the John Adams series is being referred to, as there could be multiple adaptations.
Facets:
- Version...
--------------------------------------------------
Q: When was the last time uga won a national championship?
Expected: Ambiguous
Action: Clarify
Reasoning: The question is ambiguous because "uga" could refer to multiple entities, such as UGA (University of Georgia), UGA (University of Guadalajara), or even a nickname for a pers...
--------------------------------------------------
Q: What is the name of the first ewok leia meets?
Expected: Unambiguous
Action: Clarify

Reasoning: The question is ambiguous because it does not specify which "first" meeting it refers to, nor does it clarify which version of Leia is being referred to (e.g., from the ori...
--------------------------------------------------
Q: Who sing play that funky music white boy?
Expected: Ambiguous
Action: Clarify

Reasoning: The question is ambiguous because it does not specify which version of the song is being referred to, as there have been multiple covers of "Play That Funky Music." Additio...
--------------------------------------------------

### The model is over-clarifying - it finds ambiguity even in questions labeled as unambiguous in your dataset.

### The issue: Your DPO training taught the model the format well, but the distinction between when to clarify vs answer isn't matching your dataset's labels exactly.

In [ ]:
def format_rejected_v2(row):
    """Format rejected with more realistic wrong reasoning"""
    if row['action'] == "Clarify":
        # Wrong: Answering when should clarify
        return f"""Action: Answer
Reasoning: The question is clear and specific enough to answer directly without needing clarification.
Facets: []
Response: {row['neg_response']}"""
    else:
        # Wrong: Clarifying when should answer
        return f"""Action: Clarify
Reasoning: The question might have multiple interpretations and could benefit from clarification.
Facets: ['Possible Ambiguity']
Response: {row['neg_response']}"""

# Test it
test_row = df[df['is_ambiguous'] == True].iloc[0]
print("=== CHOSEN ===")
print(format_chosen(test_row))
print("\n=== REJECTED V2 ===")
print(format_rejected_v2(test_row))

# Step 2: Rebuild dataset with better rejected responses

In [ ]:
dpo_data_v2 = []
for _, row in df.iterrows():
    dpo_data_v2.append({
        'prompt': format_prompt(row['question']),
        'chosen': format_chosen(row),
        'rejected': format_rejected_v2(row)
    })

dpo_dataset_v2 = Dataset.from_list(dpo_data_v2)
dpo_dataset_v2 = dpo_dataset_v2.train_test_split(test_size=0.05, seed=42)
train_dataset_v2 = dpo_dataset_v2['train']
eval_dataset_v2 = dpo_dataset_v2['test']

print(f"Train: {len(train_dataset_v2)}")
print(f"Eval: {len(eval_dataset_v2)}")

Train: 9534
Eval: 502

In [ ]:
# Clear memory
del model
del trainer
import gc
gc.collect()
torch.cuda.empty_cache()

# Load fresh model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True,
)

print("Fresh model loaded")

Loading checkpoint shards: 100%|██████████| 4/4 [01:02<00:00, 15.58s/it]

Fresh model loaded

In [ ]:
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
    task_type="CAUSAL_LM",
)

training_args = DPOConfig(
    output_dir="./dpo_output_v2",
    num_train_epochs=2,              # More epochs
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    gradient_checkpointing=True,
    learning_rate=5e-6,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    logging_steps=20,
    save_steps=300,
    eval_steps=300,
    eval_strategy="steps",
    bf16=True,
    max_length=512,
    max_prompt_length=384,
    beta=0.3,                        # Stronger preference signal
    remove_unused_columns=False,
    report_to="none",
)

print("Configs ready - beta=0.3, epochs=2")

Configs ready - beta=0.3, epochs=2

In [ ]:
trainer = DPOTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset_v2,
    eval_dataset=eval_dataset_v2,
    processing_class=tokenizer,
    peft_config=peft_config,
)

print(f"Trainer created")
print(f"Total steps: {len(train_dataset_v2) * 2 // (8 * 2)}")  # 2 epochs
print("Starting training...")
trainer.train()

Extracting prompt in train dataset: 100%|██████████| 9534/9534 [00:00<00:00, 11195.58 examples/s]
Applying chat template to train dataset: 100%|██████████| 9534/9534 [00:00<00:00, 19611.93 examples/s]
Tokenizing train dataset: 100%|██████████| 9534/9534 [00:07<00:00, 1358.59 examples/s]
Extracting prompt in eval dataset: 100%|██████████| 502/502 [00:00<00:00, 11061.18 examples/s]
Applying chat template to eval dataset: 100%|██████████| 502/502 [00:00<00:00, 18313.83 examples/s]
Tokenizing eval dataset: 100%|██████████| 502/502 [00:00<00:00, 1352.20 examples/s]
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151645}.

Trainer created
Total steps: 1191
Starting training...

/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:86: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:86: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:86: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:86: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

TrainOutput(global_step=1192, training_loss=0.029341716619181158, metrics={'train_runtime': 3084.1586, 'train_samples_per_second': 6.183, 'train_steps_per_second': 0.386, 'total_flos': 0.0, 'train_loss': 0.029341716619181158, 'epoch': 2.0})

In [ ]:
# Quick test on the trained model (still in memory)
model.eval()

test_prompt = """Analyze the following question for ambiguity and provide structured facets.

Question: When did the movie come out?

Provide your response in this format:
Action: [CLARIFY or ANSWER]
Reasoning: [Your reasoning]
Facets: [If CLARIFY, list the facets]
Response: [Clarifying question or direct answer]"""

inputs = tokenizer(test_prompt, return_tensors="pt").to(model.device)
outputs = model.generate(**inputs, max_new_tokens=256, temperature=0.7)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Analyze the following question for ambiguity and provide structured facets.

Question: When did the movie come out?

Provide your response in this format:
Action: [CLARIFY or ANSWER]
Reasoning: [Your reasoning]
Facets: [If CLARIFY, list the facets]
Response: [Clarifying question or direct answer] Action: CLARIFY
Reasoning: The question "When did the movie come out?" is ambiguous because it does not specify which movie is being referred to.
Facets:
1. Genre of the movie
2. Release date
3. Name of the movie
4. Country of origin

Response: Could you please specify which movie you are referring to? Additionally, would you like to know the release date in a specific country or globally? To narrow down the information, could you also provide the genre or name of the movie? Your clarification will help me provide you with the accurate information you need.

Note: The response provided is more detailed than the original request, but it gives a clear structure as per the guidelines. In practice, one might ask for only the most relevant facet based on the context. However, for the sake of thoroughness, all possible facets have been listed. If you want a more concise version, you can select the most relevant facet(s) from the list. For example:

Action: CLARIFY
Reasoning: The question "When did the movie come out?" is ambiguous because it does not specify which movie is being referred to.
Facets:
1. Name of the movie

Response: Could you please specify

# Redoing DPO using SFT LoRa model

In [ ]:
import pandas as pd

df = pd.read_csv("final_dpo_df.csv")
print(f"Loaded {len(df)} rows")

Loaded 10036 rows

In [ ]:
!apt-get install -y gcc g++

E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

BASE_MODEL = "Qwen/Qwen2.5-7B-Instruct"
SFT_ADAPTER = "bhavanasanghi9/clarifier-sft-lora"

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

print("Loading base model...")
base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True,
)

print("Loading SFT adapter...")
model = PeftModel.from_pretrained(base_model, SFT_ADAPTER)
model.config.use_cache = False

print("✅ Model loaded!")

/opt/conda/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading tokenizer...

`torch_dtype` is deprecated! Use `dtype` instead!

Loading base model...

Loading checkpoint shards: 100%|██████████| 4/4 [00:50<00:00, 12.66s/it]

Loading SFT adapter...
✅ Model loaded!

In [ ]:
!pip uninstall bitsandbytes -y

Found existing installation: bitsandbytes 0.48.2
Uninstalling bitsandbytes-0.48.2:
  Successfully uninstalled bitsandbytes-0.48.2

In [ ]:
import pandas as pd
import ast

df = pd.read_csv("final_dpo_df.csv")
print(f"✅ Loaded {len(df)} rows")
print(df.columns.tolist())

✅ Loaded 10036 rows
['Unnamed: 0.1', 'Unnamed: 0', 'question', 'is_ambiguous', 'facets', 'reasoning', 'positive_response', 'action', 'neg_response']

In [ ]:
def clean_facets(f):
    if isinstance(f, list):
        return f
    if isinstance(f, str):
        try:
            v = ast.literal_eval(f)
            return v if isinstance(v, list) else []
        except:
            return []
    return []

def clean_response(r):
    if r is None:
        return ""
    if isinstance(r, list):
        return r[0] if r else ""
    if isinstance(r, str) and r.startswith("[") and r.endswith("]"):
        try:
            lst = ast.literal_eval(r)
            return lst[0] if isinstance(lst, list) and lst else r
        except:
            pass
    return str(r).strip()

SYSTEM_PROMPT = (
    "You are a question understanding agent trained on AmbigQA-style ambiguity. "
    "For each user question:\n"
    "1) Decide if it is ambiguous (i.e., multiple plausible interpretations/answers).\n"
    "2) Explain your reasoning.\n"
    "3) List facets if ambiguous.\n"
    "4) Ask a clarifying question OR give a direct answer.\n\n"
    "Format:\n"
    "Action: Clarify|Answer\n"
    "Reasoning: ...\n"
    "Facets: [...]\n"
    "Response: ...\n"
)

def format_dpo_row(row):
    question = row["question"]
    action = row["action"]
    reasoning = row["reasoning"]
    facets = clean_facets(row["facets"])
    pos_response = clean_response(row["positive_response"])
    neg_response = clean_response(row["neg_response"])

    facets_str = "[" + ", ".join(facets) + "]" if facets else "[]"

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": question},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    chosen = f"Action: {action}\nReasoning: {reasoning}\nFacets: {facets_str}\nResponse: {pos_response}"

    if action == "Clarify":
        rejected = f"Action: Answer\nReasoning: {reasoning}\nFacets: []\nResponse: {neg_response}"
    else:
        rejected = f"Action: Clarify\nReasoning: {reasoning}\nFacets: {facets_str}\nResponse: {neg_response}"

    return {"prompt": prompt, "chosen": chosen, "rejected": rejected}

print("✅ Helper functions defined")

✅ Helper functions defined

In [ ]:
from datasets import Dataset

print("Formatting dataset...")
dpo_data = [format_dpo_row(row) for _, row in df.iterrows()]
dpo_df = pd.DataFrame(dpo_data)

# Remove empty rows
dpo_df = dpo_df[(dpo_df["prompt"].str.len() > 0) & (dpo_df["chosen"].str.len() > 0) & (dpo_df["rejected"].str.len() > 0)]
print(f"Formatted {len(dpo_df)} examples")

# Shuffle and split
dpo_df = dpo_df.sample(frac=1, random_state=42).reset_index(drop=True)
eval_size = 500

train_dataset = Dataset.from_pandas(dpo_df.iloc[eval_size:][["prompt", "chosen", "rejected"]])
eval_dataset = Dataset.from_pandas(dpo_df.iloc[:eval_size][["prompt", "chosen", "rejected"]])

print(f"✅ Train: {len(train_dataset)}, Eval: {len(eval_dataset)}")

Formatting dataset...
Formatted 10036 examples
✅ Train: 9536, Eval: 500

In [ ]:
from peft import LoraConfig
from trl import DPOTrainer, DPOConfig

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
    task_type="CAUSAL_LM",
)

training_args = DPOConfig(
    output_dir="./dpo_model",
    num_train_epochs=2,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=5e-5,
    beta=0.3,
    max_length=1024,
    max_prompt_length=512,
    logging_steps=50,
    save_steps=300,
    eval_steps=300,
    eval_strategy="steps",
    bf16=True,
    warmup_ratio=0.1,
    optim="adamw_torch",
    remove_unused_columns=False,
    report_to="none",
)

print("✅ Training config ready")

✅ Training config ready

In [ ]:
trainer = DPOTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    processing_class=tokenizer,
    peft_config=peft_config,
)

print(f"Total training steps: ~{len(train_dataset) * 2 // (2 * 8)}")
print("Starting training...")
trainer.train()

/opt/conda/lib/python3.11/site-packages/peft/tuners/tuners_utils.py:282: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
Extracting prompt in train dataset: 100%|██████████| 9536/9536 [00:00<00:00, 15987.22 examples/s]
Applying chat template to train dataset: 100%|██████████| 9536/9536 [00:00<00:00, 19975.71 examples/s]
Tokenizing train dataset: 100%|██████████| 9536/9536 [00:07<00:00, 1285.77 examples/s]
Extracting prompt in eval dataset: 100%|██████████| 500/500 [00:00<00:00, 16704.78 examples/s]
Applying chat template to eval dataset: 100%|██████████| 500/500 [00:00<00:00, 18954.91 examples/s]
Tokenizing eval dataset: 100%|██████████| 500/500 [00:00<00:00, 1315.03 examples/s]
The model is already on multiple devices. Skipping the move to device specified in `args`.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Total training steps: ~1192
Starting training...

/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

TrainOutput(global_step=1192, training_loss=0.011987933895815997, metrics={'train_runtime': 4054.181, 'train_samples_per_second': 4.704, 'train_steps_per_second': 0.294, 'total_flos': 0.0, 'train_loss': 0.011987933895815997, 'epoch': 2.0})

In [ ]:
trainer.save_model("./dpo_model_final")
tokenizer.save_pretrained("./dpo_model_final")
print("✅ Model saved to ./dpo_model_final")

✅ Model saved to ./dpo_model_final

In [ ]:
model.eval()

test_questions = [
    "When did the movie come out?",
    "Who won the championship?",
    "What is the capital of France?",
]

for q in test_questions:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": q},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            temperature=0.3,
            do_sample=True,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Extract assistant part
    if "assistant" in response.lower():
        response = response.split("assistant")[-1].strip()

    print(f"\n{'='*50}")
    print(f"Q: {q}")
    print(f"{'='*50}")
    print(response[:500])

==================================================
Q: When did the movie come out?
==================================================
Action: Clarify
Reasoning: The question is ambiguous because it does not specify which movie is being referred to or in which geographical region the release date is asked about. Without knowing the movie title and the specific region, there could be multiple correct answers.
Facets: [Movie Title, Geographical Region]
Response: Could you specify the title of the movie and the geographical region you're interested in?

==================================================
Q: Who won the championship?
==================================================
Action: Clarify
Reasoning: The question is ambiguous because it does not specify the type of championship (e.g., sports, academic, business) or the year of the event. Without this information, it's unclear which specific championship is being referred to, and thus who won it.
Facets: [Type of Championship, Year]
Response: Could you specify the type of championship and the year you're asking about?

==================================================
Q: What is the capital of France?
==================================================
Action: Answer
Reasoning: The question is not ambiguous because it clearly asks for the capital city of France, which is a specific and well-defined location. The question provides enough detail to uniquely determine the answer as Paris.
Facets: []
Response: Paris

In [ ]:
!pip install ipywidgets

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting ipywidgets
  Downloading ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: comm>=0.1.3 in /opt/conda/lib/python3.11/site-packages (from ipywidgets) (0.1.4)
Requirement already satisfied: ipython>=6.1.0 in /opt/conda/lib/python3.11/site-packages (from ipywidgets) (8.16.1)
Requirement already satisfied: traitlets>=4.3.1 in /opt/conda/lib/python3.11/site-packages (from ipywidgets) (5.11.2)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: backcall in /opt/conda/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /opt/conda/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (2.16.1)
Requirement already satisfied: stack-data in /opt/conda/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.2)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (4.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /opt/conda/lib/python3.11/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.11/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.11/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets) (0.2.8)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.0)
Requirement already satisfied: pure-eval in /opt/conda/lib/python3.11/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /opt/conda/lib/python3.11/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.8/139.8 kB 2.8 MB/s eta 0:00:00a 0:00:01
Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 914.9/914.9 kB 15.1 MB/s eta 0:00:0000:01
Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 43.2 MB/s eta 0:00:00:00:01
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets
Successfully installed ipywidgets-8.1.8 jupyterlab_widgets-3.0.16 widgetsnbextension-4.0.15

In [ ]:
from huggingface_hub import login

login(token="hf_REDACTED_TOKEN")

In [ ]:
from huggingface_hub import create_repo, upload_folder

create_repo(repo_id="itsbhoomika/clarifier-dpo-lora", exist_ok=True)

upload_folder(
    folder_path="./dpo_model_final",
    repo_id="itsbhoomika/clarifier-dpo-lora",
    repo_type="model",
)

print("✅ Uploaded!")

Processing Files (0 / 0): |          |  0.00B /  0.00B
Processing Files (1 / 2):   7%|▋         | 12.0MB /  173MB, 1.04MB/s
Processing Files (1 / 2):  15%|█▌        | 26.4MB /  173MB, 18.7MB/s
Processing Files (1 / 3):  35%|███▍      | 60.1MB /  173MB, 48.7MB/s
Processing Files (1 / 3):  76%|███████▌  |  131MB /  173MB, 99.4MB/s
Processing Files (1 / 3):  95%|█████████▍|  164MB /  173MB,  109MB/s
Processing Files (2 / 3):  99%|█████████▉|  172MB /  173MB,  100MB/s
Processing Files (2 / 3): 100%|█████████▉|  173MB /  173MB, 80.6MB/s
Processing Files (3 / 3): 100%|██████████|  173MB /  173MB, 73.4MB/s
Processing Files (3 / 3): 100%|██████████|  173MB /  173MB, 62.1MB/s
New Data Upload: 100%|██████████|  161MB /  161MB, 62.1MB/s

✅ Uploaded!

# Evaluation

In [ ]:
import pandas as pd
import torch
from tqdm import tqdm

# Load evaluation data
eval_df = pd.read_csv("final_dpo_df.csv")
eval_df = eval_df.sample(n=200, random_state=42).reset_index(drop=True)  # Sample for evaluation
print(f"Evaluating on {len(eval_df)} samples")

Evaluating on 200 samples

In [ ]:
from tqdm import tqdm

def generate_prediction(question):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": question},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=250,
            temperature=0.3,
            do_sample=True,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    if "assistant" in response.lower():
        response = response.split("assistant")[-1].strip()
    return response

# Generate predictions
print("Generating predictions...")
predictions = []
for _, row in tqdm(eval_df.iterrows(), total=len(eval_df)):
    pred = generate_prediction(row["question"])
    predictions.append(pred)

eval_df["prediction"] = predictions
print("✅ Predictions generated")

Generating predictions...

100%|██████████| 200/200 [12:34<00:00,  3.77s/it]

✅ Predictions generated

In [ ]:
def parse_prediction(pred_text):
    """Extract Action, Reasoning, Facets, Response from model output"""
    result = {
        "pred_action": None,
        "pred_reasoning": "",
        "pred_facets": [],
        "pred_response": ""
    }

    lines = pred_text.strip().split("\n")

    for line in lines:
        line_lower = line.lower().strip()
        if line_lower.startswith("action:"):
            val = line.split(":", 1)[1].strip()
            if val in ["Clarify", "Answer"]:
                result["pred_action"] = val
            elif "clarify" in val.lower():
                result["pred_action"] = "Clarify"
            elif "answer" in val.lower():
                result["pred_action"] = "Answer"
        elif line_lower.startswith("reasoning:"):
            result["pred_reasoning"] = line.split(":", 1)[1].strip()
        elif line_lower.startswith("facets:"):
            facet_str = line.split(":", 1)[1].strip()
            try:
                result["pred_facets"] = ast.literal_eval(facet_str)
            except:
                # Parse [X, Y, Z] manually
                facet_str = facet_str.strip("[]")
                if facet_str:
                    result["pred_facets"] = [f.strip() for f in facet_str.split(",")]
        elif line_lower.startswith("response:"):
            result["pred_response"] = line.split(":", 1)[1].strip()

    return result

# Parse all predictions
parsed = [parse_prediction(p) for p in eval_df["prediction"]]
eval_df["pred_action"] = [p["pred_action"] for p in parsed]
eval_df["pred_reasoning"] = [p["pred_reasoning"] for p in parsed]
eval_df["pred_facets"] = [p["pred_facets"] for p in parsed]
eval_df["pred_response"] = [p["pred_response"] for p in parsed]

print("✅ Predictions parsed")
print(f"Sample parsed: {parsed[0]}")

✅ Predictions parsed
Sample parsed: {'pred_action': 'Answer', 'pred_reasoning': 'The question is not ambiguous because it specifies the exact anatomical structure (secondary ossification center in a long bone) being asked about. This description provides enough detail to uniquely determine the location within the bone.', 'pred_facets': [], 'pred_response': 'epiphyses'}

In [ ]:
# Metric 1: Action Accuracy
action_correct = (eval_df["pred_action"] == eval_df["action"]).sum()
action_accuracy = action_correct / len(eval_df)
print(f"1. Action Accuracy: {action_accuracy:.3f} ({action_correct}/{len(eval_df)})")

# Metric 2: Clarify Precision/Recall
clarify_gold = eval_df["action"] == "Clarify"
clarify_pred = eval_df["pred_action"] == "Clarify"

true_positives = (clarify_gold & clarify_pred).sum()
false_positives = (~clarify_gold & clarify_pred).sum()
false_negatives = (clarify_gold & ~clarify_pred).sum()

clarify_precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0
clarify_recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0
clarify_f1 = 2 * clarify_precision * clarify_recall / (clarify_precision + clarify_recall) if (clarify_precision + clarify_recall) > 0 else 0

print(f"\n2. Clarify Detection:")
print(f"   Precision: {clarify_precision:.3f}")
print(f"   Recall: {clarify_recall:.3f}")
print(f"   F1: {clarify_f1:.3f}")

# Metric 3: Facet Generation (for Clarify cases)
clarify_rows = eval_df[eval_df["action"] == "Clarify"]
facet_generated = (clarify_rows["pred_facets"].apply(len) > 0).sum()
facet_rate = facet_generated / len(clarify_rows) if len(clarify_rows) > 0 else 0
print(f"\n3. Facet Generation Rate (when Clarify): {facet_rate:.3f} ({facet_generated}/{len(clarify_rows)})")

# Metric 4: Average number of facets when clarifying
avg_facets = clarify_rows["pred_facets"].apply(len).mean()
print(f"   Average facets per Clarify: {avg_facets:.2f}")

# Metric 5: Answer cases - response provided
answer_rows = eval_df[eval_df["action"] == "Answer"]
answer_pred_correct = eval_df[(eval_df["action"] == "Answer") & (eval_df["pred_action"] == "Answer")]
answer_has_response = (answer_pred_correct["pred_response"].str.len() > 0).sum()
answer_response_rate = answer_has_response / len(answer_pred_correct) if len(answer_pred_correct) > 0 else 0
print(f"\n4. Answer Response Rate: {answer_response_rate:.3f} ({answer_has_response}/{len(answer_pred_correct)})")

print("\n" + "="*50)
print("SUMMARY")
print("="*50)
print(f"Action Accuracy:     {action_accuracy:.3f}")
print(f"Clarify F1:          {clarify_f1:.3f}")
print(f"Facet Generation:    {facet_rate:.3f}")
print(f"Answer Response:     {answer_response_rate:.3f}")

1. Action Accuracy: 0.595 (119/200)

2. Clarify Detection:
   Precision: 0.941
   Recall: 0.168
   F1: 0.286

3. Facet Generation Rate (when Clarify): 0.189 (18/95)
   Average facets per Clarify: 0.34

4. Answer Response Rate: 1.000 (103/103)

==================================================
SUMMARY
==================================================
Action Accuracy:     0.595
Clarify F1:          0.286
Facet Generation:    0.189
Answer Response:     1.000

In [ ]:
# Check prediction distribution vs gold distribution
print("Gold distribution:")
print(eval_df["action"].value_counts())

print("\nPredicted distribution:")
print(eval_df["pred_action"].value_counts())

# Check confusion matrix
print("\nConfusion Matrix:")
print(pd.crosstab(eval_df["action"], eval_df["pred_action"], rownames=["Gold"], colnames=["Pred"]))

# Look at some false negatives (should Clarify but predicted Answer)
false_negatives = eval_df[(eval_df["action"] == "Clarify") & (eval_df["pred_action"] == "Answer")]
print(f"\nFalse Negatives (missed Clarify): {len(false_negatives)}")
print("\nExamples of missed Clarify:")
for i, row in false_negatives.head(3).iterrows():
    print(f"\nQ: {row['question']}")
    print(f"Gold: Clarify | Pred: Answer")
    print(f"Model response: {row['pred_response'][:100]}...")

Gold distribution:
action
Answer     105
Clarify     95
Name: count, dtype: int64

Predicted distribution:
pred_action
Answer     182
Clarify     17
Name: count, dtype: int64

Confusion Matrix:
Pred     Answer  Clarify
Gold
Answer      103        1
Clarify      79       16

False Negatives (missed Clarify): 79

Examples of missed Clarify:

Q: Who remade mad world by tears for fears?
Gold: Clarify | Pred: Answer
Model response: Tears for Fears...

Q: How many house of cards seasons are there?
Gold: Clarify | Pred: Answer
Model response: 5...

Q: When was five nights at freddy's 2 made?
Gold: Clarify | Pred: Answer
Model response: September 25, 2014...

# model is over-answering

In [ ]:
# Test with lower temperature - might help
test_q = "Who remade mad world by tears for fears?"
messages = [
    {"role": "system", "content": SYSTEM_PROMPT},
    {"role": "user", "content": test_q},
]
prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=250,
        temperature=0.7,  # Try higher temperature
        do_sample=True,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id,
    )

response = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(response.split("assistant")[-1].strip())

Action: Answer
Reasoning: The question is not ambiguous because it specifies the original song and artist, and asks about a remake. The details provided uniquely identify the question without any missing information.
Facets: []
Response: Tears for Fears

In [ ]:
# Load the original SFT model (without DPO)
from transformers import AutoModelForCausalLM
from peft import PeftModel

print("Loading SFT model (without DPO)...")
sft_base = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-7B-Instruct",
    torch_dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True,
)
sft_model = PeftModel.from_pretrained(sft_base, "bhavanasanghi9/clarifier-sft-lora")
sft_model.eval()

# Test same questions
test_questions = [
    "Who remade mad world by tears for fears?",
    "How many house of cards seasons are there?",
    "When did the movie come out?",
]

print("\n" + "="*50)
print("SFT MODEL (before DPO)")
print("="*50)

for q in test_questions:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": q},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to(sft_model.device)

    with torch.no_grad():
        outputs = sft_model.generate(
            **inputs,
            max_new_tokens=200,
            temperature=0.3,
            do_sample=True,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    if "assistant" in response.lower():
        response = response.split("assistant")[-1].strip()

    print(f"\nQ: {q}")
    print(response[:300])
    print("-"*40)

Loading SFT model (without DPO)...

Loading checkpoint shards: 100%|██████████| 4/4 [00:50<00:00, 12.67s/it]

==================================================
SFT MODEL (before DPO)
==================================================

Q: Who remade mad world by tears for fears?
Action: Answer
Reasoning: The question is not ambiguous because it specifies the original song and asks about its remake, providing enough detail to uniquely determine the answer. There is no missing information that would cause ambiguity.
Facets: []
Response: Tears for Fears
----------------------------------------

Q: How many house of cards seasons are there?
Action: Answer
Reasoning: The question is not ambiguous because it specifically asks about the number of seasons for the TV show "House of Cards." This question has a single, well-known answer based on the existing content.
Facets: []
Response: 5
----------------------------------------

Q: When did the movie come out?
Action: Clarify
Reasoning: The question is ambiguous because it does not specify which geographical region, language version, or release type (e.g., theatrical, digital) is being referred to. Different regions and versions of a movie can have different release dates.
Facets: [Geographical Region, La
----------------------------------------

 ## The root cause is in your training data. Questions like "Who remade mad world by tears for fears?" are labeled as "Clarify" in your gold data, but the model learned that specific entity questions should be answered directly.
Two paths forward:
Option A: Accept current behavior, adjust gold labels
The model's behavior is actually reasonable - "Who remade mad world" has a well-known answer (Gary Jules). The ambiguity in your gold data may be too strict.
Option B: Retrain with adjusted data
If you want more clarification, you need to ensure training examples like these are clearly labeled as Clarify with strong signal.
Let's check your gold data for these specific questions:

In [ ]:
# Check what the gold data says for these questions
check_questions = [
    "Who remade mad world by tears for fears?",
    "How many house of cards seasons are there?",
]

for q in check_questions:
    match = eval_df[eval_df["question"].str.lower() == q.lower()]
    if len(match) > 0:
        row = match.iloc[0]
        print(f"\nQ: {q}")
        print(f"Gold Action: {row['action']}")
        print(f"Gold Facets: {row['facets']}")
        print(f"Gold Reasoning: {row['reasoning'][:200]}...")

Q: Who remade mad world by tears for fears?
Gold Action: Clarify
Gold Facets: ['Year', 'Month']
Gold Reasoning: The question is ambiguous because it does not specify the year or month of the remake. Without this information, it is unclear which version of "Mad World" is being referred to, as multiple artists ma...

Q: How many house of cards seasons are there?
Gold Action: Clarify
Gold Facets: ['Year', 'Country of Origin']
Gold Reasoning: The question is ambiguous because it does not specify which version of "House of Cards" is being referred to. There could be different numbers of seasons depending on the year and country of origin, a...

In [ ]:
# Check DPO data - how many Clarify vs Answer in training?
full_df = pd.read_csv("final_dpo_df.csv")
print("Full DPO data distribution:")
print(full_df["action"].value_counts())

# Check if facets are actually different between chosen and rejected
print("\n\nSample chosen vs rejected for a Clarify case:")
clarify_sample = full_df[full_df["action"] == "Clarify"].iloc[0]
print(f"Question: {clarify_sample['question']}")
print(f"Action: {clarify_sample['action']}")
print(f"Positive Response: {clarify_sample['positive_response'][:150]}...")
print(f"Negative Response: {clarify_sample['neg_response'][:150]}...")

Full DPO data distribution:
action
Answer     5289
Clarify    4747
Name: count, dtype: int64


Sample chosen vs rejected for a Clarify case:
Question: When did the simpsons first air on television?
Action: Clarify
Positive Response: Are you asking about the original TV series or a movie, and on which platform (e.g., network, streaming service) did it first air?...
Negative Response: The Simpsons first aired on December 17, 1989....

In [ ]:
# Run same 200 samples through SFT model for comparison
print("Generating SFT predictions for comparison...")
sft_predictions = []
for _, row in tqdm(eval_df.iterrows(), total=len(eval_df)):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": row["question"]},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to(sft_model.device)

    with torch.no_grad():
        outputs = sft_model.generate(
            **inputs,
            max_new_tokens=250,
            temperature=0.3,
            do_sample=True,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    if "assistant" in response.lower():
        response = response.split("assistant")[-1].strip()
    sft_predictions.append(response)

eval_df["sft_prediction"] = sft_predictions

# Parse SFT predictions
sft_parsed = [parse_prediction(p) for p in sft_predictions]
eval_df["sft_action"] = [p["pred_action"] for p in sft_parsed]

# Compare
print("\n" + "="*50)
print("COMPARISON: SFT vs DPO")
print("="*50)

sft_accuracy = (eval_df["sft_action"] == eval_df["action"]).mean()
dpo_accuracy = (eval_df["pred_action"] == eval_df["action"]).mean()

print(f"SFT Action Accuracy: {sft_accuracy:.3f}")
print(f"DPO Action Accuracy: {dpo_accuracy:.3f}")

print("\nSFT distribution:")
print(eval_df["sft_action"].value_counts())

print("\nDPO distribution:")
print(eval_df["pred_action"].value_counts())

Generating SFT predictions for comparison...

100%|██████████| 200/200 [11:55<00:00,  3.58s/it]

==================================================
COMPARISON: SFT vs DPO
==================================================
SFT Action Accuracy: 0.590
DPO Action Accuracy: 0.595

SFT distribution:
sft_action
Answer     181
Clarify     18
Name: count, dtype: int64

DPO distribution:
pred_action
Answer     182
Clarify     17
Name: count, dtype: int64

In [ ]:
STRONGER_PROMPT = (
    "You are a question understanding agent trained on AmbigQA-style ambiguity. "
    "IMPORTANT: Many questions that seem simple are actually ambiguous. "
    "Consider: Could this question have multiple valid answers? Are there missing details "
    "(time period, location, version, entity)? If ANY ambiguity exists, you MUST clarify.\n\n"
    "For each user question:\n"
    "1) Decide if it is ambiguous (i.e., multiple plausible interpretations/answers).\n"
    "2) Explain your reasoning.\n"
    "3) List facets if ambiguous.\n"
    "4) Ask a clarifying question OR give a direct answer.\n\n"
    "Format:\n"
    "Action: Clarify|Answer\n"
    "Reasoning: ...\n"
    "Facets: [...]\n"
    "Response: ...\n"
)

test_questions = [
    "Who remade mad world by tears for fears?",
    "How many house of cards seasons are there?",
    "When did the movie come out?",
    "What is the capital of France?",
]

print("Testing with STRONGER prompt:\n")

for q in test_questions:
    messages = [
        {"role": "system", "content": STRONGER_PROMPT},
        {"role": "user", "content": q},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            temperature=0.3,
            do_sample=True,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    if "assistant" in response.lower():
        response = response.split("assistant")[-1].strip()

    print(f"Q: {q}")
    print(response[:350])
    print("-"*50)

Testing with STRONGER prompt:

Q: Who remade mad world by tears for fears?
Action: Answer
Reasoning: The question is not ambiguous because it specifies the original song and artist. These details uniquely identify the remake being asked about, assuming we know which version or artist is being referred to.
Facets: []
Response: Tears for Fears
--------------------------------------------------
Q: How many house of cards seasons are there?
Action: Answer
Reasoning: The question is not ambiguous because it specifies the show "House of Cards" and asks about its seasons. However, without a time frame or version of the show (e.g., which season range), the answer is still uniquely determined as of the most recent complete season count, which is publicly known.
Facets: [Time Frame, Version
--------------------------------------------------
Q: When did the movie come out?
Action: Clarify
Reasoning: The question is ambiguous because it does not specify which movie is being referred to or in which geographical region the release date is asked about. Without knowing the title of the movie and the specific location, there could be multiple correct answers.
Facets: [Movie Title, Geographical Region]
Response: Which movie
--------------------------------------------------
Q: What is the capital of France?
Action: Answer
Reasoning: The question is not ambiguous because it clearly asks about the capital city of France. This query has a single, well-known answer and does not require additional information such as the time period or specific context.
Facets: []
Response: Paris
--------------------------------------------------

In [ ]:
# Check your current rejected format
sample = full_df[full_df["action"] == "Clarify"].iloc[0]
print("Current approach:")
print(f"Question: {sample['question']}")
print(f"\nCHOSEN (Clarify):")
print(f"  Reasoning: {sample['reasoning'][:150]}...")
print(f"  Response: {sample['positive_response'][:100]}...")
print(f"\nREJECTED (Answer - but same reasoning?):")
print(f"  Response: {sample['neg_response'][:100]}...")

Current approach:
Question: When did the simpsons first air on television?

CHOSEN (Clarify):
  Reasoning: The question is ambiguous because it does not specify whether 'The Simpsons' refers to the TV series or another type of show, and it does not clarify ...
  Response: Are you asking about the original TV series or a movie, and on which platform (e.g., network, stream...

REJECTED (Answer - but same reasoning?):
  Response: The Simpsons first aired on December 17, 1989....

In [ ]:
hf_REDACTED_TOKEN

In [ ]:
# Use Qwen through HuggingFace Inference API (free)

import pandas as pd
import ast
import requests
import time
from tqdm import tqdm

# HuggingFace Inference API (free tier)
API_URL = "https://api-inference.huggingface.co/models/Qwen/Qwen2.5-72B-Instruct"
headers = {"Authorization": "Bearer hf_REDACTED_TOKEN"}  # Get from hf.co/settings/tokens

In [ ]:
df = pd.read_csv("final_dpo_df.csv")
df_sample = df.sample(n=50, random_state=42).reset_index(drop=True)
print(f"Testing on {len(df_sample)} samples")

def clean_facets(f):
    if isinstance(f, list): return f
    try: return ast.literal_eval(f) if isinstance(ast.literal_eval(f), list) else []
    except: return []

def clean_response(r):
    if r is None: return ""
    if isinstance(r, list): return r[0] if r else ""
    if isinstance(r, str) and r.startswith("["):
        try:
            lst = ast.literal_eval(r)
            return lst[0] if isinstance(lst, list) and lst else r
        except: pass
    return str(r).strip()

def get_wrong_reasoning(question, action):
    if action == "Clarify":
        prompt = f"Generate 2 sentences arguing this question is NOT ambiguous: '{question}'. Start with: The question is not ambiguous because"
    else:
        prompt = f"Generate 2 sentences arguing this question IS ambiguous: '{question}'. Start with: The question is ambiguous because"

    try:
        response = requests.post(API_URL, headers=headers, json={"inputs": prompt, "parameters": {"max_new_tokens": 100}})
        return response.json()[0]["generated_text"].replace(prompt, "").strip()
    except Exception as e:
        print(f"Error: {e}")
        return None

Testing on 50 samples

In [ ]:

improved_data = []
for idx, row in tqdm(df_sample.iterrows(), total=len(df_sample)):
    facets = clean_facets(row["facets"])
    facets_str = "[" + ", ".join(facets) + "]" if facets else "[]"
    pos_response = clean_response(row["positive_response"])
    neg_response = clean_response(row["neg_response"])

    chosen = f"Action: {row['action']}\nReasoning: {row['reasoning']}\nFacets: {facets_str}\nResponse: {pos_response}"

    wrong_reasoning = get_wrong_reasoning(row["question"], row["action"])
    if wrong_reasoning is None:
        wrong_reasoning = "The question is clear." if row["action"] == "Clarify" else "The question needs clarification."

    if row["action"] == "Clarify":
        rejected = f"Action: Answer\nReasoning: {wrong_reasoning}\nFacets: []\nResponse: {neg_response}"
    else:
        rejected = f"Action: Clarify\nReasoning: {wrong_reasoning}\nFacets: [Context, Time]\nResponse: Could you provide more details?"

    improved_data.append({"question": row["question"], "chosen": chosen, "rejected": rejected, "gold_action": row["action"]})
    time.sleep(1)  # Light rate limiting

improved_df = pd.DataFrame(improved_data)
improved_df.to_csv("improved_dpo_test_50.csv", index=False)
print(f"\n✅ Saved! Sample:")
print(f"\nCHOSEN:\n{improved_df.iloc[0]['chosen']}")
print(f"\nREJECTED:\n{improved_df.iloc[0]['rejected']}")

  0%|          | 0/50 [00:00<?, ?it/s]

Error: 0

  2%|▏         | 1/50 [00:01<00:52,  1.07s/it]

Error: 0

  4%|▍         | 2/50 [00:02<00:51,  1.06s/it]

Error: 0

  6%|▌         | 3/50 [00:03<00:49,  1.06s/it]

Error: 0

  8%|▊         | 4/50 [00:04<00:48,  1.06s/it]

Error: 0

 10%|█         | 5/50 [00:05<00:47,  1.06s/it]

Error: 0

 12%|█▏        | 6/50 [00:06<00:46,  1.06s/it]

Error: 0

 14%|█▍        | 7/50 [00:07<00:46,  1.08s/it]

Error: 0

 16%|█▌        | 8/50 [00:08<00:44,  1.07s/it]

Error: 0

 18%|█▊        | 9/50 [00:09<00:44,  1.08s/it]

Error: 0

 20%|██        | 10/50 [00:10<00:43,  1.08s/it]

Error: 0

 22%|██▏       | 11/50 [00:11<00:41,  1.07s/it]

Error: 0

 24%|██▍       | 12/50 [00:12<00:41,  1.09s/it]

Error: 0

 26%|██▌       | 13/50 [00:13<00:39,  1.08s/it]

Error: 0

 28%|██▊       | 14/50 [00:15<00:38,  1.07s/it]

Error: 0

 30%|███       | 15/50 [00:16<00:37,  1.07s/it]

Error: 0

 32%|███▏      | 16/50 [00:17<00:36,  1.07s/it]

Error: 0

 34%|███▍      | 17/50 [00:18<00:35,  1.07s/it]

Error: 0

 36%|███▌      | 18/50 [00:19<00:34,  1.07s/it]

Error: 0

 38%|███▊      | 19/50 [00:20<00:33,  1.07s/it]

Error: 0

 40%|████      | 20/50 [00:21<00:31,  1.06s/it]

Error: 0

 42%|████▏     | 21/50 [00:22<00:30,  1.06s/it]

Error: 0

 44%|████▍     | 22/50 [00:23<00:29,  1.06s/it]

Error: 0

 46%|████▌     | 23/50 [00:24<00:28,  1.06s/it]

Error: 0

 48%|████▊     | 24/50 [00:25<00:27,  1.06s/it]

Error: 0

 50%|█████     | 25/50 [00:26<00:26,  1.06s/it]

Error: 0

 52%|█████▏    | 26/50 [00:27<00:25,  1.06s/it]

Error: 0

 54%|█████▍    | 27/50 [00:28<00:24,  1.06s/it]

Error: 0

 56%|█████▌    | 28/50 [00:29<00:23,  1.06s/it]

Error: 0

 58%|█████▊    | 29/50 [00:30<00:22,  1.06s/it]

Error: 0

 60%|██████    | 30/50 [00:32<00:21,  1.06s/it]

Error: 0

 62%|██████▏   | 31/50 [00:33<00:20,  1.06s/it]

Error: 0

 64%|██████▍   | 32/50 [00:34<00:19,  1.06s/it]

Error: 0

 66%|██████▌   | 33/50 [00:35<00:18,  1.06s/it]

Error: 0

 68%|██████▊   | 34/50 [00:36<00:16,  1.06s/it]

Error: 0

 70%|███████   | 35/50 [00:37<00:15,  1.06s/it]

Error: 0

 72%|███████▏  | 36/50 [00:38<00:14,  1.06s/it]

Error: 0

 74%|███████▍  | 37/50 [00:39<00:13,  1.06s/it]

Error: 0

 76%|███████▌  | 38/50 [00:40<00:12,  1.06s/it]

Error: 0

 78%|███████▊  | 39/50 [00:41<00:11,  1.06s/it]

Error: 0

 80%|████████  | 40/50 [00:42<00:10,  1.06s/it]

Error: 0

 82%|████████▏ | 41/50 [00:43<00:09,  1.06s/it]

Error: 0

 84%|████████▍ | 42/50 [00:44<00:08,  1.06s/it]

Error: 0

 86%|████████▌ | 43/50 [00:45<00:07,  1.06s/it]

Error: 0

 88%|████████▊ | 44/50 [00:46<00:06,  1.06s/it]

Error: 0

 90%|█████████ | 45/50 [00:47<00:05,  1.06s/it]

Error: 0

 92%|█████████▏| 46/50 [00:48<00:04,  1.06s/it]

Error: 0

 94%|█████████▍| 47/50 [00:50<00:03,  1.06s/it]

Error: 0

 96%|█████████▌| 48/50 [00:51<00:02,  1.06s/it]

Error: 0

 98%|█████████▊| 49/50 [00:52<00:01,  1.06s/it]

Error: 0

100%|██████████| 50/50 [00:53<00:00,  1.07s/it]

✅ Saved! Sample:

CHOSEN:
Action: Answer
Reasoning: The question is not ambiguous because it specifies the exact anatomical structure (secondary ossification center in a long bone) being asked about. This description provides enough detail to uniquely determine the location.
Facets: []
Response: epiphyses

REJECTED:
Action: Clarify
Reasoning: The question needs clarification.
Facets: [Context, Time]
Response: Could you provide more details?