# Text Cleaning

## Load Dataset

In [1]:
import pandas as pd

In [2]:
headlines = pd.read_excel("headlines_Working.xlsx")

In [3]:
headlines.shape

(133375, 5)

In [4]:
headlines['RIC'].value_counts()

RIC
INF.L        4109
CEZP.PR      3305
AAPL.OQ      3024
JNJ.N        2152
COR          1888
             ...
ITP.A           1
OBLG.OQ         1
VINCIT.HE       1
CPC.L           1
PW.A            1
Name: count, Length: 2221, dtype: int64

In [5]:
headlines = headlines.drop('Unnamed: 0', axis = 1)

In [6]:
headlines = headlines.dropna()

In [7]:
headlines.shape

(132063, 4)

In [8]:
from IPython.display import display
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', True) 

display(headlines.head)

<bound method NDFrame.head of             RIC                sdate                edate  \
0           COR  2021-10-16 00:00:00  2021-11-10 00:00:00
1           COR  2021-10-16 00:00:00  2021-11-10 00:00:00
2           COR  2021-10-16 00:00:00  2021-11-10 00:00:00
3           COR  2021-10-16 00:00:00  2021-11-10 00:00:00
4           COR  2021-10-16 00:00:00  2021-11-10 00:00:00
...         ...                  ...                  ...
133370  HYFM.OQ           1969-12-02           1969-12-27
133371  HYFM.OQ           1969-12-02           1969-12-27
133372  HYFM.OQ           1969-12-02           1969-12-27
133373  HYFM.OQ           1969-12-02           1969-12-27
133374  HYFM.OQ           1969-12-02           1969-12-27

                                                                                                               Headlines
0                                                    CIF/FOB Gulf Grain-Corn barge basis steady to lower, soybeans mixed
1                                         Export Summary-Philippine importer buys feed wheat, South Korea seeks soybeans
2                                                      PLATTS: 698--Platts Latin America Corn Daily Commentary - 09Nov21
3                                                                                       DJ Thailand Corn Weather - Nov 9
4                                                                                DJ Northeast China Corn Weather - Nov 9
...                                                                                                                  ...
133370                                                4 Agriculture - Products Stocks to Watch Despite Industry Concerns
133371  Is Hydrofarm Holdings Group, Inc. (NASDAQ:HYFM) the Best Vertical Farming and Hydroponic Stock to Invest In Now?
133372                               Why Hydrofarm Holdings Group (HYFM) Is Among the Best Cannabis Stocks To Invest In?
133373                                                          3 US Penny Stocks With Market Caps Over $30M To Consider
133374                                       Hydrofarm sees FY24 sales to decrease low-to-high teens in percentage terms

[132063 rows x 4 columns]>

In [9]:
df = headlines

## Text Formatting

## Clean Text

In [10]:
!pip install langdetect

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: langdetect in ./.local/lib/python3.12/site-packages (1.0.9)
Requirement already satisfied: six in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from langdetect) (1.16.0)

In [11]:
!wget -nc https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin

File ‘lid.176.bin’ already there; not retrieving.

In [12]:
from joblib import Parallel, delayed

In [13]:
# Step 2: Imports
import re
import fasttext
from joblib import Parallel, delayed

# Step 3: Load the fastText language model
ft_model = fasttext.load_model("lid.176.bin")

# Step 4: Fast regex-based prefilter
regex_platts = re.compile(r'platts:.*?(daily|report|assessment|commentary|rationale|summary)', re.IGNORECASE)
regex_dj = re.compile(r'dj cbot corn options close.*', re.IGNORECASE)

def is_potentially_valid(text):
    if not isinstance(text, str): return False
    if regex_platts.search(text): return False
    if regex_dj.search(text): return False
    return True

# Filter with fast regex logic
df = df[df['Headlines'].apply(is_potentially_valid)].reset_index(drop=True)
print(f"After regex filtering: {len(df)} rows")

# Step 5: Language detection using fasttext
def fast_lang_detect(text):
    if len(text.strip()) <= 5:
        return True  # Assume short lines are okay
    lang = ft_model.predict(text)[0][0]
    return lang == '__label__en'

# Parallelize language detection using joblib
lang_filter = Parallel(n_jobs=16, backend="threading")(
    delayed(fast_lang_detect)(text) for text in df['Headlines']
)

# Final filtered dataframe
df = df[lang_filter].reset_index(drop=True)
print(f"After language detection: {len(df)} rows")

After regex filtering: 131612 rows
After language detection: 129249 rows

In [14]:
df.shape

(129249, 4)

In [15]:
import re
from joblib import Parallel, delayed
import multiprocessing

# Precompile all regex patterns
regexes = [
    re.compile(r'\bpercent\b', re.IGNORECASE),  # "percent" → "%"
    re.compile(r'\bplatts\s*:\s*\d+\b', re.IGNORECASE),
    re.compile(r'(?<=\w)/(?=\w)'),  # Replace "/" between words
    re.compile(r'\b(19|20)\d{2}[-/](19|20)?\d{2}\b'),  # 2021-22
    re.compile(r'\b(?:NASDAQ|NYSE|AMEX):(\w{1,6})\b', re.IGNORECASE),  # Keep only ticker

    # ⬇️ NEW: Single super-regex for months/dates (combines many patterns cleanly)
    re.compile(r'\b(?:jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)\s*[\-–/]?\s*\d{1,2}(?:st|nd|rd|th)?(?:[\-–/]\d{1,2})?(?:\s+\d{2,4})?\b', re.IGNORECASE),

    re.compile(r'\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b', re.IGNORECASE),
    re.compile(r'\b(dj|usda)\b', re.IGNORECASE),
    re.compile(r'\(\d+\s+pages\)', re.IGNORECASE),
    re.compile(r'<.*?>'),  # HTML tags
    re.compile(r'\b(19|20)\d{2}\b'),  # Years
    re.compile(r'[:,?]'),  # punctuation
    re.compile(r'\b\d{1,2}[–-]\d{1,2}\b'),  # standalone 1-2 day ranges
    re.compile(r'\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b'),  # date formats like 01/01/2024
    re.compile(r'[\(\)\[\]\{\}\|]'),  # brackets
    re.compile(r'[–-]{1,2}')  # dashes
]

# Merge tokens like "$ 20" → "$20" and "15 %" → "15%"
def merge_symbols(text):
    tokens = text.split()
    merged = []
    i = 0
    while i < len(tokens):
        current = tokens[i]
        next_token = tokens[i + 1] if i + 1 < len(tokens) else ""

        if current == "$" and next_token.replace('.', '', 1).isdigit():
            merged.append(current + next_token)
            i += 2
        elif current.replace('.', '', 1).isdigit() and next_token == "%":
            merged.append(current + next_token)
            i += 2
        else:
            merged.append(current)
            i += 1
    return " ".join(merged)

# Main fast cleaner function
def cleaned_text_fast(text):
    if not isinstance(text, str):
        return text
    for i, pattern in enumerate(regexes):
        if i == 0:  # "percent" → "%"
            text = pattern.sub('%', text)
        elif i == 4:  # NASDAQ:HYFM → HYFM
            text = pattern.sub(r'\1', text)
        else:
            text = pattern.sub(' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return merge_symbols(text)

# Apply to all headlines using all CPU cores
cleaned = Parallel(n_jobs=multiprocessing.cpu_count())(
    delayed(cleaned_text_fast)(text) for text in df['Headlines']
)

# Store result
df['Cleaned_Headlines'] = cleaned

## Tokenization

In [16]:
!pip install spacy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: spacy in ./.local/lib/python3.12/site-packages (3.8.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./.local/lib/python3.12/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./.local/lib/python3.12/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./.local/lib/python3.12/site-packages (from spacy) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./.local/lib/python3.12/site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./.local/lib/python3.12/site-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in ./.local/lib/python3.12/site-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./.local/lib/python3.12/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in ./.local/lib/python3.12/site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./.local/lib/python3.12/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in ./.local/lib/python3.12/site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in ./.local/lib/python3.12/site-packages (from spacy) (0.15.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy) (4.66.5)
Requirement already satisfied: numpy>=1.19.0 in ./.local/lib/python3.12/site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy) (2.8.2)
Requirement already satisfied: jinja2 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in ./.local/lib/python3.12/site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in ./.local/lib/python3.12/site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.8.30)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in ./.local/lib/python3.12/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in ./.local/lib/python3.12/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Collecting numpy>=1.19.0 (from spacy)
  Downloading numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: click>=8.0.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in ./.local/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (13.7.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in ./.local/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: marisa-trie>=1.1.0 in ./.local/lib/python3.12/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Downloading numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 68.6 MB/s eta 0:00:00a 0:00:01
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.2.5 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.5 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.5 which is incompatible.
Successfully installed numpy-2.2.5

In [17]:
!python -m spacy download en_core_web_sm

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/spacy/errors.py", line 3, in <module>
    from .compat import Literal
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/spacy/compat.py", line 4, in <module>
    from thinc.util import copy_array
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/thinc/__init__.py", line 5, in <module>
    from .config import registry
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/thinc/config.py", line 5, in <module>
    from .types import Decorator
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/thinc/types.py", line 27, in <module>
    from .compat import cupy, has_cupy
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/thinc/compat.py", line 99, in <module>
    import h5py
  File "/opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5r.pyx", line 1, in init h5py.h5r
  File "h5py/h5p.pyx", line 1, in init h5py.h5p
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [18]:
import spacy
import pandas as pd

# Load spaCy
nlp = spacy.load("en_core_web_sm", disable=["ner", "parser", "tagger"])

# Merge function
def merge_symbols(tokens):
    merged = []
    i = 0
    while i < len(tokens):
        current = tokens[i]
        next_token = tokens[i + 1] if i + 1 < len(tokens) else ""

        if current == "$" and next_token.replace('.', '', 1).isdigit():
            merged.append(current + next_token)
            i += 2
        elif current.replace('.', '', 1).isdigit() and next_token == "%":
            merged.append(current + next_token)
            i += 2
        else:
            merged.append(current)
            i += 1
    return merged

# Tokenize headlines in batches (uses multiple threads internally)
texts = df["Cleaned_Headlines"].fillna("").astype(str).str.lower().tolist()

tokens = []
for doc in nlp.pipe(texts, batch_size=1000, n_process=1):  # Use n_process=1 to avoid multiprocessing errors
    raw_tokens = [token.text for token in doc if token.text.strip()]
    tokens.append(merge_symbols(raw_tokens))

df["Tokens"] = tokens

/jet/home/sadapa/.conda/envs/clean_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/jet/home/sadapa/.conda/envs/clean_env/lib/python3.10/site-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)

## Lemmatization

## NER

### NER using en_core_web_sm

In [19]:
import spacy

# Load spaCy with all pipeline components
nlp = spacy.load("en_core_web_sm")  # Keep full pipeline for NER

# Function to extract named entities from a spaCy doc
def get_ents(doc):
    return [(ent.text, ent.label_) for ent in doc.ents]

# Convert text column to list
texts = df["Cleaned_Headlines"].fillna("").astype(str).tolist()

# Use n_process > 1 to enable parallelism
ner_results = []
for doc in nlp.pipe(texts, batch_size=1000, n_process=4):  # Adjust n_process to your core count
    ner_results.append(get_ents(doc))

# Assign back to DataFrame
df["NER"] = ner_results

In [20]:
!python -m spacy download en_core_web_trf

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/spacy/errors.py", line 3, in <module>
    from .compat import Literal
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/spacy/compat.py", line 4, in <module>
    from thinc.util import copy_array
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/thinc/__init__.py", line 5, in <module>
    from .config import registry
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/thinc/config.py", line 5, in <module>
    from .types import Decorator
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/thinc/types.py", line 27, in <module>
    from .compat import cupy, has_cupy
  File "/jet/home/sadapa/.local/lib/python3.12/site-packages/thinc/compat.py", line 99, in <module>
    import h5py
  File "/opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5r.pyx", line 1, in init h5py.h5r
  File "h5py/h5p.pyx", line 1, in init h5py.h5p
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [21]:
!pip install spacy[transformers]

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: spacy[transformers] in ./.local/lib/python3.12/site-packages (3.8.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (0.15.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy[transformers]) (4.66.5)
Requirement already satisfied: numpy>=1.19.0 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (2.2.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy[transformers]) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy[transformers]) (2.8.2)
Requirement already satisfied: jinja2 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy[transformers]) (3.1.4)
Requirement already satisfied: setuptools in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy[transformers]) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from spacy[transformers]) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (3.5.0)
Requirement already satisfied: spacy_transformers<1.4.0,>=1.1.2 in ./.local/lib/python3.12/site-packages (from spacy[transformers]) (1.3.8)
Requirement already satisfied: language-data>=1.2 in ./.local/lib/python3.12/site-packages (from langcodes<4.0.0,>=3.2.0->spacy[transformers]) (1.3.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[transformers]) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[transformers]) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[transformers]) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy[transformers]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy[transformers]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy[transformers]) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy[transformers]) (2024.8.30)
Requirement already satisfied: transformers<4.50.0,>=3.4.0 in ./.local/lib/python3.12/site-packages (from spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (4.49.0)
Requirement already satisfied: torch>=1.8.0 in ./.local/lib/python3.12/site-packages (from spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (2.7.0)
Requirement already satisfied: spacy-alignments<1.0.0,>=0.7.2 in ./.local/lib/python3.12/site-packages (from spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (0.9.1)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in ./.local/lib/python3.12/site-packages (from thinc<8.4.0,>=8.3.4->spacy[transformers]) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in ./.local/lib/python3.12/site-packages (from thinc<8.4.0,>=8.3.4->spacy[transformers]) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy[transformers]) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in ./.local/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy[transformers]) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy[transformers]) (13.7.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in ./.local/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy[transformers]) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from weasel<0.5.0,>=0.1.0->spacy[transformers]) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from jinja2->spacy[transformers]) (2.1.3)
Requirement already satisfied: marisa-trie>=1.1.0 in ./.local/lib/python3.12/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy[transformers]) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[transformers]) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[transformers]) (2.15.1)
Requirement already satisfied: filelock in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (3.13.1)
Requirement already satisfied: sympy>=1.13.3 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (1.13.3)
Requirement already satisfied: networkx in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (3.3)
Requirement already satisfied: fsspec in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (1.11.1.6)
Requirement already satisfied: triton==3.3.0 in ./.local/lib/python3.12/site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (3.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in ./.local/lib/python3.12/site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (0.30.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (2024.9.11)
Requirement already satisfied: tokenizers<0.22,>=0.21 in ./.local/lib/python3.12/site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (0.21.1)
Requirement already satisfied: safetensors>=0.4.1 in ./.local/lib/python3.12/site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (0.5.3)
Requirement already satisfied: mdurl~=0.1 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[transformers]) (0.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/packages/anaconda3-2024.10-1/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (1.3.0)

### NER using en_core_web_trf

In [22]:
import spacy

# Load the transformer-based spaCy model
nlp = spacy.load("en_core_web_trf")  # This includes the transformer pipeline by default

# Function to extract NER from a spaCy Doc
def get_ents(doc):
    return [(ent.text, ent.label_) for ent in doc.ents]

# Get texts
texts = df["Cleaned_Headlines"].fillna("").astype(str).tolist()

# Use spaCy's efficient nlp.pipe for batching
ner_results = []
for doc in nlp.pipe(texts, batch_size=32):  # Transformer model: small batch size recommended (e.g., 8–32)
    ner_results.append(get_ents(doc))

df["NER2"] = ner_results

### Combining the results

In [23]:
from collections import defaultdict

def combine_ner_lists(ner1, ner2):
    combined = defaultdict(set)
    
    for text, label in ner1 + ner2:
        combined[(text.lower(), label)].add(text)  # case-insensitive match

    # Keep only one version of each entity (you can prefer trf text version if needed)
    return [(list(texts)[0], label) for (text_lower, label), texts in combined.items()]

# Combine row-wise
df["NER_combined"] = [
    combine_ner_lists(n1, n2)
    for n1, n2 in zip(df["NER"], df["NER2"])
]

# option 2: linking named entities to class labels (peer or target)

### Combining NERs per company

In [24]:
df.head()

,RIC,sdate,edate,Headlines,Cleaned_Headlines,Tokens,NER,NER2,NER_combined
0,COR,2021-10-16 00:00:00,2021-11-10 00:00:00,"CIF/FOB Gulf Grain-Corn barge basis steady to lower, soybeans mixed",CIF FOB Gulf Grain Corn barge basis steady to lower soybeans mixed,"[cif, fob, gulf, grain, corn, barge, basis, steady, to, lower, soybeans, mixed]","[(CIF, ORG)]","[(CIF FOB, ORG)]","[(CIF, ORG), (CIF FOB, ORG)]"
1,COR,2021-10-16 00:00:00,2021-11-10 00:00:00,"Export Summary-Philippine importer buys feed wheat, South Korea seeks soybeans",Export Summary Philippine importer buys feed wheat South Korea seeks soybeans,"[export, summary, philippine, importer, buys, feed, wheat, south, korea, seeks, soybeans]","[(Philippine, NORP), (South Korea, GPE)]","[(Philippine, NORP), (South Korea, GPE)]","[(Philippine, NORP), (South Korea, GPE)]"
2,COR,2021-10-16 00:00:00,2021-11-10 00:00:00,DJ Thailand Corn Weather - Nov 9,Thailand Corn Weather,"[thailand, corn, weather]","[(Thailand, GPE)]","[(Thailand, GPE)]","[(Thailand, GPE)]"
3,COR,2021-10-16 00:00:00,2021-11-10 00:00:00,DJ Northeast China Corn Weather - Nov 9,Northeast China Corn Weather,"[northeast, china, corn, weather]","[(Northeast, ORG), (China, GPE)]","[(China, GPE)]","[(Northeast, ORG), (China, GPE)]"
4,COR,2021-10-16 00:00:00,2021-11-10 00:00:00,Corn: Cargo market without buyers,Corn Cargo market without buyers,"[corn, cargo, market, without, buyers]",[],[],[]

In [25]:
# Assumes df already has 'RIC' and 'Normalized_Entities' columns
grouped_df = df.groupby("RIC")["NER_combined"].apply(lambda x: sum(x, [])).reset_index()
grouped_df.columns = ["RIC", "NER_combined"]

In [26]:
display(grouped_df.head(10))

,RIC,NER_combined
0,000150.KS,"[(Second Quarter, DATE), (11 cent, MONEY), (CERV Cervus Equipment, ORG), (Cervus Equipment Corporation Cervus, ORG), (Second Quarter, DATE), (Cervus Equipment Corporation, ORG), (Cervus, ORG), (Press Release Cervus, ORG), (Second Quarter, DATE), (Cervus, ORG), (Second Quarter, DATE), (Cervus, ORG), (Asia Pacific Corporate, ORG), (13, CARDINAL), (Asia Pacific Corporate Calendar, EVENT), (Month Ahead, DATE), (13, DATE), (Doosan, PRODUCT), (Korean, NORP), (06 09, CARDINAL), (NH Investment & Securities Previously Woori Research, ORG), (Second Half, DATE), (06 09, DATE), (MSCI ESG Research, ORG), (Doosan Corporation, ORG), (Korea, GPE), (SK, ORG), (Cervus Equipment Corporation Cervus Equipment Peterbilt, ORG), (Open New TRP Parts Location, ORG), (Cervus Equipment Corporation, ORG), (Cervus Equipment Peterbilt, ORG), (Prince Albert, GPE), (Saskatchewan, GPE), (200, CARDINAL), (6, CARDINAL), (REG Ceres Power Holdings Notice of Capital Markets Teach, ORG), (REG Ceres Power Holdings, ORG), (BitPath CAST.ERA, ORG), (ONE, CARDINAL), (ONE Media, ORG), (BitPath CAST.ERA, ORG), (ONE, CARDINAL), (ONE Media, ORG), (NextGen Broadcast Standard, PRODUCT), (Doosan Corp MarketLine, ORG), (Doosan Corp, ORG), (Daegu Mao Elementary School Expression, PERSON), (Daegu Mao, ORG), (Eastern Environmental Improvement Electric Sector Design Service, ORG), (Daegu Doosan Elementary School, FAC), (nautmark Eastern Environmental Improvement, ORG), (the Rolls Royce Group's, ORG), (Competition Authority of the French Republic, ORG), (Autorité, ORG), (Framatome, ORG), (EDF, ORG), (Industrial Air Compressor Market, ORG), (17.8, MONEY), (Global Market Insights Inc., ORG), ($17.8 Bn, MONEY), (Doosan Bobcat, PERSON), (Cogniac, ORG), (Sustain Asia Daily, ORG), (Japan, GPE), (26, CARDINAL), (CLSA, ORG), (Japan week, DATE), (26 May CLSA, DATE), (Machines From The Manufacturer Doosan, WORK_OF_ART), (Doosan, ORG), (Korea Morning Notes, ORG), (26, CARDINAL), (CLSA, ORG), (Korea, GPE), (26 May, DATE), (Korea, GPE), (CLSA, ORG), (BBB0, PERSON), (Doosan, ORG), (Seoul, GPE), (Korean, NORP), (Warranty Maintenance Services Doosan Dx200a, ORG), (Doosan, PRODUCT), (Dx200a, PRODUCT), (Excavator, PRODUCT), (dhkcebdxcl0001807, PRODUCT)]"
1,002230.SZ,"[(Iflytek Co Ltd, ORG), (Overnight Returns Marktfeld, PERSON), (Intraday, TIME), (Overnight, TIME), (Marktfeld, PERSON), (China, GPE), (China Software, ORG), (Goldman Sachs, ORG), (Iflytek, ORG), (China Knowledge Online Pte. Ltd., ORG), (1, CARDINAL), (Apr, DATE), (China, GPE), (Goldman Sachs, ORG), (China, GPE), (Zhuiyi AI /, PERSON), (NLP, ORG), (75%, PERCENT), (17, CARDINAL), (China Software, ORG), (Goldman Sachs, ORG), (APAC Quantitative & Systematic Strategy Northbound, ORG), (Credit Suisse, ORG), (HK Bourse Results Announcement, ORG), (33, CARDINAL), (HK Bourse, ORG), (Great Wall Motor 33, ORG), (HK Bourse Announcement, ORG), (Chinasoft International, FAC), (9, CARDINAL), (Chinasoft International 9, ORG), (iFLYTEK Co. Ltd., ORG), (MarketLine, PERSON), (NIKKEI Asia Pacific Corporate, ORG), (19 2, CARDINAL), (NIKKEI, ORG), (NIKKEI Asia Pacific Corporate, ORG), (18 2, CARDINAL), (NIKKEI, ORG), (HK Bourse Announcement, ORG), (China Merchants Direct, ORG), (6, CARDINAL), (Iflytek 002230, DATE), (Mar, PERSON), (China Knowledge Online Pte. Ltd., ORG), (Iflytek, ORG), (002230, PRODUCT), (Mar, ORG), (New Decade, EVENT), (AWE2021, EVENT), (Press Release Kingdee International, ORG), (Kingdee International, ORG), (Annual, DATE), (Kingdee International, ORG), (Annual, DATE), (iFlytek, ORG), (Tindall, ORG), (Iflytek Co Ltd Deliver Long Term Returns Sadif Analytics, ORG), (Iflytek Co Ltd, ORG), (Sadif Analytics, ORG), (NZ, GPE), (Australia, GPE), (China, GPE), (NZ Australia, GPE), (AWE, ORG), (Haier Smart Home Brings, PERSON), (Smart Home Solution, ORG), (Haier, ORG), (Haier Smart Home Brings, PERSON), (Smart Home Solution, ORG), (Haier, ORG), (Haier Smart Home Brings, PERSON), (Smart Home Solution, ORG), (Haier, ORG), (Software & Services Results Preview Software & services, ORG), (19, CARDINAL), (China International Capital Corporation, ORG), (COVID 19, EVENT), (China International Capital Corporation Hong Kong Limited, ORG), (Software & Services Results Preview Software & services, ORG), (19, CARDINAL), (China International Capital Corporation, ORG), (COVID 19, EVENT), (China International Capital Corporation Hong Kong Limited, ORG), (China Software LinkingMed, ORG), (AI Medical, ORG), (Goldman Sachs, ORG), (Asia Pacific Corporate, ORG), (26, CARDINAL), (Asia Pacific Corporate Calendar, EVENT), (Month Ahead, DATE), (26, DATE), (Asia Pacific Corporate, ORG), (25, CARDINAL), (Asia Pacific Corporate Calendar, EVENT), (Month Ahead, DATE), (25, DATE), (Greater China Technology Hardware Incorporating, ORG), (Greater China Technology Hardware, ORG), (Morgan Stanley, ORG), ...]"
2,002281.SZ,"[(Accelink Technologies, ORG), (China Knowledge Online Pte., ORG), (2, CARDINAL), (Oct, DATE), (China Knowledge Online Pte. Ltd., ORG), (Accelink Technologies 002281.SZ Data Update, ORG), (3Q21 Goldman Sachs, ORG), (Accelink Technologies, ORG), (3Q21, DATE), (Goldman Sachs, ORG), (First Read Accelink Technologies ""Transmission, ORG), (biz grew, PERSON), (UBS Equities, ORG), (First Read Accelink Technologies, ORG), (Accelink Technologies, ORG), (1, CARDINAL), (Citi, GPE), (Citi, ORG), (Asian Daily China, ORG), (3Q21, ORG), (5, CARDINAL), (OUTPERFORM Credit Suisse, ORG), (Asian Daily, ORG), (China Accelink, ORG), (3Q21, DATE), (Credit Suisse, ORG), (Asia Pacific Corporate, ORG), (3, CARDINAL), (Asia Pacific, LOC), (Asia Pacific Corporate, ORG), (5, CARDINAL), (Asia Pacific, LOC), (Asia Pacific Corporate, ORG), (8, CARDINAL), (Accelink Technologies, ORG), (002281, DATE), (one, CARDINAL), (China Knowledge Online Pte. Ltd., ORG), (Accelink Technologies 002281, ORG), (Oct, DATE), (Asian Daily China Accelink Self, ORG), (OUTPERFORM Credit Suisse, ORG), (Asian Daily, ORG), (China Accelink, ORG), (Credit Suisse, ORG), (China Communication Infrastructure Sector Accelerating, ORG), (2H21, CARDINAL), (1H22, CARDINAL), (Credit Suisse, ORG), (China, GPE), (2H21 1H22, DATE)]"
3,002405.SZ,"[(ADAS Company MINIEYE Closes C Round of Financing, ORG), (270 Million RMB, MONEY), (ADAS, ORG), (MINIEYE, ORG), (World ADAS & AV Technologies and Components Market Report Focus on Camera Radar & Lidar, ORG), (Mapping & Localization and Robotaxis, ORG), (Montage Rare, PERSON), (Credit Suisse, ORG), (NavInfo Co. Ltd. Mergers & Acquisitions M&A Partnerships & Alliances and, ORG), (NavInfo Co. Ltd., ORG), (Mergers & Acquisitions, ORG), (China, GPE), (September, DATE), (Daiwa Capital Markets Hong Kong Ltd., ORG), (Technavio, ORG)]"
4,002432.SZ,"[(Blood Glucose Monitoring Devices Market Size, ORG), (Arizton, ORG), (USD 37 Billion, MONEY), (Arizton, GPE), (MarketGrader Research Report, ORG), (Andon Health Co. Ltd., ORG)]"
5,017670.KS,"[(Fourth Quarter, DATE), (Asia Pacific, ORG), (10, CARDINAL), (AIS China Mobile Globe Telecom Optus, ORG), (Telkomsel & True Corporation, ORG), (Asia Pacific, LOC), (AIS, ORG), (China Mobile, ORG), (Globe Telecom, ORG), (Optus PLDT, ORG), (Singtel, ORG), (SK Telecom, ORG), (SoftBank Telkomsel, ORG), (True Corporation, ORG), (Nanox, GPE), (Nanox, ORG), (Fourth Quarter, DATE), (Press Release Nanox, ORG), (Nanox, ORG), (Fourth Quarter, DATE), (Seoul Closing Stock Prices, ORG), (Seoul, GPE), (Disruptive Tech, PERSON), (5, CARDINAL), (Asia, LOC), (6, CARDINAL), (BofA Global Research, ORG), (Global Voice, ORG), (Smartphones Wearable Tech IoT Virtual Reality Telepresence Robotics, ORG), (Spotify Kakao M Spotify, ORG), (Kakao M, ORG), (Spotify, ORG), (Korea Republic, GPE), (SKT, ORG), (Korea Republic of SKT, GPE), (SK TELECOM CO LTD 6, ORG), (SK TELECOM CO LTD, ORG), (REG SK Telecom Co Ld Resolution, ORG), (REG SK Telecom Co, ORG), (AGM, ORG), (S. KOREA, ORG), (NEARS, ORG), (13, CARDINAL), (JANUARY, DATE), (S. KOREA, GPE), (5, PRODUCT), (S. Korea Telecom Chart, ORG), (SKT, ORG), (Hynix, GPE), (107%, PERCENT), (Morgan Stanley, ORG), (S. Korea, ORG), (the Week, DATE), (Hynix, ORG), (5, CARDINAL), (S. Korea, GPE), (13, CARDINAL), (Jan., DATE), (Jan, DATE), (13 mln, CARDINAL), (Press Release VMware Reports, ORG), (Fourth Quarter, DATE), (VMware, ORG), (Fiscal Year, DATE), (VMware Reports Fourth Quarter and, PERSON), (VMware, ORG), (Fourth Quarter, DATE), (5, CARDINAL), (UBS Equities, ORG), (Key Trades, ORG), (Risks Less Beta, ORG), (Robert Hackl, PERSON), (Advisory Board, ORG), (mce, ORG), (SPRINT, ORG), (Remote Learning Allows TCS', ORG), (Reach 1 Million U.S. K 12 Students, ORG), (TCS, ORG), (1 Million, CARDINAL), (U.S., GPE), (12, CARDINAL), (Press Release Pivot, ORG), (Reach 1 Million U.S. K 12 Students, ORG), (TCS, ORG), (1 Million, CARDINAL), (U.S., GPE), (12, CARDINAL), (Strategy Korea, PERSON), (10 year, DATE), (ERR, ORG), (Global Research, ORG), (BofA Global Research, ORG), (KT, ORG), (Seezn, ORG), (Asia Pacific, ORG), (10, CARDINAL), (Telcos, ORG), (Asia Pacific, LOC), (Korea Republic, GPE), (Bundang, PERSON), ...]"
6,036460.KS,"[(South Korean, NORP), (September, DATE), (Asia Crude Oil Tenders Summary Surgut, ORG), (CPC, ORG), (Asia, LOC), (Surgut, ORG), (over $2, MONEY), (Korean, NORP), ($2 bn, MONEY), (Hai Lang 1.5GW, PERSON), (Hai Lang 1.5GW LTP, FAC), (SXY.AX Senex Energy Limited Finally, ORG), (POSCO, ORG), (Credit Suisse, ORG), (SXY.AX Senex Energy Limited, ORG), (Asia Pacific, ORG), (LNG, ORG), (Asia Pacific LNG, ORG), (Seoul, GPE), (U.S., GPE), (Asia Crude Oil Tenders Summary Surgut, ORG), (Dec ESPO, PERSON), (22, CARDINAL), (Formosa, PERSON), (Asia, LOC), (Surgut, ORG), (22 mth, DATE), (Formosa, ORG), (Malaysia, GPE), (Petronas, PERSON), (LNG, ORG), (Petronas, ORG), (SXY.AX Senex Energy Limited SXY, ORG), (POSCO International Credit Suisse, ORG), (SXY.AX Senex Energy Limited, ORG), (Limited Coal, PERSON), (South Korean, NORP), (Argus Media Limited Coal, ORG), (IM, ORG), (MSCI ESG Research, ORG), (KoreaGasCorporation, ORG), (MSCI ESG Research, ORG), (ESG, ORG), (KoreaGasCorporation MSCI, ORG), (LNG, ORG), (Chinese, NORP), (Russian, NORP), (Asia Pacific, ORG), (Asia Crude Oil Tenders Summary Sakahlin Energy, ORG), (Dec Jan, DATE), (Asia, LOC), (Sakahlin Energy, ORG), (KOGAS International, ORG), (LNG, ORG), (Prelude, PRODUCT), (Prelude, FAC), (Asia Crude Oil Tenders Summary Surgut, ORG), (Asia, LOC), (South Korea, GPE), (LNG, ORG), (September, DATE), (Asia Crude Oil Tenders, ORG), (Rongsheng, PERSON), (first, ORDINAL), (Asia, LOC), (Rongsheng, GPE), (KOGAS September, ORG), (12%, PERCENT), (S.Korea, GPE), (September, DATE), (y y, DATE), (Korea Gas, ORG), (3Q, CARDINAL), (Korea, GPE), (3Q, DATE), (Korea Gas Target Price Raised, ORG), (000, CARDINAL), (Hana Financial Investment >, ORG), (Korea, GPE), (KRW62 000, MONEY), (KRW44 000, MONEY), (Hana Financial Investment, ORG), (Asia Crude Oil Tenders Summary, ORG), (Hai Thach, PERSON), (Asia, LOC), (Hai Thach, ORG), (Atlantic, LOC), (Asia Crude Oil Tenders Summary SOMO, ORG), (Dec Basra, GPE), (Asia, LOC), (SOMO, ORG), (Dec Basra Lt, ORG), (Asia Pacific, ORG), (LNG, ORG), (S Korea, GPE), (Asia Crude Oil Tenders Summary PetroBrunei, ORG), (Dec Kimanis, PERSON), (Asia, LOC), (PetroBrunei, ORG), (Dec Kimanis, ORG), ...]"
7,0623.HK,"[(Jefferson Research Financial Sonar Report, ORG), (Jilin Aodong Medicine Industry Group Co. Ltd., ORG), (Jefferson Research, ORG), (Sinomedia Holding Ltd NOTIFICATION OF BOARD, ORG), (Sinomedia Holding Ltd, ORG), (Sinomedia Holding Ltd NOTIFICATION OF BOARD MEETING, ORG), (Sinomedia Holding Ltd, ORG), (HK Bourse Announcement, ORG), (Sinomedia Holding, ORG), (Sichuan From Poverty Eradication, ORG), (Sichuan, GPE), (Rating Update for Sinomedia Holding Ltd Sadif Analytics, ORG), (Sinomedia Holding Ltd, ORG), (Sadif Analytics Prime, ORG), (Sinomedia Holding Ltd Monthly Return, ORG), (the month ended 28 February, DATE), (Sinomedia Holding Ltd, ORG), (Sinomedia Holding Ltd, ORG), (Sinomedia Expects, ORG), (Sinomedia, ORG), (FY, DATE), (About RMB70 Mln RMB90 Mln, MONEY), (BRIEF Sinomedia Expects, ORG), (Sinomedia, ORG), (FY, DATE), (About RMB70 Mln RMB90 Mln, MONEY), (SinoMedia Holding Cites Factors Such, ORG), (SinoMedia Holding, ORG), (SinoMedia Holding Ltd., ORG), (SINOMEDIA HOLDING LTD, ORG), (SINOMEDIA HOLDING LTD, ORG), (SINOMEDIA HOLDING LTD, ORG), (RMB70 MLN TO RMB90 MLN, MONEY), (YEAR, DATE)]"
8,0685.HK,"[(Jefferson Research Financial Sonar Report, ORG), (Media Chinese International Limited, ORG), (Jefferson Research, ORG), (Jefferson Research Financial Sonar Report, ORG), (Zhongshan Public Utilities Group Co. Ltd, ORG), (Jefferson Research, ORG), (HK Bourse Announcement, ORG), (2, CARDINAL), (HK Bourse, ORG), (Playmates Toys, ORG), (HK Bourse Circular, ORG), (General Mandate / Explanatory Statement for Repurchase of Shares / Re, ORG), (Shareholders, ORG), (Approval / Other 7, WORK_OF_ART), (Playmates Toys, ORG), (HealthSpace, ORG), (Market Awareness Advisory Groups, ORG), (Press Release HealthSpace, ORG), (Market Awareness Advisory Groups, ORG), (HealthSpace, ORG), (56983846, DATE), (EN MEDIA CHINESE INTERNATIONAL LIMITED, ORG), (56983846, CARDINAL), (CHAPTER 14 OF LISTING REQUIREMENTS DEALINGS OUTSIDE CLOSED, LAW), (Media Chinese International Ltd Sadif Analytics, ORG), (Media Chinese International Ltd, ORG), (Sadif Analytics Prime, ORG), (Media Chinese International Ltd MONTHLY, ORG), (Media Chinese International Ltd, ORG), (THE MONTH ENDED 28 FEBRUARY, DATE), (One, CARDINAL), (Media Group Ltd, ORG), (One Media Group Ltd, ORG), (THE MONTH ENDED 28 FEBRUARY, DATE)]"
9,0688.HK,"[(LAND & INVESTMENT LTD, ORG), (MSCI ESG Research, ORG), (CHINA OVERSEAS LAND & INVESTMENT LTD., ORG), (Jefferson Research Financial Sonar Report, ORG), (Jianxin Mining Co. Ltd, ORG), (Jefferson Research, ORG), (Hong Kong Closing Stock, ORG), (Hong Kong, GPE), (HK Bourse Circular, ORG), (China State Construction, ORG), (3, CARDINAL), (China, GPE), (HK Bourse Circular, ORG), (China State Construction on General Mandate / Explanatory Statement for Repurchase of Shares / Re, ORG), (Shareholders, ORG), (China, GPE), (DIARY, GPE), (Hong Kong, GPE), (week, DATE), (China, GPE), (JPMorgan Econ & FI, ORG), (Asian Daily China Market Strategy Identifying, ORG), (Credit Suisse, ORG), (HK Bourse Announcement, ORG), (China Overseas Grand Oc, ORG), (HK Bourse Circular, ORG), (Sino Biopharmaceutical 3, NORP), (Sino Biopharmaceutical 3, ORG), (Panorama No.240, ORG), (China International Capital Corporation, ORG), (China International Capital Corporation Hong Kong Limited, ORG), (Panorama No.240, ORG), (China International Capital Corporation, ORG), (China International Capital Corporation Hong Kong Limited, ORG), (China, GPE), (Morgan Stanley, ORG), (3M21, CARDINAL), (China International Capital Corporation, ORG), (3M21, DATE), (China International Capital Corporation Hong Kong Limited, ORG), (3M21, CARDINAL), (China International Capital Corporation, ORG), (3M21, DATE), (China International Capital Corporation Hong Kong Limited, ORG), (HK Bourse Circular, ORG), (Kingboard Laminates, PERSON), (3, CARDINAL), (China Overseas Land & Investment ST, ORG), (18.7, CARDINAL), (22.15, CARDINAL), (LAND & INVESTMENT LTD, ORG), (MSCI ESG Research, ORG), (CHINA OVERSEAS LAND & INVESTMENT LTD, ORG), (China, GPE), (Daiwa Capital Markets Hong Kong Ltd., ORG), (Hong Kong, GPE), (Traditional, GPE), (Beijing, GPE), (China, GPE), (1Q, CARDINAL), (JPMorgan Econ & FI, ORG), (1Q, DATE), (Beijing, GPE), (HK, GPE), (China International Capital Corporation, ORG), (China International Capital Corporation Hong Kong Limited, ORG), (China International Capital Corporation, ORG), (China International Capital Corporation Hong Kong Limited, ORG), (China International Capital Corporation, ORG), (China International Capital Corporation Hong Kong Limited, ORG), (China International Capital Corporation, ORG), (China International Capital Corporation Hong Kong Limited, ORG), (Industrials News Weekly Sany, ORG), (monthly, DATE), (March, DATE), (Credit Suisse, ORG), (Industrials News Weekly, ORG), (Sany, ORG), (Rmb10 bn, MONEY), (China Overseas Land & Investment ST, ORG), (17.34, CARDINAL), (Property Services, ORG), (China, GPE), (ESG, ORG), (CLSA, ORG), (MOORE Day, DATE), (China, GPE), (00688 Mar, CARDINAL), (45%, PERCENT), (China Overseas, ORG), (Mar, DATE), (China Overseas Land & Investment, ORG), (January March, DATE), (50%, PERCENT), (Year, DATE), (China, GPE), (China Overseas Land & Investment, ORG), (January March, DATE), (CNY89.41B, MONEY), (China Overseas Land & Investment March Contracted Sales Rose, ORG), ...]"

In [27]:
grouped_df[grouped_df['RIC'] == 'HYFM.OQ']

,RIC,NER_combined
980,HYFM.OQ,"[(Hydrofarm Holdings Group Inc, ORG), (HYFM, ORG), (Q4, DATE), (Q4 Hydrofarm Holdings Group Inc Earnings Call, ORG), (Q4, DATE), (Hydrofarm Holdings Group Inc, ORG), (Hydrofarm Holdings Group Inc., ORG), (HYFM, ORG), (Q4, DATE), (US Penny Stocks, ORG), (January, DATE), (US, GPE), (Zacks Industry Outlook Highlights West Fraser, ORG), (CalMaine Foods Andersons, ORG), (Hydrofarm, PERSON), (Zacks, ORG), (West Fraser Timber, ORG), (CalMaine Foods, ORG), (Hydrofarm, ORG), (4 Agriculture Products Stocks, ORG), (Watch Despite Industry Concerns, ORG), (4, CARDINAL), (Hydrofarm Holdings Group Inc., ORG), (Invest, ORG), (HYFM, ORG), (Hydrofarm Holdings Group, ORG), (3 US Penny, MONEY), (3, CARDINAL), (US, GPE), (30, MONEY), (Hydrofarm, ORG), (FY24, DATE), (Hydrofarm Holdings Group Inc, ORG), (HYFM, ORG), (Q4, DATE), (Q4 Hydrofarm Holdings Group Inc Earnings Call, ORG), (Q4, DATE), (Hydrofarm Holdings Group Inc, ORG), (Hydrofarm Holdings Group Inc., ORG), (HYFM, ORG), (Q4, DATE), (US Penny Stocks, ORG), (January, DATE), (US, GPE), (Zacks Industry Outlook Highlights West Fraser, ORG), (CalMaine Foods Andersons, ORG), (Hydrofarm, PERSON), (Zacks, ORG), (West Fraser Timber, ORG), (CalMaine Foods, ORG), (Hydrofarm, ORG), (4 Agriculture Products Stocks, ORG), (Watch Despite Industry Concerns, ORG), (4, CARDINAL), (Hydrofarm Holdings Group Inc., ORG), (Invest, ORG), (HYFM, ORG), (Hydrofarm Holdings Group, ORG), (3 US Penny, MONEY), (3, CARDINAL), (US, GPE), (30, MONEY), (Hydrofarm, ORG), (FY24, DATE)]"

In [28]:
grouped_df.shape

(2216, 2)

In [29]:
# Save to Excel
df.to_excel("NER.xlsx", index=False)